### ISSUE TITLE
Open source license

### ISSUE THREAD

**Issue by fson** [graphql/graphiql#10]
The license included in the LICENSE file for this project does not look like any standard open source license.
```
Facebook, Inc. (“Facebook”) owns all right, title and interest, including all
intellectual property and other proprietary rights, in and to the GraphiQL
software. Subject to your compliance with these terms, you are hereby granted a
non-exclusive, worldwide, royalty-free copyright license to ...
```
What license is this?

Is there a reason why this project could not be licensed with a normal [OSI approved license](http://opensource.org/licenses) like the BSD License used in [GraphQL.js](https://github.com/graphql/graphql-js/blob/master/LICENSE)? I think this would ensure compatibility with open source licenses and that people using GraphQL can use GraphiQL without having to consult their lawyers about the custom license.

**Comment by leebyron** [comment]
This has something to do with how our open source team likes us licensing libraries vs interfaces and examples. cc @iamscott who made the decision to use this particular license and can hopefully explain further.

**Comment by leebyron** [comment]
I spoke with that team, and the licensing decision is because this is a UI developer tool FB grants a broad license to the source code, but maintains IP ownership. I hope that this is not a practical issue, but please let me know if this creates a real issue for you.

**Comment by devknoll** [comment]
@leebyron Actually, this might pose a challenge for something I wanted to work on. I wanted to extract the hinting/linting out from CodeMirror so that it could be integrated with different tools or editors.

Without an OSI approved license, that might be tough. At the very least, it would be nice if *that* part could be extracted out and open sourced under a different license.

**Comment by leebyron** [comment]
Great suggestion, I will do some investigation to understand the implications.

**Comment by luisobo** [comment]
@leebyron I having the same issue as @devknoll, trying to integrate graphiql into my Scala app via WebJars is not possible because of the license. See #25 for more details. The list of accepted licenses by WebJars is [here](https://bintray.com/docs/api/#_footnote_1). 

If by any chance the license could be changed to something standard it would enable the integration of graphiql in other ecosystems.

Thanks for your time.

**Comment by devknoll** [comment]
Thanks @leebyron :+1:

**Comment by leebyron** [comment]
FYI: I just published https://github.com/graphql/codemirror-graphql which is also on npm which uses Facebook's standard BSD-3-Clause open source license.

I also just published a version of GraphiQL to npm which leverages that module. GraphiQL itself remains licensed our dev tools & examples license.

**Comment by fson** [comment]
Thanks @leebyron!

**Comment by drunkirishcoder** [comment]
@leebyron after the recent relicensing of React, GraphQL spec, GraphQL.js + Relay, are there any plan to relicense graphiql to a more open source friendly license?

**Comment by Totktonada** [comment]
@leebyron I think the issue can be reopened to bring some attention to it? Thanks.

**Comment by tuxether** [comment]
Please consider Apache 2.0

**Comment by mc0** [comment]
It seems the license doesn't allow modifying the code and then distributing it? I'm not really sure what this license actually lets us do beyond run it.

**Comment by tuukka** [comment]
Please reconsider: If I'm not allowed to modify the code, how can I make a pull request?

**Comment by AGS-** [comment]
I'm no longer in the GraphQL org, but let me see if I can push on this a little bit.

**Comment by AGS-** [comment]
Great news, we are now on MIT!

**Comment by tuukka** [comment]
Thank you @AGS- and Facebook--this is an awesome continuation of your contributions to developer experience! At least 40 dependent projects already: https://www.npmjs.com/browse/depended/graphiql

**Comment by naddeoa** [comment]
Any plans to do the same for related packages or is it just a matter of getting around to it?

https://github.com/graphql/graphql-language-service/blob/master/LICENSE
