### ISSUE TITLE
CSS missing

### ISSUE THREAD

**Issue by aleksandrenko** [graphql/graphiql#100]
In the given example the css is forgotten and the rendered graphiql is styleless.

**Comment by asiandrummer** [comment]
@aleksandrenko do you mean this [live demo](http://graphql-swapi.parseapp.com/)? For me it renders as expected - could you elaborate the problem you're having?

**Comment by nikhilaravi** [comment]
@aleksandrenko I had the same problem! I ended up having to require the grpahql css file into my index.js file like this `require('../node_modules/graphiql/graphiql.css')` and adding a css loader to my webpack config.

**Comment by leebyron** [comment]
Thanks for the report. I added more to the README to explain the requirement of adding the CSS file to the page.

**Comment by nikhilaravi** [comment]
cool thanks @leebyron!
