### ISSUE TITLE
Support GraphQL 15.0.x

### ISSUE THREAD

**Issue by acao** [graphql/graphiql#1000]
First Alpha was already released over a month ago:
https://github.com/graphql/graphql-js/releases/tag/v15.0.0-alpha.1

The changes are mostly non-breaking, drop-in really, with some slight changes to schema introspection.

However, the arc towards a stable release will have:

- Major changes to schema introspection, introducing dual or dynamic introspection (for example, `introspectionQuery` constant is deprecated!)
- Interfaces implementing interfaces
- Breaking changes to the type, validation, language system

Major changes to schema introspection, as well as to language and type libraries that GraphiQL, `codemirror-graphql` and the rest of the LSP ecosystem rely on heavily. The same can be said for `graphql-language-service`.

I think it's safe to say that @IvanGoncharov will take great care and time to get it right for the stable release, and ecosystem adoption, buying us some time to adopt it, which we will need plenty of. We are iterating so heavily so quickly, any fork we create for graphql 15 support now may not end up mergeable but will be useful for when we are ready to adopt it.

An important point to make - GraphiQL and the other services in this repository are a key member of the reference ecosystem. This means they should be the lead tools available to adopt these new features and allow experimentation.  Many graphql frameworks will be hot on the heels with adoption of GraphQL 15 features, so we will probably want to work closely with folks.

For example, @binaryseed how is Absinthe doing on dual query instrospection and interfaces implementing interfaces? I'm guessing GraphiQL supporting the first alpha would be very nice to have right now? Probably using functional tests and cURL/etc?

Also, @divyenduz we will probably want to get this implemented in the LSP soon for you to experiment with your vscode extensions!

**Comment by toxsick** [comment]
Just to be sure, graphql v15 ist still not supported right?

**Comment by acao** [comment]
@toxsick it is in almost all cases, except for codemirror-graphql where interfaces implementing interfaces is concerned, I believe. do you see any issues with graphql-js 15 support?

**Comment by toxsick** [comment]
hey @acao, sorry just saw your response. I got everything running in a big project of mine, but my graphql query was not highlighted and I got not auto completion:

<img width="311" alt="_2020-06-22_14-54-03" src="https://user-images.githubusercontent.com/951466/98682394-29cdff80-2364-11eb-97cb-f4f9b98476a6.png">

Is there a trick?

regards

**Comment by acao** [comment]
can you open a new ticket? thanks!

**Comment by acao** [comment]
`implements &` syntax implenented!
