### ISSUE TITLE
Windows: Running tests reports errors with line endings

### ISSUE THREAD

**Issue by PeteDuncanson** [graphql/graphiql#1032]
Following the instructions on https://github.com/graphql/graphiql/blob/master/CONTRIBUTING.md#getting-started results in line ending issue being reported when running the test (yarn test):

![image](https://user-images.githubusercontent.com/1674590/69888294-f1641b80-12e2-11ea-9a26-561f19570748.png)

Seems by default git for windows will checkout files and convert them to CRLF line endings rather than LF as everyone else is using.

Initially I can fix this by running `npm run lint-fix` but I had to find that and google about it to know I could do it, better to not have to have Windows devs run that each time.

Seems a new rule is needed to be added to a currently non-existant file (.gitattributes) to overrule this setting when first checked out on windows machines.

https://eslint.org/docs/rules/linebreak-style#using-this-rule-with-version-control-systems

Alternative is to add something to the docs.

**Comment by PeteDuncanson** [comment]
Adding to this noticed the eslint says the linebreak-style rule should be string (https://github.com/graphql/graphiql/blob/master/CONTRIBUTING.md#getting-started) but its set to just a 1. Not sure if that is an issue or not but something check maybe as its not been touched for 3 years?

![image](https://user-images.githubusercontent.com/1674590/69888472-ea89d880-12e3-11ea-951f-f70ddda276d7.png)

**Comment by acao** [comment]
@PeteDuncanson just normal eslint config:
https://eslint.org/docs/user-guide/configuring#configuring-rules

also i saw that you were using npm which will probably also give you lots of issues, as you can see we have a checked in yarn.lock file

**Comment by acao** [comment]
i think the issue here @PeteDuncanson is that you have your editor configured to use CRLF by default, and it automatically formatted everything it would seem?

**Comment by acao** [comment]
please re-open if this is not the issue? we have some more improvements coming to eslint and windows tooling, but I can only imagine you have this issue because you are defaulting to CRLF. possibly we need a .editorconfig to be 100% certain but the industry norm to expect is LF.

**Comment by PeteDuncanson** [comment]
I did indeed have VSCode set to CRLF which I switched over to LF after doing some googline. However I hadn't even opened it in VSCode before I got the error. An .editorconfig would solve my editor setup being wrong but I think a .getattribute file will be needed to force window to checkout with LF line endings from what I've read https://git-scm.com/docs/gitattributes

New territory for me working with multiple file systems, normally its windows all the way for all the team so sorry if some of these issues/suggestions are daft, still learning.

**Comment by benjie** [comment]
Hi @PeteDuncanson please feel free to raise a PR with these suggestions; our core development team don't use Windows.

**Comment by PeteDuncanson** [comment]
I've added an .editorconfig and a .gitattributes file which should normalise the line endings for everyone. Reduces the noise and head scratching when first getting up and running.

Big thanks to this post for correct syntax https://stackoverflow.com/a/42136008/107691
