### ISSUE TITLE
Windows: Running yarn tests reports trying to use "printf"

### ISSUE THREAD

**Issue by PeteDuncanson** [graphql/graphiql#1033]
Running the https://github.com/graphql/graphiql/blob/master/CONTRIBUTING.md#getting-started steps on windows 10 (command line running as admin) I get an error showing at the end of the run about `printf` which doesn't exist on windows. Not sure whats throwing it as the `yarn tests` command chains a bunch of stuff together so I'll run them individual and see if I can narrow it down.

**Comment by PeteDuncanson** [comment]
![image](https://user-images.githubusercontent.com/1674590/69888572-84ea1c00-12e4-11ea-83e9-69dd687e12e2.png)

**Comment by PeteDuncanson** [comment]
Ahh this seems to be fixed after I corrected the CRLF issue (#1032) so this isn't a "real" issue.

For the record I fixed that by running `npm run lint-fix`

**Comment by PeteDuncanson** [comment]
Found this again. There is a printf after the lint command in the package.json https://github.com/graphql/graphiql/blob/master/package.json#L32

Suggest we swap this out for a echo instead? Terrified of making any changes myself as I simply don't know enough bash etc (not touched it since college) so hope its ok if I just flag up what breaks here instead?

**Comment by benjie** [comment]
Hey @PeteDuncanson 

Please edit the line to:

```
"lint": "eslint --ext=ts,js,jsx,tsx . || (echo && echo && echo 'Try:  yarn format' && echo && exit 1)",
```

Test it locally, and if it works, submit it as a PR.

Thanks!

**Comment by acao** [comment]
ah thanks! we need to get rid of that echo statement anyways. i have a branch for that where we make lots of eslint and prettier fixes

**Comment by PeteDuncanson** [comment]
@benjie thanks for the pointers and the encouragement :)

Ok so I've been playing around with this one. Here it is as is:

![image](https://user-images.githubusercontent.com/1674590/70851045-88ef6f80-1e88-11ea-9e50-88e198547a18.png)

Your version:

![image](https://user-images.githubusercontent.com/1674590/70850938-bb4c9d00-1e87-11ea-9897-b4656d3df66f.png)

Final version with some tweeks (I assumed the multiple echos are for new lines):

![image](https://user-images.githubusercontent.com/1674590/70851026-6eb59180-1e88-11ea-8c38-4831c17ef5fb.png)

Will get this in a PR so you can double check its not broken anything on the Macs.

**Comment by acao** [comment]
@PeteDuncanson can you confirm that you have no issues on Windows with this PR?

**Comment by acao** [comment]
the one that i just linked here #1099
