### ISSUE TITLE
v0.17.1 Can't resolve '../css/doc-explorer.css' in graphiql/dist/components

### ISSUE THREAD

**Issue by Fi1osof** [graphql/graphiql#1045]
Topic

**Comment by MichaelBurgess** [comment]
It looks to me like the entire `./css/...` directory is missing, as I'm getting this when I try to build for production:

```
Creating an optimized production build...
Failed to compile.

./node_modules/graphiql/dist/index.js
Cannot find module: './css/show-hint.css'. Make sure this package is installed.

You can install this package by running: npm install ./css/show-hint.css.
```

**Comment by acao** [comment]
oops! will fix this asap

**Comment by acao** [comment]
@MichaelBurgess @Fi1osof thanks for the report! can you let me know if that PR helps?

try these steps locally:

1. `yarn`
1. `yarn build`
1. `lerna run build-bundles`
1. `lerna run build-demos` (about to introduce a developer docs PR sorry)
