### ISSUE TITLE
chore: convert codemirror-graphql tests from mocha to jest, remove mocha and chai completely

### ISSUE THREAD

**Issue by acao** [graphql/graphiql#1053]
I had some issue with how async throw() assertions work or some such that caused me to skip this. would be great to:
- convert codemirrror-graphql unit tests from mocha and chai to jest and jest.Assert. rename to follow jest spec.js pattern
- ensure all tests do not use chai across the monorepo
- remove mocha/chai from the build process

**Comment by codecog** [comment]
@acao assign to me and I'll complete the task.

**Comment by benjie** [comment]
Assigned :+1:

**Comment by acao** [comment]
thanks @codecog ! it has proven quite tricky. you’ll probably want to re-use and extend the manual mock we use in GraphiQL for codemirror

**Comment by codecog** [comment]
No problem, will reach out there if i hit any roadblocks.

**Comment by codecog** [comment]
PR open: https://github.com/graphql/graphiql/pull/1630

**Comment by Jordanlelay** [comment]
It seems that this issue has been solved by https://github.com/graphql/graphiql/pull/1763

**Comment by acao** [comment]
yes it has! thanks for the cleanup @Jordanlelay !
