### ISSUE TITLE
New GraphiQL Screenshot

### ISSUE THREAD

**Issue by acao** [graphql/graphiql#1089]
So until the redesign/monaco/etc, we need a more up to date and more handsome screenshot of GraphiQL. I think its still the same one from the original 0.13.2 release?

Upload any here, gifs or jpegs!

some criteria
- minimal customization ideally. should not show any features that don't exist in GraphiQL component. and should have default GraphiQL logo etc.
- no graphql explorer. its a wonderful project but not officially part of graphql orgspace

nice to haves:
- cutesy emojis and stuff
- something whimsical or memorable
- something unconventional seeming thats still possible with the default GraphiQL

**Comment by acao** [comment]
![Screen Shot 2019-12-15 at 2 49 44 PM](https://user-images.githubusercontent.com/1368727/70868036-3bd3d200-1f4a-11ea-917e-6bb82da18483.png)

huh I guess this is ok.

why does also the one i upload look all yellowed like that?

**Comment by benjie** [comment]
Colour profiles? Looks alright to me, but I'm on Linux so it probably ignores colour profiles ;)
