### ISSUE TITLE
Windows: Can't resolve imports without file extensions

### ISSUE THREAD

**Issue by PeteDuncanson** [graphql/graphiql#1096]
Could be me missing something here.

Fresh clone, run "yarn" then run "yarn build" and then get errors like this:

![image](https://user-images.githubusercontent.com/1674590/70853395-6e77bf00-1ea5-11ea-9d89-e740b9088046.png)

"yarn lint" reports similar:

![image](https://user-images.githubusercontent.com/1674590/70853409-8d765100-1ea5-11ea-8de3-47c80dd680d6.png)

**Comment by PeteDuncanson** [comment]
Much googling points to this as a possible fix but I can't get it working. Any pointers?

https://stackoverflow.com/questions/55198502/using-eslint-with-typescript-unable-to-resolve-path-to-module

**Comment by acao** [comment]
looks like you need to `yarn` in your root? and then a fresh `yarn build`?

**Comment by PeteDuncanson** [comment]
root folder? If so I already am.

**Comment by PeteDuncanson** [comment]
`yarn build` leads to the same errors:

![image](https://user-images.githubusercontent.com/1674590/70854308-d6cc9d80-1eb1-11ea-9068-8a4e0390ac44.png)

**Comment by benjie** [comment]
Hey @PeteDuncanson; you've closed this but are still reporting issues so I'm not sure if you've solved it.

In case anyone comes across this issue in future, our instructions on how to get started are in this file: https://github.com/graphql/graphiql/blob/master/DEVELOPMENT.md ([permalink](https://github.com/graphql/graphiql/blob/3c5e329644f945d0d44e62dc1fa6515437e12ca3/DEVELOPMENT.md))

but namely:

```
git clone git@github.com:yournamehere/graphiql.git
cd graphiql
yarn
yarn run build
yarn workspace graphiql dev
```
