### ISSUE TITLE
React versions clash with Relay and Graphiql

### ISSUE THREAD

**Issue by asavin** [graphql/graphiql#11]
When using graphiql in Relay app, getting following issue on `npm install`:

    npm ERR! peerinvalid The package react does not satisfy its siblings' peerDependencies requirements!
    npm ERR! peerinvalid Peer graphiql@0.1.1 wants react@~0.13.x || ~0.14.x
    npm ERR! peerinvalid Peer react-relay@0.1.1 wants react@^0.14.0-beta3

`package.json` content:
````
"dependencies": {
    "classnames": "^2.1.3",
    "express": "^4.13.1",
    "express-graphql": "^0.3.0",
    "graphiql": "^0.1.0",
    "graphql": "^0.4.2",
    "graphql-relay": "^0.3.1",
    "isomorphic-fetch": "^2.1.1",
    "jade": "^1.11.0",
    "moment": "^2.10.6",
    "react": "^0.14.0-beta3",
    "react-relay": "^0.1.0",
    "react-router": "1.0.0-beta3",
    "relay-nested-routes": "^0.3.1",
    "require-dir": "^0.3.0"
  }
````

**Comment by leebyron** [comment]
Thanks for the report. I'll fix the peer dep to include the v0.14 betas

**Comment by LegNeato** [comment]
Should be fixed by https://github.com/graphql/graphiql/pull/14, right?

**Comment by steveluscher** [comment]
Yep! This was the driver behind #14.

**Comment by asavin** [comment]
Works fine now :+1:
