### ISSUE TITLE
Component state update uses potentially inconsistent value

### ISSUE THREAD

**Issue by imanoracle** [graphql/graphiql#1115]
Hi there,

Is it an unsafe call?
Line 153 of  `graphiql/packages/graphiql/src/components/DocExplorer.js `

Updating the state of a component based on the current value of 'this.state' or 'this.props' may lead to inconsistent component state.

**Comment by acao** [comment]
i wouldn’t find it to be a problem, it uses this.state to figure out where the user is. we are about to deprecate all these “public api” methods anyways

**Comment by benjie** [comment]
Line in question:

https://github.com/graphql/graphiql/blob/4803aec94cc723bbcaa8cfa3c5f811fbf6cd3d20/packages/graphiql/src/components/DocExplorer.js#L148-L161

This is fine; if two or more of these were to be fired without a render between then some of these triggers would be lost, but that's not important - the last one will win and that's the behaviour a user would want.
