### ISSUE TITLE
Harfbuzz version too old (1.2.7) on Fedora

### ISSUE THREAD

**Issue by Crease29** [graphql/graphiql#1126]
Hi,

I can't run the AppImage on Fedora 31 (Kernel 5.3.16-300.fc31.x86_64):
```
./graphiql-app-0.7.2-x86_64.AppImage 
installed: X-AppImage-BuildId=24b6ccb0-2df4-11a8-2ae7-31fb38ad6b4e image: X-AppImage-BuildId=24b6ccb0-2df4-11a8-2ae7-31fb38ad6b4e

(graphiql-app:36844): Pango-ERROR **: 19:15:40.473: Harfbuzz version too old (1.2.7)

[1]    36844 trace trap (core dumped)  ./graphiql-app-0.7.2-x86_64.AppImage
```
Anyone knows this issue?

```
Pango version:    1.44.7-1.fc31
Harfbuzz version: 2.6.1-2.fc31
```

**Comment by acao** [comment]
hey @Crease29 ! thanks for reporting this. I think this might be a particular issue with your Harfbuzz implementation, which seems to package graphiql in some way, I'm guessing for a native c++ app with a webview? Either way, after looking into Harfbuzz, it looks like a really cool project and I'm stoked to see it's making use of GraphiQL! 

it's not clear to me where they are bundling GraphiQL or how, if the maintainer of this Harfbuzz graphiql implementation has any questions that we can answer from the javascript side, let me know!

**Comment by Crease29** [comment]
I'm not exactly sure why it uses harfbuzz, but I just downloaded the AppImage file from the artifacts of the latest release here on github. Either it's Fedora trying to render the view with it or something else. So you're not actively using it in GraphiQL?

**Comment by acao** [comment]
@Crease29 we are not actively using Harfbuzz at all, i think it is using graphiql in some way that we don't know, which is common. there are so so many userspace [implementations of graphiql](implementations of graphiql) that we cannot keep track of them (that's a really good problem to have!).

**Comment by benjie** [comment]
(For future visitors, I believe this is an issue in @skevy's GraphiQL.app; you can find the relevant issue here: https://github.com/skevy/graphiql-app/issues/154)
