### ISSUE TITLE
Customising HTTP Headers

### ISSUE THREAD

**Issue by MarkAndrewJohnson** [graphql/graphiql#114]
I'm using the express graphql connector to build the public interface for our application.

One thing that would be ideal in the web UI would be to specify custom HTTP Headers that get sent with requests.  For example I would like to set the following manually after doing an auth request:
`Authorization: xvI8GX8Kb2rzBsusHztC9GeEZ76TI9XKLpCWr9NqDUZqgWwNvD2gfMOJnlJoPzwE`
This HTTP header in turn gets passed (possibly via setting a RootValue) to our loopbackjs backend for authenticated requests.

**Comment by asiandrummer** [comment]
Hey @MarkAndrewJohnson - would it be possible for you to define a custom `graphQLFetcher`? If you look at how our `/example` is set up, we use `express-graphql` but we define/render our own graphQLFetcher/GraphiQL component, and in the fetcher is where you can define network configurations as you like. I can point you to this [example] (https://github.com/graphql/graphiql/blob/master/example/index.html).
> Often, when your GraphQL endpoint is behind a authorization feature like this, it is common to expose the GraphiQL tool via a different endpoint on your server.

For some more information, #59 and #96 discuss about this.

**Comment by MarkAndrewJohnson** [comment]
I will checkout those references, thanks.

**Comment by MarkAndrewJohnson** [comment]
I mustn't have seen those two since they were closed, so will mark this as such as well.

**Comment by Durisvk** [comment]
@MarkAndrewJohnson 

Hello I've implemented the feature you've requested

Here are the links to the library files:
https://cdn.jsdelivr.net/npm/graphiql-custom-headers@1.0.0/graphiql-custom-headers.css
https://cdn.jsdelivr.net/npm/graphiql-custom-headers@1.0.0/graphiql-custom-headers.js
https://cdn.jsdelivr.net/npm/graphiql-custom-headers@1.0.0/graphiql-custom-headers.min.js

Here is a simple example of how to use it:
https://github.com/Durisvk/graphiql

It's really simple, you don't have to do almost any changes to your current running app.

And it's also available on NPM: https://www.npmjs.com/package/graphiql-custom-headers

This is how it looks like: http://imgur.com/a/3VQDT

I've also implemented it already to my project: https://github.com/Durisvk/senegraph
so it's already available on HapiJS servers. Somewhere in the future I would like to implement it also on Express. Maybe you could help me out with this.

Hopefully you'll like my solution @MarkAndrewJohnson  ...

**Comment by shtse8** [comment]
Any updates? I can't see this feature in the latest release.

**Comment by wincent** [comment]
@shtse8: It's not in the latest release nor on the master branch because no PR for it was merged. As @asiandrummer linked above, the relevant discussion is in #59 or #96.

**Comment by imolorhe** [comment]
@shtse8 You can use https://github.com/imolorhe/altair with custom headers as well if you don't want to customize your GraphiQL implementation, although that shouldn't be much of a challenge either.
