### ISSUE TITLE
feature request: Custom validation rules in editor

### ISSUE THREAD

**Issue by boopathi** [graphql/graphiql#1143]
Provide a way to extend the editor with custom GraphQL validation rules.

Example: I want to provide custom graphql validation rules from the <GraphiQL/> Component

```jsx
<GraphiQL validationRules=[customRule] />
```

The graphql-language-server-interface provides the functionality and passes the rules to GraphQL-js `validate` fn - https://github.com/graphql/graphiql/blob/c9507101427768169e505692d187747e7eef727c/packages/graphql-language-service-interface/src/getDiagnostics.ts#L42-L47

There is no such option in graphiql-codemirror project and the param is ignored
https://github.com/graphql/graphiql/blob/c9507101427768169e505692d187747e7eef727c/packages/codemirror-graphql/src/lint.js#L36

If this is something we can add, I can work on it and contribute.

**Comment by acao** [comment]
we will have this soon! there are custom validation rules in the LSP already, and we will bring them to the browser when we switch to monaco editor here soon.

**Comment by thomasheyenbrock** [comment]
Resolved by #1716 and available since `1.2.0`
