### ISSUE TITLE
GraphiQL is having trouble with custom scalars

### ISSUE THREAD

**Issue by kamek-pf** [graphql/graphiql#115]
I defined a few custom scalar types, a `Point` type for example, to represent GPS coordinates.
It's defined as a `GraphQLScalarType` and a few verifications are made (we're supposed to get an array of 2 floats, values must be within a certain range, etc).

It works fine, but GraphiQL is complaining about the type being incorrect :
![graphiql](https://cloud.githubusercontent.com/assets/3883992/13931288/01c5c956-ef79-11e5-9166-cae9f31f17fb.png)

Here's a gist with the custom type: https://gist.github.com/kamek-pf/759835d64ff26511d992

Is this a weakness from GraphiQL or am I doing something wrong ?

**Comment by leebyron** [comment]
I think we just never expected the use of a custom scalar to represent non scalar literal values such as Lists.

GraphiQL currently only allows the scalar value literals int/float/string/boolean to be used for scalar types including custom scalar types.

I think the broader question here is whether or not custom scalars should support non-scalar literals or not.

**Comment by kamek-pf** [comment]
Reading your comment makes me realize this is probably a bad idea.
It's a nice way to perform validations though.

**Comment by kamek-pf** [comment]
Closing this since this is obviously not how scalar types were intended to be used. I also ran into some other issues in Relay when composing fragments because of this.

I ended up implementing 2 scalars (latitude and longitude), and a GraphQLObjectType on top of them.
Much better.
