### ISSUE TITLE
Render documentation for query variables

### ISSUE THREAD

**Issue by jLouzado** [graphql/graphiql#1159]
Ideally I'd like to add information per variable, like so.

![image](https://user-images.githubusercontent.com/2016685/71399197-e59d1800-2648-11ea-9d6a-1d8663444cc7.png)

But right now that's not possible, and I have to put it in the heading (where it might get missed)

![image](https://user-images.githubusercontent.com/2016685/71399272-154c2000-2649-11ea-9707-4e45c6228b77.png)

**Comment by acao** [comment]
strange... this should work for arguments. ill look into this

**Comment by jLouzado** [comment]
Running apollo-server-express 1.4.0

```
├─┬ apollo-server-express@1.4.0
│ ├─┬ apollo-server-core@1.4.0
│ │ ├─┬ apollo-cache-control@0.1.1
│ │ │ └── graphql-extensions@0.0.10 deduped
│ │ ├─┬ apollo-tracing@0.1.4
│ │ │ └── graphql-extensions@0.0.10 deduped
│ │ └─┬ graphql-extensions@0.0.10
│ │   ├── core-js@2.6.1
│ │   └─┬ source-map-support@0.5.9
│ │     ├── buffer-from@1.1.1 deduped
│ │     └── source-map@0.6.1
│ └── apollo-server-module-graphiql@1.4.0
```

**Comment by acao** [comment]
which vscode editor plugin are you using?

**Comment by benjie** [comment]
Hey @jLouzado you're using comments in your GraphQL schema rather than documentation strings. This behaviour changed in [graphql-js v0.12.0](https://github.com/graphql/graphql-js/releases/tag/v0.12.0); previously comments were used for documentation, but now comments are comments.

Your definitions should be:

```graphql
type Query {
  """If tourId not provided, return all matches"""
  matches(
```
