### ISSUE TITLE
Request: Docs for customization

### ISSUE THREAD

**Issue by kevinSuttle** [graphql/graphiql#116]
Are there more docs for customizing GraphiQL other than the short note at the end of the README?

**Comment by asiandrummer** [comment]
Hi @kevinSuttle! I thought our example code contains how to use `props` and `children` for customization, but it actually doesn't - I'll go ahead and either add more docs or modify example codes with some use cases I've encountered personally, as well as the popular issues people have had problems with if I'm missing any.

But to better assist you, what are the problems you're having to customize GraphiQL?

**Comment by kevinSuttle** [comment]
Sounds great @asiandrummer. The main issues I'm having are around _where_, _when_, and how to add the customizable components mentioned in the README, but the big one is around adding new panels and the APIs exposed to do so. Thanks!

**Comment by asiandrummer** [comment]
@kevinSuttle I've just added some examples to README - go check it out and let me know what you think!
Feel free to reopen this issue if you have any other suggestions for which examples should be added please.
