### ISSUE TITLE
(question) How can i get the schema after it has been fetched

### ISSUE THREAD

**Issue by mjarkk** [graphql/graphiql#1183]
I'm trying to add [graphiql-explorer](https://github.com/OneGraph/graphiql-explorer/) to a project but it requires the graphql schema (*of type GraphQLSchema*) that i guess is somewhere inside this library.  

I've found that the state of the `GraphiQL` contains that but i can't seem to get it out using:  
```jsx
<GraphiQL ref={c => { console.log(c ? c.state.schema : c) }} fetcher={fetcher}>
// Console output: undefined
```
The wired thing is if i log just the reference (`c`) i can click to `.state.schema` and see the schema???  

I've tried a lot of things but the only solution seems to be fetching the schema separately and putting it inside the GraphiQL and the GraphiQL explorer but i have no idea of how to do that.

**Comment by acao** [comment]
hello there! the schema fetching is a simple http fetch using the fetcher you provide to GraphiQL. Explorer should have examples of how to set up with GraphiQL, have you checked their repository or documentation?

**Comment by mjarkk** [comment]
Not really looked into examples mostly just googeling but with no result.  
Maybe they have a good example i can use, i'll look into it tomorrow and see if they have anything useful.  

Thanks for the advice

**Comment by acao** [comment]
Here's an example that they made @mjarkk:
https://github.com/OneGraph/graphiql-explorer-example

hope that's helpful!

soon we wil have our own plugin system.

fyi though, with GraphiQL, either `fetcher` or `schema` is required. so `fetcher` is a promise that can be used to retrieve your schema, etc

**Comment by mjarkk** [comment]
Thanks, I've found it!
