### ISSUE TITLE
Auto-completion for fragment-names does not provide Interfaces in the query editor.

### ISSUE THREAD

**Issue by nodkz** [graphql/graphiql#119]
I have **`UserDatable`** Interface in schema, but it does not suggested in fragment names:

<img width="264" alt="screen shot 2016-03-30 at 15 13 23" src="https://cloud.githubusercontent.com/assets/1946920/14137563/17c2c64c-f68a-11e5-8fa4-552c58334ec8.png">

I try investigate problem, but it too difficult for me to make PR. I'm not familiar with codemirror.

**Comment by leebyron** [comment]
Thanks for this report! The fix likely applies to https://github.com/graphql/codemirror-graphql/blob/master/src/hint.js#L151 if you're interested in taking a stab.

What this typeahead currently shows is the possible concrete types for the selection's parent type, but it should also include the interfaces that each of those types implement

**Comment by nodkz** [comment]
Problem for me is to combine `codemirror-graphql` and `graphiql` with webpack and get normal dev environment.  I tried on my webpack kit, but it needs code reformatting. Or webpack/babel tuning.

So if you provide some dev-kit, I will do it with pleasure. I think, that not only me have problem to run it on dev env.

**Comment by leebyron** [comment]
I've got a PR up for this now, but just FYI if you ever would like to contribute to code that operates across modules, unit tests are a good place to start, but also you can use `npm link` to make changes in one repo and then use your recent changes as the npm dependency in another in order to do more manual testing.

**Comment by nodkz** [comment]
Thanks for advice. I'm very appreciate it.

Right now I don't use `npm link` - it very dumb, instead I'm using `resolve.alias` in the webpack config. It supports hot-reload and of course debugging es6 code, not transpiled mash. With webpack only one problem - babel version (some freezed on v5), so need extract `src` folder to the own project.

Also I have zero experience in testing, and past several years try find somebody who show me importance of unit tests and TDD. And now I felt it deeply... with your lib's perfect coverage and how tests helps in open source.

Thank you very much, you and Sebastian are my idols in new react-relay-gql ecosystem. You are inventors of web 3.0!
