### ISSUE TITLE
Support `graphql@15.0.0` release

### ISSUE THREAD

**Issue by IvanGoncharov** [graphql/graphiql#1191]
@acao @benjie Took a long long time than I initially anticipated but I finally released `graphql@15.0.0-rc1`.
It includes a number of small breaking changes:
https://github.com/graphql/graphql-js/releases/tag/v15.0.0-alpha.1
https://github.com/graphql/graphql-js/releases/tag/v15.0.0-alpha.2
https://github.com/graphql/graphql-js/releases/tag/v15.0.0-rc.1

Can you please test it with packages in this repo so I can release `15.0.0` without worrying about breaking GraphiQL?

Note: It doesn't yet include two-stage introspection that I currently working on and will add in the next release since it's not a breaking change.

**Comment by acao** [comment]
awesome work @IvanGoncharov ! i tested it with first alpha before, looking forward to giving it a spin!

**Comment by acao** [comment]
@IvanGoncharov good news, only a few failing tests around error message formatting, and the minified build is looking solid with some manual and automated tests. I'll push a PR  tonight, and hopefully I can check in on some of the breaking changes in more depth, as well as test out the LSP server

**Comment by acao** [comment]
yeah just that one failing test related to graphql-config for the dev server. everything else is looking great overall. I'll keep it open and bump to the next RC if/when that comes.

**Comment by IvanGoncharov** [comment]
@acao @benjie Just release RC2 can you please test it?
https://github.com/graphql/graphql-js/releases/tag/v15.0.0-rc.2

**Comment by acao** [comment]
yes, can do!

**Comment by acao** [comment]
@IvanGoncharov as noted on the PR we merged, we need to remove peer resolutions up to graphql 14 across the board, correct?

**Comment by IvanGoncharov** [comment]
@acao Yes, it would be great!

**Comment by acao** [comment]
@IvanGoncharov i did a patch release where we merged the #1204 bump, and will follow up with peer resolutions!

**Comment by acao** [comment]
then we can follow up with seperate issues for adopting each new feature, i can create a whole project on here for it

**Comment by acao** [comment]
@IvanGoncharov going to close this, we pre-released with 15 support a while ago, and i'm going to open new issues to adopt new features, as we are likely about to rebuild the doc explorer from scratch
