### ISSUE TITLE
Change repo description

### ISSUE THREAD

**Issue by acao** [graphql/graphiql#1205]
Can we change the repository description to say:
`GraphiQL & the GraphQL LSP Reference Ecosystem for building browser & IDE tools`

**Comment by IvanGoncharov** [comment]
Done ✅ 
@acao Do you want any link to demo or docs?
![image](https://user-images.githubusercontent.com/8336157/72044601-b6dc9e00-32e6-11ea-95db-516eea42aafd.png)

**Comment by acao** [comment]
lets have the link go to graphql.org/swapi-graphql, we will have a doc site soon!
