### ISSUE TITLE
buildClientSchema, introspection result missing interfaces

### ISSUE THREAD

**Issue by iambumblehead** [graphql/graphiql#1207]
I'm trying to use graphql's `buildClientSchema` to generate a schema that can be used for mocking/testing components as [seen in this link.][0]

This error is thrown and I'm un-sure how to proceed,
```
Error: Introspection result missing interfaces
```
To try and simplify the situation, I've modified the schema slightly for now to define one type.
```javascript
jsonSchema.__schema.types = [ jsonSchema.__schema.types[0] ];
const schema = buildClientSchema( jsonSchema );
```
and the following is the error result,
```
Error: Introspection result missing interfaces:
{ kind: "OBJECT", name: "Query", possibleTypes: null }
```
The service originating the schema and the sources calling buildClientSchema are using graphql version 14.5.8.

I would be glad if someone would tell what I'm doing wrong and would welcome any solution.

[0]: https://www.apollographql.com/docs/graphql-tools/mocking/#mocking-a-schema-using-introspection

**Comment by acao** [comment]
it looks like you need to build a full schema, rather than a schema with a specific type. you'll need to define the base operation types first, thus the error

also maybe you are looking for graphql/graphql-js? this is the graphiql monorepo for the web IDE and official graphql lsp tooling

**Comment by iambumblehead** [comment]
@acao thank you for looking at my issue. I removed the line which redefines types so that the entire schema is being used (schema is requested using this query btw)
```
            query: '{ __schema { types { kind, name, possibleTypes { name } } } }'
```
The same error still occurs, even when the full schema is used.

I'll take a look at graphql-js. My end goal is to customize query and mutation [behaviour for test components using addMockFunctionsToSchema,]0] in a way that is similar to the [somewhat dated blog post here.][1]

[0]: https://www.apollographql.com/docs/graphql-tools/mocking/#mocking-a-schema-using-introspection
[1]: https://www.freecodecamp.org/news/a-new-approach-to-mocking-graphql-data-1ef49de3d491/#gist93239794

**Comment by acao** [comment]
indeed, the graphql slack is actually a great place for support on this issue, or the apollo spectrum. again this really isnt in our wheelhouse, so im helping as a peer because i dont maintain this code, though I help them review Prs sometimes. we also use the official `graphql` package (aka graphql-js) but we aren’t maintaining it in this repo.

**Comment by acao** [comment]
its confusing i know, the repo names, but the `buildClientSchema` method lives in graphql-js repository

**Comment by iambumblehead** [comment]
@acao I am in the slack general channel and have pasted a link there to this github issue

**Comment by acao** [comment]
Ok, I’ve been sick and havent used a laptop today, but I might hop on later tonight and may be able to get around to helping you with this issue? usually the slack channel is quite helpful, as is the apollo spectrum channel.

**Comment by acao** [comment]
but off the cuff, you'd only have this bug regarding `name: “Query”` if you dont define a root level Query field/object in your schema

**Comment by iambumblehead** [comment]
@acao thank you I will try a few things out using your insight

**Comment by iambumblehead** [comment]
@acao again thank you for your assistance. I tried using a utility file to make the introspection query and it seems to have resolved this issue,
```javscript
const introspectionQuery = require( 'graphql/utilities/introspectionQuery' ).introspectionQuery;
// used in the query as  `query: introspectionQuery`
```
The schema which is returned has more definition that the previous schema

I'll close this ticket later today when I'm further along

**Comment by acao** [comment]
yep that sound about right! that const will be deprecated in 15 since its dynamic now, i’d suggest using:

```js
const { getIntrospectionQuery } = require(‘graphql/utilities/introspectionQuery’)

// and then
query: getIntrospectionQuery()
```

**Comment by iambumblehead** [comment]
@acao :) thank you

**Comment by iambumblehead** [comment]
I haven't quite resolved this issue and am seeing errors related to scalar values needed in the responses.
```json
{
  "message": "GraphQL error: No mock defined for type \"UUID\""
}
```

[This graphql/graphql-js issue][0] might be related? @acao if you are available do you have any ideas for things I might try as a solution?

[0]: https://github.com/graphql/graphql-js/issues/2005

**Comment by iambumblehead** [comment]
This looks very related https://github.com/apollographql/graphql-tools/issues/545

It seems graphql-tools may not be suited for mocking services that use custom scalar values...

**Comment by iambumblehead** [comment]
I found that all of the queries values must be returned and must not be `undefined`, otherwise the mock function must be defined... resolved
