### ISSUE TITLE
[Question] Working JWT token

### ISSUE THREAD

**Issue by carvalhoviniciusluiz** [graphql/graphiql#1208]
Hi!

I'm working with protected route by jwt in the graphql. In the integrated tests can pass the token for inbound authentication everything works great, I would like to know how can I pass the token in the graphiql playground to be able to use the queries..

Thank you very much in advance.

**Comment by acao** [comment]
bom dia!

you can pass the token as a header in the custom fetcher prop which is required for the GraphiQL component. in the webpack example, you can see we set content type for example. so you can either have your own react login flow that then exposes the GraphiQL component once a valid token is retrieved, or ive also seen implementations that retrieve the value from the user session or local storage.

**Comment by carvalhoviniciusluiz** [comment]
Got it, thank you so much for your help.
