### ISSUE TITLE
Fragments on List-types syntax checking

### ISSUE THREAD

**Issue by MartinLorensen** [graphql/graphiql#122]
Hi,

I have a scema with a field of type `[Bar]` (GraphQLList of a GraphQLObjectType derived class called Bar). This works fine, and querying with GraphiQL works fine, except the syntax checking complains about the type on the fragment type.

Am I doing it wrong? Is my GraphQL implementation/scema (graphql-dotnet) wrong? Or is there a bug in the syntax checking for fragment types in GraphiQL?

Below, the first **[** of **[Bar]** is marked with error message "Expected Name, found [".

```
query foo {
  bars {
    ...F1
  }
}

fragment F1 on [Bar] {
  baz
}
```

EDIT: Now found that Relay does not like the syntax either (same error) so I guess I am doing something wrong.

**Comment by dschafer** [comment]
```graphql
query foo {
  bars {
    ...F1
  }
}

fragment F1 on Bar {
  baz
}
```

Should work.

`F1` as a selection set applies to `Bar`, so that's what it is marked as. It can be included on a field that is any non-null/list modification of `Bar`, including `[Bar]`.

**Comment by akhilaudable** [comment]
@MartinLorensen  Could you please share the code for schema with a field type "Bar" (GraphQLList of a GraphQLObjectType derived a class called Bar)? That is for my reference. Thank you.
