### ISSUE TITLE
Monorepo support

### ISSUE THREAD

**Issue by jfrolich** [graphql/graphiql#1274]
Would it be possible to pick up on the closest `.graphqlconfig` in the hierarchy. I have a project/repo with multiple sub projects (website/app/etc.) and they use different schemas. Currently the only thing that seem to work is to put a `.graphqlconfig` in the root of the project.

**Comment by acao** [comment]
great question. this is something that is really up to graphql-config for the most part in terms of handling the filesystem in this manner.

for ourselves, we are currently in the works with providing some options to override the path for the graphql config file or the entire instance itself

**Comment by acao** [comment]
@jfrolich we are about to upgrade to `graphql-config` 3 which may address this

**Comment by jfrolich** [comment]
@acao: Great!

**Comment by acao** [comment]
if you want to try it out, its #1225

**Comment by acao** [comment]
@jfrolich merged!
