### ISSUE TITLE
Logger doesn't work anymore

### ISSUE THREAD

**Issue by divyenduz** [graphql/graphiql#1306]
From the `graphql-language-service-server` package (at least, could be shared further). 

It used to work before the TS rewrite but now logger emits nothing when connected to say VSCode extension now. 

`process.stderr.write` seems to work though.

**Comment by acao** [comment]
thanks for reporting, good to know! i'll take a look here today and be sure to have it fixed before the next alpha

**Comment by divyenduz** [comment]
On the subject of alpha, IDK if it is automated or not, my current workflow is to find the latest alpha via `npm info graphql-language-service-server` (or some package) and use it, probably worth documenting.

**Comment by acao** [comment]
you can also do `npm i graphql-language-service-server@next`

**Comment by yoshiakis** [comment]
In my local environment, even if I use the version of 2.4.0-alpha.1 of `graphql-language-service-service`, logger emits a log file. I tested it following [the pattern A](https://github.com/prisma-labs/vscode-graphql#a-testinglogging-graphql-language-features).

**Comment by yoshiakis** [comment]
I tried the step 7 using the version of 2.4.0-alpha.1 of `graphql-language-service-service` and any logs didn't appear in output section under GraphQL Language Service. However, I also tried it using the version of 2.3.3 and the result is the same, which is that any logs didn't appear!

**Comment by acao** [comment]
yes i will be getting around to this bug, was trying to identify where the regression originally happened

**Comment by yoshiakis** [comment]
@divyenduz Do you mean Logger doesn't emit log file in a temp folder or in output section under GraphQL Language Service in vscode?

**Comment by acao** [comment]
I think that it’s also a lack of stdout?

**Comment by divyenduz** [comment]
> @divyenduz Do you mean Logger doesn't emit log file in a temp folder or it doesn't emit log in output section under GraphQL Language Service in vscode?

Yes that is what I meant

**Comment by yoshiakis** [comment]
@divyenduz Isn't a log file created under `${TMPDIR}/graphql-language-service-logs` directory when you follow [this set-up A](https://github.com/prisma-labs/vscode-graphql#a-testinglogging-graphql-language-features) and run and debug `vscode-graphql` extension?

**Comment by divyenduz** [comment]
@yoshiakis How do I find the `TMPDIR` path?

Also, the way it used to work was that the logs appeared in the [VSCode Language Client's `OutputChannel`](https://github.com/prisma-labs/vscode-graphql/blob/master/src/extension.ts#L56-L58). 

Visually, it should appear here: 

<img width="1176" alt="CleanShot 2020-03-14 at 18 49 43@2x" src="https://user-images.githubusercontent.com/746482/76682750-99002200-6624-11ea-9d3a-820b7aa95480.png">

As you can see, it still shows this one liner message for cmd + click on a symbol. It used to show all sorts of things like hover on a symbol (the whole LSP request/responses)

**Comment by acao** [comment]
@divyenduz want to pair on this real quick?

**Comment by divyenduz** [comment]
This one seems to work because in `graphql-language-service-*` it is a `process.stderr.write`

`process.stderr.write(`Definition not found for GraphQL type ${name}`);`

---

> Want to pair on this real quick?

In 10-20 minutes maybe?

**Comment by acao** [comment]
@divyenduz and I had a session and tried to track down what changed in graphql-languagesrver and client from 3.5.1. My guess is that the language server no longer writes to `stderr` as it did before, and somewhere in `vscode-jsonrpc` this changed over major versions. we decided manually writing to `stderr` in the `Logger._log()` will fix it for now, but it would be great to know why this regression occurred

**Comment by divyenduz** [comment]
Related issues: 
https://github.com/microsoft/language-server-protocol/issues/184#issuecomment-293530628 
https://github.com/microsoft/vscode/issues/20476 
https://github.com/microsoft/language-server-protocol/issues/184

**Comment by divyenduz** [comment]
I think we figured this out! It works now, there are random "undefined" in logs but that is a separate issue 🙌
