### ISSUE TITLE
GraphiQL throws "Uncaught TypeError: Cannot read property 'loc' of undefined" when there are more that one unnamed queries/mutations

### ISSUE THREAD

**Issue by whekin** [graphql/graphiql#1308]
GraphiQL has this behavior since the 0.14.0 version. The 0.13.x is fine

**Comment by acao** [comment]
i think this might be to spec. i know that the spec only allows for anonymous queries and not anonymous mutations

**Comment by acao** [comment]
@whekin aside from the fact that anonymous mutations aren't possible in GraphQL, how should it behave for multiple anonymous  query operations in the operation dropdown? if there were multiple anonymous operations defined, how would you want to choose the one you want?

Execute ->
- Example Named Operation
- Anon Operation 1
- Anon Operation 2

how are you able to execute multiple anonymous operations in 0.13.x? can you show an example of how its working there?

**Comment by acao** [comment]
@whekin i think the feature request here is:

- invalid operations (anonymous mutations) should not be possible

**Comment by benjie** [comment]
Anonymous mutations are definitely allowed in GraphQL. The following is valid:

```graphql
mutation {
  doTheThing
}
```

against the schema

```graphql
type Mutation {
  doTheThing: Int
}
```

**Comment by whekin** [comment]
@acao thanks for the answer! I am not talking about a feature - I am talking about an uncaught error. If I accidentally start writing the second query without a name then a javascript internal error throws and I can see it in console or a huge red screen in dev mode. 0.13.x doesn't throw this error but allows us to choose between unnamed queries. But probably there should be a way to show a user that it is not possible to create several unnamed queries instead of the uncaught error. I don't want to use ErrorBoundary for GraphiQL

**Comment by acao** [comment]
@whekin  indeed yes, I understand the bug better, my bad!

I'll work on this bug this week

**Comment by acao** [comment]
update: wow, this is bug city, found another one here I think too, with duplicate keys

**Comment by acao** [comment]
@whekin we have a resolution, if you want to try the deploy preview there and confirm? i was able to get it working with multiple types of anonymous operations

**Comment by acao** [comment]
https://deploy-preview-1323--graphiql-test.netlify.com/?query=query%20ExampleData%20%7B%0A%20%20allSpecies%20%7B%0A%20%20%20%20species%20%7B%0A%20%20%20%20%20%20name%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A%0A%7B%0A%20%20allPeople%20%7B%0A%20%20%20%20people%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A%0A%7B%0A%20%20allSpecies%20%7B%0A%20%20%20%20species%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A%0A&operationName=ExampleData

**Comment by acao** [comment]
you'll see that the graphql parser itself doesn't like this, but at least the editor and parser doesn't fail

**Comment by whekin** [comment]
@acao Good job!
