### ISSUE TITLE
Can we use graphiql features as API?

### ISSUE THREAD

**Issue by saurav-bhagat** [graphql/graphiql#1335]
I want to query my graphql server using python notebook. But I want to use graphiql features there like highlighting and auto completion. Is this possible?
Thanks

**Comment by acao** [comment]
we provide an LSP server as a CLI. so whichever editors have LSP compatibility plugins will support our LSP server!

**Comment by acao** [comment]
for example, with python:
https://packagecontrol.io/packages/LSP

**Comment by acao** [comment]
LSP = langserver.org. It's an open protocol for implementing language servers. 

@saurav-bhagat I think this might be more appropriate to your needs:
https://github.com/krassowski/jupyterlab-lsp

**Comment by acao** [comment]
@saurav-bhagat  hope that's helpful!
