### ISSUE TITLE
Variables Object wrapped in double quotes

### ISSUE THREAD

**Issue by WilliamHolmes** [graphql/graphiql#134]
According to the [GraphQL spec](https://facebook.github.io/graphql/#Variable), the variables key in the body should be sent as an Object.
GraphiQL client sends this as a string which can cause unexpected behaviour on other GraphQL servers which follow the spec.
```javascript
operationName:"getFilms"
query:"query getFilms($first: Int){↵  allFilms(first: $first) {↵    edges {↵      node {↵        id↵        title↵      }↵    }↵  }↵}↵"
variables:"{"first": 2}"
```

**Comment by WilliamHolmes** [comment]
:bump:

**Comment by rmosolgo** [comment]
Just curious, what's the alternative to strings when sending data over HTTP? How _should_ it be sent? 

In Ruby, I parse the incoming value like this: 

```ruby
variables_string = params["variables"]
variables_hash = JSON.parse(variables_string)
```

Would that work in the above case?

**Comment by asiandrummer** [comment]
Hi @WilliamHolmes, I'm not sure if I understand your question - could I ask you for more information? I'm looking through the specification document and am not seeing anything that mentions in which type variables should be passed in as. What's the unexpected behavior you're having trouble with?

**Comment by leebyron** [comment]
Closing this aging issue.

For some context - there really isn't another way to provide this information. Get & Post data expects a set of keyed strings.

Also, there is no spec for GraphQL servers, however best practices are encoded in the behavior of [express-graphql](https://github.com/graphql/express-graphql).

**Comment by psurrey** [comment]
The official graphql website states that the variables should be json object: http://graphql.org/learn/serving-over-http/#post-request

**Comment by djibarian** [comment]
Quotes are only added by GraphiQL when introspecting through a GET request, not when using POST. Still present in 0.7.2.
