### ISSUE TITLE
yarn run e2e is failing

### ISSUE THREAD

**Issue by nisarhassan12** [graphql/graphiql#1347]
When I run 'yarn run e2e' I get the following:

![image](https://user-images.githubusercontent.com/46004116/74712015-20858b80-5247-11ea-9a49-245848fffa19.png)

I'm running Ubunut Linux in the cloud.

**Comment by acao** [comment]
hello @nisarhassan12 !

you’ll need to run yarn build-bundles first, and possibly yarn build before that. we reconfigured our scripts for github actions. its a short e2e suite that we will add many more cases to soon as GraphiQL’s new ui changes stabilize
