### ISSUE TITLE
Allow fallback to hosted js files without cdn

### ISSUE THREAD

**Issue by ofbeaton** [graphql/graphiql#135]
Tried to use graphiql on an intranet without an internet connection, horrible experience, everything is loaded from cdn.

Similar issues in other flavours of graphiql, seems like I'm not the only one having this issue.
https://github.com/exponentjs/koa-graphiql/issues/1

Could we have a fallback where if the cdn fails to load the files it loads a local copy?

**Comment by dolphin278** [comment]
Right now `jsdelivr` went down, suffering from DDoS attack so GraphiQL became completely unavailable :(

**Comment by asiandrummer** [comment]
Good suggestion @ofbeaton - a fallback local copy makes sense to me.

**Comment by ofbeaton** [comment]
Perhaps something similar to what the initializr template recommends for jquery?
```
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="js/vendor/jquery.min.js') }}"><\/script>')</script>
```

**Comment by asiandrummer** [comment]
Sorry I've been super late with this - [236591] (https://github.com/graphql/graphiql/commit/2365914020348a7ad15eb89e813a46da066fb9ba) adds the fallback to the local copies. Thanks for the suggestion!
