### ISSUE TITLE
minor css linting

### ISSUE THREAD

**Issue by jraller** [graphql/graphiql#1354]
The https://github.com/graphql/graphiql/blob/master/packages/graphiql/src/css/app.css file has `margin: none;` at line 369, but `none` is not a valid option per https://developer.mozilla.org/en-US/docs/Web/CSS/margin. At line 25 there is an example of using `margin: 0;` which may be an appropriate replacement.

Additionally on line 437 there is `text-overflow: -o-ellipsis-lastline;` which might be appropriate to update to `text-overflow: ellipsis;` per https://developer.mozilla.org/en-US/docs/Web/CSS/text-overflow.

There is a usage of `box-orient` on line 428 which is marked as having been superceeded: https://developer.mozilla.org/en-US/docs/Web/CSS/box-orient and https://caniuse.com/#search=box-orient.

There is a ussage of `line-clamp` that might be worth a second glance per https://caniuse.com/#search=line-clamp.

**Comment by acao** [comment]
thanks that's helpful! we are about to replace all of the css shortly, so the toolbar implementation will likely be different, but it's important to now this for accessibility purposes!
