### ISSUE TITLE
Improve prettifying query

### ISSUE THREAD

**Issue by whekin** [graphql/graphiql#1358]
For instance a random query:
![image](https://user-images.githubusercontent.com/39103584/74953585-e2d55e00-5412-11ea-82b9-9fffac3b557b.png)
After prettifying one it becomes this:
![image](https://user-images.githubusercontent.com/39103584/74953703-0dbfb200-5413-11ea-8904-9194d0c8af86.png)
It looks not pretty, so the prettify doesn't work as it should.
Prisma's playground makes a column if there are more args than a number (7) as I know

**Comment by acao** [comment]
thanks for reporting this!
the new graphiql 1.0.0 stable will use a plugin that uses prettier, and users will be able to configure all the normal prettier options

**Comment by acao** [comment]
consolidating to this discussion: #1517, and there's an RFC branch too!
