### ISSUE TITLE
IE11 does not work

### ISSUE THREAD

**Issue by ofbeaton** [graphql/graphiql#136]
Loading graphiql in IE11 does not appear to work. The GUI appears but interacting with it fills the console with errors.

Typing in the query box procudes a lot of:

```
Unable to get property 'updateSizes' of undefined or null reference
File: graphiql.min.js, Line: 1, Column: 24155
```

Hitting the run button gives:

```
'Promise' is undefined
File: react.min.js, Line: 14, Column: 17120
```

I tried it with 3 different versions of IE11 on 2 different windows 7 computers.
- IE 11.0.9600.18204 (update version 11.0.28)
- IE 11.0.9600.18230 (update version 11.0.29)
- IE 11.0.9600.17843 (update version 11.0.20)

My server setup was just done a few days ago:

```
{
  "dependencies": {
    "dataloader": "^1.2.0",
    "express": "^4.13.4",
    "express-graphql": "^0.5.1",
    "graphql": "^0.5.0",
    "graphql-sequelize": "^1.1.1",
    "lodash": "^4.12.0",
    "mysql": "^2.10.2",
    "sequelize": "^3.23.1"
  },
  "devDependencies": {
    "babel-cli": "^6.8.0",
    "babel-polyfill": "^6.8.0",
    "babel-preset-es2015": "^6.6.0",
    "graphiql": "^0.7.1",
    "react": "^15.0.2",
    "react-dom": "^15.0.2"
  },
```

and

```
[root@]# node --version
v6.1.0
[root@]# npm --version
3.8.6
```

**Comment by leebyron** [comment]
Thanks for the report,

Could you please use the non-minified versions of react and graphiql to provide more useful debugging information?

**Comment by joelgriffith** [comment]
@ofbeaton this is fixed now that https://github.com/graphql/graphiql/pull/189 is merged. We should probably close this as I can verify functionality in both IE11/IE10.

Thanks!

**Comment by ofbeaton** [comment]
Thanks for fixing this! I'll re-open if I get it again after updating.

**Comment by joelgriffith** [comment]
I'm not sure if it's out in `npm` yet, or what that process looks like, but should be dropping soon
