### ISSUE TITLE
chore(UI): history query -> marked fav is too small.

### ISSUE THREAD

**Issue by pranshuchittora** [graphql/graphiql#1378]
Hi,
The queries in the history panel can be marked favourite by click on the :star:  icon, it can be marked un-fav in the same fashion.

The icon is too small to be clicked, additionally, padding can be added to increase the action area.

![Screenshot from 2020-02-26 23-02-50](https://user-images.githubusercontent.com/32242596/75371838-816b2e80-58ed-11ea-98d8-326fa8982f5c.png)

### Q. On clicking there's a className which gets added/removed. Unfortunately, I am not able to find the corresponding CSS class definition. 
https://github.com/graphql/graphiql/blob/1563b6029c5d2e2aeea90ab4ff48742d40538af2/packages/graphiql/src/components/HistoryQuery.tsx#L91

**Comment by acao** [comment]
we are about to implement a redesign, so most of this will go away. see the pinned issue!

**Comment by pranshuchittora** [comment]
> we are about to implement a redesign, so most of this will go away. there is a pinned issue if you want to discuss the new redesign!

Thanks for the update :+1:
