### ISSUE TITLE
Unable to build schema using buildSchema

### ISSUE THREAD

**Issue by schandrasekhar** [graphql/graphiql#1385]
My schema end point returns this string

"Directs the executor to include this field or fragment only when the if argument is true"
directive @include(
    "Included when true."
    if: Boolean!
  ) on FIELD | FRAGMENT_SPREAD | INLINE_FRAGMENT

"Directs the executor to skip this field or fragment when the if 'argument is true."
directive @skip(
    "Skipped when true."
    if: Boolean!
  ) on FIELD | FRAGMENT_SPREAD | INLINE_FRAGMENT

"Marks the field or enum value as deprecated"
directive @deprecated(
    "The reason for the deprecation"
    reason: String = "No longer supported"
  ) on FIELD_DEFINITION | ENUM_VALUE

union streamItem = Ad | Content | EditorialPackage | EntityCard
.
.
.
.

when trying to build schema object using

`
const buildSchema  = require('graphql').buildSchema;
const schema = buildSchema(schemaString);      
`

i am getting this error

`{ GraphQLError: Syntax Error GraphQL request (5:1) Unexpected String "Directs the executor to include this field or fragment only when the `if` argument is true"
4: 
5: "Directs the executor to include this field or fragment only when the if argument is true"
   ^
6: directive @include(
    at syntaxError (/node_modules/graphql/error/syntaxError.js:31:15)
    at unexpected (/node_modules/graphql/language/parser.js:996:33)
    at parseDefinition (/node_modules/graphql/language/parser.js:155:9)
    at parseDocument (node_modules/graphql/language/parser.js:109:22)
    at parse (/node_modules/graphql/language/parser.js:46:10)
    at buildSchema (/node_modules/graphql/utilities/buildASTSchema.js:469:43)
    at getRequest.then (/src/schema.js:42:32)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  message: 'Syntax Error GraphQL request (5:1) Unexpected String "Directs the executor to include this field or fragment only when the `if` argument is true"\n\n4: \n5: "Directs the executor to include this field or fragment only when the `if` argument is true"\n   ^\n6: directive @include(\n',
  locations: [ { line: 5, column: 1 } ],
  path: undefined }

`

this is my package json
`
  "dependencies": {
    "env": "0.0.2",
    "express": "4.17.1",
    "express-graphql": "0.9.0",
    "graphql": "14.6.0",
    "path": "0.12.7"
  },

Are comments invalid for directives or is there a bug with `buildSchema`

**Comment by schandrasekhar** [comment]
looks like comment in schema changed from `#` to `"`, hence `buildSchema` is breaking. is there a fix for this ?

**Comment by acao** [comment]
hello @schandrasekhar ! this is the `graphiql` repo, i think you want https://graphql/graphql-js

that said, your issue is that you need to triple quote the comment blocks:

```graphql
"""my comment"""
type MyType {
	"""inline comment"""
	field: String
}
```
