### ISSUE TITLE
Docs can go back to root

### ISSUE THREAD

**Issue by crapthings** [graphql/graphiql#139]

**Comment by asiandrummer** [comment]
Hello @crapthings - do you mean docs cannot go back to root? I'm not sure I understand your issue. Would you mind being more specific please?

**Comment by crapthings** [comment]
i think we should add a convenient method to go back to root node

**Comment by asiandrummer** [comment]
@crapthings I see. I'm assuming you're coming across the use case having to navigate into multiple documentation entries, and clicking back button many times instead of one is a bit weird. I'm thinking maybe `Documentation Explorer` title could be linked to the root node of the doc explorer.

**Comment by crapthings** [comment]
@asiandrummer yeah, it can be very handy!

**Comment by joelgriffith** [comment]
Can we close this? seems like the related PR is done

**Comment by wincent** [comment]
I think so. https://github.com/graphql/graphiql/pull/244 ended up making a smaller change than proposed here, but I don't think the original proposal is going to make it, so we may as well close this. Thanks to everybody who participated!
