### ISSUE TITLE
bug: No command definition for "server" int the language-service

### ISSUE THREAD

**Issue by pranshuchittora** [graphql/graphiql#1396]
Hi,
While working with the `language-service` CLI, I found out that there's no definition for the command `server`.

https://github.com/graphql/graphiql/blob/932a8a1e39a5b60097a7660d71a0620b3ad8eea9/packages/graphql-language-service/src/client.ts#L54

1. What's your opinion regarding this @acao  ?
2. And what's the expected function of the `server` command?

**Comment by acao** [comment]
@pranshuchittora been super busy on the web lsp side, but ill check in on this soon! thanks for your help

**Comment by acao** [comment]
here is where the `server` command is handled!
https://github.com/graphql/graphiql/blob/33fe6e1082c8886d90511ed283f5948620f032f8/packages/graphql-language-service-cli/src/cli.ts#L111

**Comment by acao** [comment]
that is confusing though, should maybe refactor so it makes more sense
