### ISSUE TITLE
`prepublish` scripts are deprecated

### ISSUE THREAD

**Issue by Smilefounder** [graphql/graphiql#1398]
I have received this error message during install and setup environment. Is it better if we could upgrade the install script to adapt to latest version of npm?

![image](https://user-images.githubusercontent.com/3785721/75784105-473dd900-5d94-11ea-853b-08814209c886.png)

**Comment by acao** [comment]
@Smilefounder if you can, please look at https://github.com/graphql/graphiql/blob/master/DEVELOPMENT.md first. npm does not work with this repo.
