### ISSUE TITLE
How to set field name(s) for automatically added leaf fields

### ISSUE THREAD

**Issue by alvaro1728** [graphql/graphiql#1401]
When the user asks for an object field without explicitly asking for one of its attributes, the UI will automatically set it to "id".  For example:

```
{
  SomeObject {
    name
    address
  }
}
```
becomes this after the query is executed:

```
{
  SomeObject {
    name
    address {
      id
    }
  }
}
```

And the UI highlights the "id" field in yellow and shows a tooltip: **Automatically added leaf fields**.  It happens here: https://github.com/graphql/graphiql/blob/0f99f17211fe7c674eabd7dfc39800ee23b0931d/packages/graphiql/src/components/GraphiQL.tsx#L677

Is there a way to control what the default leaf field(s) get set to?  In my case, I would prefer to set it to "_id" instead.

Thanks,
Alvaro

**Comment by alvaro1728** [comment]
Figured it out:

```
    function getDefaultFieldNames(type) {
      return type.getFields && type.getFields()._id && ["_id"];
    }

...

      React.createElement(GraphiQL, {
          ...
          getDefaultFieldNames: getDefaultFieldNames
      })
```

Thanks,
Alvaro

**Comment by acao** [comment]
it automatically adds fields that are required, yes
