### ISSUE TITLE
Update to new directive specification

### ISSUE THREAD

**Issue by calebmer** [graphql/graphiql#142]
Currently GraphiQL breaks with `graphql-ruby` because it uses fields no longer in the specification ([here](https://github.com/graphql/graphiql/blob/master/src/utility/introspectionQueries.js#L29-L31)). See [this](https://github.com/rmosolgo/graphql-ruby/pull/121/files#diff-c919d8ac76e334181fa31d6a5e188702L7) diff and rmosolgo/graphql-ruby#143 for more information.

\cc @maxcodes

**Comment by asiandrummer** [comment]
@calebmer - I'm on it. Thanks for the report!

**Comment by asiandrummer** [comment]
[b9dba9](https://github.com/graphql/graphiql/commit/b9dba9afd1b222193e8626a00c6e2ce75e47706d) fixes this - thanks again for the report!

**Comment by calebmer** [comment]
:tada:

**Comment by pupeno** [comment]
I'm experiencing this error in the GraphiQL Chrome extension. Since it looks like this was solved almost a year ago, is the Chrome extension abandoned?
