### ISSUE TITLE
Discussion: New features/UX changes for playground in addition to it's existing features?

### ISSUE THREAD

**Issue by acao** [graphql/graphiql#1444]
- What new features are most in demand for the playground preset?
- What feature requests can we cross reference from the soon to be retired prisma-labs/graphql-playground repo?
- how can we channel some of this into graphiql plugin proposals that can be used by other presets?

**Comment by penx** [comment]
An 'http headers' tab, as per discussion on https://github.com/graphql/graphiql/issues/59

**Comment by acao** [comment]
hey @penx! that feature already exists in playground, so it's already implicitly part of the new preset, and will be available as a plugin for other presets. 

I'm specifically asking for new features that `graphql-playground` itself does not already have that can be added to the playground specific preset spec, on behalf of the new team. So I'm looking for feature request issues from `prisma-labs/graphql-playground` repo that can act as candidates to migrate over.

**Comment by acao** [comment]
regarding that feature, we hope to have a whole network sidebar with per-project default headers, verbs per operation type, other settings, in addition to the headers tab as a standalone plugin. because HTTP is not a requirement for GraphiQL, in 0.x or 1.x, it won't be part of core but all via closely maintained official plugins. the headers tab specifically will be maintained by the proposed  playground preset crew referenced above!

**Comment by iquabius** [comment]
Export/Import operations as collections: prisma-labs/graphql-playground#6.

This is so useful for collaborating with team member and for working on different machines.

**Comment by acao** [comment]
nice! we were planning on introducing a plugin for importing queries as a collection early on, in beta or the first few major versions.
