### ISSUE TITLE
Documentation for GraphQL subscriptions in GraphiQL

### ISSUE THREAD

**Issue by killjoy2013** [graphql/graphiql#1486]
We're using graphiql in our projects and very happy with it. I wonder if there is a projection about adding subscriptions as well? I'd like to work on it if you have such a plan.

Besides, I've read somethings about graphiql plugin system. What is the current stuation?

Thanks & regards

**Comment by acao** [comment]
there is subscription support already!

there is a pinned issue where you can learn more about the current progress of the plugin API rfcs!

**Comment by acao** [comment]
if you have any other questions, you can reach me in the discord link in the docs! thanks :)

**Comment by acao** [comment]
I think we can re-open this for documenation purposes actually. This needs to be improved!

**Comment by benjie** [comment]
@killjoy2013 Am I right in guessing you're using express-graphql's GraphiQL?

**Comment by killjoy2013** [comment]
I'm using GrphiQL from nuget.org
https://www.nuget.org/packages/GraphiQL/
.
Querying a .net core backend.

**Comment by benjie** [comment]
I suspect you're better following the relevant issue on that project then: https://github.com/JosephWoodward/graphiql-dotnet/issues/8

**Comment by acao** [comment]
This has been taken care of!

You can use `@graphiql/create-fetcher` to use `graphql-ws` for subscriptions now! we also have a server example in `packages/graphiql/test/schema.js` if that's useful. we also have end to end tests to confirm subscriptions work!
