### ISSUE TITLE
Create Security Best Practices Badge for GraphiQL

### ISSUE THREAD

**Issue by caniszczyk** [graphql/graphiql#1500]
https://bestpractices.coreinfrastructure.org/en

**Comment by caniszczyk** [comment]
@brianwarner can you help @acao out with doing this for the repo?

It's a best practice for LF related projects to go through with this.

**Comment by acao** [comment]
this looks fantastic. some the criteria actually reminds me of a HIPAA audit. how should I go about this? I can prepare a writeup that addresses items one by one, there are a few that most definately need work

**Comment by caniszczyk** [comment]
@acao you can just login + create an account here: https://bestpractices.coreinfrastructure.org/en

and then automatically associate graphiql via the tool and work through the assessment, once you're done, you'll be able to add a badge to the graphiql README from the tool, i.e., https://bestpractices.coreinfrastructure.org/en/projects/569

**Comment by acao** [comment]
oh thats what they mean! for some reason, the CTA gave me the impression that i needed to do something else before i go to "get my badge now", so i jumped straight to the criteria. i didnt realize that meant "apply for a badge" bahaha ok

**Comment by acao** [comment]
@caniszczyk added via PR #1503! thanks for the heads up
