### ISSUE TITLE
GraphQL authorization issue of deviceId

### ISSUE THREAD

**Issue by hassaaneforte** [graphql/graphiql#1505]
this is my mutation...
mutation abc {
loginUser(email: "example@yopmail.com",
password: "123456789", deviceId: "1234")
{
_id
email
jwtToken {
token
createdAt
}
password
}
}

1st i logged in as example@gmail.com then i logout using
mutation abc {
logout(deviceId: "123")
{
_id
}
}

then i logged in again using all different credientials except for deviceId.. i used same deviceId as before
mutation abc {
loginUser(email: "anotherexample@gmail.com",
password: "abc123xyz", deviceId: "1234")
{
_id
email
jwtToken {
token
createdAt
}
password
}
}
but it logs in on example@gmail.com.. i dont understand why.. only if i change deviceId then it will login to anotherexample@gmail.com
can someone help me with this issue?

this is my mutation.js code
![image](https://user-images.githubusercontent.com/63094913/79505629-19fc7000-804e-11ea-933a-c451b0c92a2b.png)

and this is my user.js code
![image](https://user-images.githubusercontent.com/63094913/79505646-21bc1480-804e-11ea-82b5-b024fe5a6c69.png)

**Comment by acao** [comment]
@hassaaneforte I dont know if we can help you, it seems maybe you want to address this support with apollo server or whichever server runtime you are using. I highly reccomend their Spectrum server! This repository is for GraphiQL, which is a web based IDE for querying GraphQL Schemas. Best of luck, and happy GraphQL-ing :)
