### ISSUE TITLE
Mode graphql failed to advance stream.

### ISSUE THREAD

**Issue by yanickrochon** [graphql/graphiql#1514]
While testing, some invalid character got inserted in the text area and now the interface won't load. I have tried resetting local cache, URL, restarting the GraphQL server... the error _always_ comes back somehow.

Would be nice to have a "reset" button somewhere, and it would be nice to know how I can solve this issue right now.

**Comment by acao** [comment]
@yanickrochon what version are you using? this bug was fixed a while ago, in 0.16.x or 0.17.x

**Comment by acao** [comment]
it's a nasty bug, you'll need to clear application storage (local storage) to reset it

**Comment by yanickrochon** [comment]
I did clear the application storage, but the error keeps happening. For for which version of this package, this is the one coming with `express-graphql@0.9.0`.

**Comment by acao** [comment]
ah i see, looks like `express-graphql` is still shipping with an older verison by default. can you see what happens if you just install the latest graphiql locally, and try restarting the server? i think it resolves graphiql from node modules at server compile time now. Looks like I need to update the docs over there.

**Comment by acao** [comment]
@yanickrochon yes seems your `graphql` version seems fine, but you need to install the latest `graphiql` package locally.

**Comment by yanickrochon** [comment]
@acao I was curious to which version of `graphiql` I have installed, and I can't find it anywhere. Does it mean that some package ships with some pre-bundled one?

**Comment by acao** [comment]
if you run `yarn why graphiql`, you'll see `express-graphql` depends on an older version of it. you will need to manually install `graphiql`, or add `"resolutions": { "graphiql": "0.17.5" }` to package json

**Comment by yanickrochon** [comment]
@acao well, then something _really_ funky is going on because

```
$ yarn why graphiql
yarn why v1.19.1
[1/4] Why do we have the module "graphiql"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
error We couldn't find a match!
Done in 0.54s.
```

**Comment by acao** [comment]
here is more context on the bug itself:
https://github.com/graphql/graphiql/issues/735#issuecomment-522428215

i don't think there are any resolutions to this issue with express, but it will let you know more about the nature of the bug.

**Comment by acao** [comment]
ok then still I just suggest adding `graphiql`. let me know how that goes in our discord, if you see on our readme. i will close this as we don't handle support issues here, only bugs and feature requests. thanks!

**Comment by yanickrochon** [comment]
@acao just to be clear, which discord channel? (Nothing you suggested works.)
