### ISSUE TITLE
GraphiQL fail with error: Module not found: Can't resolve 'graphql/validation/rules/KnownFragmentNames'

### ISSUE THREAD

**Issue by ODINAKACHUKWU** [graphql/graphiql#1519]
I have a React app bootstrapped with `create-react-app`. On `npm start` fails with the error:

`Module not found: Can't resolve 'graphql/validation/rules/KnownFragmentNames' in '/home/odinakachukwu/Documents/repos/apollo-client/node_modules/codemirror-graphql/node_modules/graphql-language-service-utils/esm'`

I'm using => "graphiql": "0.17.5"

**Comment by acao** [comment]
graphql 0.17.5 predates graphql 15, you will need to use grahql 1.0.0 alpha for graphql 15 support!

**Comment by acao** [comment]
let me know if you have any other issues in discord, the link is in the readme. enjoy!

**Comment by ODINAKACHUKWU** [comment]
>@acao let me know if you have any other issues in discord, the link is in the readme. enjoy!

After installing graphiql 1.0.0 alpha 8 I still get the error:

```
./node_modules/codemirror-graphql/node_modules/graphql-language-service-utils/esm/validateWithCustomRules.js
Module not found: Can't resolve 'graphql/validation/rules/KnownFragmentNames' in '/home/odinakachukwu/Documents/repos/apollo-client/node_modules/codemirror-graphql/node_modules/graphql-language-service-utils/esm'
```

**Comment by acao** [comment]
oh, oops my bad, forgot to ask, did you install `graphql` as a peer dependency?

**Comment by ODINAKACHUKWU** [comment]
Yea, just did that and it works fine now. Thanks so much!
