### ISSUE TITLE
__typename doesn't work in subscriptions generated by graphiql

### ISSUE THREAD

**Issue by btilly** [graphql/graphiql#1527]
The following image shows the result of creating a new subscription in graphiql by clicking new subscription and selecting fields, then trying to run it.

<img width="1134" alt="Screen Shot 2020-05-13 at 1 15 12 PM" src="https://user-images.githubusercontent.com/136662/81860670-e82adc00-951b-11ea-9c45-7ad45166ec5a.png">

As you see, the query is:
`subscription MySubscription {
  __typename
  listen(topic: "msgSubscriptionDemo") {
    relatedNode {
      ... on PubSubMessage {
        payload
      }
    }
  }
}`

And we generate an error from Postgraphile because `"Subscription \"MySubscription\" must select only one top level field."`.

The error is because of `__typename`.  If I manually take it out of the query, the subscription works.  However the whole point of graphiql is to let people build queries like this with point and click without having to know graphql that well.  So in the case of subscriptions, it shouldn't insert that line.

**Comment by benjie** [comment]
This seems to be an issue with adding a new subscription within GraphiQL Explorer in PostGraphile’s GraphiQL; so the fault doesn’t lie here. I’ll open an issue against PostGraphile to track down the source 👍

**Comment by acao** [comment]
thanks @benjie!

I wonder if we should add an option to the LSP for automatically adding `__typename`

**Comment by benjie** [comment]
An option for that would be nice, particularly for Apollo. But not to the root of subscriptions (or the root of mutations, though it’s allowed there it doesn’t really make sense). It should definitely default to disabled if added.

**Comment by acao** [comment]
I'm fairly sure it just showed up after a particular upgrade to `graphql@14.x`
