### ISSUE TITLE
Bad type definition files in alpha release

### ISSUE THREAD

**Issue by Rugvip** [graphql/graphiql#1530]
The `.d.ts` files in the alpha release contains some bad imports, stemming from the package-relative imports like https://github.com/graphql/graphiql/blob/ce926bb7ab1e6fbf978ec53a0449c33869073c7d/packages/graphiql/src/components/QueryEditor.tsx#L15

A couple were fixed in https://github.com/graphql/graphiql/pull/1487, but there are a few more in the repo.

You likely don't want to set baseUrl [here](https://github.com/graphql/graphiql/blob/ce926bb7ab1e6fbf978ec53a0449c33869073c7d/packages/graphiql/tsconfig.json#L8), as that is what allows those imports during type checking of this project, but not in the published package. Although I haven't looked at what impact that will have on the rest of the build.

**Comment by acao** [comment]
thank you! i will address this. this import path has been causing a bunch of issues, and I keep forgetting that we've fixed it *only* in the rewrite

**Comment by acao** [comment]
oops, it auto-closed. I'll be kicking out a new release later today!
