### ISSUE TITLE
onEditVariables is not triggered on first render

### ISSUE THREAD

**Issue by krishnan-r** [graphql/graphiql#1532]
I'm trying to use `<GraphiQL>` as a controlled component, with a global redux store.

- In `graphiql@1.0.0-alpha.8`, `onEditVariables` is not triggered on the first render. It works fine in `graphiql@0.17.5`. 

I noticed that in 1.x, VariableEditor ignores change events till the first `componentDidUpdate` https://github.com/graphql/graphiql/blob/ce926bb7ab1e6fbf978ec53a0449c33869073c7d/packages/graphiql/src/components/VariableEditor.tsx#L62  I guess `ignoreChangeEvent` should be initialized to false

- Also both versions do not debounce `onEditVariables`, whereas `onEditQuery` seems to be debounced. 

Happy to contribute/raise a PR for this.

**Comment by acao** [comment]
@krishnan-r thanks for reporting, a PR for this would be fantastic! I might get to it myself later today anyways.

**Comment by acao** [comment]
if you could do one PR for the bugfix, and a seperate for the debounce, that would be fantastic

**Comment by krishnan-r** [comment]
Sure, I'll make the PRs
