### ISSUE TITLE
Cannot find module 'graphql/validation/rules/PossibleTypeExtensions'

### ISSUE THREAD

**Issue by Karthickgreets99** [graphql/graphiql#1552]
Error: Cannot find module 'graphql/validation/rules/PossibleTypeExtensions'
      Error: Cannot find module 'graphql/validation/rules/PossibleTypeExtensions'

graphql  : 0.13.2 
apollo-server@2.12.0
 └─┬ apollo-server-core@2.12.0
  └─┬ apollo-engine-reporting@1.7.1
   └── apollo-graphql@0.4.1

**Comment by acao** [comment]
@Karthickgreets99 it looks like you're using a very old version of https://github.com/graphql/graphql-js, you might ask for help in that repo!

The code here is not used in your setup.
