### ISSUE TITLE
Cant get variables to work

### ISSUE THREAD

**Issue by stigi** [graphql/graphiql#156]
Hi,

I'm running a very simple query with a variable, but when execute the schema I get an error that the variable isn't declared, but I pass it in a Hash.

```ruby
[1] pry(#<Cruise::App>)> query_variables
=> {"channel_id"=>"1"}
[2] pry(#<Cruise::App>)> query_string
=> "{\n channel(id:$channel_id) {\n  id\n }\n}"
[3] pry(#<Cruise::App>)> Schema.execute(query_string, variables: query_variables)
=> {"errors"=>[{"message"=>"Variable $channel_id is used by  but not declared", "locations"=>[{"line"=>2, "column"=>13}]}]}
[4] pry(#<Cruise::App>)> GraphQL::VERSION
=> "0.17.2"
```

For completeness sake here's my action code. The query comes from a graphiql instance I've set up myself (possible source of errors, but the values arriving in ruby do look ok).
```ruby
post :index do
  query_string = params['query'] || ""
  query_variables_string = params['variables']
  query_variables = query_variables_string ? JSON.parse(query_variables_string) : {}
  content_type :json
  Schema.execute(query_string, variables: query_variables).to_json
end
```

Am I doing anything obviously wrong here which I'm to blind to see? What's a good way to further debug this?

Thanks

**Comment by stigi** [comment]
Figured out the issue. Had to pass the variable in the query. With an updated query it worked:

```graphql
query($channel_id: ID!) {
 channel(id: $channel_id) {
   id
 }
}
```

**Comment by antoniopacheco** [comment]
@stigi , thanks this works for the playgroud, but can't get apollo client useQuery to pass the variables, I can't build the query like that because it throws an error 
`
const GET_GREETING = gql`
    {
        query($localityShortName: String! $stateShortName: String! $countryShortName: String!){ extinguishersByLocality(
            localityShortName: $localityShortName
            stateShortName: $stateShortName
            countryShortName: $countryShortName
    ) {
        price
        branch {
            name
            company {
                name
            }
        }
    }
    }
    }
`;
`
