### ISSUE TITLE
Error: Cannot find type definition file for 'codemirror/addon/hint/show-hint'

### ISSUE THREAD

**Issue by HermanZzz** [graphql/graphiql#1562]
Using graphiql@1.0.0-alpha.11 with webpack. 
Meet the error in 'node_modules/graphiql/dist/components/GraphiQL.d.ts':
`/// <reference types="codemirror/addon/hint/show-hint" />`.
Cannot find type definition file for 'codemirror/addon/hint/show-hint'.

**Comment by HermanZzz** [comment]
Please comment if I miss some install steps. Thanks

**Comment by acao** [comment]
wanna try and install `@types/codemirror` and see if that helps?

hmm, gonna have to address this though, thanks for the heads up

**Comment by HermanZzz** [comment]
Thanks. It works. Cool to be addressed anyway.

**Comment by acao** [comment]
doesn't seem to be an issue in our webpack example config, is there a detail I'm missing here?

**Comment by HermanZzz** [comment]
I just install graphiql into our existed project as a component. But need to install @types/codemirror to  wipe out the packing error. I may try the demo then.

**Comment by acao** [comment]
ah ok. so in the demo webpack config, we don't consume `node_modules` with the typescript loader, so that package is not needed in the example case. I'll be closing this as it diverges from our reccomended webpack config, and we can't document every variation, if that makes sense?

**Comment by HermanZzz** [comment]
Sure. get it
