### ISSUE TITLE
Problem: codemirror highlight

### ISSUE THREAD

**Issue by ksaos** [graphql/graphiql#1564]
I follow the graphiql-webpack example and run the graphiql locally. 
with graphiql@1.0.0-alpha.11, React@16 and webpack.

But the editor missing all the coding features like code highlight, auto-complete, or error warning.

![WX20200601-143055](https://user-images.githubusercontent.com/66239833/83381989-aa332080-a414-11ea-8d01-d0ee371f30e0.png)

How to fix it? Thanks!

**Comment by acao** [comment]
here's the latest master build, strange!

https://graphiql-test.netlify.app/webpack/

**Comment by acao** [comment]
did you run `yarn build` at the root first?

**Comment by ksaos** [comment]
Fix it by uninstalling the previous local codemirror package and re-installing the graphiql again.

**Comment by ksaos** [comment]
It supports highlight now, but still missing auto-complete while editing.

**Comment by acao** [comment]
what do you see in doc explorer?

**Comment by ksaos** [comment]
Get it. It's not a valid schema structure. Thanks
