### ISSUE TITLE
Usage: adding custom Toolbar by no overriding

### ISSUE THREAD

**Issue by HermanZzz** [graphql/graphiql#1570]
I try to custom the toolbar. 
Any convenient way to add a GraphiQL.Menu with the four default existed buttons?
Thanks.

**Comment by HermanZzz** [comment]
Or how to easily import and reuse the existed button function like `handlePrettifyQuery` or `handleCopyQuery`?

**Comment by harshithpabbati** [comment]
@HermanZzz yes, you can use the function `handleCopyQuery` like this

```
 handleCopyQuery = () => {
    this.graphiQL = this.ref.current;
    const editor = this.graphiQL.getQueryEditor();
    const query = editor && editor.getValue();
    if (!query) {
      return;
    }

    copyToClipboard(query);
  };

```

**Comment by HermanZzz** [comment]
Yes. But It's kinda pointless to re-implement all the four functions.
Is there any possible way to handle it, to add a new button based on the default toolbar?

**Comment by harshithpabbati** [comment]
AFAIK there isn't a way to do that. Am I right @acao ?

**Comment by HermanZzz** [comment]
OK thanks @harshithpabbati . Rewrite the default functions though, duplicate code exists.

**Comment by acao** [comment]
we have a new version 2.0.0 that will offer better customizations for this.

**Comment by HermanZzz** [comment]
look forward to it. cheers~

**Comment by halvespereira** [comment]
I'm also trying to to add to the toolbar without deleting the default ones (Prettify, Merge, Copy, History). Is version 2.0.0 ready to be used? If so, where can I find how to accomplish this?
If not, could you share the functions `handleHistory` and `handleMerge`. I have already found `handleCopyQuery` and `handlePrettify`. 

Thank you.

**Comment by whyleee** [comment]
I found this is possible already: use `toolbar.additionalContent` prop in `GraphiQL` component:

```js
ReactDOM.render(
  React.createElement(GraphiQL, {
    fetcher: fetcher,
    toolbar: {
      additionalContent: [
        React.createElement(GraphiQL.Button, {
          label: 'My button'
          onClick: () => alert('My button clicked')
        })
      ]
    }
  }),
  document.getElementById('graphiql'),
);
```
