### ISSUE TITLE
Big queries result in apache-errors

### ISSUE THREAD

**Issue by Zombaya** [graphql/graphiql#159]
I'm trying to execute a large query using graphiQL.  Because the whole query gets inserted into the referer-field of the header, my apache-server rejects the request with an error 400 with following contents:

> Bad Request.
> 
> Your browser sent a request that this server could not understand.
> Size of a request header field exceeds server limit.
> Referer

Would it be possible not to add the whole query to the referer-header?  I don't believe it is possible to adjust the allowed header size in apache.

**Comment by KyleAMathews** [comment]
I assume you're using GET not POST? Any reason not to just switch to
putting the query in the POST body?

**Comment by Zombaya** [comment]
I'm using Post.

I've checked my template and I encoded my whole query into the url by using updateURL().  I left it out now and no more problems for me.

I guess this isn't really a problem of graphiql, just of the template I used.

This ticket can be closed, for what I am concerned.

**Comment by asiandrummer** [comment]
Hello @Zombaya - as you pointed out I'm not sure if the referer-header size issue could be solved with GraphiQL. I'll close this issue, but please reopen if you find out other problems that you think are related!

**Comment by corp-ray** [comment]
Is there a way to force all graphQL requests to use POST and not change the URL query string?
Our long queries fail with a similar message whenever the URL gets too long.

**Comment by wincent** [comment]
@corp-ray: You can change the way the requests are fetched by passing in a custom `fetcher` when instantiating the `<GraphiQL />` component.

The URL query string isn't modified by default. If you are seeing it get modified that must be coming from whatever is rendering your `<GraphiQL />` component. For example, [the example in the repo here](https://github.com/graphql/graphiql/blob/c573490d1326b5cedec31cf42a77d7ac53fbb099/example/index.html#L103) uses `history.replaceState` to set it, but there is no requirement to do so.

**Comment by corp-ray** [comment]
OK cool thanks @wincent :) I see now the code that is updating the URL.
