### ISSUE TITLE
Github left side explorer

### ISSUE THREAD

**Issue by lielran** [graphql/graphiql#1591]
I really liked Github left side explorer - I can speed up to work in building queries and explanatory the graph options. 
how can I enable it on Graphiql or Github implement/extending this graphiql feature

![image](https://user-images.githubusercontent.com/1004667/85265335-c9085e00-b47a-11ea-80d8-dbaa968fe08a.png)

**Comment by Nishchit14** [comment]
It's a GraphiQL's [plugin](https://github.com/OneGraph/graphiql-explorer), you can install and use it as a plugin with your own GraphiQL interface.

**Comment by mvaneijgen** [comment]
@Nishchit14 is there a guide on how to install this?

**Comment by acao** [comment]
yes! just follow this example:

https://github.com/OneGraph/graphiql-explorer-example
