### ISSUE TITLE
 Can not find module: graphiql/graphiql.min.css

### ISSUE THREAD

**Issue by powpi2000** [graphql/graphiql#1609]
when I use examples/graphiql-create-react-app
yarn start will produce Cannot find module: 'graphiql/graphiql.min.css'
how to build graphiql.min.css

**Comment by acao** [comment]
did you run `yarn build-bundles` in the root first?

**Comment by acao** [comment]
readme has been updated, my bad I didn't review that PR well enough! you definately need to build the graphiql bundle first in order to be able to import graphiql in the example
