### ISSUE TITLE
vscode-graphql, LSP, IDE initiative

### ISSUE THREAD

**Issue by acao** [graphql/graphiql#1615]
Getting things in better shape for [`vscode-graphql`](https://github.com/prisma-labs/vscode-graphql/) which I am now maintainer of!

## `graphql-language-service-interface`
- [x] finish upgrading to `graphq-config@3.0.x` - schema loading, file loading, etc
- [x] new options argument for `getAutocompleteSuggestions` 
  - allow use of implicit fragment definitions for completion
  - option to return all completion options on empty or even invalid input (ala `codemirror-graphql`, etc)
- [x] `getOutline` for workspaces
- [x] `getDefinition` for workspaces
- [ ] when autocompleting a field that expands:
  - automatically append `{}`
  - move cursor inside new brackets (this part may require `monoco`/`vscode-languageserver`)
  -  automatically complete for descending required fields on enter? (might be for `monaco` or `vscode-languageserver`)

## `graphql-language-service-server`

- [x] offset outline/definitions positions for embedded `graphql`
- [x] build caches for all files immediately on `initialization` and on each relevant workspace folder/file event, or at least cache all definitions on `onRequestWorkspaceSymbol`. use `invalidateCache()`
- [x] handle `RequestWorkspaceDefinition` event similarly
- [x] supporting the last two might require more configuration on the extension side as well

## `vscode-graphql`

is becoming our go-to reference implementation, and this work is towards 3.x.x releases:
- [`vscode-graphql@3.0.0`](https://github.com/prisma-labs/vscode-graphql/issues/181)

## external issues:

- [x] `graphql-config` endpoints extension no longer supports `env`, so we still have to figure out how to replace use of `env`

**Comment by felippepuhle** [comment]
@acao is there a way we can implement `customValidationRules`? We're using Relay and I was thinking what's the best way to create an extension for this case.

We already have a lot of validation rules [here](https://github.com/relay-tools/vscode-apollo-relay), we just need to extract them on a generic way.

**Comment by acao** [comment]
@felippepuhle awesome! very excited about coc-graphql. i just cut an alpha of the lsp server last night that should be quite an enhancement!

`customValidationRules` can be defined in the graphql-config that's picked up by the LSP server. here's where we apply them
https://github.com/graphql/graphiql/blob/7dfaef7c96486b2a8bc23df133e3484708224dab/packages/graphql-language-service-interface/src/GraphQLLanguageService.ts#L198

previously, it would load from a specified file path, but in graphql-config@3 we support commonjs. so now you can require() a file that provides an array of custom rules, or you can define them implicitly in the graphql.config.js file, your choice!

**Comment by felippepuhle** [comment]
That's awesome! I'll take a look ASAP, thanks!

**Comment by tvvignesh** [comment]
@acao The extension is becoming way better than it used to be thanks. But one important thing which I am looking for is support for Federation: https://github.com/graphql/vscode-graphql/issues/250

Any plans for the same?

**Comment by acao** [comment]
@tvvignesh this is possible now that i've squashed some bugs i introduced during this initiative!

**Comment by acao** [comment]
the follow up!
https://github.com/graphql/graphiql/issues/2062
