### ISSUE TITLE
codemirror-graphql package not es5 compatible on npm

### ISSUE THREAD

**Issue by erikt9** [graphql/graphiql#1623]
I'm assuming from #1557, the goal is to produce es5 compatible packages.  When installing the latest (0.12.0) version of `codemirror-graphql` the distributed code contains the `const` keyword which is not es5 compatible.  For instance, the first couple lines of `codemirror-graphql/hint.js` (although every top level distribution file looks to have this problem):

```
_codemirror.default.registerHelper('hint', 'graphql', (editor, options) => {
  const schema = options.schema;

  if (!schema) {
    return;
  }

  const cur = editor.getCursor();
  const token = editor.getTokenAt(cur);
```

**Comment by acao** [comment]
looking into this, and though I was able to get what you needed working, we are going to be updating our `.browserslistrc` and dropping `ie11` and `ios10` support anyways, which will lead to using `const` by default.

`codemirror-graphql` is the only non typescript package as of this january, so it does not inherit the `es5` configuration used by the other tsconfigs, however those are about to be bumped to es6, and i may just end up adding rollup anyways

**Comment by acao** [comment]
I'm actually thinking `es6`-esque targets for a few reasons. probably going to make this choice and release today.

considering adding rollup, and building a few bundles for each package, and the necessary documentation

**Comment by erikt9** [comment]
My main motivation for getting this fixed is for including graphiql in my webpack bundle.  It is pretty standard webpack practice to skip babel transpiling node modules (it would take forever and it's assumed they've already been transpiled).  Currently I need to make an ugly exception for this one node package.  So personally, I'm happy with any decision where I don't need to hack my webpack config file for this one module 😛.

**Comment by acao** [comment]
have you seen our webpack example?

**Comment by acao** [comment]
it also works fine in create react app without any configuration. maybe start there?

**Comment by erikt9** [comment]
@acao The issue isn't that it doesn't build with webpack (it builds fine), it's that the resulting bundle is not es5 compatible due to this one module.  I have to make an exception for running the babel transpolar on this one node module out of all the hundreds that are present if I want es5 compatible code.

**Comment by acao** [comment]
for clarity’s sake, we no longer support IE. there is nothing we will change about that. we updated the babel config recently because codemirror-graphql does not use typescript. everything else transpiles to es6. after looking at the current support matrix, the only purpose of supporting es5 for us would be IE support.

if you have an issue with es6 support, please open another ticket

**Comment by erikt9** [comment]
I think I haven't been clear that I'm asking this for the 1.0 branch.  This branch lists IE11 as a supported browser (I actually don't need IE11 support, but I still need es5 for other reasons) and is your current release (non-beta / alpha) branch.  I hope you would consider reopening this for the 1.0 branch.

**Comment by acao** [comment]
the 1.0.0 branch was combined into main branch today. if you see in the git log or the changelog, one of the breaking changes leading to 1.0.0 was deprecating support for IE. we will summarize 1.0.0 breaking changes better soon!
