### ISSUE TITLE
Older NPMs (@apollographql/graphql-language-service-utils)

### ISSUE THREAD

**Issue by ariel11** [graphql/graphiql#1629]
Hi,

Is the MIT License in this repo meant to apply to the (5) NPM versions of this package here: https://www.npmjs.com/package/@apollographql/graphql-language-service-utils/v/2.0.2?  

I don't see any license info for the above package, though the package.json points here for issues (https://github.com/graphql/graphql-language-service/issues), which in turn points to this repo (on the README).

Same question for these NPM's - @apollographql/graphql-language-service-parser, @apollographql/graphql-language-service-types, and @apollographql/graphql-language-service-interface.  Does the MIT License apply to these NPMs too?

Thanks,
Ariel

**Comment by acao** [comment]
hello @ariel11! those are apollo's forks of our packages. we have no control over those npm packages.

https://www.npmjs.com/package/graphql-language-service-utils
https://www.npmjs.com/package/graphql-language-service-types (need to update this readme! converted this all to typescript, except `codemirror-graphql`)
https://www.npmjs.com/package/graphql-language-service-server used by vscode-graphql
https://www.npmjs.com/package/graphql-language-service-interface used by many projects
https://www.npmjs.com/package/graphql-language-service-parser used by interface
https://www.npmjs.com/package/codemirror-graphql used by graphql-playground, graphiql, altair, insomnia, aws, etc

**Comment by ariel11** [comment]
@acao - thank you for that history and context.

**Comment by acao** [comment]
always glad to keep folks informed. let me know if you have any questions about anything. considering this resolved :+1:
