### ISSUE TITLE
Uncaught Error: Mode graphql failed to advance stream.

### ISSUE THREAD

**Issue by postalservice14** [graphql/graphiql#163]
I can't type anything into the editor.  When looking at the developer tools I see:

```
Uncaught Error: Mode graphql failed to advance stream.
```

It worked before, and this started when I pasted some invalid GraphQL code in the editor.  I've tried clearing the localstorage, that doesn't seem to do anything.  Every time I reload it puts my bad query back in the localstorage key again. :-/

**Comment by asiandrummer** [comment]
Hey @postalservice14! It sounds like a bug to me - GraphiQL shouldn't save an invalid query to localstorage, or it shouldn't let the app from failing to initialize (which seems to be what it's doing). Meanwhile, if you have access to `GraphiQL.js` code, you could try resetting `query` variable to the empty string to get around this issue. 

It's weird though that the local storage won't reset - are you passing in a custom storage instance for this?

**Comment by postalservice14** [comment]
Ha, whoops, I meant to post this on https://github.com/skevy/graphiql-app . Not sure how I accidentally posted this here.  I think it has to do with the way this guy is wrapping graphiql.
