### ISSUE TITLE
Type error: FetcherParams.variables declared as string but actually passed as object

### ISSUE THREAD

**Issue by lunaryorn** [graphql/graphiql#1632]
GraphiQL 1.0.3 declares `FetcherParams.variables` as string, see [GraphiQL.tsx#L75](https://github.com/graphql/graphiql/blob/graphiql%401.0.3/packages/graphiql/src/components/GraphiQL.tsx#L75), presumably containing the string value from the variables editor

However in a custom fetcher I actually get a Javascript object (which [seems to be intended](https://github.com/graphql/graphiql/pull/168)).

You can easily reproduce this with:

```html
<html>

<head>
  <title>Simple GraphiQL Example</title>
  <link href="https://unpkg.com/graphiql/graphiql.min.css" rel="stylesheet" />
</head>

<body style="margin: 0;">
  <div id="graphiql" style="height: 100vh;"></div>

  <script crossorigin src="https://unpkg.com/react/umd/react.production.min.js"></script>
  <script crossorigin src="https://unpkg.com/react-dom/umd/react-dom.production.min.js"></script>
  <script crossorigin src="https://unpkg.com/graphiql/graphiql.min.js"></script>

  <script>
    const graphQLFetcher = graphQLParams => {
      const variables = graphQLParams.variables;
      console.debug('Variables', graphQLParams.variables/*  */)
      if (variables && typeof graphQLParams.variables !== "string") {
        throw new Error("variables not a string!");
      }
      return new Promise((resolve) => resolve("Hello world"));
    };
    ReactDOM.render(
      React.createElement(GraphiQL, { fetcher: graphQLFetcher }),
      document.getElementById('graphiql'),
    );
  </script>
</body>

</html>
```

**Comment by acao** [comment]
yes this is as expected, the string is for setting the default variables editor value, whereas the variables object in the fetcher is the result of whats in the editor

**Comment by acao** [comment]
let me know if you have any further questions!

**Comment by acao** [comment]
will release this shortly!

**Comment by lunaryorn** [comment]
@acao Did you release this already?

**Comment by acao** [comment]
sorry no, there are issues in the pipeline. we have to do some heavy lifting to keep cutting graphiql 1 releases from the main branch now, and I'm going to be away from work on vacation (starting today), so it will be a few PRs and some time until we can issue another graphiql 1 release
