### ISSUE TITLE
[1.0.x] fetcher Observable is expected to have different subscribe method arguments in _fetchQuery and fetchSchema

### ISSUE THREAD

**Issue by n1ru4l** [graphql/graphiql#1638]
**From Discord:**
> For GraphiQL 1.0.3 I noticed that I get a polymorphic input for an observable subscribe function returned by the fetcher function. For the introspection query that is three functions as the arguments (next, error, complete) for all the other operation sent however it is a single object argument with the functions next, error and complete on it.
See:
https://github.com/n1ru4l/graphql-live-queries/blob/2766455876b4c8e3d90bedf47e62d34da50509b6/packages/example/src/static-html.ts#L79

So the issue I see here is that observables are subscribed to with two different methods, but maybe I am misunderstanding it or it has some legacy context that I am not aware of.
https://github.com/graphql/graphiql/blob/2a7b9c13f93833205fb1fc3712aadd6165deea66/packages/graphiql/src/components/GraphiQL.tsx#L1618-L1627 which is used here https://github.com/graphql/graphiql/blob/2a7b9c13f93833205fb1fc3712aadd6165deea66/packages/graphiql/src/components/GraphiQL.tsx#L800-L808

and

https://github.com/graphql/graphiql/blob/2a7b9c13f93833205fb1fc3712aadd6165deea66/packages/graphiql/src/components/GraphiQL.tsx#L926-L945

It seems to me that the `fetchSchema` method does support `fetcher` to return and handle an observable (by converting it to a promise) while expecting the arguments of the subscribe method/function to be different than how the   `_fetchQuery` treats it (which also utilizes `fetcher` for receiving an Observable (or Promise)).

**Possible Workarounds:**

- Check whether the first parameter passed to subscribe is a function (seems rather like a hacky solution). (This is what I am currently doing here: https://github.com/n1ru4l/graphql-live-queries/blob/2766455876b4c8e3d90bedf47e62d34da50509b6/packages/example/src/static-html.ts#L74-L101 **Note:** I built my own fetcher that uses socket.io).

- Use an Observable library that supports both "signatures" and picks the correct one based on the amount/type of arguments it is called with (requires adding another dependency or writing it yourself, which brings you back to the first workaround).

- Return a Promise from fetcher (instead of Observable) if it receives an introspection query.

**Possible Solution:**

Change the `observableToPromise` function to accept an observable with the same subscribe argument signature as inside `_fetchQuery`.

**Comment by acao** [comment]
thanks for looking into this @n1ru4l ! great research.

have you seen this?
https://github.com/apollographql/GraphiQL-Subscriptions-Fetcher/blob/master/src/fetcher.ts

maybe try and see if this approach works better? it's the one most implementations use, and we should be using here for our example as well!

**Comment by n1ru4l** [comment]
It also seems that all "major" observable library implementations out there support the polymorphic subscribe arguments

zen-observable (used by apollo-client: https://github.com/zenparsing/zen-observable/blob/328fb66a99242900c0fd4a330e9ff66ecfa3a887/src/Observable.js#L210-L219

The major subscription transport implementation does also support polymorphic input:

https://github.com/apollographql/subscriptions-transport-ws/blob/3587bf4ae58fd32ecab83ae0c8e21750fcc7b889/src/client.ts#L200-L232

So the proposed change would not break users using that library.

**Comment by acao** [comment]
fantastic, thank you!
