### ISSUE TITLE
historyPaneOpen is not working properly

### ISSUE THREAD

**Issue by andreabreu-me** [graphql/graphiql#1650]
When open and close the history panel, the flag `historyPaneOpen` does not respect the current visual state of it. The live demo has the same behaviour.

**Comment by andreabreu-me** [comment]
@acao I'm on vacation too :)

I think the problem its here: https://github.com/graphql/graphiql/blob/1.0.0/packages/graphiql/src/components/GraphiQL.tsx#L1273

Since `setState` is not synchronous, the value passed to the storage will always be the previous value. 

This should fix the problem:

```javascript
  handleToggleHistory = () => {
    if (typeof this.props.onToggleHistory === 'function') {
      this.props.onToggleHistory(!this.state.historyPaneOpen);
    }
    this._storage.set(
      'historyPaneOpen',
      JSON.stringify(!this.state.historyPaneOpen),
    );
    this.setState({ historyPaneOpen: !this.state.historyPaneOpen });
  };
```

**Comment by acao** [comment]
fix was released last week! enjoy! thanks @harshithpabbati !
