### ISSUE TITLE
Dead netlify link in README.md

### ISSUE THREAD

**Issue by Crease29** [graphql/graphiql#1656]
Unfortunately the link pointing to netlify in the README.md is dead:
> We also have [a demo using our latest netlify build](http://graphiql-test.netlify.com) for the `main` branch.

The other link to the type docs is working:
> - a to-specification official language service (see: [API Docs](https://graphiql-test.netlify.app/typedoc))

**Comment by acao** [comment]
it’s not dead. i just haven’t updated the build output or docs. the graphiql 2 context rfc wip is at /bundle/dist

we’re about to restructure the repository to make way for an alternative RFC this or next week, stay tuned!

**Comment by acao** [comment]
@Crease29 most of the links should be valid again! a few of the example repos are no longer being built in every CI run to save time/cyles, but we have a full on demo/docs site coming soon!

**Comment by Crease29** [comment]
@acao Looks good, thanks! 🙂
