### ISSUE TITLE
License information missing for the package monaco-graphql

### ISSUE THREAD

**Issue by saponniah** [graphql/graphiql#1657]
Looks like the license information is missing for package `monaco-graphql`. Since `graphiql` has a dependency on `monaco-graphql` it will be great to include the license information for this package as well.

Can this be fixed?

**Comment by acao** [comment]
@saponniah good catch, thank you! need to add that, and update copyrights

**Comment by hjdivad** [comment]
@acao any chance someone could cut a release of `monaco-graphql` with the license?  It would help us use graphiql internally as we can't rely on a third-party CDN and we require licenses for libraries & dependencies.

Thanks in advance <3

**Comment by acao** [comment]
@hjdivad hopefully soon - the latest release of graphiql does not use `monaco-graphql` however! are you using 1.x? What you see in main branch is just an RFC

**Comment by saponniah** [comment]
@acao Yeah, I'm trying to use the latest stable version - `graphiql@1.0.3`.

**Comment by acao** [comment]
oh wow, i didn’t realize 1.0.3 published with `monaco-graphql` as a dependency, that is strange. i can fix this tonight!

**Comment by acao** [comment]
this was fixed last week! enjoy!
