### ISSUE TITLE
Add a possibility to somehow pass the `contextValue` for the query

### ISSUE THREAD

**Issue by wizardzloy** [graphql/graphiql#166]
Say I use the `contextValue` parameter on the server when executing the query from the client. I pass certain token that I take from the request cookie to the [`graphql`](http://graphql.org/docs/api-reference-graphql/#graphql) function call.
Can I somehow pass that value from the interface of the GraphiQL?

**Comment by asiandrummer** [comment]
Hi @wizardzloy! I think you're describing a way to pass a value from `GraphiQL` UI, build a certain token that gets constructed from the request cookie, and pass that as a part of `contextValue` to the `graphql` function call (let me know if this is somewhat incorrect).  Although not a standard feature of `GraphiQL`, you can definitely build a simple UI [like this tool built by @OlegIlyenko](http://toolbox.sangria-graphql.org/graphiql) and have your `graphQLFetcher` and your server take in that value to build out parameters for the `graphql` function call.

**Comment by wizardzloy** [comment]
ok, that makes sense. The feature is not standard and not everybody needs it, I'll take a look at the proposed implementation. Should I close the issue?

**Comment by asiandrummer** [comment]
I can close it - let us know if you have other questions!
