### ISSUE TITLE
graphiql schema editor not rendering properly

### ISSUE THREAD

**Issue by RaghuVarmaS** [graphql/graphiql#1664]
![image](https://user-images.githubusercontent.com/49497426/93383741-b3d87b00-f881-11ea-8d48-334ba280ba5d.png)

Instead of rendering in a schema pane iit is rendering in a result pane

**Comment by acao** [comment]
strange, can you show your component implementation code by chance?

**Comment by RaghuVarmaS** [comment]
> strange, can you show your component implementation code by chance?

I am getting results as expected. the problem is only with the Document Explorer rendering.

I am using custom endpoint like /abc/v1/graphql  and implementing using controllers and routing in ASP.net core.

In startup configuration

 app.UseGraphiQl("/graphql/ui", "/abc/v1/graphql");

service registration as below 
           services.AddSingleton<IEntityService, EntityService>();
            services.AddSingleton<ABCType>();
            services.AddSingleton<AYZContractType>();
            services.AddSingleton<DFDContractType>();
            services.AddSingleton<GraphQuery>();
            services.AddSingleton<ISchema, ABCSchema>();
            services.AddSingleton<IDependencyResolver>(
               c => new FuncDependencyResolver(type => c.GetRequiredService(type)));



[controller.txt](https://github.com/graphql/graphiql/files/5250811/controller.txt)

**Comment by RaghuVarmaS** [comment]
> > strange, can you show your component implementation code by chance?
> 
> I am getting results as expected. the problem is only with the Document Explorer rendering.
> 
> I am using custom endpoint like /abc/v1/graphql and implementing using controllers and routing in ASP.net core.
> 
> In startup configuration
> 
> app.UseGraphiQl("/graphql/ui", "/abc/v1/graphql");
> 
> service registration as below
> services.AddSingleton<IEntityService, EntityService>();
> services.AddSingleton();
> services.AddSingleton();
> services.AddSingleton();
> services.AddSingleton();
> services.AddSingleton<ISchema, ABCSchema>();
> services.AddSingleton(
> c => new FuncDependencyResolver(type => c.GetRequiredService(type)));
> 
> [controller.txt](https://github.com/graphql/graphiql/files/5250811/controller.txt)

Solved 👍 Added : app.UseGraphQL<ABCSchema>("/abc/v1/graphql"); in configuration
and changed ISchema to Schema in controller file.

**Comment by acao** [comment]
ah ok! sorry i couldn't help you with this implementation, I haven't used ASP.net in years, glad you resolved it!
