### ISSUE TITLE
How to execute query automatically?

### ISSUE THREAD

**Issue by alvaro1728** [graphql/graphiql#1671]
I'm able to load my graphiql page on the browser with a query: `http://mysite:4080/graphql/graphiql.html?query=%0Aquery%20%7B%20%0A%20%20...`. The problem is that it doesn't execute the query automatically so the user has to click the Execute button. 

Is there a param I can pass to have it execute automatically?

Thanks,
Alvaro

**Comment by thomasheyenbrock** [comment]
The state management for GraphiQL has been completely refactored for graphiql@2. All of it now lives in contexts and can be consumed by hooks, both of with are defined in the @graphiql/react package.

Solving this specific use-case would looks something like this:

```js
import { useExecutionContext } from '@graphiql/react';

function MyComponent() {
  const { run } = useExplorerContext();
  /**
   * Calling the `run` function will execute the current query. This is a 
   * simple example where this is triggered by a button, but you could call
   * it anywhere else, e.g. in an effect that runs after the initial render.
   */
  return <button onClick={run}>Execute</button>
}
```
