### ISSUE TITLE
[1.0.x] Variable editor requires an extra click to work when header editor is not enabled

### ISSUE THREAD

**Issue by cshaver** [graphql/graphiql#1677]
[See codesandbox for repro](https://codesandbox.io/s/graphiqllatest-jy3p9?file=/src/index.js).

Gotta have a gif!:
![Screen Recording 2020-09-23 at 2](https://user-images.githubusercontent.com/2136754/94073356-3397a580-fdac-11ea-97e3-f11bcb2ac245.gif)

Note: setting `defaultVariableEditorOpen` to `true` works as a workaround :)

**Comment by harshithpabbati** [comment]
@cshaver I fixed this issue in #1561 

It works perfectly fine in GraphiQL demo, not sure what is the reason it produced again. Prolly I guess this new version isn't released

**Comment by cshaver** [comment]
Ah, ty @harshithpabbati! I didn't see that fix, but was confused why I couldn't repro on the main branch. I checked again and it looks like only this happens when `headerEditorEnabled = false` AND `defaultVariableEditorOpen = false`.

**Comment by harshithpabbati** [comment]
Oh I see then it's a issue. I will try to fix this with a PR
