### ISSUE TITLE
language server fails to process empty types

### ISSUE THREAD

**Issue by OneCyrus** [graphql/graphiql#1681]
we have the following type as we use type extensions for stitched scenarios:

```
type EmptyType @source(name: "EmptyType", schema: "local") {
}
```

the language server fails to process this:

```
Schema.graphql:1352:1
1351 |
1352 | }
     | ^
1353 |
```

**Comment by acao** [comment]
thanks for reporting it here! so what you’re saying is that the LSP server crashes when you’re defining an object type with directives? is the file specified in graphql config schema entry?

**Comment by OneCyrus** [comment]
the directive doesn't matter. but it looks like it's spec compliant to not allow empty types (types without fields)

https://github.com/graphql/graphql-spec/issues/568

**Comment by acao** [comment]
yes I'm aware, this is why graphql-js fails to parse the schema file, however two things:

1. short term: we could have better error handling - in vscode we trap these exceptions, but for your language server implementation, is this a problem? I really need to work with the LSP outside of vscode and the browser more often!
2. mid term: we are working on improving the streaming parser to eventually build an entire GraphQLSchema for SDL validation, so it should be able to just skip over this type when building completion/validation/etc

**Comment by acao** [comment]
I'm wrong, this shouldn't be happening, there was unnecessary `graphql` `parse()` added to `getAutocompleteSuggestions` which actually uses our own `graphql-language-service-parser`, which doesn't have these kinds of issues. this bug should be fixed now
