### ISSUE TITLE
graphql-lsp server does not provide Content-length header

### ISSUE THREAD

**Issue by creasty** [graphql/graphiql#1686]
I couldn't get a server work with https://github.com/neoclide/coc.nvim.

Starting the server with `graphql-lsp server --method stream` produces an error:

<img width="653" alt="Screen Shot 2020-10-01 at 16 01 16" src="https://user-images.githubusercontent.com/1695538/94777991-5b67b880-03ff-11eb-858e-3947baa512ff.png">

Related: https://github.com/neoclide/coc.nvim/issues/1327 (According to this, it's not a bug of a lsp client, and the header supposed to be implemented on the language server)

### Reproduction

```jsonc
// coc-settings.json
{
  "languageserver": {
    "graphql": {
      "enable": false,
      "command": "graphql-lsp",
      "args": ["server", "-m", "stream"],
      "rootPatterns": [
        ".graphqlrc",
        ".graphqlrc.yml",
        ".graphql.yaml",
        ".graphqlrc.json",
        "graphql.config.js",
        ".graphqlrc.js"
      ],
      "filetypes": [
        "graphql",
        "javascript",
        "javascriptreact",
        "typescript",
        "typescriptreact"
      ]
    }
  }
}
```

**Comment by rchl** [comment]
You might have run into this bug: https://github.com/graphql/graphiql/issues/1708

I believe it was introduced in the 3.1.0 release of `graphql-language-service-cli`.

**Comment by acao** [comment]
yes we
