### ISSUE TITLE
Explorer panel

### ISSUE THREAD

**Issue by jareware** [graphql/graphiql#1690]
The [Apollo Dev Tools extension](https://chrome.google.com/webstore/detail/apollo-client-developer-t/jdkknkkbebbapilgoeccciglkfbmbnfm) bundles GraphiQL, and it has this tremendously useful Explore panel for constructing queries visually:

![Screenshot](https://user-images.githubusercontent.com/560055/95296000-af9bee00-0880-11eb-82b7-c4642a7420c5.png)

Where can I find that on standalone GraphiQL? Can't seem to find it from [the Electron app](https://www.electronjs.org/apps/graphiql) or the [live demo](https://graphiql-test.netlify.app/dev).

**Comment by kilinkis** [comment]
same, I'll uninstall it until this implemented. It's a much needed feature

**Comment by acao** [comment]
this is a plugin designed to work with this component! you can follow the instructions for adding it to your Graphiql install

**Comment by jonsevoich** [comment]
> same, I'll uninstall it until this is implemented. It's a much needed feature

**Comment by kilinkis** [comment]
@acao yeah but how do you install it on the Desktop app?

**Comment by acao** [comment]
i’m not sure which desktop app you are referring to, we do not support one. you can contact whoever maintains the desktop app to add it!

**Comment by kilinkis** [comment]
@acao here in the [Readme](https://github.com/graphql/graphiql/blob/main/README.md) file reads: 
`Whether you want a simple GraphiQL IDE instance for your server, or a more advanced web or **desktop** GraphQL IDE experience for your framework or plugin, or you want to build an IDE extension or plugin, you've come to the right place!`

also, isn't his app from this repo? https://www.electronjs.org/apps/graphiql
if not, it has the same name

**Comment by acao** [comment]
the link on that page points to a different repository

**Comment by kilinkis** [comment]
ah you're right @acao, their repo is https://github.com/skevy/graphiql-app. The Readme text is still confusing to me tho

**Comment by jareware** [comment]
@acao 

> this is a plugin designed to work with this component! you can follow the instructions for adding it to your Graphiql install

Sounds awesome! Couldn't find a list of plugins or the instructions you mentioned, though... could you point me to the right direction? 😇
