### ISSUE TITLE
Interface field autocomplete no longer present in 1.0+

### ISSUE THREAD

**Issue by wakemaster39** [graphql/graphiql#1691]
I am looking to upgrade my very old graphiql package to the latest stable, jumping from 0.11.11 to 1.0.5. During this transition, i found that when working with interfaces when upgrading from 0.17.5 (the last stable 0.x) to 1.0+ the way interface fields are suggested changed. 

Previously, when working with interfaces all interface fields would be autocomplete
![Screen Shot 2020-10-08 at 7 29 23 AM](https://user-images.githubusercontent.com/694131/95452911-fef12580-0937-11eb-843f-810119f25c72.png)

With anything in the 1.0 series, all interface fields now require a fragment to be found. The only field that autocompletes is `__typename`. Also the interface itself is being returned as a suggested autocomplete when trying to build a fragment instead of just the concrete instances.

I couldn't find anything in the issues or the change log about a breaking change like this and wondering if this is intended or if something else is going on in the schema that was being delivered to graphiql.

**Comment by yoshiakis** [comment]
It's a bug! I believe #1695 will fix this.

**Comment by acao** [comment]
`codemirror-graphql@0.12.3` contains this fix, and the latest `graphiql@1.0.6` depends on this patch release now. apologies for the regression!
