### ISSUE TITLE
Clean up licensing info from BSD-like remnants

### ISSUE THREAD

**Issue by silverhook** [graphql/graphiql#1693]
I scanned the GraphiQL code at master (commit 39f5e45) with a license scanner (FOSSology) and found that there are still remnants from Facebook’s old BSD-like (plus patents) license.

From what I can tell, Facebook changed their license from their custom BSD-like (plus patents) license to MIT a while ago, and I assume during the re-licensing of GraphiQL some of these files simply fell through the cracks.

I count 87 files affected, so it may be too long to simply copy-paste here in an issue. But happy to share the list with you, or even the SPDX file of my FOSSology scan and help you grep the affected files if that is what you would prefer.

**Comment by acao** [comment]
hey thanks for the information! it seems you are pointing at `main` branch. I changed the license across many files myself when Facebook gave us ownership, and we decided to change it to MIT. These files still have the old facebook copyright or some such? Sharing here as a file upload is fine.  @brianwarner and @caniszczyk from graphql foundation/linux foundation will be interested in this as well.

**Comment by silverhook** [comment]
That commit should be identical to [release 2.5.5](https://github.com/graphql/graphiql/releases/tag/graphql-language-service-server%402.5.5).

What you describe sounds logical to me and that’s what I suspected happened when I found these old copyright/license notices and compared it to a much older release.

Yes, the files I mention still carry Facebook’s copyright and custom license.

**Comment by acao** [comment]
are you going to share the list of files or should i use this scanning tool myself? im confused

**Comment by silverhook** [comment]
I’m happy to share it. Would you prefer just a list of files or any specific format (e.g. SPDX)?

**Comment by silverhook** [comment]
Scans I have at hand are (versions in [Package URL annotation](https://github.com/package-url/purl-spec)):
- `pkg:github/graphql/graphiql@v0.11.10` – i.e. the 0.11.10 tag/release
- `pkg:github/graphql/graphiql@1.0.0-alpha.10` – i.e. the 1.0.0 tag-alpha tag/release
- `pkg:github/graphql/graphiql@39f5e45a9d2bb469260b62ff8057cc988d853470` – i.e. at the commit I mentioned above.

**Comment by silverhook** [comment]
@acao, here’s a list of the files that I think would merit taking another look at: https://gist.github.com/silverhook/ce68461c833e38ae64ffc133c4de676b

**Comment by brianwarner** [comment]
I'm out of the office for a few days this week, but will have a look. The copyright notices are fine as-is, those don't need to change and should never be modified or removed by anybody other than the copyright holder. I'll have a look at the license question, though.

**Comment by acao** [comment]
#1814 will take care of making sure all new files have copyrights

also, it seems your scanner is scanning a lot of files that aren’t used or present in the actual npm package. Instead it’s scanning the entire repository, is that intentional?

in the future, if you want to open a ticket about this, please show us which specific files you’re talking about

**Comment by silverhook** [comment]
> in the future, if you want to open a ticket about this, please show us which specific files you’re talking about

I did:
https://gist.github.com/silverhook/ce68461c833e38ae64ffc133c4de676b

The scanner is intentionally looking at the source code, yes. NPM packages are often stripped of info, so they are not a good source of information, I find. Or do you have a better solution?
