### ISSUE TITLE
feature request: autocomplete service for brand specific hints

### ISSUE THREAD

**Issue by josecullen** [graphql/graphiql#1694]
I'm trying to add specific autocompletion hints, not included in the schema, for instance:

```
{
  product(code: "c") // => suggest my codes, calling a service or pre-fetched from the client-side. 
}
```

The only way I found to get this was touching `getAutocompleteSuggestions` but I'm wondering if it's planned to add some kind of support for this use case. 

Example of non-async implementation:

`<GraphiQL onAutocomplete=(context: AutocompleteContext) => Array<CompletionItem>  />`

then: 
```
export function getAutocompleteSuggestions(
  schema: GraphQLSchema,
  queryText: string,
  cursor: Position,
  contextToken?: ContextToken,
  fragmentDefs?: FragmentDefinitionNode[],
  customAutocompletion?: () => Array<CompletionItem>
): Array<CompletionItem> {

  if(!!customAutocompletion) {
    const result = customAutocompletion({ ... });
    if (!!result) return result;
  }

}
```

With `autocompleteContext` I mean: the word prefix and something like the path context in which the word is writing (query -> product -> code)

**Comment by acao** [comment]
@josecullen in most environments where this is used - vscode, monaco, codemirror, vim, etc, it's possible for the implementer to add their own autocompletion logic, seperately from this, so i suggest taking that approach.
