### ISSUE TITLE
Interface implements interface

### ISSUE THREAD

**Issue by Weasy666** [graphql/graphiql#1699]
It would be really nice, if support for RFC https://github.com/graphql/graphql-spec/pull/373 could be added to codemirror, so that the playground also supports this.

**Comment by acao** [comment]
for folks who are looking to use this feature, this is already supported in `monaco-graphql` because `monaco-editor` adheres to LSP transparently.

the PR to update `codemirror-graphql` would not need to be very large.

**Comment by acao** [comment]
this will take a significant effort in the parser as it turns out. two weekends ago i was able to get it partially working for a single `Type & ExampleType`, hopefully this weekend i can spend some more time on it.

**Comment by acao** [comment]
#1742 introduced some of it, #1747 added more completion logic and support for codemirror-graphql and graphiql. enjoy!
