### ISSUE TITLE
Can it work with vuejs?

### ISSUE THREAD

**Issue by studiolee** [graphql/graphiql#1709]
Can it work with vuejs?

**Comment by acao** [comment]
yes! our `monaco-graphql` or `codemirror-graphql` would work great with vuejs. see the monaco-webpack example for a vanilla js starter

the `graphiql` project that is part of this language tooling monorepo is built with react, however as you can see with the vanilla monaco example, it's relatively easy to build your own graphiql using our web IDE modes!
