### ISSUE TITLE
Can parameters pass multiple nested objects？

### ISSUE THREAD

**Issue by studiolee** [graphql/graphiql#1713]
When I pass in the parameter foo:{a:1}, it works normally. When I pass in foo:{a:{i:1,j:2}}, it does not work properly and an error is reported:
{
  "message": "Invalid or incomplete introspection result. Ensure that you are passing \"data\" property of introspection response and no \"errors\" was returned alongside: null.",
  "stack": "Error: Invalid or incomplete introspection result. Ensure that you are passing \"data\" property of introspection response and no \"errors\" was returned alongside: null.\n    at r (http://localhost:8000/src/scripts/graphiql.min.js:1:24582)\n    at lr (http://localhost:8000/src/scripts/graphiql.min.js:1:327086)\n    at http://localhost:8000/src/scripts/graphiql.min.js:7:45108"
}
I have implemented the background logic.  I can get these parameters through api access, the error only occurs in the debug page of graphiql

**Comment by acao** [comment]
seems that your provided fetcher is not fetching the introspection schema properly?

**Comment by Jawmo** [comment]
Came here with same error but different problem.

Django users, make sure you have this in your settings middleware:

`"corsheaders.middleware.CorsMiddleware"`
