### ISSUE TITLE
onToggleDocs not fired when minimizing the doc explorer

### ISSUE THREAD

**Issue by mnbattaglia** [graphql/graphiql#1717]
When resizing the doc explorer to a small size, it is collapsed and finally the _docExplorerOpen_ state is set to false.

https://github.com/graphql/graphiql/blob/main/packages/graphiql/src/components/GraphiQL.tsx#L1389

But the _onToggleDocs_ does never get fired, as it supposed to be (like in the _ handleToggleDocs_ method)

**Comment by ChiragKasat** [comment]
Hi, I would like to work on this issue.

**Comment by endurance21** [comment]
@acao  has the issue been solved ?

**Comment by imolorhe** [comment]
The MR with the fix was merged but a new version of GraphiQL hasn't been released yet.

**Comment by acao** [comment]
This has been merged and released!
