### ISSUE TITLE
SemVer breakage re: NoDeprecatedCustomRule from graphql

### ISSUE THREAD

**Issue by floyd-may** [graphql/graphiql#1723]
The `graphql-language-service-interface` package, in going from version 2.4.2 to 2.4.3, relies on an export from `graphql` named `NoDeprecatedCustomRule`. The `graphql` package added this export in v15.2.0. Furthermore, `codemirror-graphql` revved its dependency version on `graphql-language-service-interface` from 2.4.2 to 2.4.3 (requiring this change) when it went from 0.12.3 to 0.12.4. My dependency on `graphiql`, which worked fine with my version of `graphql` at `14.x`, on the publish of these new packages, started breaking, with a compiler error stating that `'NoDeprecatedCustomRule' is not exported from 'graphql'`. Now my package.json needs to pin both `codemirror-graphql` to 0.12.3 and `graphql-language-service-interface` to 2.4.2 so that I can remain compatible with `graphql` at v14.

... * sigh *

Y'all.... this is a mess, and it sucked up a bunch of my time because my builds started failing when I hadn't changed any code. For already-published packages, there's not really much you can do, but in the future, can you _please_ be more aware of this kind of thing? In particular, the `peerDependencies` for `graphql-language-service-interface` are incorrect, as this package relies on `graphql@^15.2.0` (since it needs `NoDeprecatedCustomRule` [introduced at that version](https://github.com/graphql/graphql-js/releases/tag/v15.2.0)) and appears to no longer be compatible with 14.x.

Thanks for your consideration. Let me know if I can provide any more information.

**Comment by kgoggin** [comment]
Thanks for posting this @floyd-may - I came here because of the same issue having just installed graphiql in a new project. Your documentation just saved me a ton of time. Hopefully they can address this quickly!

**Comment by acao** [comment]
hmm... perhaps ill need to lazily import this rule, as it’s supposed to use the deprecated function if the import isn’t present. should have been obvious. thanks for the heads up and apologies for the breakage. i couldn’t find anyone to help me review this PR, but our graphql 15 support was broken. will fix this in a patch release in the next few days hopefully

**Comment by acao** [comment]
just realized its been open 8 days as well! yikes. well i wouldn’t have been able to work on it had I seen it earlier. does someone want to open a PR to just use the deprecated function?

**Comment by acao** [comment]
![image](https://user-images.githubusercontent.com/1368727/101528495-668a1800-395d-11eb-9d32-bd0646af6230.png)

fix addressed in [graphql-language-service-interface@2.5.0](https://github.com/graphql/graphiql/blob/main/packages/graphql-language-service-interface/CHANGELOG.md#250-2020-12-08)

**Comment by floyd-may** [comment]
Will remove the pinned versions I have, retest, and report back. Thanks for getting on this @acao!

**Comment by floyd-may** [comment]
Works for me!

**Comment by acao** [comment]
@floyd-may thanks for identifying it so quickly! this would have rendered so many implementations unusable. this is a wake up call that pushing a `@next` tag and/or canaries is definitely in order.

**Comment by floyd-may** [comment]
`peerDependencies` are... fun... Might I suggest a compile against the oldest acceptable version in the `peerDependencies` somewhere in the CI/CD chain? That would have *definitely* caught this.

**Comment by acao** [comment]
great point, working on something similar to this at work and it makes even more sense here.
