### ISSUE TITLE
Downloading Schema from GraphiQL

### ISSUE THREAD

**Issue by paul590** [graphql/graphiql#1738]
Hello, I am currently using the apollo android and iOs libraries which require me to download the schema. Is it possible to download the schema from graphiql? Currently, I keep getting errors from the command line and there is no way to download it manually from the GraphiQL interface. Thank you in advance!

**Comment by acao** [comment]
hello! GraphiQL does not support that feature yet but it would be nice for 2.0. you can write code to programmatically generate the schema SDL though!
