### ISSUE TITLE
BUG: assert is still a dependency

### ISSUE THREAD

**Issue by mattkrick** [graphql/graphiql#1740]
looking at #1719, I think the goal of the lib is to remove assert, but there are still a few cases of this lib using invariant from it:
- https://github.com/graphql/graphiql/blob/39f5e45a9d2bb469260b62ff8057cc988d853470/packages/graphql-language-service-cli/src/client.ts#L12
- https://github.com/graphql/graphiql/blob/8f0a4ac3331785994e4fe2d98637af0359314359/packages/graphql-language-service-interface/src/getDiagnostics.ts#L20

this causes breaks in webpack v5.

if the goal is a small bundle, i think keeping invaraint (from fbjs or other) may still be useful, but replacing it with a simple throw could be good, too. Let me know what direction yall wanna take it.

cc @danielrearden @acao

**Comment by acao** [comment]
correct that `getDiangostics` shouldn’t have it, but the CLI is a proper usage. care to open a PR to help us out?

**Comment by acao** [comment]
also, why is your webpack config consuming the CLI client? what libraries are you loading in webpack? just monaco-graphql?

**Comment by acao** [comment]
AFAIK, bundle size isn't as big of an issue with node.js CLIs

**Comment by acao** [comment]
this fix was published in the last release, FYI. thank you!
