### ISSUE TITLE
Documentation generate query/mutation on click

### ISSUE THREAD

**Issue by caioflores** [graphql/graphiql#177]
Guys, I was thinking here navigating into documentation explorer in Graphiql, it would be nice if we could generate the mutation/query structure just by clicking on it's documentation in the explorer.

For example, I have a "users" query, when I click on it in the explorer, it generates this structure:
{
  users {
    FirstName
    Username
    Password
    Email
  }
}

Maybe with all fields or something like that. It would make the tests much faster. What do you think?

**Comment by mzohaibqc** [comment]
I would love this functionality.. I even tried that but it did not work :) 
Kindly add this functionality . Thanks

**Comment by leebyron** [comment]
I don't quite follow your suggestion. Are you suggesting that opening the doc explorer also overwrite your query? Where would these example queries come from?

**Comment by mzohaibqc** [comment]
Hi @leebyron,

We are saying that documentation tab contains all `Types` information. It will be great if pressing some button or drag and drop that Type in query editor can write required default query for that resource. e.g. if there is a list resource `movies` with type `Movie`, we can create required query to fetch that resource like pressing a button, query editor text changes to
```
query {
     movies (first: 10) {
           edges {
                node {
                   id
                   name
                   year
                   genre
              }
          }
    }
}
```

I hope you got my point.

**Comment by jferrettiboke** [comment]
I agree with this. I was going to open an issue about this but I saw that the issue was created by another person.

It would be very cool if we can click over a specific field on the doc to have the structure ready rather than pressing `Ctrl + space` to look up the fields. I think this would be very useful in some cases where developers want to create the structure without typing too much.

**Comment by asiandrummer** [comment]
Thanks for the suggestion. This feature sounds interesting, but I can already think of a few cases where coming up with a "default query" would be tricky (e.g. field that requires arguments that might not have default values and/or generating default queries for `InputObject/Enum` types). I also think if whatever doc explorer ends up generating should be valid queries and should execute against the server without problems, and it's difficult to assume how the type resolvers on the server behaves on GraphiQL's side, further making the assumptions much complicated. I'm also not sure how `Mutation` and `Subscription` default queries would be like.

I'm liking this idea though. I think we can try implementing this by kind of reusing the logic to automatically completing the query to the leaf node value when it's not supplied. I'm just throwing ideas at this point, but maybe a type map for the schema?

cc @leebyron

**Comment by jferrettiboke** [comment]
Take a look on [https://github.com/shahankit/custom-graphiql](https://github.com/shahankit/custom-graphiql), there is an option called "Generate Mutation". That's cool. I think, something like this should be officially part of GraphiQL.

**Comment by caioflores** [comment]
@leebyron It's exactly like @mzohaibqc explained up here, see if you can understand. 
@jferrettiboke I was going to suggest the same repository, maybe we can merge these features in GraphiQL.

**Comment by mzohaibqc** [comment]
@leebyron 
I agree with @jferrettiboke and request you to kindly merge this (https://github.com/shahankit/custom-graphiql) in main Graphiql. I can help if there is something to do.

**Comment by leebyron** [comment]
I'll leave this one open for community contribution. I think it's an interesting idea.

**Comment by joelgriffith** [comment]
I've thought about this a bit: what happens with `types` that contain potentially infinite-depth objects? There's places in my own implementations that have circular references to other types, and it's likely a somewhat-common scenario. Would the generation only be 1-level deep?

**Comment by jferrettiboke** [comment]
Hi @joelgriffith.

I think one level deep is enough. If someone needs more levels, just click again and put another level of deep.

**Comment by imolorhe** [comment]
@caioflores @jferrettiboke You can also checkout https://github.com/imolorhe/altair

There's lots of customizable options there. You also have the ability to add queries and fragments from the documentation.

**Comment by jacek213** [comment]
hello, it's been a while - any progress on this topic?

**Comment by acao** [comment]
this would be a good feature for a plugin! we are literally building out the plugin API RFC/rewrite now as you can see, so you should be able to start development on this in a month or two!

**Comment by thomasheyenbrock** [comment]
The new explorer sidebar planned in #2327 will implement this feature, you can create your query by selecting fields in the sidebar.

**Comment by thomasheyenbrock** [comment]
For `graphiql@2` there now exists a plugin `@graphiql/plugin-explorer` which includes the [GraphiQL Explorer from OneGraph](https://github.com/OneGraph/graphiql-explorer) next to the docs. This allows "visually" building up a query based on the tree structure of the GraphQL schema, which I think fulfills this feature request.

For context on my previous comment, we're still building out a new and improved explorer which will also include documentation for types and fields in a similar tree structure that the GraphiQL explorer shows. @jonathanawesome leads this effort, you can follow along the prototype development here: https://github.com/jonathanawesome/graphiql-prototype

**Comment by hsblhsn** [comment]
Hi @thomasheyenbrock, thanks for the nice work on `plugin-explorer`. 

The example provided inside the package doc, opens a new tab with the give query everytime I refresh (because of the given query state). Is there anyway to provide the query from local storage (as `graphiql` gets it)? What I mean is, I do not want to give any default query it should either resolve it from local storage or go along as `graphiql` does. Is it possible?


Thanks :)

**Comment by thomasheyenbrock** [comment]
Hey @hsblhsn and thanks 👋 

You can read the persisted value from `localStorage` before rendering `GraphiQL` and use it to initialize the `query` state. Taking the example from the README as a starter, this would look something like this:

```jsx
import { StorageContextProvider, useStorageContext } from '@graphiql/react';
import { useExplorerPlugin } from '@graphiql/plugin-explorer';
import { createGraphiQLFetcher } from '@graphiql/toolkit';
import { GraphiQL } from 'graphiql';
import { useState } from 'react';

import 'graphiql/graphiql.css';
import '@graphiql/plugin-explorer/dist/style.css';

const fetcher = createGraphiQLFetcher({
  url: 'https://swapi-graphql.netlify.app/.netlify/functions/index',
});

function GraphiQLWithExplorer() {
  const storage = useStorageContext();
  const [query, setQuery] = useState(() => storage.get('query'));
  const explorerPlugin = useExplorerPlugin({
    query,
    onEdit: setQuery,
  });
  return (
    <GraphiQL
      fetcher={fetcher}
      query={query}
      onEditQuery={setQuery}
      plugins={[explorerPlugin]}
    />
  );
}

function GraphiQLWithStorage() {
  return (
    // The GraphiQL component also renders this provider, but we want to access
    // the storage before rendering `GraphiQL`, so we just render the provider
    // a second time here.
    <StorageContextProvider>
      <GraphiQLWithExplorer />
    </StorageContextProvider>
  );
}
```
