### ISSUE TITLE
Github OAuth using Netlify Functions for demos

### ISSUE THREAD

**Issue by acao** [graphql/graphiql#1772]
This would be SUPER helpful, if anyone wants to set this up using netlify functions and github oauth

Our `NETLIFY_TOKEN` secret is already present. 

monaco webpack example and graphiql webpack examples should both have a github oauth login

**Comment by ChiragKasat** [comment]
hey, I would like to work on this.

**Comment by acao** [comment]
awesome! please feel free to open a PR once you have something ready, and a draft if you get stuck and need help

I was thinking of going the tried and true passportjs route, similarly to this:
https://markus.oberlehner.net/blog/implementing-an-authentication-flow-with-passport-and-netlify-functions

enjoy! and feel free to reach out on discord

**Comment by git-anurag-hub** [comment]
@ChiragKasat Are you still working on this?

**Comment by git-anurag-hub** [comment]
@acao I am working on it.

**Comment by acao** [comment]
ty!

**Comment by endurance21** [comment]
@git-anurag-hub 
Are you working on this   ?
If not I would like to work on the issue :)

**Comment by acao** [comment]
@endurance21 no one is currently working on this so feel free to! I may get to it myself in the coming weeks if no one else does

https://docs.netlify.com/visitor-access/oauth-provider-tokens/

we can follow this approach. 

I’ve already configured everything that needs to be configured, so all that’s needed is to replace the `prompt()` in the monaco example with the clientside example they gave (without jquery and plain js of course)

**Comment by acao** [comment]
this was implemented1! very easy to do with netlify. enjoy!
