### ISSUE TITLE
Store more than 20 queries in History?

### ISSUE THREAD

**Issue by alvaro1728** [graphql/graphiql#1782]
Hi,

Is there a way to store more than 20 queries in the History pane?  I would prefer to store the last 50.

Thanks,
Alvaro

**Comment by maraisr** [comment]
Hi there @alvaro1728 thank you for raising this, unfortunately there I is no way to store a higher count. You can see this value is hard-coded here: https://github.com/graphql/graphiql/blob/main/packages/graphiql/src/components/QueryHistory.tsx#L19

We have seen this issue come about in the past, and may look at this in the future. I'm only quite new to the project so would need @acao to make a decision with this one.

**Comment by imolorhe** [comment]
Perhaps this can be an issue that will be addressed in v2.0 (making it configurable) instead of the current version. Although I think we can still have a reasonable cap on it. I assume 20 was chosen due to storage concerns.

**Comment by acao** [comment]
`MAX_HISTORY_LENGTH` is set statically in this component. we could expose a prop in 1.0, but query history will be rewritten in 2.0 with a new UI and a hooks API

**Comment by acao** [comment]
`maxHistoryLength` Is now the prop to use to configure this and override the default of 20!
