### ISSUE TITLE
Can't run graphiql sample?

### ISSUE THREAD

**Issue by endquote** [graphql/graphiql#179]
After cloning the repo and following the install instructions in example/readme.md, I'm seeing this:

![screenshot 2016-10-26 21 50 20](https://cloud.githubusercontent.com/assets/330010/19754935/bbdcd0b0-9bc6-11e6-952d-daa172c78c92.png)

I'm using latest node (7) on latest OS X (10.12.1). Maybe it's too new?

I'm hoping to inspect a graphql server other than localhost, is there some way I can tell it what endpoint to look at? Thanks!

**Comment by asiandrummer** [comment]
Hi @endquote - it seems like I made a mistake in #146 and broke the example code since then. I'm making a fix now. Sorry for the breakage!

**Comment by endquote** [comment]
Thanks for taking a look. The behavior still seems the same to me, though.

![screenshot 2016-11-04 09 14 53](https://cloud.githubusercontent.com/assets/330010/20013116/3ace7910-a26f-11e6-873e-5d6c399067b1.png)

**Comment by endquote** [comment]
If I apply that change manually it works... guess it's just not merged yet.

**Comment by asiandrummer** [comment]
Yeah, I was communicating with the contributor/repo mentioned in #146 before merging. This should be good now!

**Comment by endquote** [comment]
@asiandrummer Related question for you here if you have a moment... http://stackoverflow.com/questions/40451636/

**Comment by asiandrummer** [comment]
And answered :) http://stackoverflow.com/questions/40451636/inspecting-a-remote-graphql-endpoint-with-graphiql/40454629#40454629

**Comment by endquote** [comment]
Hero! Thank you, definitely one step closer...
