### ISSUE TITLE
GraphiQL.createFetcher does not work for subscriptions-transport-ws

### ISSUE THREAD

**Issue by junminstorage** [graphql/graphiql#1800]
As shown in this PR on express-graphql: https://github.com/graphql/express-graphql/pull/739/files#diff-f851f2ce2fbcb0220aaca183def93d7ced5b533fead2016551cfd6d37b357ae5,  I started the graphql server with subscription using legacy subscriptions-transport-ws. 

Then on the client side I create fetcher like this:
```
window.GraphiQL.createFetcher({url: fetchURL, subscriptionUrl: ${safeSerialize(
            subscriptionEndpoint,
          )}});
```

Then I got error as shown in the below screenshot: 
<img width="924" alt="Screen Shot 2021-02-10 at 9 29 46 PM" src="https://user-images.githubusercontent.com/140900/107597200-f2335580-6be7-11eb-9d6b-f045866e1b4d.png">

The same client side code works if I started a graphql server using graphql-ws though:
https://github.com/graphql/express-graphql/pull/739/files#diff-4f5f57981087dfef3de9e960e86656c7a1d1ef9f424fd0a75e32751163a286e1

**Comment by acao** [comment]
@junminstorage thank you for looking into this, this is strange

**Comment by junminstorage** [comment]
I also pulled in ```@graphiql/toolkit``` since the fetcher is moved under toolkit now, I still got the same error.  The bug may be somewhere in those lines in this function?https://github.com/graphql/graphiql/blob/3286b9c6665a7d3a4988654d9adf1b4230ccf734/packages/graphiql-toolkit/src/lib.ts#L70-L80

**Comment by acao** [comment]
@junminstorage no changes have been made to address your bug yet. we will probably remove support for the legacy protocol

**Comment by acao** [comment]
I will let you know when there is an update, but for now just letting you know that the location of the package has changed

**Comment by junminstorage** [comment]
I tried out the approach as in https://github.com/graphql/graphiql/blob/3286b9c6665a7d3a4988654d9adf1b4230ccf734/packages/graphiql-toolkit/src/lib.ts#L70-L80, both wsClient and legacyClient can be initialized against both subscription ws server without any errors being thrown. 
the express-graphql is already on legacy ws client, it will be great if we support it. how hard is to add legacyClient as one of the options in createFetcher?

**Comment by acao** [comment]
express graphql should not be using deprecated packages imo. the legacy protocol is deprecated, so we will remove it in the next release

**Comment by junminstorage** [comment]
https://www.npmjs.com/package/subscriptions-transport-ws still have 1.7 millions weekly download.  we have the chance to support both protocols with little cost here.
 
if we remove it from express-graphql, next release will be breaking change. And we also need to make change and fix the bug in this rc as well. 

anyway, just let me know the direction we eventually take, I can help with this issue as well.

**Comment by acao** [comment]
@junminstorage do you think you could introduce a PR for this fix then? maybe collaborate with @ryan-m-walker and/or @imolorhe since i’m taking a break?

**Comment by junminstorage** [comment]
Surely and happy to do so. Let me draft a PR to start the discussion with them.

**Comment by acao** [comment]
I have a fix coming!

**Comment by acao** [comment]
@junminstorage introduced the `legacyClient` option as requested in the above PR. thanks for all your work @junminstorage getting this working in the ecosystem, hoping to help you get everything working nicely here and in `express-graphql` in the following weeks!

**Comment by junminstorage** [comment]
@acao make sense. thank you!
