### ISSUE TITLE
Ugly scrollbars in doc explorer

### ISSUE THREAD

**Issue by dllu** [graphql/graphiql#1812]
In https://github.com/graphql/graphiql/blob/3dbc90b66adc4a59d5751fff1de3c8b0df2020d2/packages/graphiql/src/css/doc-explorer.css#L28 we have `overflow-x: hidden` but there is still an `overflow-y` that is defaulted to auto. As a consequence, with some fonts on some platforms, there can be an ugly scrollbar visible even for **single line content at the default zoom level**.

This applies to elements `.doc-explorer-title` and `.doc-explorer-back`.

![pic](https://s.dllu.net/2fXei_P3Yq0-OnQb.png)

For example this is the case on Chromium Version 89.0.4389.90 (Official Build) Arch Linux (64-bit).

p.s. [scrollbar blindness](https://svenkadak.com/blog/scrollbar-blindness) is a mildly hilarious read.

**Comment by maximiliancsuk** [comment]
I was having the same issue and looked into it. The issue for me was that we are using ant design for frontend components, and use GraphiQL inside of it in a react component. ant design sets the (imho bad) CSS:
```
.ant-layout * {
    box-sizing: border-box;
}
```
So anything that's a child of an .ant-layout element gets `box-sizing: border-box;` This leads to the behaviour you show in your screenshot.

My workaround is the following CSS:
```
.graphiql-container * {
    box-sizing: unset !important;
}
```
Not a fan of it (especially the `!important bit`, but it fixed the error for me. 

Maybe this helps you! If anybody got a better fix, lmk. :)

**Comment by acao** [comment]
thanks for this tip @maximiliancsuk ! i hope it's enough of a hint for folks to track down similar issues with other design systems or even custom wrapping css

also, a css tip - I think this would allow you to remove `!important` by using a more specific selector:

```css
.ant-layout .graphiql-container * {
    box-sizing: unset;
}
```

that cascading action!

trying to decide if i should close this ticket, as it seems like a support issue. either way, we need better documentation around this!

**Comment by maximiliancsuk** [comment]
Really good catch with that CSS, thanks @acao ! I tried some combinations hoping to convince the browser to make my statement more specific, but it didn't cross my mind to just nest `.graphiql-container` in `.ant-layout`. Cheers! :)

**Comment by jonathanawesome** [comment]
Seems like there's a workaround here, so I'm going to close.
