### ISSUE TITLE
How to display multiple response?

### ISSUE THREAD

**Issue by aihornmac** [graphql/graphiql#183]
So I am building GraphQL IDE with GraphiQL, and I was testing subscription with observable. Every time observable returns result, it replaces the current response with new response. Is there a way to pile up responses in descending order by incoming time?

**Comment by asiandrummer** [comment]
Hi @aihornmac - you should be able to configure that in your Observable stream that GraphiQL is subscribed to. All GraphiQL does is to display whatever response fed by Observable stream, so if your observable stream sends the piled-up results, it'll just relay that in the ResultViewer.

**Comment by asiandrummer** [comment]
I'm closing this issue for now - let me know if you have any other questions @aihornmac!
