### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by ardsouza** [graphql/graphiql#1832]
**Error**

```


./node_modules/graphql-language-service-interface/esm/GraphQLLanguageService.js 100:23
--
239 | Module parse failed: Unexpected token (100:23)
240 | You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
241 | \|         }
242 | \|         let customRules = null;
243 | >         if (extensions?.customValidationRules &&
244 | \|             typeof extensions.customValidationRules === 'function') {
245 | \|             customRules = extensions.customValidationRules(this._graphQLConfig);


```

**Temporary Solution**

downgrade graphql-language-service-interface to 2.8.2
We're were forced to use https://github.com/rogeriochaves/npm-force-resolutions which works in this case but is not ideal.

**Actual Solution**

https://babeljs.io/docs/en/babel-plugin-proposal-optional-chaining

**Potential Issues**

Carets https://github.com/graphql/graphiql/blob/main/packages/graphiql/package.json#L52

**Comment by TomKalina** [comment]
I have the same problem.
Solution for me.
```json
"dependencies": {
  "graphql-language-service-interface": "2.8.2",
  "graphql-language-service-parser": "1.9.0"
}
```

**Comment by Dodobibi** [comment]
Finally, I keep the last versions.
My workaround : Use transpilling `graphql-language-service` when compiling

```javascript
//nuxt.config.js
build: {
    transpile: ['graphql-language-service'],
}
```
(I'm using it in Nuxt.)

**Comment by acao** [comment]
We've adjusted `esm` exports to target `es6`, so this should be fixed! `cjs` should still be `es6`

**Comment by floyd-may** [comment]
@acao how would one watch for or subscribe to whatever the next release is so one could unpin those versions?

**Comment by abisalehalliprasan** [comment]
@acao: @ardsouza 's suggestion worked to get rid of the compile error but upon rendering the playground I am getting the below  error : 
```
Cannot read property 'div' of undefined 
```
inside the file ExecuteButton.js

Appreciate any pointers!

Ref : 
https://github.com/graphql/graphql-playground/issues/1235#issuecomment-827811041

**Comment by acao** [comment]
does the latest release seem to address this? playground will not reflect these updates yet

**Comment by TomKalina** [comment]
> does the latest release seem to address this? playground will not reflect these updates yet

My problem is solved. Thanks.

**Comment by acao** [comment]
Ok good to hear! @graphql/graphiql-maintainers can someone close this?
