### ISSUE TITLE
Syntax Error: Unexpected EOF for dynamically created query

### ISSUE THREAD

**Issue by andersryanc** [graphql/graphiql#1842]
## Actual Behavior

I'm receiving the following error: `Syntax Error: Unexpected <EOF>` when trying to use a javascript variable inside the gql template tag.

## Expected Behavior

No error.

## Steps to Reproduce the Problem Or Description

I'm not sure what version this changed in, but I noticed recently (after not working on this project for a little while and then coming back to it) that something had changed. Namely, it seems like autocomplete and validation against my actual GraphQL server started working / was added (without any changes from me), which is awesome by the way!! However, I don't remember seeing any errors related to my javascript variable before this update.

```js
import gql from 'graphql-tag'
import { perPage } from '../../config'

export const ALL_EVENTS_QUERY = gql`
  query ALL_EVENTS_QUERY(
    $where: EventWhereInput
    $orderBy: EventOrderByInput
    $skip: Int = 0
    $first: Int = ${perPage}
  ) {
    events(where: $where, orderBy: $orderBy, skip: $skip, first: $first) {
      id
      date
      title
    }
  }
`
```

<img width="757" alt="Screen Shot 2019-10-22 at 2 19 38 PM" src="https://user-images.githubusercontent.com/689046/67334626-53a55180-f4d7-11e9-9379-4241cacf35d6.png">

Also, this seems like it might be related to: https://github.com/apollographql/eslint-plugin-graphql/issues/156 ??

## Specifications

  - GraphQL for VSCode Extension Version: 0.2.2
  - VSCode Version:
```
Version: 1.39.2
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:33:00.827Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 19.0.0
```
  - OS Name: MacOS
  - OS Version: 10.15

## Logs Of TS Server || GraphQL Language Service

I'm happy to provide either of these, but I'm not sure where to find them... Under the "Output" tab with "GraphQL Language Server", I'm seeing nothing...

**Comment by acao** [comment]
Transferring to the monorepo because  it’s an issue with the LSP server

**Comment by RTAndrew** [comment]
Thank you for reopening. I am looking forward to test the fix.

**Comment by lcberg** [comment]
Not a fix, but I used this workaround and it works fine for me:
![image](https://user-images.githubusercontent.com/50460080/126644450-adf34368-c6a7-4864-a907-84dd11ec3106.png)

**Comment by acao** [comment]
If someone wants to open a PR to graphql-language-service-parser to add this feature to our parser, go ahead!

until then, you can autocomplete and validate for fragments included in `documents` config like many users are doing

**Comment by PaulFidika** [comment]
I just recently started getting this error message in VSCode today. I didn't change anything; my parser just decided it hates my the query-fragments I'm importing for some reason. I ignored the error and my app works fine but it still bothers me.

**Comment by decodekult** [comment]
Having this same problem when working with fragments. Not that much more extra info, just adding weight to the ticket.

**Comment by sschneider-ihre-pvs** [comment]
> This is a straight up bug. Just because an issue is tricky to fix, doesn't mean it should be closed as `wontfix`.
> 
> It's the most basic way to include fragments in queries:
> 
> <img alt="Screen Shot 2020-09-29 at 1 10 20 pm" width="451" src="https://user-images.githubusercontent.com/1754873/94508392-40594500-0255-11eb-80a5-fce9e8a32752.png">
> 
> <img alt="Screen Shot 2020-09-29 at 1 10 45 pm" width="446" src="https://user-images.githubusercontent.com/1754873/94508394-43543580-0255-11eb-869f-3a9ec7077326.png">
> 
> For people using fragments like this there is no choice but to either ignore the errors caused by this extension, or to uninstall the extension. The Apollo extension doesn't display an error in this situation.

At least for fragments, putting them at the end of the gql literal seems to help

**Comment by acao** [comment]
I added this feature in late december 2021, enjoy!

**Comment by acao** [comment]
https://github.com/graphql/graphiql/pull/2111

**Comment by miguel-sf** [comment]
im getting this error still inside the query

![image](https://github.com/graphql/graphiql/assets/153878329/87555c15-60f6-431c-809b-6ffe18caea61)

**Comment by acao** [comment]
again, it's unexpected syntax so graphql will fail validation, there's nothing else we can do here without it getting ridiculously complex. in your case it would be much easier to use variables, and then you'll get better validation!
