### ISSUE TITLE
Set custom height for Graphiql React component

### ISSUE THREAD

**Issue by casperOne** [graphql/graphiql#1849]
This is similar to, but I'm not sure it's exactly the same:

https://github.com/graphql/graphiql/issues/87

Namely, I'm hosting the `Graphiql` React component which has other components on the page.  Because of this, there isn't an HTML component that we can set the style of in the page.

It would be beneficial if there was a prop of type `CSSProperties` which would be applied to the root element that `Graphiql` is rendered to.  In my case, I'd set either the `height` or `flex-grow`, but I think it would be beneficial to be able to set any CSS property on the root element.

A `className` to attach to the root would also work, but style is probably more flexible in case there are style properties which need to be calculated on-the-fly and applied to the `Graphiql` component.

**Comment by acao** [comment]
`<GraphiQL />` is stylable as a component whether rendered alongside other react components or on it's own.
The React element or component that surrounds the GraphiQL component is able to control the height of the GraphiQL editor.
