### ISSUE TITLE
Politics in README.md

### ISSUE THREAD

**Issue by barvhaim** [graphql/graphiql#1861]
Code should be politics free.

**Comment by orta** [comment]
That's never realistically going to happen given that software is made by people and people have opinions, let's keep this in a single issues instead of many

**Comment by leebyron** [comment]
The GraphQL technical steering committee is working on a policy to guide the use of political speech from the voice of a GraphQL project. The original author chose to revert the original change via #1879 until we complete that policy. This should resolve this issue.

As a reminder, all discussion within GraphQL projects must adhere to our [Code of Conduct](https://github.com/graphql/foundation/blob/main/CODE-OF-CONDUCT.md).
