### ISSUE TITLE
Political phrasing is used in the read me which is controversial and might provoke anti semitism

### ISSUE THREAD

**Issue by aviv1ron1** [graphql/graphiql#1862]
The term "free palestine" which was posted on the readme:
A. has no relevance to the project
B. violates the graphql code of conduct
C. is controversial politically
D. is many times accompanied to anti semitic behavior such as the recent attacks on jews in LA: https://www.nytimes.com/2021/05/20/us/jewish-hate-crime-los-angeles.html

**Comment by barvhaim** [comment]
+1

**Comment by andreyFinkel** [comment]
+1

**Comment by almogbl** [comment]
+1

**Comment by yuvalapidot** [comment]
+1

**Comment by gennady9** [comment]
+1

**Comment by Eitaje** [comment]
+1

**Comment by saputkin** [comment]
+1

**Comment by olegsu** [comment]
+1

**Comment by ad-venture** [comment]
+1

**Comment by mjm** [comment]
How does this statement violate the GraphQL code of conduct?

**Comment by avshyz** [comment]
+1

**Comment by eladcandroid** [comment]
+1

**Comment by aviv1ron1** [comment]
@mjm

1. It is a political issue which is controversial depending on your political view
2. It is interpreted in a different way by different people - hence controversial. There is no clear definition of what palestine is and meither what free means.
3. People who are using it are commiting hate crimes against jews all over the world lately - so this phrasing is encouraging these attacks
4. The graph QL code of conduct says to avoid political attacks
5. "Free Palestine" is a political attack on the state of Israel

We can debate what these two words mean in the deepp and historical context of Israel and Palestine, but whats the point? Is open source the place to hold political debates?
And why the maintainers political agenda should be "preached" to anyone reading the readme of this open source?

**Comment by aviv1ron1** [comment]
@mjm 

to make my statement that this phrase is controversial:
[qoura](https://www.quora.com/When-people-say-Free-Palestine-do-they-mean-West-bank-and-Gaza-or-the-whole-region-of-Palestine)
[free palestine movement](https://en.wikipedia.org/wiki/Free_Palestine_Movement) - a Palestinian Syrian armed movement that opposes the existence of Israel

**Comment by twof** [comment]
@aviv1ron1 "Controversial" activity doesn't seem to be banned or mentioned in the code of conduct. I think this would qualify more as a political statement than an attack since it wasn't directed at any particular person.

Code of conduct: https://graphql.org/codeofconduct/

**Comment by aviv1ron1** [comment]
Excuse me @twof  but if many people think that these two words define a threat to my existence that is a political attack.
If there is a movement with that name that wants me dead that is threatning me.

Shall I encourage now every developer I know to post "I stand with israel" in the title of their repos?
Is that the atmosphere that we want to encourage in open source?

**Comment by twof** [comment]
@aviv1ron1 are there words people could use to support Palestinians that you wouldn't feel is a threat to your existence? Is it the words that are a problem for you, or the support?

**Comment by aviv1ron1** [comment]
The context that might be associated to these words is the problem. Also the one sidedness of these words is problematic to me.

Personally I support the two state solution, but that has nothing to do with open source.

By the way - in Israel many who felt bad about the situation lately posted a message saying : "jews and arabs refuse to be enemies" 
Posting something like that which promotes peace will contribute more to the cause.
Another issue has been opened, I also recommend reading his suggestions, they are very good.

But frankly - all this just doesnt belong to open source.
We should not involve politics in open source. Neither gender race and religion discrimination. Lets keep it clean.

**Comment by avshyz** [comment]
+1

**Comment by nafg** [comment]
Forget controversial, "free Palestine" is a well known dog whistle call to violence.

Supposedly pro-Palestinian groups don't advocate for helping Palestinians nearly as much as they advocate harming Israel. See e.g. https://elderofziyon.blogspot.com/2021/05/bds-list-of-what-supporters-should-do.html?m=1

Even if you disagree with this characterization, many potential readers equate harming Jews with helping Palestinians.

Therefore I recommend avoiding throwing more fuel into the fire.

If you want to help Palestinians, advocate for overthrowing Hamas which has its boot on their neck and uses them as human shields. It stores rockets near children and prevents them from leaving when Israel gives them advance notice of a coming bombing. It denies them freedom of press. Palestinians that disagree with their narrative are afraid to speak up.

**Comment by nafg** [comment]
Other ways to help Palestinians include buying from their businesses, ending terrorism training camps as well as school textbooks and media that instill in them hatred of Jews and peace, and replace them with curricula that value peace, democracy, truth, and individual liberty.

**Comment by aviadhahami** [comment]
What worries me more than this one-developer-unimportant-opinion is the fact that he was able to push directly to prod w/o any reviewing mechanism.

This makes the maintaining group of this project targetable by malicious actors if such wanna poison the codebase and its users.

Shouldn't there be a safer flow for changes introduction and review?

**Comment by pab1it0** [comment]
+1

**Comment by DeepSpace2** [comment]
Just another reason for **not** using graphql...

**Comment by acao** [comment]
there are many islamaphic comments here, and other comments which violate the CLA. I take offense as people I care about have dealt with harassment and hate crimes already because of this kind of rhetoric, not to mention the muslim women who were hospitalized over this last week.

**Comment by Evilu** [comment]
> there are many islamaphic comments here, and other comments which violate the CLA. I take offense as people I care about have dealt with harassment and hate crimes already because of this kind of rhetoric, not to mention the muslim women who were hospitalized over this last week.

Please, let me tell you something, even anti-Semitism always comes up when messages like you posted arrive 
And the president himself tweeted about it yesterday.
Please leave the open source community out of these divisive conflicts.

**Comment by pantchox** [comment]
@acao 
Bringing your sided opinions to the open source community does not support each "sides" causes. 
This is just dividing and triggering people to drift to this wormhole of never-ending discussions.
You used your power to to promote something you think its right (without consent).
This is not the place.

As for the people you care about getting hurt its on both sides, Due to these calls of what you are promoting this what happens https://twitter.com/wokal_distance/status/1395555636650430467
Call it islamophobia call it anti-Semitism - its just promotes hate.

As well your Twitter comments on your actions shows your contempt for this repo and its community (even if you were promoting a different side, it does not matter) 

Just remove your change and lets all move on doing what we do best.
Thank you.

**Comment by DeepSpace2** [comment]
> How does this statement violate the GraphQL code of conduct?

From https://graphql.org/codeofconduct: 

> Trolling, insulting/derogatory comments, and personal or political attacks

And maybe also

> Focusing on what is best for the community

(This event is certainly not "best for the community")

**Comment by nafg** [comment]
> there are many islamaphic comments here

Name one. I think your definition of islamaphobic must is any suggestion that anyone hijacks their cause. Nothing in this thread is anti-Islam. Nor anti-Palestinian or anti-Muslim. Just anti antisemitic dog whistles.

> I take offense as people I care about have dealt with harassment and hate crimes already because of this kind of rhetoric, not to mention the muslim women who were hospitalized over this last week.

I can say the same thing. I take offense as people I care about have dealt with harassment and hate crimes already because of this kind of anti-Israel rhetoric, not to mention the people who were hospitalized over this in last few weeks.

**Comment by DeepSpace2** [comment]
@AGS- @benjie @eapache @IvanGoncharov @orta @saihaj @tvalentius

**Comment by arielweinberger** [comment]
> there are many islamaphic comments here
1. @acao It's called "Islamophobic". But I'm not surprised, judging based on your Tweets, you genuinely have no idea what you're talking about. And it also seems like there are a handful of people on Twitter who identify with what you say, which says a lot for somebody with 1k+ followers.

2. Quote one Islamophobic comment here. Provide a link please. Until you do that, I'll bluntly call you a liar.

Right now, this project looks like a kindergarden.

**Comment by arielweinberger** [comment]
> there are many islamaphic comments here
1. @acao It's called "Islamophobic". But I'm not surprised, judging based on your Tweets, you genuinely have no idea what you're talking about. And it also seems like there are a handful of people on Twitter who identify with what you say, which says a lot for somebody with 1k+ followers.

2. Quote one Islamophobic comment here. Provide a link please. Until you do that, I'll bluntly call you a liar.

Right now, this project looks like a kindergarden. And you don't seem to care about that at all. You'll do anything to spread hate and division, and you knew that your fellow maintainers wouldn't feel comfortable rebasing your commit. Destructive actions with a wide range of impact. Not something I'd expect a colleague to do - that's called a d**k move.

**Comment by SRachamim** [comment]
Oh! This is the place to talk about politics? Can I open a new issue for each one of the [thousands of terror attacks](https://en.wikipedia.org/wiki/Palestinian_political_violence#Second_Intifada_(2000%E2%80%932005)) that murdered ten-thousands of civilians in the name of the "Free Palestine" phrase?

[This is an example to how one can try to free Palestine](https://www.youtube.com/watch?v=0dsVSi4U3Ek&t=38s)

**Comment by leebyron** [comment]
The GraphQL technical steering committee is working on a policy to guide the use of political speech from the voice of a GraphQL project. The original author chose to revert the original change via #1879 until we complete that policy. This should resolve this issue, so I am closing it.

As a reminder, all discussion within GraphQL projects must adhere to our [Code of Conduct](https://github.com/graphql/foundation/blob/main/CODE-OF-CONDUCT.md).

**Comment by markrity** [comment]
@leebyron It's still dangerous that one of your maintainers can push things to master without any approving mechanism, 
What will be next time? Commit some malware, so every user will join Hamas botnet army? Ransomware that only will be activated on Israeli computers? How can users trust such a project ?

**Comment by leebyron** [comment]
@markrity - that seems disingenuous.

I think you'll find nearly every project on Github have maintainers who have commit rights and are fully capable of pushing things to master. How can you trust any open source project? You can read it's source code for yourself.

Rikki is clearly apologetic about not consulting the other maintainers before making that change, hence reverting it. I think it's insulting to equate a maintainer's political opinion with an assumption that such a person would commit malware.

**Comment by SnirShechter** [comment]
@leebyron 

I appreciate your responsiveness on the matter, although I must say Rikki commented in a different issue about not being apologetic and about Palestinian friends saying this act did in fact help them and made a change.

I'm not judging, but I must say it seems like Rikki accomplished exactly what was planned. Congrats.

**Comment by markrity** [comment]
@leebyron I understand what you are saying, but those restrictions I mentioned are my personal "best-practice", that I implement at all of the repos I had a chance to maintain. 
From what I have seen there were couple of projects that were compromised by "unstable" maintainers.  

I do not have anything personal agains Rikki or his political views, but in my opinion, doing such a move without getting backed up (by a PR) from other maintainers, was a hasty and unfaithful move.

Anyway, this drama is over, so thank you for your patience and replies to everyone.
