### ISSUE TITLE
Readme -  anti semitism 

### ISSUE THREAD

**Issue by yedri101** [graphql/graphiql#1863]

**Comment by orta** [comment]
Let's keep this to a single issue

**Comment by leebyron** [comment]
The GraphQL technical steering committee is working on a policy to guide the use of political speech from the voice of a GraphQL project. The original author chose to revert the original change via #1879 until we complete that policy. This should resolve this issue.

As a reminder, all discussion within GraphQL projects must adhere to our [Code of Conduct](https://github.com/graphql/foundation/blob/main/CODE-OF-CONDUCT.md).
