### ISSUE TITLE
Freedom supporter

### ISSUE THREAD

**Issue by barvhaim** [graphql/graphiql#1864]
Hi freedom supporter, I wonder why you are not putting visibility for the mass murdering of Syria government in Syrian civilians.. Are their souls are less worthy than terror organization Hamas in Gaza that was firing over 4000 rockets on our homes in Israel the last 2 weeks? Or do you prefer to close your eyes in the US? Why bringing this to public GitHub and taking sides in favor to a terror organization? 

You are reported, I believe this is against the GitHub community rules.

Enjoy
https://en.wikipedia.org/wiki/Casualties_of_the_Syrian_civil_war

**Comment by orta** [comment]
Lets keep this to a single issue

**Comment by leebyron** [comment]
The GraphQL technical steering committee is working on a policy to guide the use of political speech from the voice of a GraphQL project. The original author chose to revert the original change via #1879 until we complete that policy. This should resolve this issue.

As a reminder, all discussion within GraphQL projects must adhere to our [Code of Conduct](https://github.com/graphql/foundation/blob/main/CODE-OF-CONDUCT.md).
