### ISSUE TITLE
Free Palestine in README

### ISSUE THREAD

**Issue by benjamingr** [graphql/graphiql#1865]
Hi,

I'm Israeli. I'm not personally opposed to the Free Palestine message in the readme. I don't want to get into my personal opinions regarding Palestine. 

My goal with this issue is to try and help you avoid a mistake I believe I was a part of. If you'd rather have this discussion elsewhere feel free to email me instead.

Personally, I regret the #BlackLivesMatter banner that I supported in the Node.js website. It did very little to help with the injustice or tech's complictness in it - I believe we have failed in our promise to be part of the solution.

What I'd like to do is challenge you to do more than "performative allyship" here. "Free Palestine" is an ambiguous message that is divisive and doesn't do enough to help Palestinians. 

Instead, I'd like to suggest supporting organisations that actively help Palestinians or promoting Palestinians yourself:
 - Promote technology and initiatives from companies that promote peaceful co-existence and hire Palestinians like [Mellanox/Nvidia](https://nocamels.com/2018/06/rawabi-tech-israeli-palestinian-initiatives/). 
 - Put a link to tech accelerators that help Palestinians like [GazaSkyGeeks](https://gazaskygeeks.com/). They also accept donations (I have donated myself in the past).
 - Add a link to programs that help Palestinians like [Manara](https://www.manara.tech/) and suggest hiring from there yourself.
 - Offer direct mentorship/training to Palestinians who want to get involved (e.g. https://news.ycombinator.com/item?id=11860938 )

**Comment by benjamingr** [comment]
To be clear - my point applies equally to the BlackLivesMatter message in the README. Saying "black lives matter" isn't enough nor does it deal with the systematic problem.

The only reason I did not recommend companies/charities/accelerators for that cause is that I do not have experience with any.

**Comment by aviv1ron1** [comment]
@benjamingr those are beautiful ideas that you brought up!

**Comment by KimiNewt** [comment]
that last link to a random post from 2016 is *chef's kiss*

**Comment by benjamingr** [comment]
That last post was just a real example of a message that worked for me personally. That is my username in hacker news.

**Comment by DeepSpace2** [comment]
Just another reason for **not** using graphql...

**Comment by FlickerLogicalStack** [comment]
Nice place for some political discussions guys, applause.
Any relation of Palestine to graphiql issues?

**Comment by aviv1ron1** [comment]
> Nice place for some political discussions guys, applause.
> Any relation of Palestine to graphiql issues?

Yes. Once the maintainer posts "free Palestine" in the title of the readme there you have a relation.

**Comment by arielweinberger** [comment]
@FlickerLogicalStack you didn't read the instructions did you...

**Comment by leebyron** [comment]
The GraphQL technical steering committee is working on a policy to guide the use of political speech from the voice of a GraphQL project. The original author chose to revert the original change via #1879 until we complete that policy. This should resolve this issue, so I am closing it.

As a reminder, all discussion within GraphQL projects must adhere to our [Code of Conduct](https://github.com/graphql/foundation/blob/main/CODE-OF-CONDUCT.md).

**Comment by benjamingr** [comment]
Thanks for the update. Removing the banner seems like a good call to me.

@acao if you would like to constructively contribute towards helping Palestinians please feel free to reach out to me or to any of the organisations I mentioned in this post.

**Comment by acao** [comment]
@benjamingr I am already working with local palestinian organizations and helping my jewish friends forming an IJAN chapter! This is something I’ve already discussed. The local organizations are the ones who encouraged use of the phrase “free palestine” at local protests where our rainbow coalition assembled, where people from all faiths assembled to call for an end to the apartheid. This act *was* a constructive way of helping the Palestinians, according to my Palestinian friends. I am not interested in any further condescending “guidance” on the matter

**Comment by benjamingr** [comment]
Fair enough, sorry if my message came off as condescending that was not my intention and best of luck.

If we learned a lesson about performative activism that'll have to do.
