### ISSUE TITLE
Free Palestine Readme

### ISSUE THREAD

**Issue by Evilu** [graphql/graphiql#1869]
Dear @acao 
While I greatly appreciate your work and your huge contribution to the project, and as a great supporter of the LGBTQ + community,
I would like to protest about your unnecessary commit that adds the Palestinian flag to the project’s Readme file. I urge you to read about the suffering of the LGBTQ + community in the Palestinian territories and how the vast majority of them reach asylum in Israel.

https://en.m.wikipedia.org/wiki/LGBT_rights_in_the_State_of_Palestine

Peace

**Comment by DeepSpace2** [comment]
![Uploading received_316197366635370.jpeg…]()

**Comment by DeepSpace2** [comment]
![received_316197366635370](https://user-images.githubusercontent.com/6841988/119535681-f1868f80-bd90-11eb-88cc-7b13d9c35f80.jpeg)

**Comment by leebyron** [comment]
The GraphQL technical steering committee is working on a policy to guide the use of political speech from the voice of a GraphQL project. The original author chose to revert the original change via #1879 until we complete that policy. This should resolve this issue, so I am closing it.

As a reminder, all discussion within GraphQL projects must adhere to our [Code of Conduct](https://github.com/graphql/foundation/blob/main/CODE-OF-CONDUCT.md).
