### ISSUE TITLE
Keep the Docs sidebar opened/closed between refreshes 

### ISSUE THREAD

**Issue by ivosabev** [graphql/graphiql#187]
That will save me a lot of time opening the Docs after each refresh. Thanks!

**Comment by joelgriffith** [comment]
Fixed in: https://github.com/graphql/graphiql/pull/191

**Comment by ivosabev** [comment]
Awesome, hopefully it gets released soon!

**Comment by asiandrummer** [comment]
Hey @ivosabev and @joelgriffith, thanks for the suggestion! #191 looks good to me, but I just wanted to make sure that fix wouldn't save the search results/history - it'll basically make sure the tab is opened when you reload the page, and the doc explorer will display the initial page without any results.

**Comment by joelgriffith** [comment]
Correct. Just persists the state of expansion on the doc explorer. No history pushes or state persistence.

**Comment by asiandrummer** [comment]
Cool - will close this issue since it's already merged. Thanks again!
