### ISSUE TITLE
Free Palestine in README

### ISSUE THREAD

**Issue by SnirShechter** [graphql/graphiql#1874]
Taking a political stand is not the way of the open source community. That is unrelated and highly unprofessional.

You care about the Israeli-Palestinian conflict? You can add a comment without picking sides. Here are some suggestions:
* "Jews and Arabs refuse to be enemies"
* "End the war"
* "End the conflict"
* "Stop the innocent casualties"
* "The Graphiql project stands with the innocent casualties on both sides"
* "We wish peace in the middle east"

**Comment by codepharmer** [comment]
End the conflict seems appropriate. But what does GraphQL have to do with peace in the middle east?

**Comment by SnirShechter** [comment]
> 'End the conflict" seems appropriate. But what does GraphQL have to do with peace in the middle east?

It doesn't, but the README says otherwise.

**Comment by SRachamim** [comment]
Here is an Open Source project that all of his issues, PRs and discussions deal with politics instead of how to improve its product.

This is what happens when people deals with things that they don't understand.

**Comment by leebyron** [comment]
The GraphQL technical steering committee is working on a policy to guide the use of political speech from the voice of a GraphQL project. The original author chose to revert the original change via #1879 until we complete that policy. This should resolve this issue, so I am closing it.

As a reminder, all discussion within GraphQL projects must adhere to our [Code of Conduct](https://github.com/graphql/foundation/blob/main/CODE-OF-CONDUCT.md).

**Comment by mhawwari** [comment]
These suggestions are inherently equivalent to saying "All lives matters" so not sure why Black lives matter is still up in the readme page. It's very unfortunate to see people backing down from these statements for the fear of being "too political" or from pressure of clear beneficiaries from systems of oppressions. While a lot of people don't see the need for tech, art or any similar field to make any kind of political statements, other groups of people do not have the privilege of ignoring the unjust politics that lead to their oppression. Their existence is political.
