### ISSUE TITLE
Israeli–Palestinian conflict

### ISSUE THREAD

**Issue by SRachamim** [graphql/graphiql#1876]
I see from the [README.md](https://github.com/graphql/graphiql#black-lives-matter--free-palestine-) that this is the place to talk about the Israeli–Palestinian conflict. I always wanted to do that in the [GraphiQL](https://github.com/graphql/graphiql) repository! Let's educate ourselves in that matter then.

May I open a new issue for each one of the [thousands of terror attacks](https://en.wikipedia.org/wiki/Palestinian_political_violence#Second_Intifada_(2000%E2%80%932005)) that murdered ten-thousands of civilians in the name of the "Free Palestine" phrase?

[This is an example to how one can try to free Palestine](https://www.youtube.com/watch?v=0dsVSi4U3Ek)

**Comment by leebyron** [comment]
The GraphQL technical steering committee is working on a policy to guide the use of political speech from the voice of a GraphQL project. The original author chose to revert the original change via #1879 until we complete that policy. This should resolve this issue, so I am closing it.

As a reminder, all discussion within GraphQL projects must adhere to our [Code of Conduct](https://github.com/graphql/foundation/blob/main/CODE-OF-CONDUCT.md).
