### ISSUE TITLE
Why is it's still in README? 

### ISSUE THREAD

**Issue by odeds-confetti** [graphql/graphiql#1877]
I am shocked that it's still in README.

I am sure that if somebody would add "Free Palestine From Hamas" or "Stand With Israel", Even "Arabs and Jews Refuse to be enemies" it was long removed by one of the maintainers.  

And to @acao I would hope to have just a fraction of a white man's confidence when talking about things that happen thousands of miles away from where I live.

**Comment by leebyron** [comment]
The GraphQL technical steering committee is working on a policy to guide the use of political speech from the voice of a GraphQL project. The original author chose to revert the original change via #1879 until we complete that policy. This should resolve this issue, so I am closing it.

As a reminder, all discussion within GraphQL projects must adhere to our [Code of Conduct](https://github.com/graphql/foundation/blob/main/CODE-OF-CONDUCT.md).
