### ISSUE TITLE
npm vulnerability in `@graphiql/toolkit` via `subscriptions-transport-ws`, which is unmaintained

### ISSUE THREAD

**Issue by s100** [graphql/graphiql#1884]
`graphiql` [depends on `@graphiql/toolkit@^0.2.0`](https://github.com/graphql/graphiql/blob/944205854e66eeccbcbcd88427ae6d4939c519cc/packages/graphiql/package.json#L46) which [has an optional dependency on `subscriptions-transport-ws@^0.9.18`](https://github.com/graphql/graphiql/blob/944205854e66eeccbcbcd88427ae6d4939c519cc/packages/graphiql-toolkit/package.json#L33), which [depends on `ws@^5.2.0`](https://github.com/apollographql/subscriptions-transport-ws/blob/ffc6b674fd3c3ebcc8b66025b3b272afc4133887/package.json#L16), which has [this vulnerability in it](https://www.npmjs.com/advisories/1748).

The ideal solution would be for `subscriptions-transport-ws` to upgrade its version of `ws`, and [this issue](https://github.com/apollographql/subscriptions-transport-ws/issues/875) has been opened to address this... however, `subscriptions-transport-ws`'s README states that it is not being actively maintained, and recommends that consumers use [`graphql-ws`](https://github.com/enisdenjo/graphql-ws) instead.

So, suggested approach is for `@graphiql/toolkit` to switch from `subscriptions-transport-ws` to `graphql-ws`. Alternatively, since `subscription-transport-ws` is an optional dependency, an extremely quick fix would be to remove it entirely.

**Comment by acao** [comment]
@s100 thanks for pointing this out!

the best option is to remove it from `optionalDependencies`. I was mistaken about how they work, embarassingly enough

we only include legacy support for `subscription-transport-ws` by popular demand, the new `graphql-ws` protocol is going to join the graphql transport spec as the official websockets protocol implementation.

if you or someone wants to fork `subscriptions-transport-ws` and make security fixes while keeping the legacy protocol in place, that would be welcome!

**Comment by acao** [comment]
@s100 are you aware that it already supports `graphql-ws`?

**Comment by s100** [comment]
In that case the solution is simply for `@graphiql/toolkit` to eliminate its optional dependency on `subscription-transport-ws` entirely.

**Comment by acao** [comment]
agreed! unfortunately there have been more pressing matters, I will get to this soon
