### ISSUE TITLE
editorTheme option dont change the resultViewer background color

### ISSUE THREAD

**Issue by cgarnier** [graphql/graphiql#1919]
The theme dont apply on the result window due to this rule: 

https://github.com/graphql/graphiql/blob/65aa64811ccd40c5e8ba99edec825a91115a3c8b/packages/graphiql/src/css/app.css#L216

The selector `.result-window .CodeMirror` override the theme selector `.cm-s-monokai.CodeMirror`

**Comment by acao** [comment]
oof! would you like to open a PR?
