### ISSUE TITLE
When header value is too long not able to see results of a query

### ISSUE THREAD

**Issue by ukasiu** [graphql/graphiql#192]
with header:
<img width="1280" alt="with header" src="https://cloud.githubusercontent.com/assets/816363/20030631/581364ea-a369-11e6-93fb-badc2b0cf395.png">
without header:
<img width="1280" alt="no header" src="https://cloud.githubusercontent.com/assets/816363/20030630/581116f4-a369-11e6-96da-6baebd096680.png">

**Comment by asiandrummer** [comment]
Hey @ukasiu - `GraphiQL` does not implement the header view, so this issue might not be relevant here. Seems like you could open an issue in [`graphql-toolbox`](https://github.com/OlegIlyenko/graphql-toolbox) repo here?

cc @OlegIlyenko

**Comment by OlegIlyenko** [comment]
Good catch :) @ukasiu I added the header value truncation. https://github.com/OlegIlyenko/graphql-toolbox/commit/3c0980e17124e86ed13b0c54ea6ab8005d40b53f

not a perfect solution, but I think it should do the trick for reasonably-sized monitors :) And indeed this is and issue `graphql-toolbox` and not GraphiQL itself.
