### ISSUE TITLE
TypeError: Cannot convert object to primitive value

### ISSUE THREAD

**Issue by TomasBarry** [graphql/graphiql#1929]
Using `{}` as a default value an argument of type `GraphQL::Types::JSON` gives the above error when inspecting a type:

```ruby
module Types
  class MyType < Types::BaseObject
    field(
      :thing,
      String,
      null: true
    ) do
      argument(
        :arguments,
        GraphQL::Types::JSON,
        required: false,
        default_value: {}
    )
    end
  end
end
```

Using the Documentation Explorer, clicking on `MyType` makes GraphiQL error out so that it is just a blank screen with the above error in the console.

Functionally this works just fine so I believe it's to do with the serialization. If you point me to where this is I can open up a PR with a fix.

**Comment by acao** [comment]
I'm not sure which language this is, but it seems you are using a tool or library that uses GraphiQL, and this support issue would be best addressed by the authors of your library.
