### ISSUE TITLE
[help] How to integrate graphiql with apollo-server-express

### ISSUE THREAD

**Issue by OmkarK45** [graphql/graphiql#1930]
Hi there, I want to use GraphiQL on the server-side (apollo-server-express), but I did not find any guide on how to do it. Can anyone point me in the right direction?

**Comment by acao** [comment]
@OmkarK45 you can just write an express middleware that serves up html and/or scripts, loading dependencies from CDN. look at the `examples/graphiql-cdn` example to get started!
