### ISSUE TITLE
Is it possible to use graphiql just as a readonly schema viewer for documentation?

### ISSUE THREAD

**Issue by bigman73** [graphql/graphiql#1931]
Is there a way to hide the editor and results panes and maximize the docs pane?

voyager is a schema viewer but it is displaying a graph, that can get complex with large schema. It doesn't provide the same experience as a structured schema browse found in graphiql.

For reference, for openapi there is a react schema viewer: https://github.com/temando/open-api-renderer

**Comment by acao** [comment]
you can import the `DocExplorer` component from `graphiql` directly! :)

**Comment by acao** [comment]
did that help @bigman73 ?

**Comment by bigman73** [comment]
yes, thanks for the direction
