### ISSUE TITLE
Missing dependency declaration for `graphql-language-service-utils`

### ISSUE THREAD

**Issue by oliversalzburg** [graphql/graphiql#1944]
`graphiql` and `codemirror-graphql` both try to import from `graphql-language-service-utils`, but do not declare the dependency.

See:
- https://github.com/graphql/graphiql/blob/main/packages/graphiql/src/components/GraphiQL.tsx#L28
- https://github.com/graphql/graphiql/blob/main/packages/codemirror-graphql/src/hint.ts#L18

The dependency should be properly declared.

**Comment by acao** [comment]
this should be fixed now

**Comment by willstott101** [comment]
Thanks @acao but it looks like there's been no changes to `codemirror-graphql`, it still uses `graphql-language-service-utils` at https://github.com/graphql/graphiql/blob/main/packages/codemirror-graphql/src/hint.ts#L18 wihtout declaring the dep

**Comment by acao** [comment]
Oops, it’s fixed in a PR, i got this mixed up with another ticket
