### ISSUE TITLE
Reports GraphQL syntax errors in cjs & mjs files

### ISSUE THREAD

**Issue by backbone87** [graphql/graphiql#1955]
## Actual Behavior
when writing cjs or mjs, vscode-graphql reports gql syntax errors on the first keyword.

## Expected Behavior
no error is shown and vscode-graphql treats it like other js files insteadof trying to parse it as gql

## Steps to Reproduce the Problem Or Description
create an cjs or mjs file and add any valid js code, e.g. in a cjs file:
```js
module.exports = {};
```

## Specifications

  - GraphQL for VSCode Extension Version:  0.3.15
  - VS Code:
  - Version: 1.53.2 (system setup)
  - Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
  - Date: 2021-02-11T11:48:04.245Z
  - Electron: 11.2.1
  - Chrome: 87.0.4280.141
  - Node.js: 12.18.3
  - V8: 8.7.220.31-electron.0
  - OS: Windows_NT x64 10.0.19042

**Comment by acao** [comment]
@dreilacadin you are free to open a PR! Also your company is welcome to pay me to fix this

**Comment by acao** [comment]
sorry that was rude. I'm onto a fix for this, my bad y'all!

**Comment by acao** [comment]
And then this PR will be the release for `vscode-graphql`:

https://github.com/graphql/vscode-graphql/pull/351

**Comment by acao** [comment]
ok! should be fixed now. let me know if there are any issues.

**Comment by macmillen** [comment]
confirmed. :heavy_check_mark:  thanks a lot for fixing it @acao ! :+1:
