### ISSUE TITLE
graphqiql with react + graphql-ws integration example?

### ISSUE THREAD

**Issue by tot-ra** [graphql/graphiql#1959]
Hey. Can someone add to examples how to use subscriptions with graphql-ws?
I tried https://github.com/kirgene/graphiql-ws/blob/master/src/renderGraphiQL.ts but it doesn't seem to work with latest graphiql version (it includes some packed version)

**Comment by acao** [comment]
https://github.com/graphql/graphiql/blob/main/packages/graphiql-toolkit/docs/create-fetcher.md#subscriptionurl

**Comment by acao** [comment]
I’m not sure what fork of graphiql you are using there, we only support code that is in this repository, sorry!

**Comment by tot-ra** [comment]
@acao Thanks! Got it somewhat working. 

Too bad that it expects that schema is loaded over POST and not over WS.

**Comment by acao** [comment]
that is not part of the graphql-ws spec proposal unfortunately
