### ISSUE TITLE
Auto-completion of field arguments breaks as soon as aliases are involved

### ISSUE THREAD

**Issue by OlegIlyenko** [graphql/graphiql#196]
This is an example query:

```graphql
{
  foo: human(| ← <cursor is here>
}
```

As soon as I use an alias, GraphiQL stops auto-completing the field arguments.

**Comment by asiandrummer** [comment]
@OlegIlyenko - thanks for the report :D Let me go investigate this if no one beats me to it.

**Comment by joelgriffith** [comment]
This appears to be a bug in https://github.com/graphql/codemirror-graphql as it's not firing the `onHasCompletion` function inside of GraphiQL

**Comment by joelgriffith** [comment]
Fixed via this PR: https://github.com/graphql/codemirror-graphql/pull/52 in `codemirror-graphql`

**Comment by OlegIlyenko** [comment]
Wow, that was fast! Thanks a lot, @joelgriffith!

**Comment by leebyron** [comment]
Closing this since the PR merged, but will get the chain of updated out soon :)
