### ISSUE TITLE
docs: websockets subscriptions for example?

### ISSUE THREAD

**Issue by acao** [graphql/graphiql#1969]
Seems this is possible somehow with netlify + express + websockets?

https://github.com/Nenino2/express-netlify-websockets-example/blob/master/assets/js/app.js

**Comment by dotansimha** [comment]
Also, for reference, worth adding what's available in GraphQL-Helix: https://github.com/contrawork/graphql-helix/tree/master/packages/graphiql/src 

It's basically GraphiQL with support for all subscriptions protocols (`graphql-ws`, `subscriptions-transport-ws` and also SSE based on Event-Stream).

**Comment by acao** [comment]
Done! No wss with netlify functions yet but it’s there in the test serveer and e2e!
