### ISSUE TITLE
Canary releases?

### ISSUE THREAD

**Issue by dotansimha** [graphql/graphiql#1972]
I think we can add a workflow for creating canary releases. This will allow getting faster feedback on fixes/changes we apply.  

2 options here:

1 - use NPM based on changeset - we can use a script like this (https://github.com/dotansimha/envelop/blob/main/scripts/canary-release.js) to create canary releases automatically to every authorized PR, and this will publish only packages that are changed. 

2 - Use GitHub Artifacts with tools like https://nightly.link/ to create a direct NPM link to the package (still experimenting with it). This advantage here is that we can do this for fork PRs because it's not bloating the NPM package/scope releases.

**Comment by acao** [comment]
ok, now I'm kinda stumped on whether `alpha` or `canary` are the appropriate tags here. this is one of those things where different terms mean different things to different people/teams/orgs, haha

**Comment by dotansimha** [comment]
> ok, now I'm kinda stumped on whether `alpha` or `canary` are the appropriate tags here. this is one of those things where different terms mean different things to different people/teams/orgs, haha

Totally! 
We are using alpha in all our libraries. For me it has the same meaning in this context...
