### ISSUE TITLE
Add warning/help message when using single quotes instead of double

### ISSUE THREAD

**Issue by schickling** [graphql/graphiql#198]
We (at [Graphcool](https://graph.cool)) have embedded GraphiQL as part of our visual backend administration console and for a lot of people that's the first exposure to GraphQL. As part of our onboarding experience they are asked to write the following query:

```graphql
{
  allPosts(filter: { description_contains: "some key" }) {
    description
    imageUrl
  }
}
```

A lot of people get stuck because they are trying to use single quotes instead of double quotes. (Probably as they are used to it from writing JS code.)

I think it would be very helpful to help them with a better warning message if they are trying to use single quotes instead of double quotes.

Any thoughts on this? 👍

**Comment by asiandrummer** [comment]
Hi @schickling - when I tried this out in our swapi example, I saw the below lint result:
![screen shot 2016-11-08 at 12 39 35 pm](https://cloud.githubusercontent.com/assets/1537569/20116288/8d8bc01a-a5b0-11e6-8df6-33707fe0d57b.png)
I agree that it's a bit vague, especially with not-as-long strings like quotations as error values. The lint result comes from `graphql-js/language/parser` module, so maybe we could improve the error messages over there. I'm not sure how GraphiQL could be improved to provide a better error message though - would you have some suggestions?

I do see an immediate action we can take when I executed that query above - the error message seems to be escaped, making it unreadable. We can fix that.

**Comment by schickling** [comment]
Cool! I think that already helps a lot! Thanks for your great feedback!

**Comment by schickling** [comment]
Great, thanks @leebyron!
