### ISSUE TITLE
persisting headers and variables

### ISSUE THREAD

**Issue by saihaj** [graphql/graphiql#1984]
Currently refreshing graphiql query is saved but variables and headers go away. It would be nice if we can save those too.

**Comment by acao** [comment]
huh, variables should persist. headers do not

**Comment by acao** [comment]
> When I have variables set they all go away.

This shouldn't be the case still, is it?

**Comment by acao** [comment]
the main reason we don't allow persisting headers by default is the main reason why our last XSS CVE was a level 7 and not 9 🤯

**Comment by arthurbolsoni** [comment]
apollo sandbox supports persistent caching in development without the need to change variables manually

**Comment by arthurbolsoni** [comment]
Apollo v4 using apollo sandbox has persistent headers in development by default

**Comment by markedwards** [comment]
The default behavior (at least on 3.0.0) seems broken:

1. Set `Persist headers` to `On` in the UI
2. Add headers
3. Reload, observe that headers are persisted
4. Reload again, observe that headers have now vanished

**Comment by acao** [comment]
@markedwards can you open a bug ticket?

**Comment by markedwards** [comment]
> @markedwards can you open a bug ticket?

#3369

**Comment by ramnivas** [comment]
> The default behavior (at least on 3.0.0) seems broken:
> 
> 1. Set `Persist headers` to `On` in the UI
> 2. Add headers
> 3. Reload, observe that headers are persisted
> 4. Reload again, observe that headers have now vanished

And I see that `Persist headers` in UI also goes back to `Off`. In other words, the `Persist headers` setting isn't persisted across refreshes. That also probably explains why headers are restored on the first reload but lost on the second.

**Comment by acao** [comment]
@ramnivas see the discussion here that led to a new ticket. Closing to avoid duplicate discussions
