### ISSUE TITLE
Update bundled graphql-ws version

### ISSUE THREAD

**Issue by josephlbarnett** [graphql/graphiql#2006]
We embed graphiql using the unpkg CDN bundle.

`graphiql-toolkit` currently depends on "graphql-ws": "^4.9.0", but latest graphql-ws is 5.5.5.  The addition of ping/pong messages in graphql-ws 5.x.x means that using 4.9.x with a server that implements ping/pong messages causes the client to close the socket with `4400: Invalid Message` upon receiving a ping or pong.

Would be great to have an unpkg CDN bundle that embeds graphql-ws 5.x.x in order to avoid having to build the ws fetcher ourselves.

**Comment by acao** [comment]
we were planning on upgrading after we took care of some important issues friday. PRs are welcome!

**Comment by acao** [comment]
@josephlbarnett merged, will release soon!
