### ISSUE TITLE
GraphQL config is not loaded from package.json

### ISSUE THREAD

**Issue by ionut-botizan** [graphql/graphiql#2020]
## Actual Behavior
GraphQL config is not loaded from `package.json`. This is actually an upstream issue caused by the `graphql-config` package (`vscode-graphql > graphql-language-service-server > graphql-config`) that overrides the default `cosmiconfig` search paths in order to add some extra paths, but failing to also add back `package.json`.
Issues have been opened in both upstream packages to track the progress and update the dependencies when the root issue is fixed:
`graphql-language-service-server`: https://github.com/graphql/graphiql/issues/1859
`graphql-config`: https://github.com/kamilkisiela/graphql-config/issues/692

## Expected Behavior
GraphQL config should be automatically detected and loaded from the `graphql` key in package.json

## Steps to Reproduce the Problem Or Description
Define a simple GraphQL configuration in `package.json` and see the language server logging a `ConfigNotFoundError` error.

## Specifications

  - GraphQL for VSCode Extension Version: 0.3.16
  - VSCode Version: 1.56.1
  - OS Name: 
  - OS Version: 

## Logs Of TS Server || GraphQL Language Service
```
14.05.2021, 00:27:57 [4] (pid: 7856) graphql-language-service-usage-logs: {"type":"usage","messageType":"initialize"}
14.05.2021, 00:27:57 [1] (pid: 7856) graphql-language-service-usage-logs: ConfigNotFoundError: GraphQL Config file is not available in the provided config directory: d:\Work\Gemini\api\_starter-project
Please check the config directory.
```

![image](https://user-images.githubusercontent.com/408501/118190186-6e3d7380-b44b-11eb-80a8-baf684900c09.png)

**Comment by acao** [comment]
I'm working on a PR for this now. It's hard to not be distracted by the many other bugs, but this one is as easy as upgrading graphql config for the server thankfully. More patches  and improvements coming soon! If anyone is interested in helping to maintain the language server, please reach out on discord or the "seeking co-maintainers" ticket!

**Comment by acao** [comment]
give this a try again if you can? I changed the `vscode-graphql` `activationEvents` to trigger the extension on `*` because there is no way to tell vscode to check package.json to activate.
