### ISSUE TITLE
Bug with canary releases

### ISSUE THREAD

**Issue by acao** [graphql/graphiql#2026]
So close to getting canary releases working!

It kept saying PRs with changesets didn't so I thought I would look.

It appears there are some strange webpack build failures, I will take a look. it may be that this workflow is using node 12? maybe we found a bug in the tsconfig or webpack config?

https://github.com/graphql/graphiql/runs/4203305131?check_suite_focus=true

**Comment by dotansimha** [comment]
Will check soon!

**Comment by acao** [comment]
I figured it out, just made sure the cypress test server was node 12 compatible, not sure why i thought nullish coalescing would be a good idea to use there haha
