### ISSUE TITLE
Schema documentation is requested but not shown even if received (v1.5.1)

### ISSUE THREAD

**Issue by learnerEvermore** [graphql/graphiql#2027]
I can see that the schema description is requested:

```GraphQL
query IntrospectionQuery {
  __schema {
    description
    ...
}
```
but it isn't displayed even if received. Just the default "A GraphQL schema provides a root type for each kind of operation." shows up.

**Comment by acao** [comment]
I have tests the confirm that it works now!

If `schema` prop was provided it was working, just had to specify `schemaDescription: true` in `getIntrospectionQuery()`, see #2077! if you want to try this before it's released, you can try the canary release mentioned in the PR comments :)

**Comment by acao** [comment]
released!

**Comment by sebastienbarre** [comment]
Unfortunately 1.5.9, 1.5.11, and 1.5.12 are broken at this point when using unpkg (1.5.10 does not exist). 
Only 1.5.8 is functioning.
So for people landing here, replace `https://unpkg.com/graphiql/graphiql.min.js` with `https://unpkg.com/graphiql@1.5.8/graphiql.min.js` until it is fixed.

**Comment by acao** [comment]
@sebastienbarre what version of graphql js are you using? Cypress tests are passing against graphql@16 and the latest graphql@15

**Comment by sebastienbarre** [comment]
I'm not entirely sure what you mean. 
I'm using `[webonyx/graphql-php: A PHP port of GraphQL reference implementation](https://github.com/webonyx/graphql-php)` under the hood, and the latest version is v14.11.3.

Did GraphiQL become tied to the JavaScript reference implementation for GraphQL specifically? 
I thought one could use it against any server implementation of the spec...

**Comment by acao** [comment]
@sebastienbarre graphiql has always used `graphql-js` as a peer dependency somewhere in your client implementation. if it's static html and cdn packages, then `graphql` and `react` and `react-dom` are imported somewhere as vendors, likely as script tags pointing to jsdelivr, unpkg, cdnjs, etc. this error only shows up if you are on an old version of graphql, I am able to reproduce it.

**Comment by acao** [comment]
I don't see anywhere in `graphql-php` where graphiql is served up as a client statically, so there is likely another composer package you are using that is doing this for you, and therein lies the dependency on an older version of `graphql`

**Comment by acao** [comment]
@saihaj or @IvanGoncharov what do I do about this? do i feature flag based on the version when introspection schemaDescription was introduced? Or set the peer dependency at the version when `graphql` introduced this, add a note to the docs, and move on?

**Comment by acao** [comment]
ohh right so this is a schema introspection issue. this means `graphql-php` doesn't support schema description in type introspection

**Comment by acao** [comment]
this is where `graphql-php` is missing the `description` field for `Schema`:

https://github.com/webonyx/graphql-php/blob/44ed079229b6e954ba4edd55e65d697a2df67211/src/Type/Introspection.php#L233

we use this at work, so maybe I'll add it :)

**Comment by acao** [comment]
@learnerEvermore this is now an opt-in feature via props, fyi! same with argument deprecations which is now supported by `DocExplorer` as well

**Comment by sebastienbarre** [comment]
Thanks @acao. I'm going to try to tag @spawnia here since they are very active on that graphqlphp repo and that feature might be in v15.

**Comment by spawnia** [comment]
Tracked in https://github.com/webonyx/graphql-php/issues/1027, I will happily accept PRs.

**Comment by learnerEvermore** [comment]
I confirmed that this works now, with the freshest version from `unpkg`.

**Comment by learnerEvermore** [comment]
Thank you1
