### ISSUE TITLE
GraphiQL schema prop type error

### ISSUE THREAD

**Issue by kikkupico** [graphql/graphiql#2028]
The `schema` prop of the GraphiQL component is documented to accept `GraphQLSchema | null | undefined` . But its type is defined as `GraphQLSchema | undefined`. This makes it impossible to provide `null` for the `schema` prop ( and thereby, prevent introspection) when using Typescript.

Doc - https://github.com/graphql/graphiql/blob/main/packages/graphiql/README.md

Type definition - https://github.com/graphql/graphiql/blob/25fb5c50f655b838873dcb348b3295e962a05f12/packages/graphiql/src/components/GraphiQL.tsx#L113

**Comment by acao** [comment]
Huh! Good to know for the typefix. But behaviorally - passing the schema prop doesn’t prevent introspection either? Or just an issue with null?

**Comment by kikkupico** [comment]
Behaviourally, when `null` is assigned to the `schema` prop, no introspection query is sent. That works as documented.

My only problem here is that I cannot assign `null` to the `schema` prop in Typescript because of the type mismatch.

**Comment by acao** [comment]
ah ok, that makes sense, that's an easy fix!
