### ISSUE TITLE
problem handling file path of graphql config file in Windows

### ISSUE THREAD

**Issue by adielBm** [graphql/graphiql#2066]
## Actual Behavior
**When doing the "Execute Query":**  Get an empty tab. (The right tab in the image)

**When saving graphql config file:** Problem handling file path.
> (node:2880) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/c%3A/Users/adiel/Desktop/raz-ecommerce/raz-ecommerce-front/.graphqlrc.yml'

![image](https://user-images.githubusercontent.com/62875424/143767273-fa902f37-0162-4ac4-b8e1-b4289ceae711.png)

## Expected Behavior
That everything will work properly. It will be possible to execute queries

## Specifications

  - GraphQL for VSCode Extension Version: v0.3.26
  - VSCode Version: 1.62.3
  - OS Name: Windows 10
  - OS Version: Windows_NT x64 10.0.19042
  - graphql config filename and format example: `.graphqlrc.yml`
```
schema: 'schema.graphql'
extensions:
  endpoints:
    default:
      url: http://localhost:1337/graphql
```

## Logs Of TS Server || GraphQL Language Service

**When saving graphql config file**
```
28.11.2021, 14:23:03 [3] (pid: 2880) graphql-language-service-usage-logs: updating graphql config
(node:2880) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/c%3A/Users/adiel/Desktop/raz-ecommerce/raz-ecommerce-front/.graphqlrc.yml'
    at Object.openSync (fs.js:476:3)
    at Object.func [as openSync] (electron/js2c/asar_bundle.js:5:1846)
    at Object.readFileSync (fs.js:377:35)
    at Object.e.readFileSync (electron/js2c/asar_bundle.js:5:8872)
    at c:\Users\adiel\.vscode\extensions\graphql.vscode-graphql-0.3.26\out\server\server.js:107571:31
    at Array.map (<anonymous>)
    at MessageProcessor.handleWatchedFilesChangedNotification (c:\Users\adiel\.vscode\extensions\graphql.vscode-graphql-0.3.26\out\server\server.js:107553:43)
    at c:\Users\adiel\.vscode\extensions\graphql.vscode-graphql-0.3.26\out\server\server.js:115845:126
    at handleNotification (c:\Users\adiel\.vscode\extensions\graphql.vscode-graphql-0.3.26\out\server\server.js:112043:17)
    at processMessageQueue (c:\Users\adiel\.vscode\extensions\graphql.vscode-graphql-0.3.26\out\server\server.js:111817:13)
(node:2880) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 30)
```
**When doing the "Execute Query":**
```
NetworkHelper: operation: query
NetworkHelper: endpoint: http://localhost:1337/graphql
```

**Comment by adielBm** [comment]
Sorry, but it's not related to the version of graphql-config, 
My version is updated: graphql-config **4.1.0**.

This is the path of the project folder:
`C:\Users\adiel\Desktop\raz-ecommerce\raz-ecommerce-front`

And it looks like he's looking for this config file: _(And because of this it does not find the config file)_
`/c%3A/Users/adiel/Desktop/raz-ecommerce/raz-ecommerce-front/.graphqlrc.yml`

thanks @acao

**Comment by acao** [comment]
Ohh i see, you see this when saving the config files that makes sense. I’ll look into it some more. The major bugfix recently involved reverting some changes to how we parse file uris into system paths and as i guess the revert is url encoding them again! I have a windows machine i can try this out on tomorrow morning. Thanks for reporting this!

**Comment by acao** [comment]
I think vscode-uri would be the appropriate uri parser to switch to

**Comment by acao** [comment]
here’s a stackoverflow example. To look for the offending lines, you can just look for `new Uri(uri).basename`, in cases where a vscode file URI needs to be converted to a system path that can be used by something like `fs.readFile` etc

https://stackoverflow.com/a/55660674

**Comment by acao** [comment]
I think this fix to the server will take care of this for good
