### ISSUE TITLE
Small bug when autocompleting variables

### ISSUE THREAD

**Issue by bartenra** [graphql/graphiql#2068]
## Steps to Reproduce the Problem Or Description

Type
```
query ($test: String!) {
  hello (test: $[CURSOR HERE])
}
```

Press tab to autocomplete, select `$test`.

## Expected Behavior

```
query ($test: String!) {
  hello (test: $test)
}
```

## Actual Behavior

```
query ($test: String!) {
  hello (test: $$test)
}
```

## Specifications

  - GraphQL for VSCode Extension Version: v0.3.16
  - VSCode Version: 1.56.2
  - OS Name: Arch Linux
  - OS Version: 2021.05.01

**Comment by bartenra** [comment]
Awesome! :tada:

**Comment by acao** [comment]
https://github.com/graphql/graphiql/blob/503c37613d645e25bdf66d1f609511583f20b55a/packages/graphql-language-service-interface/src/getAutocompleteSuggestions.ts#L604 and https://github.com/graphql/graphiql/blob/503c37613d645e25bdf66d1f609511583f20b55a/packages/graphql-language-service-interface/src/getAutocompleteSuggestions.ts#L609 are the offending lines

as a note for a PR, the `insertText` does not need to be passed at all if no transformation happens, just `label` is sufficient

**Comment by acao** [comment]
does it seem to fix the issue in this monaco example?
https://61a621696bff9e00a952ce2b--monaco-graphql.netlify.app/

quick way to demonstrate the universal LS features until we have a code-server deploy preview!
