### ISSUE TITLE
Welcome message and hints for new starters to dive in querying

### ISSUE THREAD

**Issue by intellix** [graphql/graphiql#208]
When using Graphiql for the first time and when presenting it to frontend members of the team who have never used GraphQL, it's not clear how to make queries and that you can press Cmd + Space to get autocomplete suggestions.

To first get something you need to create a query wrapper, which isn't clear without reading documentation:
```
query Something { 

}
```
or
```
{ 

}
```

It would be nice if you could dive in without having to read any documentation.

I quite like the welcome screen of Atom and VS Code, where you get a list of suggested keys to start doing things: 
![screenshot 2016-11-12 10 46 49](https://cloud.githubusercontent.com/assets/1162531/20236965/ef0f4060-a8c5-11e6-87f4-3527a23229cc.png)

Perhaps we could display a similar message when the query browser is empty to improve the first time experience.
Thoughts?

**Comment by asiandrummer** [comment]
Hi @intellix - it seems like you're requesting for two things:
1) A quick tutorial for newcomers trying out GraphQL for the first time, and
2) A welcome screen with a list of shortcuts explained, as well as the features that aren't obvious.

For 1), we have [this graphql.org website](http://graphql.org/learn/) for this exact purpose. As you navigate through that website, there are built-in GraphiQL instances and you can try out the example queries in context with how the tutorial progresses. Would that be closer to what you want?

For 2), you're absolutely right - we have some more shortcuts for showing typeahead and running queries (Cmd + Enter), and it'd be more helpful if we had some kind of ways to elaborate them. A welcome screen/tooltip that is shown on the startup would be great.

**Comment by leebyron** [comment]
This sort of already exists:

<img width="789" alt="screenshot 2017-01-19 17 31 57" src="https://cloud.githubusercontent.com/assets/50130/22132158/3863f85a-de6d-11e6-9d5a-b16c24b545f0.png">

It's also configurable so internal installations of GraphiQL can add more specific information.

I can add more info about what a query looks like to this, I like that suggestion. What else should be added?

**Comment by intellix** [comment]
LGTM! Previously the auto-complete settings were hidden in a paragraph of text. Now I like that it's split. Think the change is really good :)

**Comment by leebyron** [comment]
Awesome! We'll I'll close this task but feel free to open new ones with future suggestions.
