### ISSUE TITLE
graphql-language-service ^4.0.0 has invalid dependencies for browser

### ISSUE THREAD

**Issue by PabloSzx** [graphql/graphiql#2094]
@acao 

I created a small reproduction repo showing the issue: https://github.com/PabloSzx/graphiql-browser-bundle.

Basically:

Doing a browser bundle using esbuild:

`esbuild --bundle --platform=browser --outdir=dist index.ts`

An error is shown:

```
✘ [ERROR] Could not resolve "punycode"

    node_modules/.pnpm/markdown-it@12.2.0/node_modules/markdown-it/lib/index.js:14:27:
      14 │ var punycode     = require('punycode');
         ╵                            ~~~~~~~~~~

  The package "punycode" wasn't found on the file system but is built into node. Are you trying to
  bundle for node? You can use "--platform=node" to do that, which will remove this error.

✘ [ERROR] Could not resolve "path"

    node_modules/.pnpm/picomatch@2.3.0/node_modules/picomatch/lib/picomatch.js:3:21:
      3 │ const path = require('path');
        ╵                      ~~~~~~

  The package "path" wasn't found on the file system but is built into node. Are you trying to
  bundle for node? You can use "--platform=node" to do that, which will remove this error.

✘ [ERROR] Could not resolve "path"

    node_modules/.pnpm/picomatch@2.3.0/node_modules/picomatch/lib/constants.js:3:21:
      3 │ const path = require('path');
        ╵                      ~~~~~~

  The package "path" wasn't found on the file system but is built into node. Are you trying to
  bundle for node? You can use "--platform=node" to do that, which will remove this error.

✘ [ERROR] Could not resolve "path"

    node_modules/.pnpm/picomatch@2.3.0/node_modules/picomatch/lib/utils.js:3:21:
      3 │ const path = require('path');
        ╵                      ~~~~~~

  The package "path" wasn't found on the file system but is built into node. Are you trying to
  bundle for node? You can use "--platform=node" to do that, which will remove this error.

4 errors
 ELIFECYCLE  Command failed with exit code 1.

```

**Comment by PabloSzx** [comment]
After overriding the graphql-language-service to 3.2.5, most of the errors are gone:

```json
{
"pnpm": {
    "overrides": {
      "graphql-language-service": "3.2.5"
    }
  }
}
```

```
> esbuild --bundle --platform=browser --outdir=dist index.ts

✘ [ERROR] Could not resolve "punycode"

    node_modules/.pnpm/markdown-it@12.2.0/node_modules/markdown-it/lib/index.js:14:27:
      14 │ var punycode     = require('punycode');
         ╵                            ~~~~~~~~~~

  The package "punycode" wasn't found on the file system but is built into node. Are you trying to
  bundle for node? You can use "--platform=node" to do that, which will remove this error.

1 error
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by PabloSzx** [comment]
I think a new integration test has to be made which uses esbuild to bundle graphiql with --platform=browser, that will catch all these kind of errors

**Comment by acao** [comment]
Oh ok! Well I haven’t tried it with esbuild directly yet. It seems to be working with vite and webpack. Sounds like we need an esbuild example!

i was hoping to use esbuild to bundle dependencies for an offline-ready static browser bundle to use for middlewares or static apps

**Comment by acao** [comment]
This is the fix for now, I will add an esbuild section to the docs for `monaco-graphql` with this
```ts
{
  "browser": {
    "path": "path-browserify"
  }
}
```
https://esbuild.github.io/getting-started/#bundling-for-the-browser

**Comment by PabloSzx** [comment]
> This is the fix for now, I will add an esbuild section to the docs for `monaco-graphql` with this
> 
> ```ts
> {
>   "browser": {
>     "path": "path-browserify"
>   }
> }
> ```
> 
> https://esbuild.github.io/getting-started/#bundling-for-the-browser

how is that supposed to work for programmatic usage of esbuild?

**Comment by PabloSzx** [comment]
>  It seems to be working with vite and webpack for the multi-schema fileMatch support. I’ll see what i can find.

Wait a moment, the examples are still using webpack 4? it stopped being maintained since 2 years ago, I think renovate has to be configured in the project

And another thing, relying on workarounds or user-specified configuration for stuff to work is clearly not the way to go, graphiql by itself should only use browser-compatible dependencies out-of-the-box

**Comment by acao** [comment]
I’m going to bed soon. They will be improved some day when there is time. You are free to introduce any improvements you see fit. Goodnight!

**Comment by acao** [comment]
When i took over these projects, graphiql was still using browserify, lol. I’m doing this for free. Please be patient. 

I think I have a way to move the `picomatch` dependency to `monaco-graphql`, if this is a `graphiql` issue. Otherwise, I don’t have an easy solution for you.

**Comment by PabloSzx** [comment]
> When i took over these projects, graphiql was still using browserify, lol. I’m doing this for free. Please be patient.
> 
> I think I have a way to move the `picomatch` dependency to `monaco-graphql`, if this is a `graphiql` issue. Otherwise, I don’t have an easy solution for you.

Sorry if I sounded demanding, I understand that this is a project that comes from a long time without having maintenance, and thanks for taking care of it, like @saihaj has mentioned before, with proper testing this kind of issues wouldn't happen in the first place, if I had time to help on actually coding for this project I would

**Comment by acao** [comment]
This does have proper testing though. We test agains 3 node versions and against two graphql js versions.

We have had users test the canary with webpack 5, CRA, vite, and parcel and it works with default configs, no workarounds. had to deploy one fix for vite and it works great

**Comment by acao** [comment]
Esbuild will probably not be readily compatible with monaco editor for graphiql 2, so you’ll probably need to change bundlers once 2 lands anyways

**Comment by PabloSzx** [comment]
With the new update, when actually using graphiql the bundle is fixed 🎉 thank you @acao 

The reproduction I have here still has an issue, which is this:

```
> esbuild --bundle --platform=browser --outdir=dist index.ts

✘ [ERROR] Could not resolve "punycode"

    node_modules/.pnpm/markdown-it@12.2.0/node_modules/markdown-it/lib/index.js:14:27:
      14 │ var punycode     = require('punycode');
         ╵                            ~~~~~~~~~~

  The package "punycode" wasn't found on the file system but is built into node. Are you trying to
  bundle for node? You can use "--platform=node" to do that, which will remove this error.

1 error
 ELIFECYCLE  Command failed with exit code 1.
```

But this happens only because the file to be bundled is specifically doing:

```ts
export * from "graphiql";
```

which catches everything on purpose, without tree-shaking

**Comment by acao** [comment]
Huh strange. Markdown-it is definitely a browser friendly dependency. Did you close because you were able to resolve the issue?

**Comment by PabloSzx** [comment]
> Huh strange. `markdown-it` is definitely a browser friendly dependency. Did you close because you were able to resolve the issue?

Yeah, when actually using graphiql the issue doesn't appear, that's why I closed it
