### ISSUE TITLE
Test against a wider graphql-js matrix

### ISSUE THREAD

**Issue by acao** [graphql/graphiql#2099]
We recently [introduced a test suite](https://github.com/graphql/graphiql/blob/main/.github/workflows/pr-graphql-15-check.yml) to guarantee graphiql monorepo build, test and cypress suite runs when graphql is set to 15
I wrote a utility that automatically fixes a package resolution, so we can test this against a wider set of of constraints

Currently, we are testing against tag `15` (whatever that resolves to) and defaulting to the current installed tag of `graphql@16.0.0-experimental-defer-stream-5` or whichever the tag is exactly.

We should make sure the repo uses graphql@16.1.0 by default, and is fully feature-flagged to build without the defer stream tags
The matrix should look like this:

- Latest 16 version (fixed, default)
- 16 w/ defer stream tags (fixed)
- Latest 15 version (fixed)
- oldest 15 version we claim to support in peer dependencies (fixed)

then, I will configure renovatebot to open PRs daily whenever `graphql` has a release, though testing against every `graphql` canary release would be interesting as well

**Comment by acao** [comment]
tagging @dotansimha @saihaj @Urigo anyone who might be interested

**Comment by saihaj** [comment]
yes we should do all the tagged latest version and I think we can even take it next level and also check against `main`
