### ISSUE TITLE
Doesn't work if config file isn't present in the first folder of workspace

### ISSUE THREAD

**Issue by karimdaghari** [graphql/graphiql#2113]
## Actual Behavior

Can't detect config file if not present in the first folder of a workspace.

## Expected Behavior

Be able to detect the config file (in the root folder) in a workspace, regardless of the order of its folders.

## Steps to Reproduce the Problem Or Description
1. Create workspace with two folders
2. Place a config file at the second folder

## Specifications

  - GraphQL for VSCode Extension Version: 0.3.13
  - VSCode Version: 1.51.1
  - OS Name: Windows / WSL
  - OS Version: 10 Pro / Ubuntu 20.04

## Logs Of TS Server || GraphQL Language Service

>  ConfigNotFoundError: GraphQL Config file is not available in the provided config directory: /home/x/y/{first folder name}
Please check the config directory.

## Workaround

Reorder the folders inside the workspace.

**Comment by maxguzenski** [comment]
This fix it
```
[workspace]
"graphql-config.load.rootDir": "../correct-folder/"

[graphqlrc]
schema: './schema.graphql'
documents: ['./src/api/**/*.{grahpql,js,jsx}']
```

**Comment by acao** [comment]
Thanks @maxguzenski , this is a good workaround

**Comment by acao** [comment]
Closing for #2379 , the more optimal solution
