### ISSUE TITLE
simplify worker loading in docs & examples

### ISSUE THREAD

**Issue by acao** [graphql/graphiql#2126]
For `monaco-graphql` examples, the webworker setup should be very simple, almost a non-issue

The vite example with the monaco-editor-vite-plugin shows us how lean it can be. So as should follow with the webpack examples. Finally the readme should be updated, but really we just need a documentation site haha!

Also document how to load the worker transparently using amd modules over cdn

**Comment by Bassel-Mouhammad** [comment]
[launches.csv](https://github.com/graphql/graphiql/files/9879909/launches.csv)
