### ISSUE TITLE
`monaco-graphql` example using `next.js`

### ISSUE THREAD

**Issue by acao** [graphql/graphiql#2128]
Because `monaco-graphql` doesn't do anything to prevent SSR issues on it's own, nor does `monaco-editor`, we need to show folks how to use `monaco-editor` in an SSR setup to prevent a lot of confusion for users.

It was the same issue with `codemirror-graphql` as well, so that's why `graphiql` waits til `didMount` to dynamically require the codemirror modes. In `graphiql@2` we hope to migrate to the more modern pattern of dynamic import. We hope to be able to use this for importing `monaco-editor` and `monaco-graphql` in a fashion that bundlers will pick up naturally, however it may require babel plugins/etc for this to work properly.

this is an excellent guide showing how to use `next/dynamic` with `ssr: false` to lazily import `monaco-editor` in a way that supports next.js SSR:

https://dev.to/swyx/how-to-add-monaco-editor-to-a-next-js-app-ha3

**Comment by amlcodes** [comment]
I have not found any example using `import { initializeMode } from 'monaco-graphql/esm/initializeMode'` with nextjs. I've been completely unsuccessful. Running after mount and everything else consistently returns navigator is not defined.

**Comment by acao** [comment]
here's a starting point!

https://github.com/acao/monaco-next-example

as with any `monaco-editor` implementation with an SSR context, you need to use `@next/dynamic`, as `monaco-editor` will immediately start looking for `window.navigator` on import.

I will incorporate this to the `examples` directory soon
