### ISSUE TITLE
CDN version treating response as an error

### ISSUE THREAD

**Issue by KTibow** [graphql/graphiql#2133]
I have a simple GraphQL config set up, and I used the CDN config. Here's the page I set up:
```html
<html>
    <head>
        <title>Simple GraphiQL Example</title>
        <link
            href="https://unpkg.com/graphiql/graphiql.min.css"
            rel="stylesheet" />
    </head>
    <body style="margin: 0">
        <div id="graphiql" style="height: 100vh"></div>

        <script
            crossorigin
            src="https://unpkg.com/react/umd/react.production.min.js"></script>
        <script
            crossorigin
            src="https://unpkg.com/react-dom/umd/react-dom.production.min.js"></script>
        <script
            crossorigin
            src="https://unpkg.com/graphiql/graphiql.min.js"></script>

        <script>
            const fetcher = GraphiQL.createFetcher({ url: "/" });

            ReactDOM.render(
                React.createElement(GraphiQL, { fetcher: fetcher }),
                document.getElementById("graphiql")
            );
        </script>
    </body>
</html>
```
However, it treats the response to the schema request as an error:
![image](https://user-images.githubusercontent.com/10727862/147842274-e7be379d-fa3f-43c2-ba50-1f56c833a7b5.png)
Why is this happening? How can I fix it? (FYI the link is https://graphql.ktibow.repl.co/graphiql)

**Comment by acao** [comment]
It looks like there’s an error with the introspection schema response. What do you see in the browser network tab?

**Comment by KTibow** [comment]
It's probably because I wrote a custom response, instead of using a dedicated library (sanic-graphql was out of date). 
Here's the headers screenshot:
![image](https://user-images.githubusercontent.com/10727862/147852219-610ac6a8-9c5f-407b-9686-2d07159d0954.png)
Here's the request screenshot:
![image](https://user-images.githubusercontent.com/10727862/147852223-35bc3714-aca1-4fb8-ace5-3780d73d419c.png)
Here's the response screenshot:
![image](https://user-images.githubusercontent.com/10727862/147852230-a3365572-104d-4868-89c0-5127f2791266.png)

**Comment by KTibow** [comment]
I had to change my server to put the response under `"data"`.

**Comment by acao** [comment]
Ohh that makes sense!

Yes, our client follows the http transport spec
