### ISSUE TITLE
Error highlighting for queries & mutations doesn't clear in gql literals in .js files in MERNG app

### ISSUE THREAD

**Issue by LauraCole1900** [graphql/graphiql#2136]
## Actual Behavior

When editing fields in queries & mutations in gql literals in front-end .js files, the error highlighting doesn't clear after matching queryable fields in both front-end and back-end files

## Expected Behavior

Once fields match up and down the chain, error highlighting clears

## Steps to Reproduce the Problem Or Description

1. Add fields to an existing MongoDB model
2. Add those fields to relevant front-end queries and/or mutations
3. Add those fields to relevant typeDefs, including back-end queries and/or mutations

## Specifications

  - GraphQL for VSCode Extension Version: 0.3.41
  - VSCode Version: 1.63.2
  - OS Name: Windows
  - OS Version: 10
  - graphql config filename and format example: graphql.config.json

  ```
{
  "schema": "http://localhost:3001/graphql",
  "extension": {
    "endpoints": {
      "default": "http://localhost:3001/graphql"
    }
  }
}
```

## Logs Of TS Server || GraphQL Language Service

No errors thrown if query or mutation is correct, but error highlighting stays put

**Comment by LauraCole1900** [comment]
Thanks for responding! I'm having trouble getting the syntax right for that. No matter what filepath I put in, whether server-side, client-side or an array of both, I keep getting this error on running the query:

```
Error: graphql operation failed Error: Unable to find any GraphQL type definitions for the following pointers: - ./server/schema/*.js
```

I don't have enough experience to have many tools to figure this out, so any pointers are appreciated!

**Comment by acao** [comment]
Can you try this:

```
documents: ./server/schema/**/*.js
```

and I’m assuming the graphql strings in the files are delimited with gql`` tags or similar?

**Comment by LauraCole1900** [comment]
Thank you for the help! Yes, the gql strings are delineated with gql`` tags. For example:
```
export const QUERY_ALL_ADMINS = gql`
query admins {
  admins {
    _id
    fullName
    preferredName
    email1
    phone1
    section
    position
    isAdmin
  }
}
`;
```

I just ran that query in the app itself and it runs there, but even with your suggested syntax for the "documents" key, the extension returned this:
```
Error: graphql operation failed Error: Unable to find any GraphQL type definitions for the following pointers: - ./server/schema/**/*.js".
```

This isn't the first time I've struggled to understand something from documentation that others seem to get pretty easily, so I don't think the problem is the documentation, I think I just need to keep coding.

Also, I am using apollo/client v3.5.7 on the front-end, apollo-server-core v3.6.1 & apollo-server-express v 3.6.1 & graphql v16.2.0 on the back-end, and graphql-config v4.1.0 at the root, if that makes a difference, with apologies for not mentioning that earlier

**Comment by acao** [comment]
Is the file extension in use correct? Or are you using jsx? Tsx?

**Comment by LauraCole1900** [comment]
Yes, the relevant files are all .js files. This project isn't using TS at all, and all JSX is in .js files

**Comment by acao** [comment]
@LauraCole1900 just pushed a fix for this. please open a new bug if there are issues!
