### ISSUE TITLE
Line breaks not showing for Doc Explorer Schema Descriptions

### ISSUE THREAD

**Issue by danielleletartesonos** [graphql/graphiql#2137]
When the description of a schema item includes `\n` a line break is not rendered. It seems as though the break option is not set when `markdown-it` is used to render the data.

<img width="880" alt="Screen Shot 2022-01-10 at 12 22 29 PM" src="https://user-images.githubusercontent.com/82901505/148826416-7f8d6a09-edbe-4f07-99e5-6de4b864ea14.png">
<img width="345" alt="Screen Shot 2022-01-10 at 12 26 11 PM" src="https://user-images.githubusercontent.com/82901505/148826712-60918dee-87ef-40b2-80b8-d9fd25544efc.png">

https://github.com/graphql/graphiql/blob/main/packages/graphiql/src/components/DocExplorer/MarkdownContent.tsx#L12

**Comment by acao** [comment]
Thanks for reporting this! This may be a breaking change from the markdown-it upgrade.

**Comment by danielleletartesonos** [comment]
@acao Of course! I can investigate some more.

**Comment by danielleletarte** [comment]
@acao I added a PR for this issue. Please let me know if you have any suggestions. Thank you!
