### ISSUE TITLE
Missing export or incomplete typing in @graphiql/toolkit

### ISSUE THREAD

**Issue by gael-ian** [graphql/graphiql#2140]
Hi,

I tried to follow instruction in the GraphiQL README to integrate GraphiQL in a webpack setup (in a Rails app, but I don't think it really matter).

````js
import { createGraphiQLFetcher } from '@graphiql/toolkit';
````

This makes webpack fail with an error: "export 'createClient' was not found in 'graphql-ws'". However, code seems to work so I suppose it's more an incomplete TypeScript typing than a really missing export.

Aside: [Instructions here](https://github.com/graphql/graphiql/tree/main/packages/graphiql#usage-npm-module) mention [`@graphiql/create-fetcher`](https://www.npmjs.com/package/@graphiql/create-fetcher) (not updated for more than one year) but code sample suggests the more recent [`@graphiql/toolkit`](https://www.npmjs.com/package/@graphiql/toolkit).

**Comment by acao** [comment]
thanks for reporting this inconsistency! tagging this for the docs effort

**Comment by acao** [comment]
@gael-ian this issue should be fixed now!
