### ISSUE TITLE
Unable to find any GraphQL type definitions for the following pointers: ./app/**/*.{ts,tsx}

### ISSUE THREAD

**Issue by Albert-Gao** [graphql/graphiql#2143]
1. I use Relay, so there is no `.graphql` file in code, everything is in code
![image](https://user-images.githubusercontent.com/18282328/94207882-ad4ea100-ff1c-11ea-9a46-2fe949954730.png)
1. With a config like this,
```javascript
module.exports = {
  projects: {
    default: {
      schema: ['./schema.graphql'],
      documents: ['./app/**/*.{ts,tsx}'],
      endpoints: {
        default: {
          url: 'http://localhost:4000/graphql',
          headers: { Authorization: jwt },
        },
      },
    },
  },
}
```
3. It outputs error from GraphQL language server

![image](https://user-images.githubusercontent.com/18282328/94208010-f999e100-ff1c-11ea-8da9-5564e7b090ae.png)

## Specifications
GraphQL for VSCode Extension Version: latest from store
Version: 1.49.1
Commit: 58bb7b2331731bf72587010e943852e13e6fd3cf
Date: 2020-09-16T23:21:17.533Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

**Comment by acao** [comment]
we isolated this issue and fixed it. it still seems to work sometimes if you open and close the files manually, or if changes occur to the files otherwise, but this ensures that when the project loads, all files in `documents` are loaded into the cache

**Comment by alexeychikk** [comment]
@acao I still experience the error:
```
[Info  - 14:58:59] {"type":"usage","messageType":"initialize"}
[Error - 14:59:20] invalid/unknown file in graphql config documents entry:
 'graph/schemas/types/**/*.graphqls'
[Error - 14:59:20] Error: 
      Unable to find any GraphQL type definitions for the following pointers:
        
          - graph/schemas/types/**/*.graphqls
          
[Info  - 14:59:20] GraphQL Language Server caches initialized
```

My config:
```yaml
schema: "graph/schemas/queries/schema.graphqls"
documents: "graph/schemas/types/**/*.graphqls"
```

Autocomplete, go to definition do not work, only syntax highlighting

**Comment by acao** [comment]
@alexeychikk did you try making the paths relative? not sure what else I can do as that error doesn't come from us

**Comment by acao** [comment]
also graphqls usually refers to schema files, documents path will ignore schema definitions (see: graphql config)

**Comment by alexeychikk** [comment]
@acao Relative paths didn't help. Idk the project I work on has `.graphqls` extension for all the files.
What actually helped is leaving just this in the config:
```yaml
schema: './graph/**/*.graphqls'
```

**Comment by acao** [comment]
ah, I think I know what the bug is then
