### ISSUE TITLE
Work with JS GraphQL IntelliJ plugin author to standardize config file support 

### ISSUE THREAD

**Issue by UselessPickles** [graphql/graphiql#2158]
I work with a team of developers who have mixture of using IntelliJ and VSCode IDEs, so we try to always setup our projects and processes to work equally well in both IDEs. This is proving to be a challenge when configuring GraphQL plugins, because the plugins available for both IDEs have some incompatibilities in how they find config files.

I am proposing that the authors of both projects should work together to agree on some level of commonality/standardization so that a project can be setup to use both plugins without duplicating configuration files.

"GraphQL" plugin for VSCode: https://github.com/graphql/vscode-graphql
"JS GraphQL" plugin for IntelliJ: https://github.com/jimkyndemeyer/js-graphql-intellij-plugin

## Actual Behavior
The "JS GraphQL" plugin for IntelliJ and the "GraphQL" plugin for VSCode cannot read the same config file. Some key differences are:

1. "JS GraphQL" plugin for IntelliJ requires a config file named ".graphqlconfig", but the "GraphQL" plugin for VSCode does not support a config file with that name. For a bare minimum of consistency, at least one of the plugins would need to be enhanced to create at least some overlap in supported file names/formats.
2.  "JS GraphQL" plugin for IntelliJ conveniently [supports multiple config files for nested "sub-projects"](https://jimkyndemeyer.github.io/js-graphql-intellij-plugin/docs/developer-guide#setting-up-multi-schema-projects-using-graphql-config). The plugin finds all config files all throughout the project directory structure, and automatically assumes that each config file applies to the directory it was found in (and its sub-directories). "GraphQL" plugin for VSCode only supports a single config file, so you are forced to create a single config file that defines the multiple nested "projects". It would be nice if the "GraphQL" plugin for VSCode could be enhanced to find/process all config files throughout the directory structure like "JS GraphQL" plugin for IntelliJ does.

## Expected Behavior
The "JS GraphQL" plugin for IntelliJ and the "GraphQL" plugin for VSCode should be able to read the same config file, from the same place within the project.

## Related Issues

- [Corresponding issue for "JS GraphQL" IntelliJ plugin project](https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/issues/428)

**Comment by acao** [comment]
Unfortunately I don't have much say in this! This is the library that parses our config files and acts as the reference implementation for `graphql-config`:

https://github.com/kamilkisiela/graphql-config

So as you can tell, our language server does concern itself with the parsing of graphql configuration files thanks to this library. It does listen for changes to the file and reloads the language service. @dotansimha is there a `legacy` mode we should be using to support these cases?

It looks like the IntelliJ plugin is a few spec versions out of date, adhering to the graphql-config 1.0 spec, thus the bug with legacy `.graphqlconfig` files which aren't supported it would seem?

Nested subprojects are also no longer supported in the graphql-config 3.0 spec, so please take it up with the spec authors!

I'm all for tooling interoperability, but until we can formalize ad-hoc specs like these, the graphql foundation treats the original reference implementation as the source of truth. The 2.0 format was proposed for the graphql spec, but rejected as too unrelated to language specification. 

Here in the graphiql monorepo where the language server lives, there is another issue proposing a tooling interoperability spec that I can dig up once I have time later. Any contributors are welcome to open PRs to `graphql-config or `graphql-language-service-server` as need!  Unless the IntelliJ plugin updates it's graphql-config implementation, it may be a while until we find a way to resolve this issue

**Comment by acao** [comment]
here is the fix!


https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/issues/296#issuecomment-1030844370

**Comment by ristomatti** [comment]
@acao It worked just by adding the line, awesome! You likely saved me hours of fiddling, thank you. :bow:

**Comment by acao** [comment]
Glad it helped! I work at a company now who uses jetbrains products by a strong majority, so I can understand the need for this. I may end up even helping with the intellij plugin perhaps!
