### ISSUE TITLE
Feature: Reload on save with legacy config filenames

### ISSUE THREAD

**Issue by johhansantana** [graphql/graphiql#2160]
As requested here:
https://github.com/graphql/vscode-graphql/issues/104#issuecomment-769248705

## Actual Behavior
Doesn't update generated schema on changes.

## Expected Behavior
Update generated schema on changes or have a manual option to tell it to update the generated file.

## Steps to Reproduce the Problem Or Description

When using a separate local server, I add a `.graphqlconfig` file to the root of my project with this:

```
{
  "name": "GraphQL Schema",
  "schemaPath": "schema.graphql",
  "extensions": {
    "endpoints": {
      "Default GraphQL Endpoint": {
        "url": "http://localhost:4000/graphql",
        "headers": {
          "user-agent": "JS GraphQL"
        },
        "introspect": true
      }
    }
  }
}
```

The autogenerated file gets fetched once but when I do changes I have no way on telling it to refetch it and it doesn't update on its own even after restarting vscode.

## Specifications

  - GraphQL for VSCode Extension Version: 0.3.13
  - VSCode Version: 1.52.1
  - OS Name: MacOS
  - OS Version: Big Sur 11.1

**Comment by acao** [comment]
Ok I understand much better after re-reading! This is something I was wondering about as well.  The schema is not refetching? It used to, but I think I know what has changed since

**Comment by moshest** [comment]
A quick workaround is to assign `Ctrl+S` for it:

<img width="1257" alt="image" src="https://user-images.githubusercontent.com/534911/167292875-55be5c7c-e957-4259-85ab-6c5aed5d61ec.png">

**Comment by valerii15298** [comment]
@moshest can you please point out where should I put `${fileExtname} == '.gql' || ${fileExtname} == '.graphql'` in order for vs code to execute `@command:vscode-graphql.restart` on save or when `.gql` files change?

**Comment by moshest** [comment]
@valerii15298 you should put in under the `when` column.
