### ISSUE TITLE
Monaco Grahphql error caused by loss of this

### ISSUE THREAD

**Issue by waterfoul** [graphql/graphiql#2170]
When calling the schema loader the "this" handle gets lost resulting in `TypeError: Cannot read properties of undefined (reading '_parser')` To fix it you need to bind method on [LanguageService.ts:93](https://github.com/graphql/graphiql/blob/main/packages/monaco-graphql/src/LanguageService.ts#L93)

**Comment by acao** [comment]
Huh! i've never seen this bug. Can you create a codesandbox or stackblitz to re-create it?

**Comment by acao** [comment]
Do you see the bug here with the latest version?

https://monaco-graphql.netlify.app/
