### ISSUE TITLE
Bundling: migrate to webpack 5 or vite or???

### ISSUE THREAD

**Issue by acao** [graphql/graphiql#2184]
The ecosystem has changed SO much in the last few years. iirc believe we introduced webpack 4 in 2019. we created a ticket #2100 to capture this effort, but I will consolidate it here so we can have a discussion!

We need an improved bundling strategy for every package that's consumed by web & electron-related projects. Bundling for vscode-graphql also helps a lot.  Using up to date bundlers that our users use is important, because it forces us to ensure these projects can be used by modern bundlers. Using webpack 4 still isn't helping anyone!

I think swc would be a good  choice because it seems to be more flexible with browser targeting

1. swc-loader + webpack 5
2. vite-plugin-swc + vite

**Comment by acao** [comment]
Finding a replacement for typescript project references will not be easy, so ideally we find something that still works with that and has a nice global build watcher

**Comment by dimaMachina** [comment]
closed by https://github.com/graphql/graphiql/pull/3679
