### ISSUE TITLE
Can hang GraphiQL with carefully crafted variables

### ISSUE THREAD

**Issue by steveluscher** [graphql/graphiql#22]
Typing this query and these variables into the SWAPI GraphiQL hung the browser tab for me. Couldn't get it back unless I cleared local storage.

<img width="639" alt="screen shot 2015-08-29 at 1 48 20 pm" src="https://cloud.githubusercontent.com/assets/13243/9564235/020508a2-4e55-11e5-9884-d06663f851d4.png">

**Comment by wincent** [comment]
Are you running with this fix, @steveluscher? https://github.com/graphql/graphiql/commit/9686b1ff1cac1021a693f9b29a904fa44ab8b7bc

**Comment by steveluscher** [comment]
I doubt that I am! Fixed by #13.
