### ISSUE TITLE
Getting Peer Dependency Error

### ISSUE THREAD

**Issue by AlokJoshi** [graphql/graphiql#221]
Hi Friends
I am getting the following error. Can you please help?

C:\WS\graphql-blog-schema>npm install
(node:7052) fs: re-evaluating native module sources is not supported. If you are
using the graceful-fs module, please update it to a more recent version.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher
to avoid a RegExp DoS issue
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Users\Alok\AppData\R
oaming\npm\node_modules\npm\bin\npm-cli.js" "install"
npm ERR! node v6.9.1
npm ERR! npm v2.11.2
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package react does not satisfy its siblings' peerDepend
encies requirements!
npm ERR! peerinvalid Peer graphiql@0.3.1 wants react@^0.13 || ^0.14.0-beta
npm ERR! peerinvalid Peer react-dom@0.14.8 wants react@^0.14.8

npm ERR! Please include the following file with any support request:
npm ERR! C:\WS\graphql-blog-schema\npm-debug.log

I am using npm version 2.11.2 and node version v6.9.1 and Windows 7

In addition to this I ran the ls minimatch command and got the following:

C:\WS\graphql-blog-schema>npm ls minimatch
(node:8016) fs: re-evaluating native module sources is not supported. If you ar
using the graceful-fs module, please update it to a more recent version.
react-hot-boilerplate@1.0.0 C:\WS\graphql-blog-schema
├─┬ babel-core@5.8.38
│ └── minimatch@2.0.10
├─┬ eslint@2.13.1
│ └─┬ glob@7.1.1
│ └── minimatch@3.0.3
├─┬ react@0.13.3 peer invalid
│ └─┬ envify@3.4.1
│ └─┬ jstransform@11.0.3
│ └─┬ commoner@0.10.4
│ └─┬ glob@5.0.15
│ └── minimatch@3.0.3
└─┬ webpack@1.13.3
└─┬ watchpack@0.2.9
└─┬ chokidar@1.6.1
└─┬ readdirp@2.1.0
└── minimatch@3.0.3

npm ERR! peer invalid: react@0.13.3 C:\WS\graphql-blog-schema\node_modules\reac

Very grateful for any help.

**Comment by asiandrummer** [comment]
Hi @AlokJoshi - it seems like you have an outdated version of `react`. Would you try upgrading it?
Sometimes for me the modules won't update with just doing `npm install/update` - `rm -rf node_modules && npm install` helps with that case.

**Comment by asiandrummer** [comment]
Let me know if this gets resolved :D and feel free to reopen the issue when you can'1.

**Comment by AlokJoshi** [comment]
@asiandrummer Please close the issue. I was able to resolve it by updating npm and updating react. The npm update was difficult as I had npm installed both in my user folder as well as globally.
