### ISSUE TITLE
Maintain argument order in the schema.

### ISSUE THREAD

**Issue by coady** [graphql/graphiql#2219]
Fields maintain their original schema order in both the docs and the autocomplete suggestions (#884). But arguments are sorted alphabetically.

As with fields, although the order doesn't matter functionally it still indicates importance, grouping, etc. Also it looks inconsistent since input fields are in schema order.

**Comment by ritikBhandari** [comment]
Hi,
Can I have a try on this issue?

**Comment by acao** [comment]
@ritikBhandari sure! `getAutocompleteSuggestions` is where you would start in the language service

**Comment by ritikBhandari** [comment]
thank you @acao, I'll start it right away!

**Comment by coady** [comment]
Looks like this is already done in recent versions.
