### ISSUE TITLE
Should not show syntax error in JavaScript file

### ISSUE THREAD

**Issue by lensbart** [graphql/graphiql#2238]
I have a `.sequelizerc` file that contains JavaScript code.

This extension seems to parse the file as GraphQL and shows a `Syntax Error: Unexpected Name "const".` on the first line.

I can’t find seem to find any misconfiguration that caused this to happen, so perhaps it’s default behaviour by this plugin?

Thanks

**Comment by acao** [comment]
I'm guessing you saw this as soon as you opened this file? Or did you see it after making edits?

Did you see the `Syntax Error` in vscode itself?

Perhaps the content provicer for `Execute <operation type>` is too overzealous with parsing?

**Comment by lensbart** [comment]
Hello, not sure what I changed, but after fiddling with my ESLint config, the issue seems to be gone.

Apologies for not being more helpful! But as far as I’m concerned, the issue can be closed.

**Comment by acao** [comment]
thanks for reporting it!

**Comment by nopeless** [comment]
@acao I seem to have this exact error. I would like to help reproduce this error but I'm not sure. Can you look into it? Also, let me know if this should be a separate issue. Thanks in advance
