### ISSUE TITLE
optional chaining for graphql-language-service@5.0.0 breaks upstream build

### ISSUE THREAD

**Issue by b-admike** [graphql/graphiql#2240]
Hi,

We are using `graphiql` module in our app which takes the latest of `1.x.x` version and since upgrading recently to `1.7.1` building `graphql-language-service@5.0.0` is failing with the following reason:

```
16:39:07  Module parse failed: Unexpected token (45:28)
16:39:07  You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
16:39:07  |     if (kind === RuleKinds.IMPLEMENTS ||
16:39:07  |         (kind === RuleKinds.NAMED_TYPE &&
16:39:07  >             state.prevState?.kind === RuleKinds.IMPLEMENTS)) {
16:39:07  |         return getSuggestionsForImplements(token, state, schema, queryText, typeInfo);
16:39:07  |     }
16:39:07   @ ../node_modules/apiconnect-explorer/node_modules/graphql-language-service/esm/interface/index.js 2:0-45 2:0-45
16:39:07   @ ../node_modules/apiconnect-explorer/node_modules/graphql-language-service/esm/index.js
16:39:07   @ ../node_modules/apiconnect-explorer/node_modules/graphiql/esm/components/GraphiQL.js
16:39:07   @ ../node_modules/apiconnect-explorer/node_modules/graphiql/esm/index.js
16:39:07   @ ../node_modules/apiconnect-explorer/dist/es/components/TestToolGraphQL.js
16:39:07   @ ../node_modules/apiconnect-explorer/dist/es/components/GraphQLDisplay.js
16:39:07   @ ../node_modules/apiconnect-explorer/dist/es/components/Routing.js
16:39:07   @ ../node_modules/apiconnect-explorer/dist/es/App.js
16:39:07   @ ../node_modules/apiconnect-explorer/dist/es/Bootstrap.js
```
similar issue https://github.com/graphql/graphiql/issues/1852, but we are using webpack 4.x and babel 6.x, so wondering if it is something we need to resolve on our end by doing something like https://danw1ld.medium.com/optional-chaining-for-javascript-with-babel-7-and-webpack-4-2de8fd9dbdd5 to handle optional chaining or it can be resolved from the module itself?

**Comment by edwinckc** [comment]
Same issue here. A previous workaround was to pin the parser/interface versions, but it looks like `graphql-language-service@5.0.0` specifically retired those 🤔

**Comment by acao** [comment]
hey thanks for reporting @b-admike, apologies for this error, I will take a look into this. We should have caught this in CI, so possibly something is missing after moving back to netlify deploy previews

@edwinckc we are about to deprecate all of those as they have been merged with the `graphql-language-service`

**Comment by acao** [comment]
every library from this repo that is universal or browser centric should uses `target` `es6` with typescript by default, which should not include optional chaining, as that is equivalent `es2015`. we only override `target` to a later version for the LSP server, vscode-graphql and CLI

**Comment by acao** [comment]
Looking at unpkg, i see nullish coalescing as well!

![Screenshot 2022-03-23 at 16 24 20](https://user-images.githubusercontent.com/1368727/159735132-5910f97b-6597-4042-95ae-bb4634914ff2.png)

This same file for `cjs`, the `dist/` path did not have it

and I overlooked this! doh! ok this would be the culprit. it overrides the base esm tsconfig to target esnext.

https://github.com/graphql/graphiql/blob/37a66b1933a3c1c97b7d5dbfad435d1a67d329b9/packages/graphql-language-service/tsconfig.esm.json#L12

**Comment by acao** [comment]
@timsuchanek about to do a quick patch fix PR for this, let's release that before tabs? so that folks don't need a minor increment to graphiql to fix this?

**Comment by acao** [comment]
trying to decide what `target` is most suitable for the browsers we support since IE is no longer supported, and safari support isn't expected (it's a developer tool after all!)

`es2018` actually looks feasible across the board these days? But maybe just keep it to `es6` for now to keep it safe?

**Comment by edwinckc** [comment]
It looks like we're still getting the same error on `1.7.2`, with `graphql-language-service "^5.0.1"` 🤔 

<img width="935" alt="image" src="https://user-images.githubusercontent.com/2934985/159981344-70725faa-4f1f-4e34-ac63-c926cf983dec.png">

**Comment by retrodaredevil** [comment]
I'm also getting that error. What is the largest version I can use for the time being to avoid that error? And can this issue be reopened if it was never fixed?

**Comment by acao** [comment]
We are targeting `es6`? I will take a look in a few days when I have a chance

**Comment by retrodaredevil** [comment]
I'm pretty new to the JS ecosystem, but from what I understand that stuff doesn't seem to be getting transpiled like TypeScript code has to be. So my guess is that the resulting transpiled code (all the TypeScript code) is targeting es6, but not that JavaScript code. 

I could be wrong though. I also have no idea on how to fix it if that is the case. Thanks for reopening.

**Comment by retrodaredevil** [comment]
So... I'm looking at the main branch, and that change to remove the `ESNext` target doesn't seem to be there: https://github.com/graphql/graphiql/blob/e793f887b28af471c4d55522a57b61ebadafd14f/packages/graphql-language-service/tsconfig.esm.json#L7

The fact that we're getting this error for `esm` stuff makes sense then. Did 352013395917ac7c9926bb22e1c7fa409c5a4e26 get merged in? The release that was supposed to have this change doesn't have it: https://github.com/graphql/graphiql/releases/tag/graphql-language-service%405.0.1
