### ISSUE TITLE
React App: Module not found: Error: Can't resolve 'graphql'

### ISSUE THREAD

**Issue by leonel-os** [graphql/graphiql#2242]
I'm trying to run the following code:

```
import GraphiQL from "graphiql";
import { createGraphiQLFetcher } from "@graphiql/toolkit";
import logo from "./logo.svg";
import "./App.css";

function App() {
  const fetcher = createGraphiQLFetcher({
    url: "http://localhost:4000/graphql",
  });
  return (
    <div className="App">
      <GraphiQL fetcher={fetcher} editorTheme={"dracula"} />
    </div>
  );
}

export default App;

```

However I'm getting a lot of errors related to "Module not found: Error: Can't resolve 'graphql' in"

![image](https://user-images.githubusercontent.com/70973862/158941288-11684e48-cd9b-4951-8487-ff76e28d18ab.png)

Can you help me please, am I missing a dependency? 

I installed graphiql and @graphiql/toolkit

Thanks

**Comment by acao** [comment]
You must install `graphql` as a peer dependency as well!

**Comment by leonel-os** [comment]
> You must install `graphql` as a peer dependency as well!

Awesome. That solution fixed my issue.

Thanks!

**Comment by timsuchanek** [comment]
Closing this as it has been resolved.
