### ISSUE TITLE
GraphIQl on AWS Lambda

### ISSUE THREAD

**Issue by maitriyogin** [graphql/graphiql#226]
Hi,
I've set up a graphql endpoint with API gateway and AWS lambda.
I'm using the GraphiQL electron app to query my endpoint and it's working like a dream!
Although ... the docs don't show up?
My lambda is just accepting the request, extracting the query, stripping out \n and \ and then sending this off to graphql.  ( its not express so no body-parser ... bummer )
```graphql(Schema, query)```
This is working fine for queries and mutations but something is wrong when trying to open up the docs tab, just get a spinner ...
I'm not 100% sure whats happening when I open the docs tab and I can't see any requests...
I can introspect the schema with 
```
{__schema { 
  queryType { 
    name, 
    fields { name, description} }}
}
```
I get a correct response and the docs on the schema are displayed as expected...

So, what does the docs tab do? do I need to supply it manually with the schema?
Many thanks for any help,
Stephen.

**Comment by asiandrummer** [comment]
Hi @maitriyogin - GraphiQL tries to send an introspection query using your fetcher function to your endpoint when it's first brought up, and the docs explorer wouldn't show up unless your schema is ready, either from this initial introspection step or by manually providing it. It sounds like your introspection step in the beginning when the component is mounted is not successful - would you mind checking that?

**Comment by bradennapier** [comment]
Mine is not working and I appear to successfully work with the introspection step?  I also do not have any kind of auto complete.  Not sure what is wrong but all the queries work fine.
