### ISSUE TITLE
import interface with absolute path

### ISSUE THREAD

**Issue by JaegerJens** [graphql/graphiql#2260]
I got the following error in my project (using TypeScript 4.6.3):
```
node_modules/codemirror-graphql/variables/hint.d.ts:3:24 - error TS2307: Cannot find module 'src/hint' or its corresponding type declarations.

3 import { IHints } from 'src/hint';
                         ~~~~~~~~~~
```

I traced it back to this `import` statement:

https://github.com/graphql/graphiql/blob/main/packages/codemirror-graphql/src/variables/hint.ts#L22

```
import { IHints } from 'src/hint';
```

My fix would be a relative import:

```
import { IHints } from '../hint';
```

**Comment by acao** [comment]
does `codemirror-graphql@1.2.15-canary-e0939150.0` solve your issue @JaegerJens ?

**Comment by JaegerJens** [comment]
`codemirror-graphql@1.2.15-canary-e0939150.0` fixes my problem. Thank you!
