### ISSUE TITLE
Can't install graphql-language-service-cli globally without graphql-language-service-server

### ISSUE THREAD

**Issue by elken** [graphql/graphiql#2264]
# Description

Simply put, I'm not able to install `graphql-language-service-cli` globally without `graphql-language-service-server` for the purposes of [lsp-mode](https://github.com/emacs-lsp/lsp-mode/) (and I would imagine similar issues for other LSP consumers)

# What I've tried

I've narrowed it down to [this](https://github.com/graphql/graphiql/commit/3626f8d5012ee77a39e984ae347396cb00fcc6fa) commit.

I've also tried using the previous version as an LSP client and all seems fine.

If there is a larger reason for the removal of the dependancy, feel free to close this and I'll try and find a workaround.

**Comment by acao** [comment]
Moving today, so @elken if you can open a PR that re-adds the server but not utils, I could merge in a few hours, it would be a godsend!

**Comment by elken** [comment]
> Oh goodness, this is embarrassing, thanks for reporting

No worries! :D

**Comment by elken** [comment]
> Moving today, so @elken if you can open a PR that re-adds the server but not utils, I could merge in a few hours, it would be a godsend!

I'm actually moving tomorrow myself! (small world, eh?) but yes I'll add one now quickly
