### ISSUE TITLE
Unable to load schema from `gql` tag

### ISSUE THREAD

**Issue by alexturpin** [graphql/graphiql#2270]
## Actual Behavior

When I try to load my schema from a `gql` tag, the GraphQL language server crashes.

## Expected Behavior

The server should not crash.

## Steps to Reproduce the Problem Or Description

Two files , both in the root of my project:

.graphqlrc.yml
```
schema: ./schema.ts
```

schema.ts
```
import gql from "graphql-tag"

gql`
  type Query {
    me: User
  }

  type User {
    id: ID
    name: String
  }
`
```

## Specifications

  - GraphQL for VSCode Extension Version: 0.3.53
  - VSCode Version: 1.6..0
  - OS Name: macOS Monterey
  - OS Version: 12.2.1
  - graphql config filename and format example: see above

## Logs Of TS Server || GraphQL Language Service

```
[Info  - 4:03:47 PM] The graphql server has stopped running
GraphQL LSP restarted
(node:54701) ExperimentalWarning: stream/web is an experimental feature. This feature could change at any time
(Use `Electron --trace-warnings ...` to show where the warning was created)
3/31/2022, 4:03:48 PM [3] (pid: 54701) graphql-language-service-usage-logs: {"type":"usage","messageType":"initialize"}
/Users/alexturpin/.vscode/extensions/graphql.vscode-graphql-0.3.53/out/server/server.js:119874
        throw new Error(`
              ^

Error: 
      Unable to find any GraphQL type definitions for the following pointers:
        
          - ./schema.ts
          
    at prepareResult (/Users/alexturpin/.vscode/extensions/graphql.vscode-graphql-0.3.53/out/server/server.js:119874:15)
    at loadTypedefs (/Users/alexturpin/.vscode/extensions/graphql.vscode-graphql-0.3.53/out/server/server.js:119848:14)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.loadSchema (/Users/alexturpin/.vscode/extensions/graphql.vscode-graphql-0.3.53/out/server/server.js:119892:23)
    at async GraphQLCache.getSchema (/Users/alexturpin/.vscode/extensions/graphql.vscode-graphql-0.3.53/out/server/server.js:122642:22)
[Error - 4:03:48 PM] Connection to server got closed. Server will not be restarted.
[Info  - 4:03:48 PM] The graphql server has stopped running
```

Am I doing something wrong? graphql-code-generator can load that same schema fine, through the same GraphQL config file.

**Comment by acao** [comment]
does this canary release work for y'all?

`graphql-language-service-cli@3.2.19-canary-5991895d.0`

aka

`npm install -g graphql-language-service-cli@3.2.19-canary-5991895d.0`

**Comment by alexturpin** [comment]
@acao thanks for the quick answer! I did the npm install, but after a restart of VS Code and the GQL Language Server I get the same error in the output. I validated that the canary version is installed globally:

```
$ graphql-lsp --version
3.2.19-canary-5991895d.0
```

**Comment by acao** [comment]
@alexturpin I'm terribly sorry, i responded to the wrong bug. I hope to respond to yours soon

**Comment by acao** [comment]
@dotansimha do we know why graphql config getSchema() would fail like this? Is this a known bug with code file loader?

**Comment by acao** [comment]
<img width="636" alt="Screenshot 2022-05-03 at 11 00 20" src="https://user-images.githubusercontent.com/1368727/166428072-529f82f4-9d14-41f7-8636-5934a6fbb46b.png">

<img width="949" alt="Screenshot 2022-05-03 at 10 59 59" src="https://user-images.githubusercontent.com/1368727/166428030-e28ea4dc-b5da-42ec-8b25-286ea84a9c13.png">

these settings are working for me, I'll have to check later when I have time

**Comment by DPangerl** [comment]
Same problem here. It does work with remote schemas. But reading gql tags the server crashes.

**Comment by acao** [comment]
Ok, I’ll take a look this week hopefully, sorry y‘all, not sure what in the LSP would’ve caused this regression


This specific error is coming from `graphql-config`, so I wonder what‘s causing it to fail to parse the file?

**Comment by scamden** [comment]
@acao did you ever end up taking a look at this? i'm running into this same problem almost a year later.

**Comment by scamden** [comment]
oh i'm realizing item #3 in https://github.com/graphql/graphiql/issues/2050 might be the fix for this

**Comment by acao** [comment]
@alexturpin I found the resolution to this bug! `graphql-config` had dropped code file loader for `graphql-config@4` and we had overlooked this, so I've created a new graphql config extension (not related to vscode extensions). This should ensure that we can always load `schema` and `documents` from .ts, .tsx, .js and .svelte files

**Comment by scamden** [comment]
Great news! We can get this fix by updating vscode extension?
