### ISSUE TITLE
Decorators break completion

### ISSUE THREAD

**Issue by sdykae** [graphql/graphiql#2294]
## Actual Behavior
![image](https://user-images.githubusercontent.com/50224521/141252579-a2f9177d-8729-4a4c-bd25-aa2f0a15e8fe.png)

## Expected Behavior
![image](https://user-images.githubusercontent.com/50224521/141252692-6f9c20eb-04fc-4c2f-b3b0-108a39dd2b35.png)

## Steps to Reproduce the Problem Or Description
![image](https://user-images.githubusercontent.com/50224521/141252771-35c15b4a-f170-4048-b960-541e9ec1999e.png)

## Specifications

  - GraphQL for VSCode Extension Version:  0.3.18

  - VSCode Version: latest
  - OS Name: linux
  - OS Version: ubuntu 20.04

#fix              
https://github.com/babel/babel-eslint/issues/774
https://github.com/babel/babel-eslint/issues/662
https://stackoverflow.com/questions/53483066/babel-7-using-the-export-keyword-between-a-decorator-and-a-class-is-not-allowed/54516632

Why babel-eslint is triggered? Wtf?
My project don't use babel, or eslint.

**Comment by fajarclodeo** [comment]
Affect my nestjs project as well.

**Comment by acivier-serial** [comment]
Any update on this issue ?

**Comment by acao** [comment]
I’m in the midst of a big project at work, but if someone wants to open a PR with those changes to the babel parser options and a test for findGraphQLTags that proves the fix, it would be very welcome!

**Comment by acao** [comment]
At this service level we have `decorators-legacy` available for this type, however I get this:

<img width="564" alt="Screenshot 2022-07-16 at 01 21 56" src="https://user-images.githubusercontent.com/1368727/179323638-7368c4a5-2f13-4855-b7a5-c6ac410c44dd.png">

we can add an option to allow someone to optionally enable support for `decorators-legacy`, which would disable support for `decorators`? one could use projects to filter which files have this setting enabled?

**Comment by joepjoosten** [comment]
https://github.com/graphql/graphiql/blob/48e7710a80739931565e1d472ed38136cc73865f/packages/graphql-language-service-server/src/findGraphQLTags.ts#L43

**Comment by jrwpatterson** [comment]
any updates on this. is there a way just to block it looking at the typescript with decorators, we are currently running a monorepo with the graph queries defined in a react app and a nest server. The nest server doesn't need any graph queries but because it has decorators its breaking the rest of the thing..

**Comment by acao** [comment]
If someone wants to open a PR it’s a relatively simple option to allow legacy decators.

**Comment by mvnrhd** [comment]
@acao I've added the changes in this fork: https://github.com/mvnrhd/graphiql/tree/feat/add-opt-in-for-legacy-decorators.
Unfortunately, I didn't manage to fully test my changes locally and tests are missing as well. But maybe you (or someone else) could use it as a basis for addressing the issue soon? 🚀

**Comment by acao** [comment]
@mvnrhd indeed, happy to do that! Thank you!

**Comment by marvinrohde-leanix** [comment]
> @mvnrhd indeed, happy to do that! Thank you!

Hey @acao, do you think you could tackle this soon? 🙂

**Comment by mvnrhd** [comment]
Hey @acao, do you think you could tackle this soon? 🙂

**Comment by acao** [comment]
@mvnrhd hey this is awesome, thank you! finally had a chance to take a look

The only thing is that it's a vscode setting only, with no graphql-config options yet - 

This means non-vscode users might have more trouble opting in to this feature - for example most nvim coc users just configure the graphql config for the LSP server, and aren't used to needing to set extension settings.

It also means you can't have it enabled for a single project, and disabled for others - it's all or nothing. 

We just need to support this config coming from  the matching `graphql-config` project _or_ vscode settings. Do you think you can add that to the branch? I see this bug has 9 watchers which means it's one of our top priority bugs with the LSP - this is the one that blocks nest.js and others yes?

**Comment by mvnrhd** [comment]
Thanks for the implementation hints @acao. Since I'm quite busy at work (what a surprise) not sure if I can make it this week. Sounds straightforward though.

**Comment by acao** [comment]
Thanks for this @mvnrhd! I've been thinking about this fix for a long time, making it happen tonight! Sorry it's been so long everyone

**Comment by acao** [comment]
After finally writing some unit tests, from what I can tell, enabling `decorators-legacy` actually allows both legacy @decorate() and acceped @decorate syntax so... i think this is just as easy as changing one line, and no configuration setting will be needed. i was mistaken and thought they were exclusive

**Comment by acao** [comment]
the latest `vscode-graphql@0.8.3` and related lsp server version should fix this! thanks everyone
