### ISSUE TITLE
Syntax Highlighting fails when mixing `implements` and directives

### ISSUE THREAD

**Issue by d3dc** [graphql/graphiql#2300]
## Actual Behavior

<img width="1552" alt="Screen Shot 2021-03-08 at 10 51 41 AM" src="https://user-images.githubusercontent.com/4175887/110360744-59340680-7ffc-11eb-9b93-521ae822c77d.png">

## Expected Behavior

The syntax is consistently colored

## Steps to Reproduce the Problem Or Description

Use too much metaprogramming.

## Specifications

  - GraphQL for VSCode Extension Version:  0.3.15
  - VSCode Version: 1.54
  - OS Name: MacOS
  - OS Version: 10.15.7

**Comment by acao** [comment]
Are you still able to see this problem? I cannot re-create the bug. I think we fixed it in the referenced PR

![image](https://user-images.githubusercontent.com/1368727/201515511-4bc30069-4aaf-4db1-8072-db25d7221699.png)
