### ISSUE TITLE
VS Code Extension: Installation / update fails on Windows

### ISSUE THREAD

**Issue by kryops** [graphql/graphiql#2302]
Hi there,

the VS Code extension does not want to be installed or updated on Windows any longer. My system just tried and failed to update from 0.3.53 to 0.4.1. It's not just on my machine, a colleague of mine could reproduce as well.

It seems to affect automatic and manual updates as well as fresh installations. The only thing that seems to work is installing via the command line.

Sadly, I could not find any actual errors in the logs, the only thing that pops up is the "No ptyHost heartbeat after 12 seconds" error.

Here is the "Log (Shared)" output:
```
[2022-04-12 12:09:37.762] [sharedprocess] [info] Getting Manifest... graphql.vscode-graphql
[2022-04-12 12:09:38.372] [sharedprocess] [info] Installing extension: graphql.vscode-graphql
[2022-04-12 12:09:38.434] [sharedprocess] [info] Downloaded extension: graphql.vscode-graphql c:\Users\xxx\AppData\Roaming\Code\CachedExtensionVSIXs\graphql.vscode-graphql-0.4.1
[2022-04-12 12:09:54.395] [sharedprocess] [warning] No ptyHost heartbeat after 6 seconds
[2022-04-12 12:09:59.409] [sharedprocess] [error] No ptyHost heartbeat after 12 seconds
```

Environment:
* VS Code 1.66.1
* Windows 10 21H2

Seems to work fine on macOS.

Thanks for looking into it!

**Comment by acao** [comment]
This looks quite bad!

it will be some time until I can reproduce on windows to find out more

**Comment by kryops** [comment]
I just had time to fiddle around with this a bit myself. I could not find the original cause of the problem, but it seems to be gone when building the current `main` branch locally.

@acao https://github.com/graphql/graphiql/pull/2288 looks like you intended to publish a 0.4.2 for the VS Code extension? 0.4.1 is still the current version on the marketplace, so it probably didn't work.

When building locally, I hat to change https://github.com/graphql/graphiql/blob/main/packages/vscode-graphql/esbuild.js#L4 to `console` to make it work, maybe that's the issue there as well.

**Comment by acao** [comment]
The issue is with our publishing pipeline which I haven’t had time to fix. Atlassian changesets makes it quite difficult to define alternative publishing logic, compared to say, semantic release. 

The version you are using isn’t bundled vs the version in the repo is bundled. Thus path issues go away because the extension and dependencies resolve from a single file.

Once I have stable internet and furniture I will get back to this, in a couple weeks

**Comment by acao** [comment]
just published that version to vscode marketplace finally! I will fix the github actions later. let me know if your issue is resolved in the latest release!

**Comment by kryops** [comment]
0.4.3 installs perfectly again, thanks a lot! ☺️
