### ISSUE TITLE
Schema directive TM scope for syntax highlight

### ISSUE THREAD

**Issue by latipun7** [graphql/graphiql#2306]
## Actual Behavior

Directive has same scope as scalar types.
![Schema directive](https://drive.google.com/uc?id=1aZNqzthztIB_JMs1CyPLYf1WbEm4bFEJ)

## Expected Behavior
Schema directive has it's own TM scope, so we can color them differently. I want different color syntax highlight for directive. 
Thanks.

## Specifications

  - GraphQL for VSCode Extension Version: 0.1.7
  - VSCode Version: 1.32.1
  - OS Name: Windows
  - OS Version: windows 10

**Comment by acao** [comment]
pretty sure that a user resolved this already

**Comment by latipun7** [comment]
Sorry, I forgot that I had this issue 3 years ago. 
Thanks. I close this for now.
