### ISSUE TITLE
On-Demand Request Authorization

### ISSUE THREAD

**Issue by mastorm** [graphql/graphiql#2307]
I want to get a bearer token from my backend before sending off a request. 

Of course it would be an option to use string interpolation in the `graphql.config.js` file, but being able to define some sort of middleware to get a Bearer token would be neat.
 
Example:
```js
module.exports = {
  projects: {
    app: {
      schema: 'schema.graphql',
      documents: ['**/*.{graphql,js,ts,jsx,tsx}', 'my/fragments.graphql'],
      extensions: {
        endpoints: {
          default: {
            url: 'http://localhost:5000/graphql',
            middleware: (request) => ({...request, headers: { Authorization: getBearerToken() }})
          },
        },
      },
    },
  },
};
```

Is there a simple way to solve my problem?

**Comment by acao** [comment]
Unfortunately we have removed query execution from the extension for the time being
