### ISSUE TITLE
Markdown support in GraphQL block strings

### ISSUE THREAD

**Issue by mfulton26** [graphql/graphiql#2310]
## Actual Behavior

Markdown within GraphQL block strings is not highlighted using the Markdown syntax highlighting .

````graphql
"""
## Example Request

```graphql
query {
  a
}
```

## Example Response

```json
{ "a": 42 }
```
"""
type Query {
  a: Number!
}
````

## Expected Behavior

I can write Markdown (specifically code blocks) within my GraphQL block strings and get great syntax highlighting and code completion as if I were writing a Markdown (*.md) file.

## Steps to Reproduce the Problem Or Description

1. Create a `*.graphql` or `*.gql` file
2. Define a simple schema (see above for example)
3. Add a code block within said schema
4. Use Markdown features such as code blocks with a language tag within said code block

## Specifications

  - GraphQL for VSCode Extension Version: 0.2.2
  - VSCode Version: 1.39.2
  - OS Name: macOS Mojave
  - OS Version: 10.14.6

**Comment by acao** [comment]
the markdown grammar support was released a while ago! let us know if you have any issues
