### ISSUE TITLE
Require modules not working on remote + Yarn 3

### ISSUE THREAD

**Issue by Chnapy** [graphql/graphiql#2317]
I'm working on a project using Yarn 3 with GraphQL extension.
Locally I have no issue, this extension works perfectly.

This project allows to use VSCode devcontainers ([developing inside a Docker container](https://code.visualstudio.com/docs/remote/containers)).

When I open my project from remote (from inside the devcontainer), GraphQL does not work anymore.
Issue is from my `.graphqlrc.js` config file. All my modules `require()` throw errors: my dependencies are not found anymore.

Logs from `GraphQL Language Server` output:
```
4/14/2022, 2:39:38 PM [2] (pid: 1018) graphql-language-service-usage-logs: Error: Cannot find module 'glob'
Require stack:
- /workspace/.graphqlrc.js
- /root/.vscode-server/extensions/graphql.vscode-graphql-0.4.1/node_modules/graphql-config/node_modules/cosmiconfig/dist/loaders.js
- /root/.vscode-server/extensions/graphql.vscode-graphql-0.4.1/node_modules/graphql-config/node_modules/cosmiconfig/dist/ExplorerBase.js
- /root/.vscode-server/extensions/graphql.vscode-graphql-0.4.1/node_modules/graphql-config/node_modules/cosmiconfig/dist/Explorer.js
- /root/.vscode-server/extensions/graphql.vscode-graphql-0.4.1/node_modules/graphql-config/node_modules/cosmiconfig/dist/index.js
- /root/.vscode-server/extensions/graphql.vscode-graphql-0.4.1/node_modules/graphql-config/index.js
- /root/.vscode-server/extensions/graphql.vscode-graphql-0.4.1/node_modules/graphql-language-service-server/dist/GraphQLCache.js
- /root/.vscode-server/extensions/graphql.vscode-graphql-0.4.1/node_modules/graphql-language-service-server/dist/MessageProcessor.js
- /root/.vscode-server/extensions/graphql.vscode-graphql-0.4.1/node_modules/graphql-language-service-server/dist/index.js
- /root/.vscode-server/extensions/graphql.vscode-graphql-0.4.1/dist/server/index.js
```

My `.graphqlrc.js` file (just first lines):
```js
// this line throw error: Cannot find module 'glob'
// but works perfectly locally
console.log(require.resolve('glob'));
const glob = require('glob');
```

My `package.json` file (simplified):
```json
{
    "name": "frontend",
    "devDependencies": {
        "glob": "7.2.0",
        "graphql": "15.8.0",
    },
    "packageManager": "yarn@3.2.0"
}

```

Extension is installed using default config:
<img width="359" alt="image" src="https://user-images.githubusercontent.com/7474483/163416700-205e7b57-fef1-40b7-b6f7-43b01a98a1ef.png">

<img width="512" alt="image" src="https://user-images.githubusercontent.com/7474483/163416640-03959e27-9b6c-43dd-8226-3e17f379b1de.png">

Note that:
- `glob` dependency is present in `.yarn/cache`
- in remote if I run `yarn node` then type `console.log(require.resolve('glob'))` it works well

Thanks !

**Comment by acao** [comment]
Thanks for reporting! This is very strange. The next release will bundle the extension into a single file using esbuild so this shouldn’t be an issue after the next release

**Comment by Chnapy** [comment]
Hi, I haven't reproduce this issue for a while. I guess it's resolved now, thanks 👍
