### ISSUE TITLE
Instruct all graphiql/toolkit users to install graphql-ws

### ISSUE THREAD

**Issue by eMerzh** [graphql/graphiql#2322]
seems it breaks my builds with 

```
Module not found: Error: Can't resolve 'graphql-ws' in '/proj/node_modules/@graphiql/toolkit/esm/create-fetcher'
```

i don't use graphql-ws directly but the fetcher as described in doc

```js
import { createGraphiQLFetcher } from '@graphiql/toolkit'

const fetcher = createGraphiQLFetcher({
	url: '/graphql',
})
```

would pin point the breakage here https://github.com/graphql/graphiql/commit/c36504a804d8cc54a5136340152999b4a1a2c69f BC graphql-ws was included by graphql-config which is not true anymore? 

Thanks for the work here :)

**Comment by acao** [comment]
`graphql-ws` is a peer dependency if you check the readme. if we marked a specific version in `dependencies` it would break people's implementations

**Comment by acao** [comment]
@enisdenjo do you think we should just depend on the latest version of `graphql-ws`, or keep `graphlq-ws` as a peer dep?

**Comment by acao** [comment]
it's less than ideal that non-wss users have to install it for our fetcher, though.
perhaps we can re-architect the "createGraphiQLFetcher" to allow "plugins", just worried that would send us down a path of complexity.

@dotansimha and @timsuchanek  what do you think?

**Comment by enisdenjo** [comment]
I'd suggest leaving it as a peer dep, absolutely no need to push a new version of `@graphiql/toolkit` everytime `graphql-ws` updates.

**Comment by eMerzh** [comment]
so i should include it in my package.json even though i don't use it directly?

**Comment by acao** [comment]
@eMerzh for now, yes, sorry. this is generally the case for all `peerDependencies` of `graphiql`

**Comment by eMerzh** [comment]
👌 thanks for the help 👍  

it would probably help to make it as explicit code dependancy like in examples 
with createGraphiQLFetcher using a "simple" client ... to make it clearer.
anyway, you can close this if you want :)

**Comment by timsuchanek** [comment]
I'd also say we keep it as a peer dependency for now, but then revisit this topic once we're looking at a more elaborate plugin system targeting v2.

**Comment by timsuchanek** [comment]
I'll close this for now, as it seems to be resolved in this case.

**Comment by acao** [comment]
I’m reopening until we resolve this ticket by updating the docs at least.

@eMerzh agreed, I think we need to update several markdown files with these instructions

**Comment by thomasheyenbrock** [comment]
Related: https://github.com/graphql/graphiql/issues/2405

**Comment by acao** [comment]
I found a much better solution to this problem!

`peerDependenciesMeta` allows you to specify which peer dependencies are optional

**Comment by thomasheyenbrock** [comment]
The latest version (`@graphiql/toolkit@0.7.2`) now specifies `graphql-ws` as _optional_ peer dependency
