### ISSUE TITLE
Can't zoom in 

### ISSUE THREAD

**Issue by charlie2clarke** [graphql/graphiql#2324]
Have I gone crazy or is there not a way to zoom in? Ctrl and scroll wheel doesn't work, neither does ctrl and +, nor is there any options available in the view menu item. 

Is there something I am not spotting, or is this not yet implemented?

**Comment by acao** [comment]
It should work as long as you aren’t focused on an editor pane. Otherwise, codemirror 5 overrides allmost all keyboard events

**Comment by acao** [comment]
Oh my bad, we don’t support a desktop application. You’ll have to ask the maintainer of that repository to enable this in the electron menu. Perhaps it is GraphiQL.app? I‘m closing this now, hope you can get ahold of the maintainer!
