### ISSUE TITLE
Implement new design with CodeMirror 5

### ISSUE THREAD

**Issue by timsuchanek** [graphql/graphiql#2325]
To achieve the [new design](https://github.com/graphql/graphiql/discussions/2216) in an incremental fashion, we want to first implement as much as possible of it with the current GraphiQL technology stack before moving to Monaco / modernize any components.
This is the tracking issue for that work.

**Comment by thomasheyenbrock** [comment]
The new design has been implemented and shipped with `graphiql@2`
