### ISSUE TITLE
How to add definition for custom directives? Or even better, any support for Relay.js directives?

### ISSUE THREAD

**Issue by Albert-Gao** [graphql/graphiql#2330]
## Steps to Reproduce the Problem Or Description
A Relay.js directive gives error:
![image](https://user-images.githubusercontent.com/18282328/94208375-cd329480-ff1d-11ea-95fd-3ca23fa3231c.png)

Any way we can add this definition and or just add support for Relay.js?
There is an open issue: graphql/graphiql#2329

It said follow GraphQL config doc, but I can not find any example there in terms of adding a custom directive: https://graphql-config.com/usage#extensions

So, how to solve this problem, or simply ignore it?

## Specifications

GraphQL for VSCode Extension Version: latest from store
Version: 1.49.1
Commit: 58bb7b2331731bf72587010e943852e13e6fd3cf
Date: 2020-09-16T23:21:17.533Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

**Comment by acao** [comment]
@Albert-Gao the _only_ thing missing from your working example is the validation rules

If anyone is looking for a compatibility layer this is up to date (and is the home of the old javascript relay validaton rules)
https://github.com/relay-tools/relay-graphql-js/tree/main/packages/graphql-config

you also may have better luck with the relay compiler LSP than ours. enjoy
