### ISSUE TITLE
Improve autocompletion: insert all fields of type

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [graphql/graphiql#2333]
## Actual Behavior
Currently, it's possible to insert fields of type via autocomplete only one by one.

## Expected Behavior
It would be great to insert all fields of type at once (and then remove only unnecessary). E.g. by typing `{ *` after the name of type.

**Comment by acao** [comment]
graphiql supports this already. though it doesn't do this by default, you can already configure it to insert all fields using `getDefaultFieldNames` prop! Here's [the default behavior](https://github.com/graphql/graphiql/blob/9944f7dedb1a030c0e19ded601d50ee1c55e0a2c/packages/graphiql-toolkit/src/graphql-helpers/auto-complete.ts#L86)

try this:

1. autocomplete for a leaf field, choose an autocomplete option
2. type CMD + enter (or Ctrl + enter)
3. watch as common fields like `id`, `node` and `edge` appear automatically
![leaf-fields-example](https://user-images.githubusercontent.com/1368727/172599068-894a88d5-a66d-44dc-a323-b45b2fb3db1f.gif)
