### ISSUE TITLE
Cannot load schema.graphql

### ISSUE THREAD

**Issue by 0xTimepunk** [graphql/graphiql#2341]
## Actual Behavior
Vscode output:

(node:10595) UnhandledPromiseRejectionWarning: Error: 
Unable to find any GraphQL type definitions for the following pointers: schema.graphql

with  .graphqlrc.yml

`schema: 'schema.graphql'
documents: 'src/**/*.{graphql,tsx,jsx,ts,js}'
extensions:
  endpoints:
    dev:
      url: https://api.thegraph.com/subgraphs/name/astraldao/spatial-assets-nfts
      subscription:
        url: wss://api.thegraph.com/subgraphs/name/astraldao/spatial-assets-nfts`

and schema.graphql at the root of the project

`type SpatialAsset @entity {
  id: ID!
  owner: String!
  active: Boolean!
}
`
## Expected Behavior
Finding Graphql type definitions and allow running graphql queries from js files within src

## Specifications

  - GraphQL for VSCode Extension Version: 0.3.10
  - VSCode Version: 1.50.1
  - OS Name: Windows 10 /WSL2

**Comment by acao** [comment]
this bug should be cleared up now!
