### ISSUE TITLE
proposal: introduce VSCode Textmate grammar test for testing grammar

### ISSUE THREAD

**Issue by yoshiakis** [graphql/graphiql#2343]
Currently grammar files aren't being tested so it's likely to happen a regression when grammar files are edited in order to fix bugs or add new functionalities. I've looked for a node module that can test grammar files and I've found [VSCode Textmate grammar test](https://github.com/PanAeon/vscode-tmgrammar-test) which is being used in some of vscode extensions, such as [Angular Language Service](https://github.com/angular/vscode-ng-language-service) and [Scala Syntax](https://github.com/scala/vscode-scala-syntax), providing syntax highlighting feature. Both extensions are using this module more than 10 months now and there are almost no issues on that as far as I can see.

This module can do unit test and snapshot test. I think it's better to use mainly snapshot test since it needs less manual code than unit test, though sometimes unit test is also needed when changed part of snap file is large and you think you're likely to overlook regression.

What do you think?

If it looks good, I can write code for grammar test using this module.

**Comment by acao** [comment]
this is a great idea @yoshiakis !
