### ISSUE TITLE
Emojis in paths are not recognized

### ISSUE THREAD

**Issue by yairopro** [graphql/graphiql#2360]
I have a file in a path like the following:
/Users/yair/Workspace/firebase-microservices/functions/src/microservice/retailer/⚡️onRetailerDB/index.ts

## Actual Behavior

It replaces the ⚡️ in the path with `%E2%9A%A1%EF%B8%8F`.

## Expected Behavior

To read the path with emojis correctly .

## Steps to Reproduce the Problem Or Description

Place a fragment in a folder which has an emoji in his name.

## Specifications

  - GraphQL for VSCode Extension Version: GraphQL Insiders v0.3.5
  - VSCode Version: 1.62.3
  - OS Name: Darwin x64
  - OS Version: 21.1.0
  - graphql config filename and format example:
```javascript
module.exports = {
	schema: "https://...",
	documents: "functions/**/*.{graphql,js,ts,jsx,tsx}",
	extensions: {
		endpoints: {
			default: {
				url: "https://...",
				headers: {
					"secret": "...."
				},
			}
		}
	}
};
```

## Logs Of TS Server || GraphQL Language Service

![image](https://user-images.githubusercontent.com/8110568/144844781-6c8cea34-66af-4ce1-b001-814a124f4956.png)

**Comment by acao** [comment]
@yairopro we swapped out for a better cross-platform path resolution approach that shouldn't result in these encoding errors, does this issue still exist?
