### ISSUE TITLE
Feature - Option to disable "validate against schema"

### ISSUE THREAD

**Issue by jgoux** [graphql/graphiql#2363]
Hello all 👋 

Now that there is the awesome https://github.com/dotansimha/graphql-eslint for doing linting and validation against a schema directly as part of ESLint, I'd like to use the vscode extension only for the purpose of autocompletion and code navigation.

## Actual Behavior
At the moment, both ESLint and the extension are validating my operations : 

![image](https://user-images.githubusercontent.com/1443499/106598983-c31e4380-6558-11eb-88b9-298aabf9a50f.png)

In term of performance, the work is done twice. Also we can go further with ESLint by enforcing conventions and even writing custom lint plugins.

## Expected Behavior

I'd like to have a `validate against schema` (default true) configuration option for this plugin so I can use it to enhance my DX in VSCode, but defer all my validation and linting to ESLint.

## Specifications

  - GraphQL for VSCode Extension Version: v0.3.14

**Comment by zachallaun** [comment]
I'm running up against the same fragment issue as @arvindell above. Would love to see an option to disable this kind of validation.
