### ISSUE TITLE
Generating GraphQL Schema in VSCODE

### ISSUE THREAD

**Issue by sam-hsbu** [graphql/graphiql#2366]
Hello.

I am struggling with generating the graphql schema in VSCODE. Can somebody helps me ? here is my "graphql.config.json" file : 

```
{
  "name": "Remote Schema",
  "schemaPath": "remote-schema.graphql",
  "extensions": {
    "endpoints": {
      "Remote GraphQL Endpoint": {
        "url": "http://localhost:8055/graphql",
        "headers": {
          "user-agent": "JS GraphQL"
        },
        "introspect": true
      }
    }
  }
}
```

**Comment by acao** [comment]
@sam-hsbu I think you want this!

```json
{
  "name": "Remote Schema",
  "schema": "http://localhost:8055/graphql",
  "extensions": {
    "endpoints": {
      "Remote GraphQL Endpoint": {
        "url": "http://localhost:8055/graphql",
        "headers": {
          "user-agent": "JS GraphQL"
        },
        "introspect": true
      }
    }
  }
}
```

or if you want to edit both local SDL files and use a remote schema, you should be able to do this do this:

```json
{
  "name": "Remote Schema",
  "schema": ["http://localhost:8055/graphql", "./schema/**/*.{ts,graphql}"],
  ...
}
```

**Comment by sam-hsbu** [comment]
Hello my friend @acao 

I know that IDE like Webstorm can generate automatically a schema from an API endpoint. This schema will help the IDE to auto complete the GraphQL queries, this would be very helpful for me but I use VSCode ! There is no documentation about it or I did not find it after many days of research on Google :(

Do you understand my request ?

Thanks !

**Comment by acao** [comment]
Yes! You can learn how to enable this feature in the readme

**Comment by Vildnex** [comment]
Any update regarding this problem @acao @sam-hsbu? I'm also searching for the same problem and I could not find anything neither on google nor on the readme file. 
Could any of you point me in the right direction, please?

**Comment by koyta** [comment]
No joke, this topic is still rising in people's heads. Nothing in README or the VS Code itself mentions a generation of schema.graphql file. :(

**Comment by acao** [comment]
@koyta the vscode docs point to the LSP readme, as this is a feature used by all IDE users, not just vscode users:

https://github.com/graphql/graphiql/tree/main/packages/graphql-language-service-server#workspace-configuration

> 
> <span id="user-content-custom-graphql-config"><span id="user-content-workspace-configuration" data-react-autofocus="true">
> vscode-graphql.cacheSchemaFileForLookup | false | generate an SDL file based on your graphql-config schema  configuration for schema definition lookup and other features. useful  when your schema config are urls
> -- | -- | --
