### ISSUE TITLE
graphiql + webpack 5 errors

### ISSUE THREAD

**Issue by noelportugal** [graphql/graphiql#2374]
"graphiql": "^1.8.7",
"graphql": "^16.3.0"

After upgrading to webpack 5 (I'm using the latest graphql and graphiql versions) I am getting a lot of the following errors:

`ERROR in ./node_modules/graphiql/esm/components/DocExplorer.js 83:17-23
export 'isType' (imported as 'isType') was not found in 'graphql' (possible exports: default)`

Anyone else running into these issues?

**Comment by acao** [comment]
oof - we aren't testing for graphql@16.3.0 yet my bad, I have [this PR](https://github.com/graphql/graphiql/pull/2208) where we will address this issue

**Comment by noelportugal** [comment]
I solved my issue by changing my `webpackChunkName` to something **other** than  "graphql"
