### ISSUE TITLE
Error: Unable to find any GraphQL type definitions for the following pointers: - schema.graphql

### ISSUE THREAD

**Issue by mgpwilson** [graphql/graphiql#2406]
Hi there, I am following [this tutorial](https://www.typescript-training.com/course/full-stack-typescript) in order to learn GraphQL. The author seems to be using your VSCode extension so I decided to install it myself. However when I open the file with the following code:

```typescript
import { ApolloServerPluginDrainHttpServer } from 'apollo-server-core';
import { ApolloServer, ExpressContext, gql } from 'apollo-server-express';
import * as express from 'express';
import { Server } from 'http';
import Db from './db';

export async function createApolloServer(
  _db: Db,
  httpServer: Server,
  app: express.Application
): Promise<ApolloServer<ExpressContext>> {
  const typeDefs = gql`
    type Query {
      currentUser: User!
      suggestions: [Suggestion!]!
    }
    type User {
      id: String!
      name: String!
      handle: String!
      coverUrl: String!
      avatarUrl: String!
      createdAt: String!
      updatedAt: String!
    }
    type Suggestion {
      name: String!
      handle: String!
      avatarUrl: String!
      reason: String!
    }
  `;
  const server = new ApolloServer({
    typeDefs,
    plugins: [ApolloServerPluginDrainHttpServer({ httpServer })],
  });
  await server.start();
  server.applyMiddleware({ app });
  return server;
}
```

I get the following error from the GraphQL extension: `The GraphQL Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted.`

On opening the GraphQL Language Server output, I see the following error:
```
Error: 
      Unable to find any GraphQL type definitions for the following pointers:
        
          - schema.graphql
          
    at fAe (/Users/matthew.wilson/.vscode/extensions/graphql.vscode-graphql-0.4.4/out/server/index.js:548:5279)
    at fx (/Users/matthew.wilson/.vscode/extensions/graphql.vscode-graphql-0.4.4/out/server/index.js:548:4804)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.Rtt [as loadSchema] (/Users/matthew.wilson/.vscode/extensions/graphql.vscode-graphql-0.4.4/out/server/index.js:552:410)
    at async Zx.getSchema (/Users/matthew.wilson/.vscode/extensions/graphql.vscode-graphql-0.4.4/out/server/index.js:558:18966)
    at async LY.getDiagnostics (/Users/matthew.wilson/.vscode/extensions/graphql.vscode-graphql-0.4.4/out/server/index.js:199:9357)
    at async /Users/matthew.wilson/.vscode/extensions/graphql.vscode-graphql-0.4.4/out/server/index.js:571:2399
    at async Promise.all (index 0)
    at async D1e.handleDidOpenOrSaveNotification (/Users/matthew.wilson/.vscode/extensions/graphql.vscode-graphql-0.4.4/out/server/index.js:571:2342)
    at async /Users/matthew.wilson/.vscode/extensions/graphql.vscode-graphql-0.4.4/out/server/index.js:606:54431
[Error - 2:32:02 PM] Connection to server got closed. Server will not be restarted.
[Info  - 2:32:02 PM] The graphql server has stopped running
``` 

This error repeats each time I reload the developer window. However, the syntax highlighting works.

I am unsure how to fix the issue and my Googling hasn't yielded any results, any help would be appreciated. FYI, I am using GraphQL v15.0.0, please let me know if you need any more information as I'm brand new to this!

EDIT: On further investigation it seems like I need a file called "schema.graphql" to be present, however the tutor didn't have this issue despite not having that file.

**Comment by mgpwilson** [comment]
Nevermind, the edit I made was exactly the issue and is resolved later in the tutorial, apologies!

**Comment by aaabinbin** [comment]
I have the same question. How did you solve this problem?
`Error: 
      Unable to find any GraphQL type definitions for the following pointers:
         - schema.graphql`

**Comment by aaabinbin** [comment]
@mgpwilson Hey bro. I have the same question. How did you solve this problem?
`Error: Unable to find any GraphQL type definitions for the following pointers: - schema.graphql`

**Comment by mgpwilson** [comment]
> @mgpwilson Hey bro. I have the same question. How did you solve this problem? `Error: Unable to find any GraphQL type definitions for the following pointers: - schema.graphql`

Hey @aaabinbin, I created a file called `schema.graphql` in the server src file with the definitions in the gql`` portion of the code.
