### ISSUE TITLE
yarn build --watch is broken

### ISSUE THREAD

**Issue by acao** [graphql/graphiql#2429]
it looks like somewhere along the line, someone broke the `tsc --build --watch` setup we had. `yarn build --watch` no longer works. this breaks the development workflow for the LSP server and other parts of the ecosystem, because the file watcher is no longer. It took me a few hours to realise that this was the issue with developing the LSP server, because as you can see the vscode launch task is now broken

for a long time we've had two scripts, as documented in CONTRIBUTING.md:

- `yarn build` builds the typescript project references. this should be reduced to esm/modern only as we introduce vite
- `yarn build-bundles` builds with vite, esbuild or webpack, with bundlers.

many scripts depend on being able to pass parameters to `tsc --build` such as `tsc --build --watch` or `tsc --build --clean`.

My proposal:

1. `@graphiql/react` should be added to the [list of project references](https://github.com/graphql/graphiql/blob/90ec49affb498ccb9a87505d2d3a82eda650c58d/resources/tsconfig.build.esm.json#L7)
2. the `yarn build-bundles` script should be added to graphiql-react workspace for the vite build. see graphiql or vscode-graphql for an example.
3. the `yarn build` command should work as before, so that the other commands and tooling that depends on it can count on that, so that we can use `yarn build --watch` or `yarn build --clean` again, which is documented in CONTRIBUTING.md. Currently, if a user tried to contribute to the repository, the CONTRIBUTING.md would not reflect this at all!
4. the result would be that the vscode debugger runs properly, and actually watches and rebuilds on changes again!

**Comment by benjie** [comment]
I recommend that you move to `yarn build:watch` / `yarn build:clean` style of commands; these are less likely to break in this manner, but more importantly should you change your build tooling from tsc to an alternative, the commands devs type would not change even if the new tooling expects different flags.

**Comment by acao** [comment]
agreed! this is the more transparent approach.

**Comment by acao** [comment]
I think I can do this as a small PR later today to address this as a transitional solution, and pull it into my current working branch for the LSP server and `vscode-graphql`

big picture wise, we can look at alternative, incremental, cross-monorepo tooling that truly replaces what project references provides. I haven't found anything in vite/rollup or esbuild or other ecosystems to match, but there are promising contenders I keep revisiting! I was hoping to open a discussion about this. we have a PR open to migrate graphiql's bundling to vite that potentially invites this transition itself!

this looks like a promising path away from typescript project references, perhaps:

https://vitejs.dev/guide/dep-pre-bundling.html#automatic-dependency-discovery

Personally I think SWC is the most promising compiler, and vite/rollup the most promising bundler ecosystem, so I would love to look at something like this:

https://github.com/natrim/vite-plugin-swc-only

**Comment by thomasheyenbrock** [comment]
@acao just opened this PR related to this, maybe this helps (if not feel free to adapt or close 🙂 ): https://github.com/graphql/graphiql/pull/2431

**Comment by acao** [comment]
I was the one who broke it 😆
