### ISSUE TITLE
Definition support for operation fields

### ISSUE THREAD

**Issue by tomcharles** [graphql/graphiql#2472]
When writing a query, you should be able to go-to definition on individual fields, but that is not working.

[Here](https://github.com/tomcharles/vscode-graphql-playground) is a demo repo with reproducible config.

> No definition found for `[field name]`

Given this `graphql.config.js`
```
module.exports = {
  schema: "./build/schema.graphql",
};
```

And this `build/schema.graphql`
```
type Query {
  items: [Item]!
}

type Item {
  fieldOne: String!
  fieldTwo: String!
}
```

When writing this query, I'd expect go-to definition on `items` to take me to line 2 of the schema or go-to definition on `fieldOne` or `fieldTwo` to take me to line 6 or 7, respectively, of the schema.

```
query MyQuery {
  items {
    fieldOne
    fieldTwo
  }
}
```

As far as I can tell, the graphql config is correct, which is demonstrated by the fact that code completion and validation is happening.

See this demo below, where you can see code completion working, but go-to definition failing.

https://user-images.githubusercontent.com/3206804/171949633-9b2d0a07-f7fe-419b-8613-006e17fd1c1c.mov

**Comment by acao** [comment]
Was this feature working and not before? As far as I can remember this is on the wishlist

**Comment by acao** [comment]
It could be added [to this file in the LSP server](https://github.com/graphql/graphiql/blob/main/packages/graphql-language-service-server/src/GraphQLLanguageService.ts#L281), one would just need to add another case to the switch statement, and a method, like this

<img width="622" alt="Screenshot 2022-06-04 at 15 00 05" src="https://user-images.githubusercontent.com/1368727/172000495-e7cca867-1964-47a0-9c15-39f1d4c0f22c.png">


perhaps a utility function in `graphql-language service/interface` `getDefinition.ts`. which should eventually contain a generalized, node.js-free function that can be used by the LSP server's language service and `monaco-graphql`. either way, this code will end up being used by `monaco-graphql` when we add definitions support.

if anyone is interested in learning how to add this feature, let me know!

CC @stonexer @zth @orta @

**Comment by stonexer** [comment]
> It could be added [to this file in the LSP server](https://github.com/graphql/graphiql/blob/main/packages/graphql-language-service-server/src/GraphQLLanguageService.ts#L281), one would just need to add another case to the switch statement, and a method, like this:
> 
> <img alt="Screenshot 2022-06-04 at 15 00 05" width="622" src="https://user-images.githubusercontent.com/1368727/172000495-e7cca867-1964-47a0-9c15-39f1d4c0f22c.png">
> 
> perhaps a utility function in `graphql-language service/interface` `getDefinition.ts`. which, as a side note, should eventually contain a generalized, node.js-free function that can be used by the LSP server's language service and `monaco-graphql`. either way, this code will end up being used by `monaco-graphql` when we add definitions support.
> 
> if anyone is interested in learning how to add this feature, let me know!
> 
> CC @stonexer @zth @orta

It looks interesting, I'd like to give a try

**Comment by tomcharles** [comment]
> Was this feature working and not before? As far as I can remember this is on the wishlist

@acao I think you're right, it was never working. For some reason I thought it was, but I believe I was thinking about the Apollo plugin.

**Comment by acao** [comment]
This should be available in the last few vscode-graphql releases now, thanks to @stonexer . Thanks everyone for reporting this!
