### ISSUE TITLE
Unicode icons turns into boxes for some fonts

### ISSUE THREAD

**Issue by golopot** [graphql/graphiql#2480]
When rendered font is Liberation Sans, the Unicode icons for closing a tab turns into boxes:

![image](https://user-images.githubusercontent.com/16285118/172035603-7137e67e-cdec-4315-bfb9-41ca5ac01a4f.png)

**Comment by acao** [comment]
Thanks for reporting! Important to note for impact that Liberation Sans is the default on most Linux OSes outside of Ubuntu

**Comment by thomasheyenbrock** [comment]
This will be resolved with the upcoming design for GraphiQL v2 where we'll use SVG icons instead of unicode characters.

**Comment by thomasheyenbrock** [comment]
`graphiql@2` has now been released and used SVG icons in most places instead of unicode characters. When using the CDN bundles it also ships with custom fonts and doesn't rely on any system fonts, so this issue should be fixed.
