### ISSUE TITLE
Webjars support

### ISSUE THREAD

**Issue by luisobo** [graphql/graphiql#25]
Hi,

I'm trying to embed graphiql in my Play! app. In order to get the dependency in my project the most popular way (for js/css/html) is via [webjars](http://www.webjars.org/) which packages npm modules (also bower packages) into jars to be included in JVM apps. 

The problem is, when trying to deploy the latest version of graphiql to webjars, it fails to read the license with the following message:

> Failed! No valid licenses found. Detected licenses: See LICENSE The acceptable licenses on BinTray are at: https://bintray.com/docs/api/#_footnote_1 License detection first uses the package metadata (e.g. package.json or bower.json) and falls back to looking for a LICENSE, LICENSE.txt, or LICENSE.md file in the master branch of the GitHub repo. Since these methods failed to detect a valid license you will need to work with the upstream project to add discoverable license metadata to a release or to the GitHub repo.

The problem seems to be that the `license` field in `package.json` is set to `See LICENSE`, instead of the name of the license. I really don't know if this is supposed to be like this, but I'm wondering if there is any other way we could specify the license that would make webjars work. 

In order to reproduce the problem:
1. go to http://www.webjars.org/npm, 
2. On the top right cornet click on `Add a new NPM WebJar`
3. Type `graphiql` in the name
4. Select `0.1.1` in the version
5. Click `Deploy!`

Another issue could be that graphiql license is not compatible with WebJars. See full list in [this footnote](https://bintray.com/docs/api/#_footnote_1). I'm not sure about this either.

Thanks for your time.

**Comment by fson** [comment]
I'm not familiar with WebJars, but also `npm` warns about the `license` field:
```
npm WARN package.json graphiql@0.1.1 license should be a valid SPDX license expression
```
For `npm` the solution seems to be using this SPDX expression (according to the [npm docs](https://docs.npmjs.com/files/package.json#license)):
```
{ "license" : "SEE LICENSE IN <filename>" }
```
(in this case, "SEE LICENSE IN LICENSE")

I wonder if that would work for WebJars too?

**Comment by luisobo** [comment]
One way to find out :smiley: https://github.com/graphql/graphiql/pull/26

In any case, what's the name of the license in `LICENSE`?

**Comment by toulouse** [comment]
Wouldn't it be `LICENSE AGREEMENT For GraphiQL software`?

**Comment by fson** [comment]
@luisobo: Thanks for opening the PR!

The license in `LICENSE` is a custom license, see the question and discussion about it on https://github.com/graphql/graphiql/issues/10.

**Comment by luisobo** [comment]
@fson gotcha, so even if we fixed this issue, it wouldn't fly because that license is not one of the [supported licenses by WebJars](https://bintray.com/docs/api/#_footnote_1). I'll add a comment in #10 and see if that changes. Thank you.

**Comment by toulouse** [comment]
Hold on a second, you linked to BinTray's API, which charges for proprietary licenses, but I don't see any specification limiting the WebJar format from packaging nonfree software.

It shouldn't be that difficult to package up the static resources into a WebJar and deploy it to a repository that *isn't* BinTray.

**Comment by luisobo** [comment]
@toulouse the issue with WebJars has two parts, first WebJars no being able to find the license since the package.json file does not comform with the spec (#26 fixes that). second is, yes, the license type. If the license type is a problem and cannot be changed I'm sure I'll find a workaround but I'd rather publish the artifacts to the :v:standard:v: channels to avoid confusion down the road.

**Comment by leebyron** [comment]
I've just pushed a new version of graphiql to npm which includes #10 so it may be parsed mechanically. Does this solve the WebJars issue?

**Comment by luisobo** [comment]
@leebyron I'm afraid not. Seems that the real issue is that the LICENSE is not compatible, unfortunately. If there are no plans to change that, this can be closed.

Thanks

**Comment by leebyron** [comment]
Alright, will do. Sorry about the trouble. Hopefully WebJars can consider custom licenses in the future. In the meantime I've submitted a PR to jsdelivr (https://github.com/jsdelivr/jsdelivr/pull/6666) to host these files across common CDNs, hopefully that may suffice as an alternative to WebJars.
