### ISSUE TITLE
onSchemaChange callback not triggered

### ISSUE THREAD

**Issue by toxsick** [graphql/graphiql#2503]
Hey guys,

not sure if I'm missing something, but as I understand it the callback fn **onSchemaChange** should be called with the new schema, after the introspection query:

https://github.com/graphql/graphiql/blob/main/packages/graphiql/src/components/GraphiQL.tsx#L280

For me this seems to not be the case with `"graphiql": "1.9.7"`. Further I can not find the callback being triggered anywhere in the code.

This callback seems seems to have been added in #2190 and at that time the callback was also triggered:

https://github.com/n1ru4l/graphiql/blob/a03ef2db62b557c4272e00ceb38840e4494707a2/packages/graphiql/src/components/GraphiQL.tsx#L1127

Am I missing something?

Thanks and regards

**Comment by thomasheyenbrock** [comment]
Hey @toxsick 👋 thanks for reporting this, and sorry for the delay in picking this up! This is definitely a regression that came in with the recent refactors, I'll fix this today.

**Comment by thomasheyenbrock** [comment]
The fix was just published with `graphiql@1.9.11`
