### ISSUE TITLE
Header edit/delete buttons are inaccessible for long headers

### ISSUE THREAD

**Issue by robertpeacock22** [graphql/graphiql#256]
When you add a very long header such as an auth token, the masked token does not wrap. As a result it pushes the edit and delete buttons far off the right side of the page.

In Firefox I can access the buttons by zooming out extremely far.
![screen shot 2016-12-16 at 11 26 11 am](https://cloud.githubusercontent.com/assets/608951/21270156/5cb08962-c383-11e6-8cb6-612b80032bb1.png)

In Chrome I'm not even able to zoom out far enough to bring the buttons on screen.

Expected:
Either the position of the buttons should be moved (e.g. just under the header name), or the masked token should wrap lines, leaving space at the right for the buttons.

**Comment by wincent** [comment]
@robertpeacock22: That looks like it might be a screenshot from https://github.com/OlegIlyenko/graphiql-workspace or similar. Should this be filed against that project instead?

**Comment by robertpeacock22** [comment]
You're absolutely correct. My apologies.
