### ISSUE TITLE
Feature: Go to definition support for union

### ISSUE THREAD

**Issue by ba-nitesh** [graphql/graphiql#2575]
Wonderful work team! This really helps during the development process! Thanks a lot.

Currently, go-to definition support is not there. It would be great if we can support the go-to definition for a union.

**Comment by thomasheyenbrock** [comment]
Hey and thanks @ba-nitesh 👋 in our test schema I can successfully
- Cmd-click a field that returns a union
- Click the union type in the mouseover tooltip
- Cmd-Click a union member type in an inline fragment

Can you specify which case exactly is not working for you? Can you also tell us which GraphiQL version you are seeing this issue in?

https://user-images.githubusercontent.com/22288634/179691052-4a75400e-20c3-409e-ad57-57551c3fbcca.mp4

**Comment by ba-nitesh** [comment]
To clarify this repository getting used by vs-code extension [GraphQl](https://marketplace.visualstudio.com/items?itemName=GraphQL.vscode-graphql)  right?

**Comment by ba-nitesh** [comment]
No worry, Thanks for your response. Let me know if I can help you guys.

**Comment by acao** [comment]
@ba-nitesh thank you! so are you asking for go-to-definition support for unions in the LSP server for vscode or another IDE plugin?

Currently we only support [these cases](https://github.com/graphql/graphiql/blob/65df5b814bc7a46a43c264fcadff4e4963d908c3/packages/graphql-language-service-server/src/GraphQLLanguageService.ts#L282) for definition lookup, however this is where one would want to start to add this behavior!

**Comment by ba-nitesh** [comment]
Right, your example is completely conveying what I am trying to say. Thanks!

**Comment by acao** [comment]
fabulous! we can add that

**Comment by ba-nitesh** [comment]
You are great! When are we planning to add this?

**Comment by acao** [comment]
@ba-nitesh sorry I cannot say, I've been quite busy with work!

**Comment by AaronMoat** [comment]
https://github.com/graphql/graphiql/pull/3150

I believe this PR should resolve it! Raised the PR before realising there was an issue for it already. 

That being said, pretty new to this codebase, so might be missing something with the approach!
