### ISSUE TITLE
Feature: Typescript generic argument on graphql template function breaks highlighting

### ISSUE THREAD

**Issue by Mike-Logit** [graphql/graphiql#2579]
I noticed this (press play to view the GIF):

![graphql with generic typescript](https://user-images.githubusercontent.com/41903446/180212616-d3b7879c-5186-47f5-9787-18de546eb890.gif)

As you can see, highlighting is not supported when using a generic argument to add Typescript features. I can use `#graphql` to fix this but sometimes prettier will format it onto a new line and break it which isn't ideal.

I'd prefer to just have Typescript support using the generic argument if possible.

Thank you.

**Comment by acao** [comment]
@Mike-Logit we just added the regex for `graphql(` so this must be missing from that. Try this for now: 

```ts
graphql<MyType>` 
  query myQuery{
  
  }
`
```

**Comment by acao** [comment]
This is where the fix would be implemented
https://github.com/graphql/graphiql/blob/b5feda28c61848d62df2615d85fe417e5e355298/packages/vscode-graphql/grammars/graphql.js.json#L19

**Comment by Mike-Logit** [comment]
> @Mike-Logit Try this for now, which we know is working:
> 
> ```ts
> graphql<MyType>` 
>   query myQuery{
>   
>   }
> `
> ```

Thanks. This doesn't work for me because I believe the graphql function I'm using isn't typed to support that syntax. I'm using Gatsby.js so it might not be the same type of graphql function you're used to seeing:

> Argument of type 'TemplateStringsArray' is not assignable to parameter of type 'string'.ts(234

**Comment by Mike-Logit** [comment]
However, I solved it another way by splitting the query string from where it was being passed into the function so prettier wouldn't think my line was too long and move the `#graphql` part to another line and break the highlighting.

**Comment by DennisRosen** [comment]
Any update on this? I dislike having to refactor my code just to get the syntax highlighting to work.

**Comment by acao** [comment]
@DennisRosen @Mike-Logit please re-open if this is still an issue.

 we have [snapshot tests confirming this case](https://github.com/graphql/graphiql/blob/04b44fab2b74da6de12b12c84be50ab666991467/packages/vscode-graphql-syntax/tests/__fixtures__/test.ts#L34) now. enjoy!
