### ISSUE TITLE
Graphiql variables usage

### ISSUE THREAD

**Issue by sudheerj** [graphql/graphiql#260]
I tried to apply JSON string as variable for the but it fails with an error as below

![image](https://cloud.githubusercontent.com/assets/3127317/21470707/15ffa422-cad0-11e6-9896-fe69df1a18c8.png)

The schema and model are defined as follows

```
let RootQuery = new GraphQLObjectType({
  name: 'Query',      //Return this type of object
  fields: () => ({
    accounts: AccountQueries.accounts,
    ibx: IBXQueries.IBXCode,
    ibxes: IBXQueries.ibxes
  })
});

export default {
  accounts: {
    type: new GraphQLList(AccountType),
    args: {
      skip: {
        type: GraphQLInt
      },
      limit:{
        type: GraphQLInt
      },
      sort_field: {
        type: GraphQLString
      },
      sort_order:{
        type: GraphQLString
      },
      filter:{
        type: GraphQLString
      }
    },
    resolve: Account.getListOfAccounts
  }
```

**Comment by asiandrummer** [comment]
Do you mind pasting the URL address from above screen? I'm suspecting there's an URL parameter named "operationName" or something similar. Removing it should work if that's the case.

**Comment by sudheerj** [comment]
I didn't find any parameter with "operationName"

> 
http://localhost:3000/graphql?query=query%20RootQuery(%24filter%3A%20String)%20%7B%0A%20%20accounts(skip%3A%200%2C%20limit%3A%2013%2C%20sort_field%3A%20%22account_number%22%2C%20sort_order%3A%20%22descending%22%2C%20filter%3A%20%24filter)%20%7B%0A%20%20%20%20account_number%0A%20%20%20%20account_type_code%0A%20%20%20%20parent_ucm_id%0A%20%20%20%20account_status%0A%20%20%20%20streamlined_flag%0A%20%20%20%20account_name%0A%20%20%20%20ibxes%20%7B%0A%20%20%20%20%20%20ibx_code%0A%20%20%20%20%7D%0A%20%20%20%20region%0A%20%20%7D%0A%7D%0A&variables=%7B%0A%20%20%22filter%22%3A%20%7B%0A%20%20%20%20%22region%22%3A%20%22APAC%22%2C%0A%20%20%20%20%22code%22%3A%20%7B%22in%22%3A%20%5B%20%22HK1%22%2C%20%22SG1%22%20%5D%7D%2C%0A%20%20%20%20%22account_number%22%3A%20%7B%22nin%22%3A%20%5B%20%221%22%20%5D%7D%0A%20%7D%0A%7D

**Comment by leebyron** [comment]
The error "Must provide an operation" results when your server detects a request that does not contain a `query` within it. I suspect you might get similar errors even for simpler queries, the issue here is likely how you have configured graphiql and your graphql server, it may not be getting a query body - I suggest investigating the traffic over HTTP to your server and ensuring it appears as you expect.
