### ISSUE TITLE
A few small improvements for the key bindings modal

### ISSUE THREAD

**Issue by acao** [graphql/graphiql#2604]
We could add a little footnote on the keybindings dialog if you want that contains a little link to these docs, keyed by `prop.keyMap`:

https://codemirror.net/5/demo/sublime.html
https://codemirror.net/5/demo/vim.html
https://codemirror.net/5/demo/vim.html

we should also add docs for this, or backport a way to programatically dynamically (and thus optionally ofc) import the additional vim and emacs modes

also, just noticed i was completely wrong about that vim PR! this does have insert mode already, i forgot, this should be good to say we already have vim support. i will correct myself there.

**Comment by thomasheyenbrock** [comment]
I added this to the short key dialog in #2601. Regarding dynamically importing the CM keymaps, there is https://github.com/graphql/graphiql/issues/2583, so I'm closing this issue as half completed and half duplicate 😉
