### ISSUE TITLE
JSON object as String in query variables

### ISSUE THREAD

**Issue by sudheerj** [graphql/graphiql#262]
Can you please guide on how to pass below JSON object as String

> {
>   "filter": {
>     "region": "APAC",
>     "code": {"in": [ "HK1", "SG1" ]},
>     "account_number": {"nin": [ "1" ]}
>   }
> }

**Comment by asiandrummer** [comment]
Hey @sudheerj! I'm not really sure what you mean by passing JSON object as String - are you trying to execute a query with above JSON as variables?

**Comment by sudheerj** [comment]
Exactly.I want to pass above JSON object as String query variable.It contains many operators and fields.The above expression is a direct Mongoose schema that works on DB.I don't want to pass it as InputObject.

**Comment by asiandrummer** [comment]
Let me try answering in a couple phases:

1. I guess the easiest way is, given that the JSON is simple enough (which is probably not what you want), if you declare the type of `$filter` argument as `GraphQLString`, you could pass it in as a `JSON.stringify`ed string from Variable Editor I presume:
```
{
  "filter": "{ "region: "APAC", ... }"
}
```
If what you wanted is to pass an object and convert it into a string later, it'll be difficult to achieve that as `GraphiQL` does not (and probably should not) attempt to process the query/variables strings; instead it merely passes the provided strings to GraphQL executor (in this case `graphql-js`). You might be able to tweak the fetcher function to detect certain GraphQL variable keys and process into the string format there, but it feels too much of a hack.

2. I'd advise to create a `GraphQLInputObject` type for this:
```
new GraphQLInputObjectType({
  name: 'filter',
  fields: {
    "region": { type: GraphQLString },
    "code": { type: new GraphQLInputObjectType({ ... }) },
    "account_number": { type: new GraphQLInputObjectType({ ... }) },
  }
});
```
FYI, you may already know this, but I did a quick google search and came up with a couple of example adapter libraries with GraphQL and Mongoose DB (e.g. [graffiti-graphql](https://github.com/RisingStack/graffiti-mongoose)), as well as some posts on what other people did to connect the two.

For the last mark, this question is probably more suited for [`graphql-js`](https://github.com/graphql/graphql-js/) repository (I'm making an educated guess from looking at your other questions and the fact that you may be using `graphql-js` reference implementation for your application)

**Comment by sudheerj** [comment]
I should pass JSON object only because it contains mongoose operators which executed directly.You can observe $gt,$gte,$in,$nin etc so I'am expecting them as String instead on Input object.

Do I need to pass filter args for Root query here? Other inputs will be passed to Model object

`let RootQuery = new GraphQLObjectType({
  name: 'Query',      //Return this type of object
  fields: () => ({
    accounts: AccountQueries.accounts
    
  })
});`

**Comment by leebyron** [comment]
@asiandrummer's suggestion is a good one. You simply provide a string for your variable which happens to appear as JSON:

```js
{
  "filter": "{ \"region\": \"APAC\", ... }"
}
```

Within your application, you can first call JSON.parse() on the string variable to get your unstructured JSON object within your server.

**Comment by nikordaris** [comment]
@leebyron the suggestion to escape quotes in a string is very cumbersome for large data and not a reasonable solution for this in my opinion. Given there is a JSONString input type, GraphiQL should support transforming the Object variable to JSONString. Defining custom Input Types is also not possible for my situation since this is for a mutation that needs to support multiple types and interfaces are not supported for input types. My work around for now is to do the hacky modification of my fetcher. This still has the problem of GraphiQL highlighting my variables saying, "Expected value of type JSONString". But I guess I can just ignore this since this is only used by our sys admins.

For anyone else facing this same situation this is my fetcher:

```
fetcher = (params) => {
    let {variables = {}} = params;
    variables = Object.keys(variables).reduce((result, key) => {
      if (hasIn(variables[key], '__stringify')) {
        return {...result, [key]: JSON.stringify(variables[key].__stringify)};
      }
      return {...result, [key]: variables[key]};
    }, {});
    return fetch('/graph', {
      method: 'POST',
      headers: new Headers({
          'Content-Type': 'application/json'
      }),
      body: JSON.stringify({...params, variables})
    }).then((response) => {
      return response.json();
    });
  }
```

I used a __stringify wrapper to avoid stringifying unintended objects.

**Comment by leebyron** [comment]
@nikordaris, JSONString is not part of the standard set of scalars and GraphiQL only supports the standard set, that's a custom scalar type added by your server. If you're sending complex unstructured JSON data as a string - I suggest calling JSON.stringify on the client before sending the query

**Comment by acronoah** [comment]
I have the same issue.  I can submit the JSON just fine, but graphIQL complains that the type is supposed to be Json.

**Comment by robross0606** [comment]
I'm still seeing this problem as of today:
![image](https://user-images.githubusercontent.com/2965467/166731761-fcecdbe3-3b0f-459c-bac0-dd6897373f32.png)

**Comment by acao** [comment]
In terms of using custom scalars by URL, we have support now for `specifiedBy` directive!

https://github.com/graphql/graphql-js/blob/5ccf579a3bfd98243700ef541a6939af7a6f545c/src/utilities/__tests__/buildClientSchema-test.ts#L566

just a matter of implementing the result in the client validation in `codemirror-graphql` and/or `monaco-graphql`

**Comment by nikolov9996** [comment]
<img width="519" alt="Screenshot 2023-09-15 at 10 53 00" src="https://github.com/graphql/graphiql/assets/92812302/9d1a5b47-86c9-4a76-a062-65672d0596ed">

This worked!
