### ISSUE TITLE
style regression in Docs Explorer after #2601

### ISSUE THREAD

**Issue by jonathanawesome** [graphql/graphiql#2629]
It looks like [this change to the root css file](https://github.com/graphql/graphiql/blob/68212e81252f4fd6016a44dc371760b3287eb71a/packages/graphiql-react/src/style/root.css#L114) in `graphiql/react` has some unintended consequences: 

<img width="400" alt="Screen Shot 2022-08-02 at 9 54 50 AM" src="https://user-images.githubusercontent.com/963528/182405385-ea546bfa-6e8c-437a-b093-a46a18ff6d7b.png">

**Comment by thomasheyenbrock** [comment]
Good catch thanks for spotting, will fix!
