### ISSUE TITLE
Broken release 0.8.0

### ISSUE THREAD

**Issue by kumarharsh** [graphql/graphiql#263]
Hello, I just updated my graphiql to 0.8.0 (latest release as of today), and everything broke - I mean the UI is completely messed up:
![image](https://cloud.githubusercontent.com/assets/760112/21518143/46904f10-cd0a-11e6-971a-5ff7140c8e80.png)

I have checked this in the latest opera, latest edge and latest firefox, all with the same results.
It seems like [this commit](https://github.com/graphql/graphiql/commit/39086a931359abfb3d185151d71f0b355e25bf50) replaced `display: flex` with vendor-prefixed flex alternatives, but almost all browsers have stopped supporting the vendor prefixes for flex (even Chrome dropped support recently). I also see that a more recent commit added auto-prefixr to graphiql but that version has not yet been published to npm yet. Can it be published soon?

**Comment by wincent** [comment]
Yep, this was reported earlier in #250, and fixed in #252. We'll cut a release soon to get this out there.

**Comment by asiandrummer** [comment]
Let me actually go ahead and cut it now - thanks for the report!
