### ISSUE TITLE
Publish codemirror-graphiql@^2.0.0.next.2

### ISSUE THREAD

**Issue by tomfrew** [graphql/graphiql#2667]
Trying to test out the latest `@graphiql/react` changes; When installing with `@graphiql/react@next`  I get an npm error of 
```No matching version found for codemirror-graphql@^2.0.0-next.2```

It looks like all the packages published `X-next.2` versions after their versions where bumped except the `codemirror-graphql` package which only has a `2.0.0-next.1` version

**Comment by acao** [comment]
@tomfrew thank you, I will get to this in a bit!

**Comment by thomasheyenbrock** [comment]
This version has been published (thanks @acao). In the meantime we also released `codemirror-graphql@2.0.0` which powers `graphiql@2.0.0` and the latest `@graphiql/react` version, so we recomment just upgrading to that :v:
