### ISSUE TITLE
Toolbar buttons reloading page

### ISSUE THREAD

**Issue by Interlogy** [graphql/graphiql#2677]
As a user i want to use the toolbar buttons without a site reload.

The graphiql cdn example index.html was added to my  jsf application. All toolbar buttons realoading the whole site. 

In browser i added to the toolbar buttons the attribute type=„button“ which has worked perfectly. 

this could be added in graphiql.min.js, since this is the expected behavior.

**Comment by thomasheyenbrock** [comment]
This should be fixed with `graphiql@1.11.5`. If you use the CDN example (i.e. fetching `https://unpkg.com/graphiql/graphiql.min.js`) it should automatically be fixed.

**Comment by xLevision** [comment]
Same issue for the explorer plugin, all checkboxes i tick reloading the site. Maybe similar issue?
