### ISSUE TITLE
[v2] initialHeaders not loading

### ISSUE THREAD

**Issue by Xef1** [graphql/graphiql#2698]
Setting headers in the Headers tab and then reloading the window crashes the page
![image](https://user-images.githubusercontent.com/7945232/186565751-bb43fb11-553c-4d27-80b3-779f7a0af6ab.png)

![image](https://user-images.githubusercontent.com/7945232/186565916-2a730369-4d40-437e-886c-2697d6866dbb.png)

![image](https://user-images.githubusercontent.com/7945232/186565985-3695f93c-73a5-4ebc-ad39-b5d9aeca5cb1.png)

This was previously working on the last version. The only way around this for us at the moment is to clear the Local Storage of the browser for graphiql.

**Comment by acao** [comment]
@Xef1 hey there! thanks for reporting this. for the last version as in 1.x? or did you mean the last graphiql@2 next version? does clearing the local storage seem to fix the issue permanently?

perhaps this is a 1 to 2 local storage migration issue that we somehow didn't catch. looks like we need to get source maps working, but it appears that `isHeadersEditorEnabled` is used before it's declared?

@thomasheyenbrock may have more context

**Comment by acao** [comment]
I am having so much trouble re-creating this bug!

**attention bug reporters:** if you have not cleared your local storage first before getting this bug, can you share it? redacting headers where necessary of course? this will allow us to more easily reproduce the bug hopefully

**Comment by Xef1** [comment]
Hey @acao it was working on 1.x
Clearing the local storage needs to be done for each refresh for the page to load

Looks like isHeadersEditorEnabled might be undefined for the incoming props.


Also looks like the bug only happens if **nothing** is in the **Variables** tab but something is in the Headers tab. Putting an empty object in variables works quite well for us at the moment
![image](https://user-images.githubusercontent.com/7945232/186600192-57961ce9-3e6e-4611-bb85-3e9878670eaf.png)

**Comment by acao** [comment]
this was auto-closed by a PR merge, release inbound...
