### ISSUE TITLE
Headers are not persisted on local storage

### ISSUE THREAD

**Issue by patrick91** [graphql/graphiql#2702]
Just doing a quick test after doing #2700, and it looks like we aren't storing (or maybe we aren't fetching) the headers from local storage

https://user-images.githubusercontent.com/667029/186611438-7d58ccd9-b5cb-41e6-b1ad-1bf187eda754.mp4

**Comment by patrick91** [comment]
@acao feel free to close this if you can't reproduce, it doesn't seem to happen on my end anymore 🤷‍♂️

**Comment by thomasheyenbrock** [comment]
@patrick91 did you pass the `shouldPersistHeaders` prop to the `GraphiQL` component? By default header values are not persisted, this is an opt-in behavior via that boolean prop.

**Comment by patrick91** [comment]
I think that might have been it, is there a particular reason this is not enabled by default? (I'll close the issue anyway)

**Comment by thomasheyenbrock** [comment]
As far as I know it's a security measure as this might store sensible auth tokens or stuff like that in localStorage (correct me if I'm wrong @acao)
