### ISSUE TITLE
Make GraphiQL only clear its own items from local storage

### ISSUE THREAD

**Issue by elias-pap** [graphql/graphiql#2754]
In the new Settings dialog, [all local storage items are deleted](https://github.com/graphql/graphiql/blob/main/packages/graphiql/src/components/GraphiQL.tsx#L796) when Clear Data button is pressed.

<img width="523" alt="Screenshot 2022-09-07 at 10 16 47" src="https://user-images.githubusercontent.com/18152197/188814321-db082f80-435a-4b27-bb07-bfc6cb8256fe.png">

When embedding GraphiQL in another application, this can be a problem since it also clears local storage data that the application has set. Would it be better if GraphiQL only cleared its own items ? A convention could be to only delete items that start with `graphiql:`.

**Comment by thomasheyenbrock** [comment]
Hey @elias-pap 👋 thanks for opening this issue! I had this in mind but apparently forgot about it again while working on v2 🙈 We should of course only remove the things related to GraphiQL and nothing else.

**Comment by thomasheyenbrock** [comment]
The fix for this has been published in `graphiql@2.0.6`, `@graphiql/react@0.13.0` and `@graphiql/toolkit@0.7.3`

**Comment by elias-pap** [comment]
Thanks for the speedy fix and release !
