### ISSUE TITLE
Use GET method instead of POST method when sending query

### ISSUE THREAD

**Issue by rr-jung-chang** [graphql/graphiql#2766]
Sorry for duplicate if this issue has already been brought up.  Can we add support to enable GraphiQL to send request via GET method?  Most GraphQL server implementations support both GET and POST.   Our GraphiQL is using POST by default.  Would be great to use GET.

**Comment by acao** [comment]
@jonathanawesome indeed, I was going to suggest the same thing. I was thinking that `createGraphiQLFetcher()` can accept a `enableQueryGET` boolean, ala `enableMultipartFetcher` option

**Comment by JankOops** [comment]
@jonathanawesome @acao hi i was just struggling to get this working. i'm trying to make a GET request with the query, however it just returns the graphiql UI. is there a way i can make that request without using a fetcher? i have a restriction meaning i can only specify a URL unfortunately :/ any help would be greatly appreciated! thanks :D

**Comment by thomasheyenbrock** [comment]
@JankOops if you don't control the GraphiQL implementation (i.e. if you use GraphiQL provided by a third-party API), it's not possible to configure sending GET requests through the UI. I also think that is the correct way. If the API does not support GET requests for whatever reason, it makes little sense that GraphiQL would allow sending that request.

Looking at the draft for the [GraphQL over HTTP spec](https://github.com/graphql/graphql-over-http/blob/main/spec/GraphQLOverHTTP.md#request), it also only required support for POST and marks support for GET as optional.
