### ISSUE TITLE
Schema is not updated after authorization headers is added

### ISSUE THREAD

**Issue by pitgrap** [graphql/graphiql#2771]
Our GraphiQL endpoint needs an "Authorization" header.

If I add it manually to the Headers tab, it works for the query. But of course I want to use the "Documentation Explorer". But this shows only a "Error fetching schema" message. Hitting the "Re-fetch GraphQL schema" is using the header too (I can see request with a 200 response in the network tab) , but the schema is not updated and the Docs still show the same error message.
Using the search suggestions/autocomplete is working, but clicking on a suggestion still shows the error message.
Clearing the storage doesn't change it too.

Reloading the page in the browser removes the Header, while the query and the variables are kept.  (Maybe a different bug)

GraphiQL version: 2.0.4

**Comment by thomasheyenbrock** [comment]
Hey @pitgrap 👋 this sounds indeed like it should be fixed with #2653. Can you check if you still see the problem in `graphiql@2.0.8`?

**Comment by thomasheyenbrock** [comment]
> Reloading the page in the browser removes the Header

By default headers are not persisted as a security measure (they might contain sensitive tokens). There is a prop called `shouldPersistHeaders` that toggles this behavior, are you using this prop?

**Comment by pitgrap** [comment]
Hi @thomasheyenbrock , we're using graphiql provided by stellate.co. So they need to update it and I cannot say, if it is possible to change the property. I will check it and will also try to test it locally.

**Comment by thomasheyenbrock** [comment]
Ah, good that I work at Stellate 😜 will see that we bump the version in our next release!

**Comment by acao** [comment]
@thomasheyenbrock perhaps this would be a good candidate for a new user definable setting? that way, other frameworks can use the safer option by default, and users can choose this riskier opt in

it seems excessive, but once we reported our first CVE that would have allowed this data to be exfiltrated by non-permissioned phishing attacks in some cases, we had to keep it this way as part of our CVE resolution that we worked on with Cure53, and it protected against _another_ CVE that allowed users to exfiltrate this data if the option was enabled 🥵

**Comment by pitgrap** [comment]
I think `shouldPersistHeaders` should be a user definable setting. So stellate can keep it disabled by default, but I can enable it in my browser.

**Comment by acao** [comment]
@thomasheyenbrock in the user settings dialog! the one we use for light/dark toggle

**Comment by thomasheyenbrock** [comment]
Ah gotcha! Very interesting proposal, worth exploring 👍

**Comment by pitgrap** [comment]
Just retestet with 2.0.8 and the problem in this ticket has been fixed. -> Closing.
For the idea of a user definable setting for persisted headers you should create a new issue.

**Comment by thomasheyenbrock** [comment]
We also just fixed this at Stellate, we're now also using GraphiQL 2.0.8 👌 

I opened a follow-up issue about the user-facing setting: https://github.com/graphql/graphiql/issues/2793
