### ISSUE TITLE
[vscode-graphql-syntax] description comments are incorrectly highlighted

### ISSUE THREAD

**Issue by mpieczaba** [graphql/graphiql#2776]
### Description

In schema files, Markdown blocks / field descriptions seem to have incorrectly highlighted syntax. 
Neither single-quoted nor triple-quoted blocks feature a properly highlighted Markdown. Moreover, the color may be misleading as it is the same one that is used for the `#` comments.

This bug is really annoying so I will do my best to help you fix this issue.

Below you can find a simple reproduction / code example when this bug occurs.

### Example
![image](https://user-images.githubusercontent.com/55853803/192104802-90dffa3e-1cce-4a2f-a067-e97907ba9652.png)

### My setup

```
GraphQL.vscode-graphql v0.7.5
GraphQL.vscode-graphql-syntax v1.0.4
```

**Comment by acao** [comment]
@mpieczaba is this with codeblocks like these?
```md
 ````graphql 
 {
 
 } 
 ````
 ```

**Comment by mpieczaba** [comment]
> @mpieczaba is this with codeblocks like these?

Well, the issue name might not be the best choice. By `Markdown blocks` I mean these sections of the schema between `"` quotes. I call them `Markdown` as many tools like GraphiQL or Insomnia parse them as a Markdown text.

A small example: 
In my schema file I have defined the `mimeType` field as follows:
```graphql
"File [mime type](https://www.iana.org/assignments/media-types/media-types.xhtml)"
mimeType: String!
```
Then in Insomnia it results in following field description (where `mime type` is a clickable link):
![image](https://user-images.githubusercontent.com/55853803/192107128-4066b0be-dd14-4647-861f-a32b450142cd.png)

But if you are asking if this bug occurs in both `.graphql` files and Markdown code blocks, my answer is `it does`.

**Comment by mpieczaba** [comment]
**Update**: 
Thanks to **safety_jon#5076** we concluded that the bug occurs only with some themes from the `Community Material Theme` extension. I would suggest keeping the issue open until we find the fix and share it here in the comments with others.

**Comment by acao** [comment]
ohh i see. yes this has been reported before

**Comment by FrankySnow** [comment]
I had the same issue with the [Nord theme](https://marketplace.visualstudio.com/items?itemName=arcticicestudio.nord-visual-studio-code) (I'm not using the Community Material Theme) :

![image](https://user-images.githubusercontent.com/22062145/192386700-f7ab6ad7-b7da-4e3f-b262-b3347954ceb8.png)

I fixed it by using the [scope inspector](https://code.visualstudio.com/docs/getstarted/themes#_editor-semantic-highlighting) and following the [customization guide](https://www.nordtheme.com/docs/ports/visual-studio-code/customization) :
```json
  "editor.tokenColorCustomizations": {
    "[Nord]": {
      "textMateRules": [
        {
          "scope": "punctuation.whitespace.comment.leading.graphql",
          "settings": {
            "foreground": "#616E88"
          }
        }
      ]
    }
  },
```
but this is a hack, and I don't know how to generalize this at the theme level.

**Comment by acao** [comment]
@safetyjon as a follow-up, we should close other duplicate bugs and reference them back to the explanation/resolution

**Comment by jonathanawesome** [comment]
@acao thank you for the reminder! I did a search and can't find duplicates for this one, so I'll add my notes from Discord here and close.

Dear future reader,
This issue isn't a bug, it's a symptom of certain VSCode themes' implementation of token scopes (both `Community Material Themes` and `Nord Theme` have been identified with this issue, but there are likely more in the wild).

Here's a screenshot of a working theme where you'll see the `foreground` token is `comment`:
<img width="543" alt="Screen Shot 2022-09-24 at 12 33 05 PM" src="https://user-images.githubusercontent.com/963528/194730819-7a16a514-98bb-4978-b06b-fce74c786e87.png">

And here's a non-working theme where the `foreground` token is `punctuation`:
<img width="510" alt="Screen Shot 2022-09-24 at 12 32 27 PM" src="https://user-images.githubusercontent.com/963528/194730851-88e908cb-8122-40f5-ab2c-bf5aef7a75b4.png">

To remedy in your local install, follow @FrankySnow's comments above to set a tighter scope for the offending token. Even better, open a pull request at your theme's repository!
