### ISSUE TITLE
Cannot read properties of undefined (reading 'split')

### ISSUE THREAD

**Issue by simPod** [graphql/graphiql#2779]
I'm trying to setup graphiql v2

```tsx
import { createGraphiQLFetcher } from '@graphiql/toolkit';
import { GraphiQL } from 'graphiql';

const fetcher = createGraphiQLFetcher({ url: 'https://my.endpoint' });

function MyComponent() {
  return (
    <GraphiQL fetcher={fetcher} />
  );
}
```

I have this simple code. It compiles and I can see the graphiql component rendered.

However, when I enter any query and Execute query it, it gives me this

<img width="1025" alt="image" src="https://user-images.githubusercontent.com/327717/192875546-232d856e-df90-4319-a385-8e8d8bf632ac.png">

```
{
  "errors": [
    {
      "message": "Cannot read properties of undefined (reading 'split')",
      "stack": "TypeError: Cannot read properties of undefined (reading 'split')\n    at splitLinesAuto (https://localhost/webpack-dev-server/dist/vendors-_yarn___virtual___graphiql-react-virtual-b20b6f5284_0_cache_graphiql-react-npm-0_13_2-4d8b7d.js:776:21)\n    at Object.splitLines (https://localhost/webpack-dev-server/dist/vendors-_yarn___virtual___graphiql-react-virtual-b20b6f5284_0_cache_graphiql-react-npm-0_13_2-4d8b7d.js:7167:16)\n    at Object.<anonymous> (https://localhost/webpack-dev-server/dist/vendors-_yarn___virtual___graphiql-react-virtual-b20b6f5284_0_cache_graphiql-react-npm-0_13_2-4d8b7d.js:6698:22)\n    at Object.setValue (https://localhost/webpack-dev-server/dist/vendors-_yarn___virtual___graphiql-react-virtual-b20b6f5284_0_cache_graphiql-react-npm-0_13_2-4d8b7d.js:4482:20)\n    at CodeMirror2.setValue (https://localhost/webpack-dev-server/dist/vendors-_yarn___virtual___graphiql-react-virtual-b20b6f5284_0_cache_graphiql-react-npm-0_13_2-4d8b7d.js:11101:27)\n    at setResponse (https://localhost/webpack-dev-server/dist/App.js:19870:22)\n    at handleResponse (https://localhost/webpack-dev-server/dist/App.js:19964:11)\n    at https://localhost/webpack-dev-server/dist/App.js:20012:9"
    }
  ]
}
```

it's kind of impossible to debug for me, the stack trace is not very helpful to target the issue.

**Comment by thomasheyenbrock** [comment]
Hey @simPod 👋 thanks for reporting this issue! At first glance this error seems to originate from CodeMirror (the editor used in GraphiQL) when trying to set the value of the response editor. Can you please check the following:
- Does clicking the execution button actually send a request to your API?
- If yes, can you share the response you get back from that request?

**Comment by simPod** [comment]
@thomasheyenbrock 👋🏾. No. no requests are issued at all.

**Comment by jonathanawesome** [comment]
@simPod what happens when you plug in a [different endpoint](https://api.spacex.land/graphql)?

**Comment by simPod** [comment]
@jonathanawesome I thought it might be maybe something in my schema but graphiql does not issue an introspection query so e.g. `https://api.spacex.land/graphql` has no effect either.

**Comment by acao** [comment]
considering webpack is being used to generate the build here, we may want to try to reproduce this in the `examples/graphiql-webpack`. our current webpack bundle for the cdn build does not recreate the scenario of consuming the library as an installed module, but that example can help us

**Comment by simPod** [comment]
Seems I reproduced it here

https://codesandbox.io/s/festive-borg-jpkmev?file=/src/index.tsx

<img width="1416" alt="image" src="https://user-images.githubusercontent.com/327717/193446740-936e4894-c949-4380-8ea7-a537786f2a7e.png">

**Comment by jonathanawesome** [comment]
Couple of things there 👆.

First, you need to upgrade the [GraphQL dependency](https://github.com/graphql/graphiql/blob/993d7e414a62472250570c0af4a0760c5638c2d4/packages/graphiql/package.json#L60).

Second, your fetcher setup is incorrect. [Here are the docs](https://github.com/graphql/graphiql/blob/main/packages/graphiql-toolkit/docs/create-fetcher.md).

Should be:
```
const graphQLFetcher = createGraphiQLFetcher({
    url: URL
  });
  ```

[Working sandbox](https://codesandbox.io/s/green-monad-tflrh2?file=/src/index.tsx)

**Comment by simPod** [comment]
Omg! Years ago, when I implemented graphiql v1 it had no types so there was `declare module 'graphiql';` somewhere in my project. That efficiently disabled typescript on v2 so did not notice. Thanks!

**Comment by emmafull** [comment]
Hi I'm hitting the same error `Cannot read properties of undefined (reading 'split')` and receiving `No GraphQL schema available`. 

[Here is a sandbox](https://codesandbox.io/s/peaceful-nobel-knq2zv) showing the problem when render is defined as 
```
render(<GraphiQL fetcher={graphQLFetcher} />, container);
```

There is no problem when render is defined as
```
render(<GraphiQL fetcher={customFetch} />, container);
```
which resembles my current implementation.

I'm trying to update to use createGraphiQLFetcher to add subscription support. [This comment](https://github.com/graphql/graphiql/issues/2779#issuecomment-1264652102) indicates my fetcher setup is incorrect. I would like to pass graphQLParams to a custom fetch function. Any advice for how to fix this?

**Comment by simPod** [comment]
@emmafull the sandbox works fine for me.

**Comment by emmafull** [comment]
@simPod whoops apologies my sandbox changes to modify graphQLFetcher to use a custom fetch function weren't saved when I shared the link. thanks for your quick reply. the sandbox is updated to resemble my implementation https://codesandbox.io/s/peaceful-nobel-knq2zv

**Comment by simPod** [comment]
TBH I don't see any problem with that though it works not.
