### ISSUE TITLE
[graphiql] user-facing setting for persisting headers

### ISSUE THREAD

**Issue by thomasheyenbrock** [graphql/graphiql#2793]
The `GraphiQL` currently provides a prop `shouldPersistHeaders` that implementors can use to decide if header values should be persisted in `localStorage`. By default, no headers are persisted as a security measure (header values often times contain sensitive tokens). This defaults leads to many GraphiQL implementations that are not persisting headers.

As a GraphiQL user I would like to override this setting. I want to be able to choose if I want my headers to be persisted or not.

Proposal: Add a section to the settings dialog where users can override the default behavior of the GraphiQL implementation around persisting headers. This setting should only have effect if the `shouldPersistHeaders` prop is not set, or in other words, the GraphiQL implementation should still be able to explicitly enforce a choice about persisting headers and GraphiQL users can only choose their preference if the implementation is not explicit about this setting.

**Comment by TheMightyPenguin** [comment]
Gonna give this one a shot 👀

**Comment by TheMightyPenguin** [comment]
Found an accessibility issue when working on this one https://github.com/graphql/graphiql/issues/2891
