### ISSUE TITLE
Grapohql Language server is not in list, highlighting graphql is not

### ISSUE THREAD

**Issue by pronovaso** [graphql/graphiql#2800]
## Current Behavior (if applicable)
In last version highlighting not working,In output I dont see GraphQL language server

## Desired Behavior
Highlighting -  I have linked graphql.schema.graphql for highlighting gql literal strings in ts or tsx file.

Helpful things to include:

Any error is not provided.

Thx ang GL

**Comment by acao** [comment]
Going to close this for #2801 with the `escape-html` bundling error, seems to be a bundling bug with the re-introduced query exec extension
