### ISSUE TITLE
[lsp-server] 🐞 The vscode-graphql server crashed 5 times in the last 3 minutes

### ISSUE THREAD

**Issue by bennycode** [graphql/graphiql#2817]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I just updated the [GraphQL: Language Feature Support VS Code Extension](https://marketplace.visualstudio.com/items?itemName=GraphQL.vscode-graphql) to v0.7.12 in VS Code v1.72.2 and since then I am getting this error:

> Error: No cache available for handleWatchedFilesChanged
>    at Vte.handleWatchedFileChangedNotification (c:\Users\bn\.vscode\extensions\graphql.vscode-graphql-0.7.12\out\server\index.js:736:4341)
>    at c:\Users\bn\.vscode\extensions\graphql.vscode-graphql-0.7.12\out\server\index.js:742:5066
>    at Array.map (<anonymous>)
>    at Gte.handleWatchedFilesChangedNotification (c:\Users\bn\.vscode\extensions\graphql.vscode-graphql-0.7.12\out\server\index.js:742:4967)
>    at c:\Users\bn\.vscode\extensions\graphql.vscode-graphql-0.7.12\out\server\index.js:770:102695
>    at ie (c:\Users\bn\.vscode\extensions\graphql.vscode-graphql-0.7.12\out\server\index.js:745:1591)
>    at Te (c:\Users\bn\.vscode\extensions\graphql.vscode-graphql-0.7.12\out\server\index.js:744:6743)
>    at Immediate.<anonymous> (c:\Users\bn\.vscode\extensions\graphql.vscode-graphql-0.7.12\out\server\index.js:744:6621)
>    at process.processImmediate (node:internal/timers:466:21)
> [Error - 11:45:59] The vscode-graphql server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
> [Info  - 11:45:59] The graphql server has stopped running

### Expected Behavior

```Markdown
No error pop up in VS Code
```

### Steps To Reproduce

```Markdown
1. Update GraphQL VS Code extension
2. Wait 3 minutes for VS Code to bring up this error
```

### Environment

```Markdown
- LSP Server Version: 0.7.12
- OS: Windows 11
- LSP Client: vscode-graphql-0.7.12
```

**Comment by acao** [comment]
I have re-opened #2421 to track this, thank you for reporting!

**Comment by acao** [comment]
@bennycode re-opening, I have a fix incoming!

**Comment by acao** [comment]
Does 0.8.1 fix this for you?
