### ISSUE TITLE
[graphiql] Verify publisher in VSCode marketplace

### ISSUE THREAD

**Issue by remcohaszing** [graphql/graphiql#2823]
VSCode allows extension authors to verify their identity by checking they own the domain on the publisher profile. If the publisher is verified, a checkmark is shown next to their name in VSCode.

![VSCode extensions list](https://user-images.githubusercontent.com/779047/196133409-3144baa3-b83f-4b66-81c0-5934f9e67116.png)

The GraphQL Foundation publishing the extension seems to be who they claim they are, but they aren’t verified.

See https://code.visualstudio.com/api/working-with-extensions/publishing-extension#verify-a-publisher for details.

**Comment by acao** [comment]
@remcohaszing ah yes, we still need to validate this.

**Comment by remcohaszing** [comment]
I just noticed this has been resolved.

**Comment by acao** [comment]
yay!! thank you @jorydotcom !!
