### ISSUE TITLE
[graphiql] Docs site is down

### ISSUE THREAD

**Issue by tylerbecks** [graphql/graphiql#2826]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

https://graphiql-test.netlify.app/typedoc/#:~:text=Looking%20for%20the-,GraphiQL%20Docs%3F,-%3A%20This%20is%20the

The URL for the docs site is broken. I found this URL [here](https://graphiql-test.netlify.app/typedoc/), which is linked in the README as API Docs.

### Expected Behavior

The site works.

### Steps To Reproduce

```Markdown
Click the link.
```

### Module pattern

- [ ] graphiql-umd
- [ ] graphiql-esm
- [ ] graphiql-commonjs

### Environment

```Markdown
- GraphiQL Version:
- OS:
- Browser:
- Bundler:
- `react` Version:
- `graphql` Version:
```

### Anything else?

```Markdown
No
```

**Comment by TallTed** [comment]
Looks like [*this* `https://graphiql-test.netlify.app/typedoc/packages/graphiql`](https://graphiql-test.netlify.app/typedoc/packages/graphiql) is the link that didn't work for you, not either of those in your report, above.

Looks like [*this* `https://graphiql-test.netlify.app/typedoc/modules/graphiql.html`](https://graphiql-test.netlify.app/typedoc/modules/graphiql.html) is what should have been the `href` of the [`packages/graphiql`](https://graphiql-test.netlify.app/typedoc/packages/graphiql) link you clicked.

Hopefully that's helpful...  to both the bug reporter and the maintainers of this project.

**Comment by acao** [comment]
@tylerbecks there are some bugs with our tsdoc version/configuration that cause duplicate identifiers which also seems to cause links to break. I would unfortunately not expect links in the API docs to be permalinks yet until we are able to fix tsdoc and/or build a proper docs site that has an API section that uses the tsdoc markdown output, more ideally
