### ISSUE TITLE
Open VSX extension out of date

### ISSUE THREAD

**Issue by simonklb** [graphql/graphiql#2838]
It looks like the [Open VSX extension](https://open-vsx.org/extension/GraphQL/vscode-graphql) hasn't been updated since the monorepo merge. Has it been published under a different name or am I missing something here?

I first created a [discussions thread](https://github.com/graphql/graphiql/discussions/2816) but didn't get any traction. However, this probably makes sense as a normal issue as it does not seem be working as expected.

**Comment by acao** [comment]
@simonklb there is a PR open. We are having issues since the merge because the cli tries to package every dependency! Will try to fix it eventually

**Comment by acao** [comment]
@simonklb i finally figured out a way to bundle and publish the extensions, but I'm not confident that the CLI worked properly, can you give it a test?
