### ISSUE TITLE
[vscode-graphql-syntax] Configure extra file extensions for VSCode extension

### ISSUE THREAD

**Issue by xenobytezero** [graphql/graphiql#2855]
### Is there an existing issue for this?

- [X] I have searched the existing issues

The list of default extensions covered by the extensions does not include the new `cts`/`mts` TypeScript extensions, and as far as I can tell there is no way on client side to configure this.

Is it possible to add these extensions, or add a configuration option to allow for extra extensions to be added?

**Comment by acao** [comment]
yes! this is the place:
https://github.com/graphql/graphiql/blob/main/packages/vscode-graphql-syntax/grammars/graphql.js.json#L2

**Comment by xenobytezero** [comment]
Aha, awesome. Would this also apply to the language server? Is this configurable or would it need to be submitted as a PR?

**Comment by acao** [comment]
@xenobytezero technically I think it would be configured by a user individually, but these are new standard extensions so I agree they should be added in a PR.

https://github.com/graphql/graphiql/blob/main/packages/vscode-graphql-syntax/grammars/graphql.js.json#L2

And you are correct, i forgot, there are LSP server changse we would need for anything beyond highlighting support:

https://github.com/graphql/graphiql/blob/f4bac351ef64838c28387598c02d6b8d0257af7f/packages/graphql-language-service-server/src/parseDocument.ts#L8

and here, to tell it to use the `typescript` babel parser plugin with these file extensions as well:
https://github.com/graphql/graphiql/blob/f4bac351ef64838c28387598c02d6b8d0257af7f/packages/graphql-language-service-server/src/findGraphQLTags.ts#L127
