### ISSUE TITLE
[graphiql] My graphiql interface has completely stopped working I can't move the insertion cursor, write queries, or anything.

### ISSUE THREAD

**Issue by wakywayne** [graphql/graphiql#2856]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Basically, I can't do anything the cursor doesn't move with the text and if I type the word mutation it takes about 30 seconds to appear. I cannot highlight or use my cursor for anything. 

I have tried: 
1. restarting the server 
2. clearing the url
3. Completely removing node modules folder and reinstalling the dependency

If anyone else is having or had this issue please comment. As I literally cannot use my graphiql environment

### Steps To Reproduce

```Markdown
### Your Example Website or App

https://github.com/wakywayne/wrestling-event-coordinator

### Steps to Reproduce the Bug or Issue

**the best thing to do for this issue is probably to look at my repository**
to reproduce the issue make a server and see if you have a similar problem
```

### Module pattern

- [ ] graphiql-umd
- [ ] graphiql-esm
- [X] graphiql-commonjs

### Environment

```Markdown
### Platform

- OS: windows
- NodeJS: 18.1.0
-    "@graphql-yoga/node": "^2.13.13",
```

### Anything else?

```Markdown
Everything was working fine in this environment for the past few days I didn't install any new dependencies or anything and then graphiql just stopped working
```

**Comment by jonathanawesome** [comment]
The version of yoga that you've installed uses a non-standard version of GraphiQL, so I'm not sure there's anything we can do here except provide some troubleshooting pointers.

The first thing I would do is remove the pothos/mongo bits and see if you can get the API route/graphiql UI running without it. [Here's the official example](https://github.com/vercel/next.js/blob/next-12-3-2/examples/api-routes-graphql/pages/api/graphql.ts). If this works, then you've got some new leads.

You may also want to try the new yoga v3 beta. Lots of examples around the web are being updated to use v3 beta (including the one I linked above), so you may have more luck there.

**Comment by wakywayne** [comment]
I can't find where I install it are you reffering to envolope? If so do I build the server the same way the docs on envelop seem to only show how to use plugins not build a server

**Comment by wakywayne** [comment]
All ifound was this: yarn add --save-exact graphql-yoga

and that says error: missing list of packages

**Comment by wakywayne** [comment]
I found it, switching to v3 seems to have worked so far so let''s keep are fingers crossed. THANK YOU SO MUCH FOR INFORMING ME ABOUT V3
