### ISSUE TITLE
[graphiql] generated bundles of graphiql is incompatible with strict CSP

### ISSUE THREAD

**Issue by simhnna** [graphql/graphiql#2868]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The top level readme in the repo states:
> codemirror-graphql and the graphiql browser bundle use the [.browserslistrc](https://github.com/graphql/graphiql/blob/main/.browserslistrc), which targets modern browsers to keep bundle size small and keep the language services performant where async/await is used, and especially to avoid the requirement of regenerator-runtime or special babel configuration.

But in fact regenerator-runtime is used [here](https://github.com/graphql/graphiql/blob/main/packages/graphiql/src/cdn.ts#L10)

If I run `build-bundles` in graphiql the generated graphiql.min.js file includes regenerator-runtime and actually differs from the version served here https://graphiql-test.netlify.app/ (the hosted version uses a newer build of regenerator-runtime which doesn't have this issue)

The easiest solution would be to remove regenerator-runtime by just removing the one line.

regenerator-runtime was updated recently to fix the issue https://github.com/facebook/regenerator/commit/cc0cde9d90f975e5876df16c4b852c97f35da436

If the lib should be kept, we could update regenerator-runtime to 0.14.8 or make sure that strict mode is _not_ used

### Module pattern

- [ ] graphiql-umd
- [ ] graphiql-esm
- [ ] graphiql-commonjs

**Comment by acao** [comment]
first of all, we need to replace webpack with vite or use webpack 5 at least, there are two PRs outstanding attempting to do this. but I did not realise that regenerator runtime was re-added, that hasn't been needed for a while since we dropped IE support a few years ago

**Comment by jonathanawesome** [comment]
Looks this `regenerator-runtime` was re-added recently, [here](#2758 ). @LekoArts do you remember your motivation for this change?

**Comment by jonathanawesome** [comment]
Looks like `regenerator-runtime` was re-added to support `graphiql-plugin-code-exporter`.  

As far as I can tell, there isn't a way to package `regenerator-runtime` with the vite library build for `graphiql-plugin-code-exporter`.  There's a vite plugin for this, @vitejs/plugin-legacy, but it doesn't run in library mode.

**Comment by thomasheyenbrock** [comment]
> Looks like regenerator-runtime was re-added to support graphiql-plugin-explorer.

It was in `cdn.ts` already before that, the commit blamed by git did only reorder imports, see here: https://github.com/graphql/graphiql/pull/2715/files#diff-bbf2e336517679d4c3102227c21f5e33b354a5518d9844c6302f2b2bcf4b542f

In fact, `regenerator-runtime` has been in there since I started working on this repo in May 🤨

**Comment by jonathanawesome** [comment]
@thomasheyenbrock thanks for the clarification!

[Found it](https://github.com/graphql/graphiql/commit/46ca2481775dfaf557fb422517b49261966fbede#diff-bbf2e336517679d4c3102227c21f5e33b354a5518d9844c6302f2b2bcf4b542f).

Lil' tiny PR in (#2939) with the removal.
