### ISSUE TITLE
[graphiql] <Visual Graph>

### ISSUE THREAD

**Issue by pablitomilenio** [graphql/graphiql#2869]
Hello,

Guten Morgen !

I would like to suggest to make a visual representation of the database using graphics

https://github.com/pablitomilenio/Oragnizational-Diagram-with-Programmatically-Created-Vector-Graphics

I have developed a program that can generate a graph as a SVG Scalable Vector Graphic with an unlimited amount of data

Waiting for your feedback

Pablo

**Comment by pablitomilenio** [comment]
http://www.escaida.net/OrgChart/lineTest.php

**Comment by thomasheyenbrock** [comment]
Hey Pablo 👋 can you share some more details of what you would like to achieve and how this relates to GraphiQL? I don't fully understand yet how generating org charts relates to GraphQL 🤔

**Comment by pablitomilenio** [comment]
Hey Thomas,

good to hear from you so soon. I assume graph-ql gets its name from the fact that the data is stored or retrieved from a graph

What I was thinking was to re-do my org-chart such that it would fit the logical structure of the graph-ql graphs

This way people could visualize the graphs with their eyes instead of running only text-only-queries

Regards from Barcelona

Pablo

**Comment by thomasheyenbrock** [comment]
GraphQL is a query language designed for clients that is agnostic to how the actual data is stored on the server. You can read more about it on the website: https://graphql.org/learn/

There already exist GraphQL-specific tools that visualize the GraphQL schema (which indeed is a graph), I think the most popular being GraphQL Voyager: https://ivangoncharov.github.io/graphql-voyager/ 

Do you imaging your org-chart code to produce something similar to that? How would it be different, and how would you like that to interact with the [GraphiQL UI](https://graphiql-test.netlify.app)?

**Comment by pablitomilenio** [comment]
Hello Thomas,

Indeed, I meant to do something like Graphql-Voyager. Your last response was clearly to the point. Apologies for my knowledge gap

Everything clarified now.


Thanks and regards

Pablo

**Comment by thomasheyenbrock** [comment]
No worries at all Pablo! Thank you for sharing your ideas 🙏 

I'm closing this issue then, feel free to reopen or create a new one if you have specific ideas on how to improve GraphiQL 🙌
