### ISSUE TITLE
[lsp-server] Off by one error in hover information location

### ISSUE THREAD

**Issue by DanielPower** [graphql/graphiql#2874]
graphql-lsp version 3.3.11

When hovering an identifier, there appears to be an off by one error, which results in the first character of an identifier not being hoverable, but the first space after the identifier is hover-able, and recognized as part of the identifier.

I've reproduced this on both VS Code and Neovim.

Neovim

https://user-images.githubusercontent.com/12166320/200630624-a6362b41-4cba-4407-9a8b-fa5413d5c067.mov

VS Code

https://user-images.githubusercontent.com/12166320/200630840-a2b0b366-49ca-4ef7-bb50-866a677365f9.mov

## Desired Behavior

Hovering the first character of an identifier should provide hover information.

**Comment by acao** [comment]
@DanielPower thank you! i will take a look at this bug
