### ISSUE TITLE
[graphiql] Seeing a lot of `act` related warnings in tests

### ISSUE THREAD

**Issue by TheMightyPenguin** [graphql/graphiql#2892]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

A few of the react unit tests are reporting warnings as they're not using `act` to wrap events that update the state. Also this is kind of tech debt, not sure what labels shout it have 
<img width="869" alt="image" src="https://user-images.githubusercontent.com/11748696/201421701-c4bf7370-3364-4000-8356-1635ef9a408f.png">

### Expected Behavior

We could wrap with `act` where necessary to get rid of these and remove some noise when running tests.

### Steps To Reproduce

```Markdown
1. Run `yarn test Graphiql.spec` and you will see a lot of these (printing the minified source as well which adds even more noise)
```

### Module pattern

- [ ] graphiql-umd
- [ ] graphiql-esm
- [ ] graphiql-commonjs

### Environment

```Markdown
- GraphiQL Version: latest
- OS: Mac OS 12.5
- Browser: Chrome 107
- Bundler:
- `react` Version: 17
- `graphql` Version: 16
```

**Comment by TheMightyPenguin** [comment]
@jonathanawesome you working on this one? If not I can help with it one next week

**Comment by jonathanawesome** [comment]
@TheMightyPenguin I'm on it!
