### ISSUE TITLE
ESLint improvements

### ISSUE THREAD

**Issue by dimaMachina** [graphql/graphiql#2894]
Below are my vision about improving ESLint linting in `graphiql` repository, it will be done with separated PRs to make review easy!

- [x] fix all warnings to have clear ESLint output https://github.com/graphql/graphiql/pull/2962
- [x] add `--max-warnings=0` and `--cache` CLI flags https://github.com/graphql/graphiql/pull/2962
- [x] <s>extend `plugin:jest/recommended` config for test files</s> **was already extended**
- [x] extend `plugin:cypress/recommended` config for e2e tests https://github.com/graphql/graphiql/pull/3035
- [x] extend `plugin:import/recommended` config #2922
- [ ] extend `plugin:jsx-a11y/recommended` config
- [x] extend `plugin:@typescript-eslint/recommended` config https://github.com/graphql/graphiql/pull/2967
- [ ] extend `plugin:@typescript-eslint/recommended-requiring-type-checking` config
- [x] ensure all code-blocks in markdown files doesn't contain syntax errors with `eslint-plugin-mdx`

**Comment by jonathanawesome** [comment]
@B2o5T very much looking forward to these changes!

**Comment by dimaMachina** [comment]
Most of theme were improved
