### ISSUE TITLE
Promise in try/catch

### ISSUE THREAD

**Issue by hinogi** [graphql/graphiql#2897]
Consider using 'await' for the promise inside this 'try' or replace it with 'Promise.prototype.catch(...)' usage

https://github.com/hinogi/graphiql/blob/1a3d034c02114c4a164e94626beb840260f05359/packages/graphql-language-service-server/src/MessageProcessor.ts#L994

**Comment by B2o5T** [comment]
Your are right!

@acao future mistakes could be avoided by using https://typescript-eslint.io/rules/no-floating-promises/ rule, but since that rule also requires type information CI in followed PR should be fixed first https://github.com/graphql/graphiql/pull/2878

**Comment by hinogi** [comment]
you could also add sonarqube to the repo, that's how I found it and it is free for OSS

**Comment by hinogi** [comment]
> Your are right!
> 
> @acao future mistakes could be avoided by using https://typescript-eslint.io/rules/no-floating-promises/ rule, but since that rule also requires type information CI in followed PR should be fixed first #2878

I guess there is a js version also
https://github.com/SebastienGllmt/eslint-plugin-no-floating-promise

**Comment by B2o5T** [comment]
> I guess there is a js version also https://github.com/SebastienGllmt/eslint-plugin-no-floating-promise

The above plugin is not maintained and it always better to use rule that requires type information
