### ISSUE TITLE
Add response time and size

### ISSUE THREAD

**Issue by KyleAMathews** [graphql/graphiql#29]
After each request, it'd be nice to see the response time + size of the response in KB somewhere. E.g. `251ms, 23.3kb`

**Comment by leebyron** [comment]
Does GraphiQL.Footer suffice?

**Comment by skevy** [comment]
@leebyron display-wise yes, but I think we'd need a hook into _fetchQuery.

**Comment by leebyron** [comment]
The provided fetcher function should be the appropriate hook, I believe.

I'd like to find a way to do this which allows for very easy extension as I think others will want more or different information about requests.

**Comment by skevy** [comment]
haha yah. of course the `fetcher` would let you do this. my bad.

So I guess the question becomes, should we just implement this completely in user-land? If so, np. We can close this and @KyleAMathews I can throw this in graphiql-app sometime soon.

**Comment by KyleAMathews** [comment]
My thought when creating this is that GraphiQL should ship with some sort of basic response info indicator that'd be easily overridable e.g. in the top section to the right of the play button.

**Comment by asiandrummer** [comment]
I feel like `GraphiQLToolbar` and `GraphiQLFooter` are available to serve exactly that purpose - to give users freedom to provide any customized information/feature they want. I do think that this should be implemented in user-land.

**Comment by kevinSuttle** [comment]
Could have this as an optional add-in for express-graphql: https://github.com/expressjs/response-time

**Comment by joelgriffith** [comment]
Why not just use `extensions` and create this yourself: https://github.com/graphql/express-graphql#options. Obviously means using the `express-graphql` server. Seems pretty trivial to implement in user-land.

**Comment by wincent** [comment]
Thanks for pinging this neglected old issue @joelgriffith. `extensions` is indeed intended for exactly this kind of use case, and rendering it in the footer is an appropriate place to put the data, so I think we should probably close this. Thanks to everybody who participated in the thread!
