### ISSUE TITLE
Support relay-local-schema

### ISSUE THREAD

**Issue by fracmak** [graphql/graphiql#291]
I use https://github.com/relay-tools/relay-local-schema in a local project and can't figure out how to use graphiql with it. It seems to need to make a request to a graphql server.

**Comment by leebyron** [comment]
This is mostly supported today! You can supply your schema instance to the `schema={}` prop on the `<GraphiQL />` component.

However GraphiQL requires a network backend provided as a `fetcher` function to fulfill queries you run. As made clear in its Readme, `relay-local-schema` isn't a substitute for a network backend, so you will not be able to run queries without a `fetcher` function.
