### ISSUE TITLE
[graphiql] Tab bar doesn't scroll fully when the tabs span the entire viewport

### ISSUE THREAD

**Issue by ardenn** [graphql/graphiql#2918]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When you open enough tabs to span the entire width of the viewport, the tab bar doesn't scroll to the end - to allow access to the "plus" button. I've observed the behaviour in both MacOS and Fedora with the latest Google Chrome.

https://user-images.githubusercontent.com/17312279/203817689-328ac787-fa35-4c66-9f05-eb29948b0aa3.mov

### Expected Behavior

The tab bar overflows or allows scrolling to the end

### Steps To Reproduce

```Markdown
1. Open enough tabs that span the width of the viewport
2. You can't access extra tabs or the add button after that
```

### Module pattern

- [ ] graphiql-umd
- [ ] graphiql-esm
- [ ] graphiql-commonjs

### Environment

```Markdown
- GraphiQL Version: latest from the demo site
- OS: MacOS 12.6
- Browser: Chrome 107
```

### Anything else?

```Markdown
https://user-images.githubusercontent.com/17312279/203817689-328ac787-fa35-4c66-9f05-eb29948b0aa3.mov
```

**Comment by thomasheyenbrock** [comment]
A fix for this has been published with `graphiql@2.2.0` and `@graphiql/react@0.15.0`
