### ISSUE TITLE
[graphiql-react] issue with setting tabs title 

### ISSUE THREAD

**Issue by vitalikda** [graphql/graphiql#2949]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

On initial render, all tabs have title `<untitled>`, then current tab correctly extracts operation name and changes the tab's title. 

https://user-images.githubusercontent.com/9862028/205900907-df2e4667-6564-4e40-8131-71cd188fa1d1.mov

From the code, I noticed that [fuzzyExtractOperationName](https://github.com/graphql/graphiql/blob/main/packages/graphiql-react/src/editor/tabs.ts#L334) does not handle comments before operation. 

E.g. 
```gql
# Some comment...
query one {
  __typename
}
```
returns `null`

### Expected Behavior

On initial render, all tabs have to have named titles

E.g. 
```gql
# Some comment...
query one {
  __typename
}
```
returns `one`

### Steps To Reproduce

You need to enable tabs to notice the issue (repro uses `defaultTabs` prop)
- https://codesandbox.io/s/elegant-mcnulty-jhmyn5?file=/src/index.js

### Module pattern

- [ ] graphiql-umd
- [ ] graphiql-esm
- [ ] graphiql-commonjs

### Environment

```Markdown
- GraphiQL Version: 2.2.0
- OS:
- Browser:
- Bundler:
- `react` Version:
- `graphql` Version:
```

### Anything else?

Not sure, but I guess you could
1. add multi line to regex: `const regex = /^(?!.*#).*(query|subscription|mutation)\s+([a-zA-Z0-9_]+)/m` (this should work for cases when there are multiple operations as well) 
3. run graphql print() on query before fuzzyExtractOperationName

**Comment by jonathanawesome** [comment]
Thank you for the sandbox! Addressed in #2968.
