### ISSUE TITLE
[lsp-server] 🐞 Incorrect variable validation for fields with default values

### ISSUE THREAD

**Issue by dylanowen** [graphql/graphiql#2974]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Default field values don't seem to be used when validating the variable input:

For the schema

```graphql
type Query {
   f(i: SomeObject!): String
}

input SomeObject {
   field: String!
   defaultField: String! = "Default Value"
}
```

and the query:
```
query op(input: SomeObject!){
   f(i: $input)
}
```
`variables`
```
{
   "input": {
      "field": "non default value"
   }
}
```

GraphiQL warns me `Object of type "SomeObject" is missing required field "defaultField"`

### Expected Behavior

```Markdown
I would expect this to not show me an error based on this section of the spec: https://spec.graphql.org/October2021/#sel-HAHhBVHBABAB5Hjxd
```

### Steps To Reproduce

```Markdown
1. Test out the schema and query I mentioned in GraphiQL
```

### Environment

```Markdown
- LSP Server Version: `5.1.0` (graphql-language-service)
- GraphiQL Version: `2.0.9`
- OS: OSX 12.6
```

### Anything else?

```Markdown
I believe this is an LSP issue based on `getJSONSchemaFromGraphQLType` being in the `graphql-language-service` module but I'm not positive.
```

**Comment by dylanowen** [comment]
Reading through the spec again I believe this is working as intended: https://spec.graphql.org/October2021/#sec-Input-Objects.Input-Coercion

Specifically the example where 

| Literal Value | Variables | Coerced Value |
|-|-|-|
|`$var`|`{ var: { a: "abc" } }`|`Error: Missing required field b`|

The default values aren't merged with the input variable object, that was a misunderstanding on my part.

**Comment by acao** [comment]
@dylanowen thank you for looking into this! if you wish the spec to change, you can always request this! there may be a discussion in `graphql/graphql-spec` repository already
