### ISSUE TITLE
[graphiql] For subscriptions "execute" button reverts back to "start" icon on receiving first update

### ISSUE THREAD

**Issue by rootkea** [graphql/graphiql#2975]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello!

When a subscription is set the "execute" button changes its icon to "stop" icon which is expected and shows that the subscription is in progress.

When a first data update is received the update is shown in output pane as expected but the "execute" button reverts back to the "start" icon indicating visually that the subscription is not in progress but in fact it is. The websocket connection is still intact and one can verify the same by generating another update for subscription or by taking look at network manager.

This is how it looks now:

![Screenshot_2022-12-15_10-54-21](https://user-images.githubusercontent.com/2694559/207782330-3ce4a640-6894-46e1-8e8f-a25484852729.png)

And this is how it used to look previously (1.8.2):

![Screenshot_2022-12-15_11-21-24](https://user-images.githubusercontent.com/2694559/207783230-3e9ac322-52c0-481b-9c1d-08356aa2574a.png)

### Expected Behavior

The execute button should not revert back to "start" icon until subscription has closed. If the subscription is in progress then the "execute" button should have "stop" icon.

### Steps To Reproduce

```Markdown
1. Execute subscription endpoint
2. Send update to subscription
3. Notice how "execute" button has reverted its icon to "start" icon indicating subscription is not in progress/has stopped.
```

### Module pattern

- [ ] graphiql-umd
- [ ] graphiql-esm
- [ ] graphiql-commonjs

### Environment

```Markdown
- GraphiQL Version: 2.0.7
- OS: Ubuntu 22.04.1 LTS
- Browser: Firefox 107.0.1 (64-bit)
- `react` Version: 17.0.2
```

**Comment by thomasheyenbrock** [comment]
Hey @rootkea 👋 this has already been fixed in `graphiql@2.2.0`, see also https://github.com/graphql/graphiql/pull/2907 and https://github.com/graphql/graphiql/issues/2774
