### ISSUE TITLE
[graphiql] @graphiql/react 0.16.0 is not tagged

### ISSUE THREAD

**Issue by simPod** [graphql/graphiql#2997]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

graphiql 2.3.0 requires @graphiql/react 0.16.0 but it is not tagged

<img width="746" alt="image" src="https://user-images.githubusercontent.com/327717/213257440-9d96f9a1-23d6-422a-bf85-d8927d434cca.png">

<img width="913" alt="image" src="https://user-images.githubusercontent.com/327717/213257307-b9ad1eb4-7488-49d5-a6ea-5e494c34551c.png">

**Comment by nicksrandall** [comment]
Same issue with `@graphiql/toolkit` it references a non-published version.

**Comment by thomasheyenbrock** [comment]
Thanks for raising this, we had a failure in our release action and some packages were not published correctly. We're looking into solving this manually.

**Comment by thomasheyenbrock** [comment]
I have to escalate this to @acao, I think you're still the only one who is part of the `graphiql` org on NPM and can create a token with access to these packages. (I've read your doc on how to add a bot user that we can use for the release workflow but can't act on it for the same reasons of lacking permissions 😕 )

**Comment by acao** [comment]
@thomasheyenbrock I created a discussion in discord on thursday with you, tim and lee asking for someone to elevate the npm permissions. i was revoked access to this org when the security breach happened

![image](https://user-images.githubusercontent.com/1368727/213861225-2768757e-faec-4bc1-bd97-e0f7e45aa9e7.png)

**Comment by benjie** [comment]
I've filed an agenda item for the next GraphQL Working Group to see what we can do to rectify this in general. IMO, build and publish infrastructure should not be dependent on a single individual's tokens.

I would like to stress that @acao has been very communicative throughout this and has done nothing wrong, absolutely no blame should lie with @acao.

This failure is a consequence of the pragmatic decisions we've had to make up until this point to allow progress to happen in a timely fashion; it's time for us to review the current state and see what can be improved. Rikki has already made a start on this, and it will be the subject of the agenda item I just filed with the Working Group.

I'm a TSC member, and I've checked my access and though I have control of packages like `graphiql` and `codemirror-graphql`, I do not have control of `@graphiql/*` scoped packages, so I'm unable to implement an interim publish.

Please be patient whilst we work through this.

https://github.com/graphql/graphql-wg/pull/1243

**Comment by acao** [comment]
thank you @benjie ! we are all doing our best.

I think for now we can just release a hotfix update where we revert this upgrade for `graphiql`'s `dependencies`

**Comment by acao** [comment]
ok, so it's tricky to find a way to do this hotfix release that doesn't create issues for further changeset releases. I will plan this out carefully tomorrow.

**Comment by sinh117801** [comment]
Hello here, I'm still stuck with `@graphiql/react@^0.16.0`.

**Comment by acao** [comment]
indeed - we are awaiting access to be restored to fix the publishing pipeline! I can't seem to find a workaround that will not break changesets publishing. It may be until next week that our colleauge is able to restore the npm token access.

**Comment by acao** [comment]
one annoying at best workaround could be to just fix to the previous `graphiql` release for now:

```json
"graphiql": "2.2.0",
```

**Comment by acao** [comment]
good news! thanks to @benjie we had the idea of removing the latest tag from 2.3.0 which @thomasheyenbrock has now done!

we still need to wait for permissions to be restored to make another release, but this at least means you won't need to pin the version, as 2.2.0 is now `latest`

**Comment by acao** [comment]
for those who are pinned to `2.2.0` - if you want to unpin it from `2.2.0` now you can use `^2.2.0`, and it will skip `2.3.0`, and when `2.4.0` and after drops it will pick up again (for reference, see [`npm dist-tag`](https://docs.npmjs.com/cli/v9/commands/npm-dist-tag?v=true) docs, formerly `npm tag`
