### ISSUE TITLE
Add syntax highlighting to headers

### ISSUE THREAD

**Issue by timuric** [graphql/graphiql#2998]
It would be great to see syntax errors contextually in the headers section like this:

![image](https://user-images.githubusercontent.com/4006792/213405735-a6e1c897-32b2-4343-a6a7-038f0ef801a9.png)

Instead of (somehow cryptic) error:
 
<img width="1275" alt="image" src="https://user-images.githubusercontent.com/4006792/213405509-554f97ee-eb8a-4000-b05a-7949bc36d6e0.png">

**Comment by acao** [comment]
there is syntax highlighting, but this is invalid json!

json5 support will come with graphiql@3 and monaco
