### ISSUE TITLE
Query Variables panel not visible in Safari 9.0

### ISSUE THREAD

**Issue by devknoll** [graphql/graphiql#3]
![screen shot 2015-08-24 at 3 26 02 pm](https://cloud.githubusercontent.com/assets/1477230/9454112/73ea2766-4a74-11e5-8599-7c3e4aa228cf.png)
 vs.
<img width="897" alt="screen shot 2015-08-24 at 3 25 44 pm" src="https://cloud.githubusercontent.com/assets/1477230/9454117/78a09d3a-4a74-11e5-999b-2f640409c644.png">

**Comment by leebyron** [comment]
Thanks for the report. I'll investigate why this is happening.
