### ISSUE TITLE
[graphiql] Display more types in `<SchemaDocumentation />`

### ISSUE THREAD

**Issue by hasparus** [graphql/graphiql#3000]
Hello 👋 

Currently, SchemaDocumentation shows only the root types in the initial screen, and has a lot of screen real estate that could be used to show more types. That would bring the UI closer to the results of `{ __schema { types { name } } }` query, so it's IMHO both a nice use of the empty space an pretty consistent.

I'm up for sending a PR if you feel it would be a worthwhile contribution. With `TypeLink` and `schema.getTypeMap()` the implementation seems be pretty straightforward.

<details>

<summary>Got a hacky implementation working with `pnpm patch`.</summary>

```diff
@@ -19643,6 +19634,9 @@ function SchemaDocumentation(props2) {
   const queryType = props2.schema.getQueryType();
   const mutationType = (_b = (_a = props2.schema).getMutationType) == null ? void 0 : _b.call(_a);
   const subscriptionType = (_d = (_c = props2.schema).getSubscriptionType) == null ? void 0 : _d.call(_c);
+  
+  const typeMap = props2.schema.getTypeMap && props2.schema.getTypeMap();
+  
   return /* @__PURE__ */ jsxs(Fragment, {
     children: [/* @__PURE__ */ jsx(MarkdownContent, {
       type: "description",
@@ -19671,6 +19665,29 @@ function SchemaDocumentation(props2) {
           type: subscriptionType
         })]
       })]
+    }), !typeMap ? null : jsxs(ExplorerSection, {
+      title: "Possible Types",
+      children: [
+        Object.values(typeMap).map(typeValue => {
+          const renderedKinds = [
+            "Interface",
+            "Object",
+          ].map(s => `GraphQL${s}Type`)
+
+          const ctorName = typeValue.constructor.name
+          const typeName = typeValue.name;
+
+          const ignoredTypes = ['Query', 'Subscription'];
+
+          if (renderedKinds.includes(ctorName) && !ignoredTypes.includes(typeName) && typeName[0] !== '_') {
+            return jsxs("div", {
+              children: [jsx(TypeLink, { type: typeValue })],
+            })
+          }
+
+          return null;
+        })   
+      ]
     })]
   });
 }
@@ -19811,7 +19828,6 @@ function fillInChunks(_ref4) {
       });
     }
   }
 }
 ```

</details>

https://user-images.githubusercontent.com/15332326/213796151-c92d1c8b-3bb4-49ef-8630-a6ace29ddb83.mov

As alternatives, I've considered disabling the Documentation Explorer plugin and swapping it with my own version, and mutating `DOC_EXPLORER_PLUGIN` export like a bandit, but I feel like it would be nice to have this feature in all GraphiQLs, not only in mine :)

**Comment by B2o5T** [comment]
Sorry for the late response, I like this idea, let's wait for thoughts for the team cc @acao @jonathanawesome @thomasheyenbrock

**Comment by acao** [comment]
@hasparus I really like this idea! we could also call it 'all schema types'

noting that some schemas include a lengthy markdown in the Schema.description, so perhaps we can make it disable-able via a plugin setting, but I like the idea of enabling this feature by default
