### ISSUE TITLE
[graphiql] unclear how directives like @includes or @cascade can be added to a query

### ISSUE THREAD

**Issue by phish108** [graphql/graphiql#3007]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when hitting the `@`-Symbol on the keyboard the editor enters a *Go-to-line* input-field instead of placing the character. 

This makes it impossible to enter directives interactively. 

### Expected Behavior

When hitting the `@`-Symbol on the keyboard the editor should display the `@`-Symbol, so [2.12 directives](https://spec.graphql.org/draft/#sec-Language.Directives) can be added interactively.

### Steps To Reproduce

```Markdown
1. hit `@` on the keyboard
2. be unable to add directive
```

### Module pattern

- [ ] graphiql-umd
- [ ] graphiql-esm
- [ ] graphiql-commonjs

### Environment

```Markdown
- GraphiQL Version: 2.2.0
- OS: MacOS
- Browser: Chrome 109
- Bundler: [CDN bundle](https://github.com/graphql/graphiql/blob/main/examples/graphiql-cdn/index.html)
- `react` Version: CDN bundle
- `graphql` Version: CDN bundle
```

### Anything else?

```Markdown
Thank you for providing the bundles.
```

**Comment by acao** [comment]
This used to work better - the autocomplete is designed to work here and works in monaco and vscode/LSP - @thomasheyenbrock do we know what happened here? perhaps a codemirror release introduced the `@` behavior and we need to disable it?

**Comment by acao** [comment]
huh, i can't seem to re-create this bug. can you supply a codesandbox that re-creates this if it's still an issue?

![image](https://user-images.githubusercontent.com/1368727/219977959-51a09564-e1b2-4a32-ab19-d7134d6f231a.png)

the other issue may be that your schema's introspection query response is not including directives, or your `schema` value does not include directives.
