### ISSUE TITLE
[graphiql] Long scalar is not being deserialized from the GraphQL response accurately.

### ISSUE THREAD

**Issue by srinivasankavitha** [graphql/graphiql#3010]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have the following schema in a Graphql service:
```
type Query {
    testLong(input: Long): Long
}
```
For the given query, I expect the input to be returned as is in my data fetcher :
```
{
    testLong(input: 198372202168701314)
}
```
I get an incorrect result since the long value is not matching the input:
```
{
  "data": {
    "testLong": 198372202168701300
  }
}
```
I have verified that the raw response is in fact correct via curl and by also inspecting the response payload in chrome's developer tools. In GraphiQL, the last 2 digits are displayed incorrectly.

### Expected Behavior

The response should be
```
{
  "data": {
    "testLong": 198372202168701314
  }
}
```

### Module pattern

- [ ] graphiql-umd
- [ ] graphiql-esm
- [ ] graphiql-commonjs

### Environment

```Markdown
- GraphiQL Version:2.3.0
- OS:Mac OS Monterey
- Browser:Chrome
- Bundler:
- `react` Version:
- `graphql` Version:
```

**Comment by acao** [comment]
Because `Long` is not a Scalar that is part of the graphql spec, we would need to implement this as part of #2386

**Comment by srinivasankavitha** [comment]
Thanks for the response. Sound good!
