### ISSUE TITLE
[lsp-server] 🐞 code intellisense in Vue SFC is not working properly

### ISSUE THREAD

**Issue by zhuscat** [graphql/graphiql#3016]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In Vue SFC, code intellisense is not working and code error is displayed at the wrong place, but in js/ts file it's working.

In Vue SFC file:

https://user-images.githubusercontent.com/14963619/217221080-1dc487d9-4bac-4eba-b51a-0cff514228c4.mov

In JS file:

https://user-images.githubusercontent.com/14963619/217221105-50a0ea45-b2d9-4b54-af25-4674e2e077e9.mov

### Expected Behavior

Code intellisense is working and code error is displayed at the right place in Vue SFC.

### Environment

- LSP Server Version: latest
- OS: macOS 13.0 (22A380)
- LSP Client: vscode

**Comment by acao** [comment]
hmm ok. this might be different from the existing issue. it's confusing because we're using the vue sfc compiler directly here!

**Comment by zhuscat** [comment]
The version of Volar is `v1.0.24`. I'm not sure it is a Volar issue or a graphql lsp issue. Can you reproduce?

**Comment by ReedSun** [comment]
I also triggered this issue. Is there any solution?

**Comment by acao** [comment]
This should be resolved as of early this year, sorry everyone!
