### ISSUE TITLE
[graphiql] Prettify the query before send it.

### ISSUE THREAD

**Issue by mostafa-rz** [graphql/graphiql#3024]
I use varnish in front of my graphQL. It is caching the response based on the body of the request. The body is hashed and used as the cache key. From this point there must not be any difference between these two queries:
```graphql
query MyQuery {
  bookies {
    data {
      id
    }
  }
}

query MyQuery {
  bookies {
    data {

      id
    }
  }
}
```
In the previous version, I reached this by prettifying the query before sending it and adding it to the fetcher parameters. In the new version, it is not working anymore.
Anyway, I think these two queries are identical and graphiql should send a prettified version to the server. Is it possible to add the feature?

**Comment by thomasheyenbrock** [comment]
Hey @mostafa-rz 👋 thanks for opening that discussion!

Prettifying the query before sending it to the origin is a opinionated preference, so I think it shouldn't be built into GraphiQL itself. That said, if you set up GraphiQL you can already achieve this today by adding some logic to the `fetcher` function passed into the `GraphiQL` component as prop like so:

```tsx
import { GraphiQL } from "graphiql"
import type { Fetcher } from "@graphiql/toolkit"
import { parse, print } from "graphql"

const fetcher: Fetcher = (graphQLParams, opts) => {
  return fetch("https://my.graphql.api", {
    method: "POST",
    headers: {
      "content-type": "application/json",
      ...opts.headers,
    },
    body: JSON.stringify({
      ...graphQLParams,
      // Printing the AST here normalizes queries that differ with regards to ignored tokens (e.g. whitespace)
      query: print(opts.documentAST || parse(graphQLParams.query)),
    }),
  })
}

function CustomGraphiQL() {
  return <GraphiQL fetcher={fetcher} />
}
```

**Comment by mostafa-rz** [comment]
Thanks for your response. Your solution worked and I send the pretty query to the origin, but now the playground doesn't show the result. I can see the result in the HTTP response but the playground result section is always an empty bracket.

**Comment by thomasheyenbrock** [comment]
Apologies, I messed up the fetcher implementation. Instead of returning the response it's supposed to return the response body parsed as JSON.

```diff
const fetcher: Fetcher = (graphQLParams, opts) => {
  return fetch("https://my.graphql.api", {
    method: "POST",
    headers: {
      "content-type": "application/json",
      ...opts.headers,
    },
    body: JSON.stringify({
      ...graphQLParams,
      // Printing the AST here normalizes queries that differ with regards to ignored tokens (e.g. whitespace)
      query: print(opts.documentAST || parse(graphQLParams.query)),
    }),
-  })
+  }).then((res) => res.json())
}
```

**Comment by mostafa-rz** [comment]
Thank you very much, everything is working now. Still, I suggest adding this at least as an option.

**Comment by thomasheyenbrock** [comment]
Awesome!

I want to emphasize again that having things like the fetcher function prop is very intentional so that users can build solutions themselves instead of us having to build everything into the project which would create a huge and unmaintainable API over time. If there is value in having a simpler API for these more opinionated things, I would suggest creating a custom utility package that provides a factory function that creates a fetcher like the one above (similar to what we have in `createGraphiQLFetcher` from `@graphiql/toolkit`).
