### ISSUE TITLE
README linting issue is failing PRs

### ISSUE THREAD

**Issue by acao** [graphql/graphiql#3079]
There was a change to `packages/graphiql/readme` that failed because of upstream changes to prettier config

![image](https://user-images.githubusercontent.com/1368727/222905559-f56c00d1-e16d-4669-b39e-3afb0a98773b.png)

prettier --write result:

![image](https://user-images.githubusercontent.com/1368727/222905994-0ac2c668-4c68-42c2-8b69-f4f5d788ac79.png)

we should consider going back to running linting & tests `on: [push, pull_request]` for this reason, so that we can run tests against the integrated work as well as the non-rebased PR. Currently we only run tests against PRs which are not rebased

**Comment by antonytphilip** [comment]
I will update README and create PR
