### ISSUE TITLE
Live demo is gone

### ISSUE THREAD

**Issue by remko** [graphql/graphiql#309]
The URL of the live demo no longer exists

**Comment by acme** [comment]
The Parse service is now shut down.

**Comment by wincent** [comment]
I migrated the demo to http://graphql.org/swapi-graphql — we just need to update any links pointing at the old Parse-hosted demo.

**Comment by wincent** [comment]
Thanks for the report, @remko. I had searched for links to the old demo, but couldn't find them, so this is much appreciated. I might have to search again...
