### ISSUE TITLE
[graphiql] Editor contents not updated when switching tabs

### ISSUE THREAD

**Issue by bakjos** [graphql/graphiql#3095]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When multiple tabs are open when switching from different tabs, the contents are lost

After debugging the method setState inside changeTab is called twice https://github.com/graphql/graphiql/blob/50674292c55eadf0e61993ffbbc7a6983c608bf4/packages/graphiql-react/src/editor/context.tsx#L392

this is the code used to render the graphiql component 
```jsx
<GraphiQL
  fetcher={graphQLFetcher}
  query={query}
  onEditQuery={setQuery}
  storage={localStorage}
  plugins={[explorerPlugin]}
  shouldPersistHeaders={true}
/>
```

### Expected Behavior

The tabs should keep the contents

### Steps To Reproduce
![Screen Recording 2023-03-09 at 11 23 54 AM](https://user-images.githubusercontent.com/1247502/224087846-650f6f1b-961e-4b0f-8b9b-459aadd4dc69.gif)

_No response_

### Module pattern

- [ ] graphiql-umd
- [ ] graphiql-esm
- [ ] graphiql-commonjs

### Environment

```Markdown
- GraphiQL Version: 2.4.0
- OS: MaxOS 13.2.1
- Browser: Chrome 110
- Bundler: Webpack(reac-scripits)
- `react` Version: 18.2.0
- `graphql` Version: 16.3.0
```

**Comment by gr-myles** [comment]
+1 I am experiencing issues with tabs as well. Anytime I switch between tabs it either copies over or erases the current state to the other tab. It makes using tabs completely broken
