### ISSUE TITLE
[lsp-server] 🐞 graphql-config.load.filePath configuration option has no effect

### ISSUE THREAD

**Issue by cdignam-segment** [graphql/graphiql#3108]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have a graphql config file named `graphql-codegen.json`. Because this is a non-standard name, I've set this configuration option for the vscode extension.

But the extension doesn't respect this option. Changing my graphql file name to `graphql.config.json` is a workaround.

.vscode/settings.json

 "graphql-config.load.filePath": "./graphql-codegen.json",

graphql-codegen.json
```json
{
  "schema": "https://app.segment.com/gateway-api/graphql"
}
```

### Expected Behavior

The vscode extension should read my `graphql-codegen.json` file.

### Steps To Reproduce

1. Create a `graphql-codegen.json` file with a schema key set to a graphql server
2. Verify the vscode extension cannot start.
3. Set `graphql-config.load.filePath` in VSCode settings to `./graphql-codegen.json`.
4. Verify extension still cannot find configuration file

### Environment

```Markdown
- LSP Server Version: v0.8.6
- OS:
- LSP Client: vscode-graphql
```

### Anything else?

```
3/22/2023, 10:14:50 AM [1] (pid: 75275) graphql-language-service-usage-logs: WARNING: graphql-config error, only highlighting is enabled:
GraphQL Config file is not available in the provided config directory: /Users/chris/projects/app
Please check the config directory.
for more information on using 'graphql-config' with 'graphql-language-service-server', 
see the documentation at https://www.npmjs.com/package/graphql-language-service-server#user-content-graphql-configuration-file
```

**Comment by RyanzpLee** [comment]
@cdignam-segment  Yeah I don't seem to be having much luck with filePath, and I'm not sure why it's not working when I had a look over the code. 

For now alternatively you could use `graphql-config.load.configName:  "graphql-codegen"` and you need to set your config file to `graphql-codegen.config.json` or `.graphql-codegen.json` I believe should work for you

**Comment by acao** [comment]
yes indeed! for future reference here always refer to graphql-config docs. glad you figured it out

**Comment by digitalmaster** [comment]
This one got me to 🙈 . So just to be sure I follow; non-supported config names are not supported?

This FAQ answer seems to imply that I can:
![CleanShot 2024-04-10 at 10 28 41@2x](https://github.com/graphql/graphiql/assets/1279335/b36faaf3-dcbd-4f38-8e42-8cb1e76c9276)

I my case the config is at root, just not supported format. Doesn't work for me either. Renaming of course does work.

**Comment by yuchenshi** [comment]
I spent some time digging into this -- it looks like it's called `filepath` with a lowercase `p` in `graphql-config` ([permalink](https://github.com/kamilkisiela/graphql-config/blob/553ea681c1d428212113e9bb8c467f45b12b3cb3/src/config.ts#L22)) but it's declared as `filePath` with uppercase `P` in the VS Code extension ([permalink](https://github.com/graphql/graphiql/blob/79d1d990040ab6430776ee2495dd4e1230bedb18/packages/vscode-graphql/package.json#L116)).

Any chance this is the culprit? Shall we reopen the issue?

**Comment by acao** [comment]
@dpnova thanks for fixing the casing issue! i think the casing changed at some point in graphql-config or it was just wrong the whole time haha
