### ISSUE TITLE
Vue support is broken when script tag is not on top

### ISSUE THREAD

**Issue by SeanDylanGoff** [graphql/graphiql#3115]
After some debugging it Vue VSCode Intellisense works if the setup scripts comes first (before template & script), but fails in any other order. If the setup script comes second, GraphQL errors are overlaid on whatever is actually there as if the script came first. So it looks like the setup script offset isn't added somewhere.   

I'm not familiar with this codebase, so maybe this is an upstream issue with the vue sfc compiler.

_Originally posted by @flotothemoon in https://github.com/graphql/graphiql/issues/2827#issuecomment-1333707395_

This issue still is still present in GraphQL: Language Feature Support v0.8.7

**Comment by KammererTob** [comment]
Can confirm. No errors in log. If `<script setup lang="ts">` is below the template, Intellisense isn't working. As soon as i move the whole script block to the top it works again.
