### ISSUE TITLE
Remove ligatures

### ISSUE THREAD

**Issue by timuric** [graphql/graphiql#3144]
GraphQL syntax doesn't benefit from ligatures, and can be confusing when data is displayed, for instance `xxxx1x1` looks like `xxx1×1`
![image](https://user-images.githubusercontent.com/4006792/233348099-ac619b53-30fb-473e-8e13-929e5bdf302b.png)

`.graphiql-container * {
  font-variant-ligatures: none;
}`

**Comment by thomasheyenbrock** [comment]
This is reproducible:
| Current state | Desired state (after adding `font-variant-ligatures: none`) |
| --- | --- |
| <img width="344" alt="CleanShot 2023-04-25 at 12 24 00@2x" src="https://user-images.githubusercontent.com/22288634/234249331-6db813d1-e503-45a1-bb0b-96a06ddb910a.png"> | <img width="352" alt="CleanShot 2023-04-25 at 12 25 58@2x" src="https://user-images.githubusercontent.com/22288634/234249482-484982be-e6c8-4aaa-b9cf-f239089a786c.png"> |

Notice the subtle difference of the x before and the x between the `1`s.
