### ISSUE TITLE
[graphiql] Don't render newlines in documentation strings

### ISSUE THREAD

**Issue by leonardehrenfried** [graphql/graphiql#3155]
Long documentation strings that contain a newline are rendered as is in GraphiQL. This makes reading them a bit confusing and disjointed.

#### Doc pane
![Screenshot from 2023-04-27 12-39-23](https://user-images.githubusercontent.com/151346/234838868-39bcb8eb-209a-4574-8e97-9089e4ca9b08.png)

#### Tooltip
![Screenshot from 2023-04-27 12-31-46](https://user-images.githubusercontent.com/151346/234838872-a99f447b-6e17-46e7-81fb-5b894441c666.png)

In the original schema this looks like this:

```graphqls
    """
    Bearing, in degrees, clockwise from North, i.e., 0 is North and 90 is East. This can be the
    compass bearing, or the direction towards the next stop or intermediate location.
    """
    heading: Float
```

I would love it if these doc strings, which in our case can be multiple paragraphs, be treated like markdown. This would mean that a single newline is ignored and a double newline treated as a new paragraph.

Thank you for making this wonderful piece of software.

**Comment by acao** [comment]
thanks @leonardehrenfried ! this is a great suggestion. `packages/graphiql-react/src/markdown.ts` is where we keep the configuration for `markdown-it`, and iirc, this is just a simple config tweak or plugin away from happening!

**Comment by dimaMachina** [comment]
will be fixed in graphiql v4
