### ISSUE TITLE
[vscode] Extension no longer publishing

### ISSUE THREAD

**Issue by AaronMoat** [graphql/graphiql#3165]
It looks like the vscode extension(s) is/are no longer publishing:

```
vscode-graphql
 | successfully bundled vscode-graphql 🚀
 | Publishing 'GraphQL.vscode-graphql v0.8.11'...
 | ::error::﻿{"$id":"1","customProperties":{"Descriptor":null,"IdentityDisplayName":null,"Token":null,"RequestedPermissions":0,"NamespaceId":"00000000-0000-0000-0000-000000000000"},"innerException":null,"message":"Access Denied: The Personal Access Token used has expired.","typeName":"Microsoft.VisualStudio.Services.Security.AccessCheckException, Microsoft.VisualStudio.Services.WebApi","typeKey":"AccessCheckException","errorCode":0,"eventId":3000}%0A%0AYou're using an expired Personal Access Token, please get a new PAT.%0AMore info: https://aka.ms/vscodepat
 | npm ERR! Lifecycle script `vsce:publish` failed with error: 
 | npm ERR! Error: command failed 
 | npm ERR!   in workspace: vscode-graphql@0.8.11 
 | npm ERR!   at location: /home/runner/work/graphiql/graphiql/packages/vscode-graphql 
 | error Command failed with exit code 1.
 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
 | `yarn release --exclude-missing --serial --recursive --changedSince main` failed with exit code 1
```

https://marketplace.visualstudio.com/items?itemName=GraphQL.vscode-graphql shows 0.8.7 which is not near the latest.

**Comment by acao** [comment]
access token needs replaced. I am currently seeking a new job so I won't have time to work on this for a while

**Comment by lsanwick** [comment]
@acao Is there anyone else that has permissions to publish it?

**Comment by acao** [comment]
not currently - there is a longstanding bug with visual studio marketplace where I cannot add outside users to the team. have opened multiple tickets with microsoft. i may share my azure credentials with the other maintainers as a workaround

**Comment by acao** [comment]
ok, I've published the extensions manually from my local, but we can close this ticket once I have been granted permissions to fix the pipeline at least. this happens every time the PAT expires, and my repo permissions are constantly changing so there is little I can do when I cannot refresh the token

**Comment by acao** [comment]
CI fixed! thanks @benjie !
