### ISSUE TITLE
[graphiql] Run dropdown list

### ISSUE THREAD

**Issue by jetsstarplus** [graphql/graphiql#3187]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

With multiple queries and mutations on the web editor, when I hit the run button a list of the commands are shown and if they exceed a certain number, some of them are hidden from the dropdown list.
Its only until I zoom in the UI for me to see the remaining commands.
The Z-Index of the dropdown is also overridden by those of the editors left pane overflow bars.

### Expected Behavior

The dropdown, should have a maximum height that should have a scroll behavior incase the items in it exceed it's height.
The z-index of the dropdown should also be higher than those of the editor pane scrollbars.

### Steps To Reproduce

```Markdown
1. Use the CDN provided for both the minified css and js for the HTML File.
```

### Module pattern

- [ ] graphiql-umd
- [ ] graphiql-esm
- [ ] graphiql-commonjs

### Environment

```Markdown
- GraphiQL Version:latest
- OS:Windows 10
- Browser: Chrome 106
- Bundler:
- `react` Version:18
- `graphql` Version:16
```

**Comment by B2o5T** [comment]
could you attach screenshot or video?

**Comment by jetsstarplus** [comment]
Ofcourse, Here is normal view. 
As you can see, the scroll bars are on top of the dropdown
![graphiql](https://github.com/graphql/graphiql/assets/52789494/d5f00455-314d-46d1-87ec-ecebb7c9a762)

The dropdown also does not show all commands, here is the view with 33% zoom
![graphiql2](https://github.com/graphql/graphiql/assets/52789494/24b1e36c-cd7f-450a-9441-e40419b221fa)

**Comment by acao** [comment]
I remember this bug in 0.x. We set the max height dynamically using vh if i recall, but that caused issues on resize of course, so we set a fixed pixel height

**Comment by B2o5T** [comment]
i think it's should be fixed with https://github.com/graphql/graphiql/pull/3183 will try it once it will be merged!

**Comment by jetsstarplus** [comment]
Thats Ok

**Comment by B2o5T** [comment]
@jetsstarplus you can try a fix in `graphiql@3.0.0-alpha.0`

**Comment by jetsstarplus** [comment]
> @jetsstarplus you can try a fix in `graphiql@3.0.0-alpha.0`

Yes It is Ok now, It has a scroll behavior.
Though the scrollbar is still on top of the dropdown as in the picture below.
I'm using the latest chrome browser on windows
![scroll bar](https://github.com/graphql/graphiql/assets/52789494/0a1a1f6e-9c9e-4db5-8504-b419d5f76e02)

**Comment by B2o5T** [comment]
@jetsstarplus you can send a PR if you found a way how to fix it, I don't use windows

**Comment by jetsstarplus** [comment]
Ok
