### ISSUE TITLE
Live demo doesn't work

### ISSUE THREAD

**Issue by spicyj** [graphql/graphiql#32]
Clicking run at http://graphql-swapi.parseapp.com/graphiql/ gives

> Uncaught TypeError: e.getFields is not a function

in defaultGetDefaultFieldNames.

**Comment by fson** [comment]
I wonder if this is related to https://github.com/graphql/graphiql/issues/23

**Comment by asiandrummer** [comment]
Does this still happen? I can't seem to reproduce - clicking run executes a query for me.

**Comment by spicyj** [comment]
Yes. I'm in Chrome 46.0.2490.22 beta so maybe specific to that – seems to work in Firefox.

![image](https://cloud.githubusercontent.com/assets/6820/9917044/6f4e6f16-5c74-11e5-8282-b6b240e53f7a.png)
