### ISSUE TITLE
[graphiql] Info popups lose position on page scroll

### ISSUE THREAD

**Issue by lesleydreyer** [graphql/graphiql#3202]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If not using the editor as full page (have other divs above or below and scroll enabled by turning off the body css overflow: hidden), the info popups will lose their place on the page when you scroll. I think it's coming from codemirror-graphql > src > utils > info-addon > onMouseOver > info on line 104. I wasn't sure if there's a way to try re-calculating the info if it's not found based on where the editor has scrolled to.

<table>
  <tr>
      <th>initial position person tooltip works</th>
      <th>scolled position person tooltip broke</th>
  </tr>
  <tr>
      <td><img src="https://github.com/graphql/graphiql/assets/38596053/b3455a13-0b99-4a06-85a8-9b35488b2d82"  alt="initial position works" /></th>
      <td><img src="https://github.com/graphql/graphiql/assets/38596053/2b79e687-b68d-4c9d-a51d-fb78e8dd37ed" alt="scrolled position broke" /></th>
  </tr>
</table>

### Expected Behavior

Should be able to see the hover tooltips

### Steps To Reproduce

```Markdown
1. Temporarily adjust grapiql > src > components > Graphiql.tsx to 
    <div>
       <div style={{height: '200px'}}/>
       ...GraphiQLProvider element that's there
       <div style={{height: '200px'}}/>
    </div>
2. graphiql > resources > index.html.ejs temporarily comment out the body css "overflow: hidden"
```

### Module pattern

- [ ] graphiql-umd
- [ ] graphiql-esm
- [ ] graphiql-commonjs

### Environment

```Markdown
- GraphiQL Version:
- OS:
- Browser:
- Bundler:
- `react` Version:
- `graphql` Version:
```

**Comment by B2o5T** [comment]
@lesleydreyer released in `graphiql@3.0.0-alpha.0`
