### ISSUE TITLE
Release bug with changesets and/or prettier

### ISSUE THREAD

**Issue by acao** [graphql/graphiql#3264]
It looks like release PRs are failing on this bug - very strange! Is cosmicconfig a peer dependency of changesets perhaps, and it was removed?
![image](https://github.com/graphql/graphiql/assets/1368727/b469961d-ef55-48f5-a90e-a550812a61b6)

**Comment by B2o5T** [comment]
It was a due incorrect installed version of prettier (for vscode)

I guess I already fixed it?
