### ISSUE TITLE
VSCode extension stuck on install/update

### ISSUE THREAD

**Issue by ZiiMakc** [graphql/graphiql#3278]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```Markdown
New version of `GraphQL: Language Feature Support` for `vscode` stuck on update. 

I've removed it manually using `code --uninstall-extension`, but installing it again still hangs.

https://prnt.sc/6OG_dvZGFiEh
```

### Expected Behavior

```Markdown
VSCode extension should be installed.
```

### Steps To Reproduce

```Markdown
Not sure how to debug it or where to look for logs.
```

### Environment

```Markdown
- latest plugin version
- OS: windows 11 WSL 2
```

**Comment by acao** [comment]
@ZiiMakc are you running `0.8.16` by chance?

**Comment by ZiiMakc** [comment]
@acao yes, I'm trying to install `GraphQL: Language Feature Support v0.8.16`, is there a way how can I try install it manually to see some error logs?

**Comment by ZiiMakc** [comment]
After few reinstallations and restarts I was able to install it fine, not sure what was an issue
