### ISSUE TITLE
Prevent the ExecuteButton click event from refreshing the page.

### ISSUE THREAD

**Issue by travisbt** [graphql/graphiql#329]
In some situations, when using the `graphiQL` component directly, clicking on the `ExecuteButton` will trigger a refresh of the page.

Fixed with [#319](https://github.com/graphql/graphiql/pull/319).

**Comment by wincent** [comment]
And we'll cut a release with this soon. Want to get another toolbar fix in from @AGS- first, but he'll have a PR up for that soon.
