### ISSUE TITLE
[graphiql] Getting 404 when loading the UI with plugin-explorer enabled

### ISSUE THREAD

**Issue by bilalebi** [graphql/graphiql#3291]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I get an empty UI with the error below in the network tab:

![image](https://github.com/graphql/graphiql/assets/62993769/563969ae-5c04-4c9c-a8f0-3678557ee62a)

I think this is due to renaming https://unpkg.com/@graphiql/plugin-explorer@0.1.21/dist/graphiql-plugin-explorer.umd.js to https://unpkg.com/@graphiql/plugin-explorer@0.1.21/dist/index.umd.js which caused the UI to break.

### Expected Behavior

Expecting the UI to load properly and `graphiql-plugin-explorer.umd.js` to be fetched.

### Anything else?

```Markdown
I'm using [Ariadne](https://ariadnegraphql.org/)
```

**Comment by B2o5T** [comment]
will be fixed for the next patch version, but will be rollback to `index.umd.js` in the next minor because it's fine to introduce breaking changes when major is `0` according to semver policy https://semver.org/#spec-item-4
