### ISSUE TITLE
recent eslint & prettier changes are clashing over `"` and `'`

### ISSUE THREAD

**Issue by acao** [graphql/graphiql#3337]
it seems that we still have some lingering issues with formatting & eslint

`prettier` expects imports to use `"` double quotes, but `eslint` wants single quotes for everything `'`. if I run a prettier fix on a file, it switches the import to use `"`, but then `eslint` fails on this change because it wants single quotes

it seems we need to address this regression that was recently introduced - previously we had a check to ensure that prettier and eslint didn't have clashing configs, it seems that was removed?

**Comment by B2o5T** [comment]
Prettier doesn't expect double quotes, it uses single quotes everywhere https://github.com/graphql/graphiql/blob/9a38de29fddf174ba9e793ac5852407537244f87/.prettierrc#L2

**Comment by acao** [comment]
the clashing I think I saw was over arrow functions and use of parenthesis actually, i think prettier calls this `arrowParens` setting, either way I will close this until it seems to be a real issue. I was having this issue only in the github online vscode instance and not on my local, when running "format file", so I think it was because the commits were bypassing the githooks
