### ISSUE TITLE
[graphiql] `visiblePlugin` errors `@graphiql/plugin-explorer` v0.3.0

### ISSUE THREAD

**Issue by benedfit** [graphql/graphiql#3339]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When upgrading from v0.2.0 to v0.3.0 of `@graphiql/plugin-explorer` when using `visiblePlugin={explorer}` an error is encountered on initial render:

`Cannot read properties of null (reading 'getValue')`

Presumably this is because the state has not been set yet?

### Expected Behavior

The explorer plugin is loaded as the visible plugin on initial load

### Steps To Reproduce

Minimal replication: https://codesandbox.io/s/heuristic-rubin-cyny3d?file=/src/App.tsx

- Load the replication and see the error
- Comment out `visiblePlugin={explorer}` and confirm the error is resolved
- Click the explore icon in the menu and verify the explore plugin is loaded

**Comment by acao** [comment]
@benedfit thanks for reporting - close! this has to do with the presence of the editor instance. patch incoming :)

**Comment by acao** [comment]
@benedfit thanks to your codesandbox, i can confirm that `@graphiql/plugin-explorer@0.3.1-canary-125d095d.0` fixes this bug!

**Comment by acao** [comment]
@benedfit see:

https://codesandbox.io/s/wispy-field-y6gpvh?file=/src/App.tsx

also, be sure to instantiate the plugin outside the react component unless you need to, there are [instructions in the changelog](https://github.com/graphql/graphiql/blob/main/packages/graphiql-plugin-explorer/CHANGELOG.md#minor-changes)

**Comment by acao** [comment]
noting for others in need of this patch - there was a bug with `@changesets/cli` and it was accidentally released as `@graphiql/plugin-explorer@1.0.0`. we will be deprecating this version, and hope to release this as `@graphiql/plugin-explorer@0.3.1` as intended. we are going to patch `changesets` temporarily until they decide how to handle this case
