### ISSUE TITLE
Question : How can i hide part of schema on  document explorer

### ISSUE THREAD

**Issue by matart15** [graphql/graphiql#334]
How can i hide part of schema on  document explorer depending on auth user.

Or how can I completely disable it on some users.

**Comment by asiandrummer** [comment]
Hi @matart15 - I think what you probably want to do is to authenticate user before loading GraphiQL, and return an introspection result that hides the part of the schema depending on the result of the authentication. GraphiQL also supports passing in `schema={null}` as a prop to instantiate without a schema instance.

**Comment by asiandrummer** [comment]
I'll close this for the time being - @matart15 let me know if you have any other questions!

**Comment by matart15** [comment]
@asiandrummer thank you. I totally miss your first comment notification and did not see it.
for now `schema={null}` works for me thank you.
