### ISSUE TITLE
Display Issue with Multiline Deprecation Reason

### ISSUE THREAD

**Issue by zahraaalizadeh** [graphql/graphiql#3348]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently, when a deprecation reason is displayed in GraphiQL, only the first paragraph of the deprecation message is visible, while the rest of the information (second paragraph and the bulleted list) is missing.
for example with the following node in schema:
```json
{
  "name": "sampleField",
  "description": "Sample description for the field.",
  "args": [],
  "type": {
    "kind": "SCALAR",
    "name": "String",
    "ofType": null
  },
  "isDeprecated": true,
  "deprecationReason": "The 'sampleField' field is deprecated.\n\nThis field has been deprecated due to sample reasons.\n\n- Marked as deprecated on 2023-07-14.\n- Will be removed on 2024-07-14."
}
```
the following html tags are created:
```html
<div class="graphiql-doc-explorer-deprecation">
  <div class="graphiql-doc-explorer-deprecation-label">Deprecated</div>
  <div class="graphiql-markdown-deprecation graphiql-markdown-preview">
    <p>The 'sampleField' field is deprecated.</p>
    <p>This field has been deprecated due to sample reasons.</p>
    <ul>
      <li>Marked as deprecated on 2023-07-14.</li>
      <li>Will be removed on 2024-07-14.</li>
    </ul>
  </div>
</div>
``` 
but it's displayed as shown in the following image:
<img width="267" alt="Screenshot 2023-07-14 at 12 59 30 pm" src="https://github.com/graphql/graphiql/assets/73332835/b2c4e331-506c-4af0-9483-29963219a9d2">

### Expected Behavior

I expected the entire deprecation message, including all paragraphs and the bulleted list, to be displayed in GraphiQL without any missing information.

### Environment

* GraphiQL Version: 2.4.1
* OS: mac os
* Browser: Chrome Version 114.0.5735.198 (Official Build) (arm64)
* `react` Version: 17.0.2
* `graphql` Version 16.4.0

**Comment by acao** [comment]
It is because of this CSS which is designed to make these sections expandable, but this behavior was overlooked for deprecated fields!

![image](https://github.com/graphql/graphiql/assets/1368727/1316d6c4-59c7-4ab6-8172-1b51941990e2)

**Comment by acao** [comment]
@zahraaalizadeh thank you for reporting this issue!

this canary version will fix it for you;

```
@graphiql/react@0.19.1-canary-251c1491.0
```
we should release the bugfix by next week :) have a lovely weekend!
