### ISSUE TITLE
[lsp-server] 🐞 VS Code "go to definition" is blocked until the language server loads

### ISSUE THREAD

**Issue by MatthewMaclean** [graphql/graphiql#3388]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When the [GraphQL: Language Feature Support](https://marketplace.visualstudio.com/items?itemName=GraphQL.vscode-graphql) plugin is enabled in VS Code, "go to definition" will block on startup until the server has parsed all the files. This is problematic in a large monorepo with GraphQL colocated in the typescript files.

One thing that did help speed up the load time was to reduce the number of documents that the server was parsing:
`  documents: ['**/*.{graphql,ts,tsx}', '!**/node_modules/**', '!**/generated/**', '!**/build/**', '!**/.*/**', '!**/dist/**'],`. It was unclear from the documentation that one should do this, so I'm happy to contribute that as a suggestion in the docs if desired. 

Currently after startup, it takes "go to definition" around 1 minute to be functional. Before the ignores in the documents blob, we were at 3m 30s.

### Expected Behavior

I'm not familiar with VS Code extension limitations, but ideally "go to definition" would be unaffected by the load time of the extension. The various files should be parsed asynchronously before holding a lock on core IDE functionality.

An alternative could be some form of a cache, but I can imagine that's much trickier to manage across IDE sessions.

### Steps To Reproduce

1. Open a large repository with GraphQL: Language Feature Support enabled in the IDE
2. Try "go to definition", it may work once or twice before the extension begins to initialize.
3. "go to definition" will hang and a progress bar will show up across the top of VS Code
4. "go to definition" will work once the Graphql Language Server has finished initial processing and moves to what I assume is incrementally updates 

### Environment

* OS: Ventura 13.5
* GraphQL: Language Feature Support = v0.8.17
* VS Code: 1.80.2

**Comment by acao** [comment]
@MatthewMaclean if you notice, the same thing happens with typescript. it shows a `loading...` text on definition hover

**Comment by MatthewMaclean** [comment]
Gotcha. The Typescript loading is just so much faster for us that I haven't noticed it holding a lock on the functionality. Well I'm happy to close this out if there's not much of an alternative.

I'll look for a spot in the docs to better highlight the glob with an exclusion filter option.
