### ISSUE TITLE
[graphiql] DOMException: An invalid or illegal character string was specified with WS subscriptions

### ISSUE THREAD

**Issue by lewebsimple** [graphql/graphiql#3396]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When submitting a subcription request to the server from the GraphiQL editor, the following error appears in the JS console: "DOMException: An invalid or illegal character string was specified".

No request is sent at all to the server (i.e. it crashes on the client side before the initial WS request and handshake).

The same subscription works fine in the app using @urql/vue on the client side.

The project is a fullstactk Nuxt 3 / GraphQL Yoga / Pothos GraphQL and it's using graphql-ws as the transport for subscriptions, with Redis as the underlying message broker for the pubsub on the server.

Project repository is available [here](https://github.com/lewebsimple/nuxt-graphql-fullstack)

### Expected Behavior

The subscription should initiate the WS connection correctly and return the results in the GraphiQL editor like it does in the app.

### Steps To Reproduce

```
git clone https://github.com/lewebsimple/nuxt-graphql-fullstack.git
cd nuxt-graphql-fullstack
# Set DATABASE_URL in .env
pnpm install
pnpm prisma db push
pnpm dev:nuxt
# Open http://localhost:3000/api/graphql
# Try to execute "subscription { pong }"
```

### Environment

* GraphiQL Version: latest
* OS: Ubuntu 22.04 / OSX 13.4.1
* Browser: Firefox / Chrome
* Bundler: Vite (Nuxt project)
* `graphql` Version: 16.7.1

### Anything else?

Under Chrome, the error is "DOMException: Failed to construct 'WebSocket': The URL '/api/graphql' is invalid." so my guess is that GraphQL Yoga is not using the proper URL and instead just passing the relative URL as subscriptions endpoint.

**Comment by acao** [comment]
are you able to configure these settings from graphql yoga?

https://github.com/graphql/graphiql/blob/main/packages/graphiql-toolkit/docs/create-fetcher.md#adding-graphql-ws-websockets-subscriptions

**Comment by acao** [comment]
ah ok, they do not use our `createGraphiQLFetcher()` at all. you can override the yoga subscriptions endpoint here:

https://github.com/dotansimha/graphql-yoga/blob/c29af1dbbfee45c96ebcd890cb39967bdd00a79e/packages/graphiql/src/YogaGraphiQL.tsx#L103

**Comment by acao** [comment]
this seems to be an issue for `graphql-yoga` to take up, wish I could help you, but they have their own graphiql implementation
