### ISSUE TITLE
Proper treatment of deprecated portions of schema

### ISSUE THREAD

**Issue by leebyron** [graphql/graphiql#34]

**Comment by stubailo** [comment]
Related: https://github.com/graphql/graphql-js/issues/389

**Comment by rewop** [comment]
I would like to contribute on this one. 

If I understand this issue correctly, we could add visual cues about deprecated fields in the `DocExplorer` such as strikethrough text for the name, and deprecation reasons in the description. 

Would this solve this issue? Or there is more?

**Comment by kdaigle** [comment]
@rewop as just another user of this library, I'd love to see the deprecation when looking through the Doc tray on the right. Super bonus points if the query itself got some treatment when using autocomplete to so a warning when using a deprecated field. 👍

**Comment by 1aurabrown** [comment]
hello, I deprecated some enum values in our codebase, however I don't see an accompanying message appearing in the Docs panel when I use the deprecated enum. In our implementation, the enum is being used as an argument. I'm not familiar with the graphql code base, and I'm wondering if the change that was made to display `deprecationReason`s in the Docs panel does not account for enums used as an argument. like @kdaigle, I also think it would be nice if the deprecated enum values were treated with some visual indication in the autocomplete.

In the examples below, we had some enums whose values were lowercase, and I wanted to standardize them with new uppercase values, deprecating the lowercase ones. 

---

no message in docs when using a deprecated enum value:
![screen shot 2017-01-12 at 12 20 02 pm](https://cloud.githubusercontent.com/assets/3171662/21888226/92213100-d8c3-11e6-9387-fab602cab8f9.png)

would be nice to have a strikethrough or grey color on deprecated fields:
![screen shot 2017-01-12 at 12 20 09 pm](https://cloud.githubusercontent.com/assets/3171662/21888225/921efff2-d8c3-11e6-8e84-1b3f6e113de1.png)

If someone can show me around a little bit, I'm happy to PR a change.

**Comment by asiandrummer** [comment]
@1aurabrown - Probably related to #273 - we can continue this discussion there!
