### ISSUE TITLE
[graphiql] custom tab names

### ISSUE THREAD

**Issue by mfulton26** [graphql/graphiql#3406]
GraphQL Playground allowed my team and me to define custom tab names. This was great when grouping multiple queries into one tab that use a common set of variables and headers so that as a user I can define those once and not have to copy/paste variables and/or headers between tabs.

The latest Graph_i_QL currently derives the tab name from the name of the last executed query in the tab and defaults to the first operation name if none have been executed yet. This dynamic behavior can be very confusing as the tab name changes depending on which operation I executed last.

Instead, I'd like a way to define explicit tab names, define them in my `defaultTabs` when rendering the React component, and being able to set a tab name that doesn't change on the operations defined within the tab nor on which operation I executed last.

Double-clicking or right-clicking the tab name to be able to enter a name edit mode could work well.

**Comment by dimaMachina** [comment]
Duplicate https://github.com/graphql/graphiql/issues/3608
