### ISSUE TITLE
[graphiql]  required errors show in variables for boolean fields that have default values

### ISSUE THREAD

**Issue by arichberg** [graphql/graphiql#3455]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Variables on object types that contain required boolean fields with default values will incorrectly flag missing errors on those fields if omitted from the variable definition.  This does not seem to occur with other scalar types.

![Screenshot 2023-11-07 at 12 33 53 PM](https://github.com/graphql/graphiql/assets/44817323/27d34245-955e-451b-99f7-865c9aace1c3)

### Expected Behavior

I expected not to see any validation errors telling me to include fields that have default values.
Despite the error I am able to submit my request to the server and it processes as expected.

### Steps To Reproduce

1. Point GraphiQL to a schema with an query that has an input type containing a boolean field that is required but has a default value set (see screenshot for example).
2. Create a test query in GraphiQL and populate the input type, omitting the boolean field.
3. See that GraphiQL renders an error message about the missing field.

### Environment

* GraphiQL Version: 0.19.4
* Browser: Chrome 119
* `react` Version: 17.0.2
* `graphql` Version: 16.18.1

**Comment by acao** [comment]
older versions of graphql are not compatible with the new graphql, including across breaking changes. you'll need to upgrade graphiql to at least a 1.x version, preferrably a more recent one to fix this and other issues

**Comment by arichberg** [comment]
Sorry I mixed up the react package version with the graphiql version, updated my post.  I get the same error using the latest packages.

**Comment by acao** [comment]
Hmm, I will need to double check the spec regarding this but it makes sense, it should not be required. With monaco and codemirror 6 we have a completely new approach to this, so very soon graphiql will derive variable features from json schema (thus allowing json5, yaml, etc)
