### ISSUE TITLE
[graphiql] Auto Build Query from Selecting Schema Item 

### ISSUE THREAD

**Issue by famous1337** [graphql/graphiql#3456]
I've just recently started delving into graphiql, and while the auto text completion when writing the query is great, it would also be nice to have a way to click on a schema item and have it auto fill into the query pane. This would also allow newer users to be able to "build" the query easier, while gaining familiarity with the schema.

**Comment by acao** [comment]
I will be introducing some hooks that allow you to intercept this event and add custom logic for this via plugins!

**Comment by dimaMachina** [comment]
@famous1337 use following plugin https://github.com/graphql/graphiql/tree/main/packages/graphiql-plugin-explorer
