### ISSUE TITLE
[graphiql] Support the proposed "incremental: ..." response format

### ISSUE THREAD

**Issue by rmosolgo** [graphql/graphiql#3470]
Hi! I'm trying to use GraphiQL with `@defer`. I found that it has some support built in via `enableIncrementalDelivery`, which defaults to `true`. 

However, there's a long-running proposal to change the standard response structure: https://github.com/graphql/graphql-spec/pull/742 .In that proposal, each patch would include a `{ incremental: [ ... ] }` array which includes `{ data: ... , path: ... }` entries. 

Although it's only a proposal, it was implemented in GraphQL-JS about a year ago (https://github.com/graphql/graphql-js/pull/3659) and has also been added to [urql](https://github.com/urql-graphql/urql/pull/3007) and [apollo client](https://github.com/apollographql/apollo-client/pull/10018)

It looks like GraphiQL expects `data` and `path` to be top-level keys in the server's response: 

https://github.com/graphql/graphiql/blob/7daa163978afbb3c8d110123552e029bd682ec24/packages/graphiql-react/src/execution.tsx#L218-L219

What do you think about also checking for `incremental: ...` entries there, to support this new response format? 

Thanks!

**Comment by acao** [comment]
our implementation should be updated with whatever the language spec you linked to, and in addition, whatever the graphql over http spec supports! please feel free to open a PR if you like!

**Comment by injae-kim** [comment]
Maybe resolved by https://github.com/graphql/graphiql/pull/3580?

**Comment by rmosolgo** [comment]
Looks like it to me -- thanks for sharing that!
