### ISSUE TITLE
[graphiql] Shopify GraphiQL App: Lost all my tabs with the queries

### ISSUE THREAD

**Issue by Cyclodex** [graphql/graphiql#3494]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Logged into shopify, opening the GraphiQL App, no tabs are there anymore

### Expected Behavior

Logged into shopify, opening the GraphiQL App, all my tabs are there. I had like around 10 tabs with queries

### Steps To Reproduce

1. Login shopify
2. Open GraphiQL
3. None of my tabs appear

### Environment

* GraphiQL Version: latest ?
* OS: -
* Browser: Chrome 120
* Bundler: -
* `react` Version: -
* `graphql` Version: -

### Anything else?

I am wondering who is responsible for the tabs, as it is from the **Shopify GraphiQL App**, the responsibility might be on shopify side, not sure so.

Anyone else having the same issue?
Maybe its related to the latest update, before I could log in, I had to accept an update of the application?

Any possibility to restore my lost tabs?

Thanks for any hints.

**Comment by acao** [comment]
@Cyclodex do you have the tabs storied in your local storage?

**Comment by acao** [comment]
did spotify disable tabs?

https://github.com/graphql/graphiql/pull/3408

**Comment by Cyclodex** [comment]
> @Cyclodex do you have the tabs storied in your local storage?

No idea... Can you cofigure that somewhere?
If localstorage... Then i would not know why or how, but then it could have been deleted by mistake?!
But that would be strange, as its a separate domain.

Could it be, that a app update messed up something, maybe cleaning the storage? Re initialized or something like that?

If no one else is affected, then dont worry, i will recreate the queries... But still bit sad

**Comment by Cyclodex** [comment]
PS: i can have tabs, just all my old ones are gone somehow

**Comment by Cyclodex** [comment]
Okey - interesting. I just lost the tabs again, I had at least 2 tabs yesterday.

Now looking at the storage, it looks like the tabs and queries are saved in the local storage key `graphiql:tabstate` right?
Does that get overriden somehow? I will monitor the situation a bit, currently it looks like this:

<img width="1242" alt="image" src="https://github.com/graphql/graphiql/assets/840929/776f1638-7476-4080-a600-74d52072de13">

**Comment by acao** [comment]
it shouldn't have been overridden... this is very strange! if you can find a repo for shopify's graphiql implementation, or have a support person reach out to me here in this issue discussion we can work on it together. it may be that a recent release caused a bug, the release allows disabling tabs, but I can't see anything that would cause this issue if they aren't using this new option

**Comment by Cyclodex** [comment]
Nope, basically empty history , but honestly I never checked the history until now! Only the few entries I did today so it looks.

Yes maybe something changed with namespaces or similar. I just try to reach out to shopify support, maybe they can tell me where I should place the request.

**Comment by Cyclodex** [comment]
Okey, they want me to monitor the situation and report if it happens again. I gave them all information I had at hand...

To note it here as well:
I am sure I had the tabs on 1.12.2023 (1.st December).
Yesterday I had no tabs anymore - Created again 2 tabs
This morning they were gone again. Currently I have around 6 tabs.

Lets see if something is happening in the upcoming hours/days :/

**Comment by acao** [comment]
[here](https://graphiql-test.netlify.app) for example, if I add new tabs and refresh, they are still there. not sure what would make the tabs disappear unless they have a custom storage implementation. without knowing the details of shopify's implementation, there isn't much I can do to help you, sorry!

**Comment by Cyclodex** [comment]
Nothing happend yet to my tabs, all seems to be stable now

**Comment by Cyclodex** [comment]
Hi @acao , I also think it could be related to localstorage get cleaned up somehow. Tabs are still there, I will close the issue, as no one else has reported issues as well. Thanks anyway for your help and cooperation!
