### ISSUE TITLE
[vscode-graphql] 🐞 Language Server crashes when presented with Svelte files containing any JS/TS code

### ISSUE THREAD

**Issue by TheKvist** [graphql/graphiql#3496]
Edit: just realized this is of an issue in `vscode-graphql` and updated the issue title, but I can't relabel anymore now

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Since the latest update of `graphql.vscode-graphql`, the LSP started crashes immediately when a Svelte file containing any code in a `<script>` tag is opened in VSCode, regardless of the actual code. The stack trace is:

```
TypeError: Ji.getModifiers is not a function
    at B7t (/Users/user/.vscode/extensions/graphql.vscode-graphql-0.8.22/out/server/index.js:4631:148)
    at age.handleVariableStatement (/Users/user/.vscode/extensions/graphql.vscode-graphql-0.8.22/out/server/index.js:4636:8914)
    at Q (/Users/user/.vscode/extensions/graphql.vscode-graphql-0.8.22/out/server/index.js:4647:2226)
    at /Users/user/.vscode/extensions/graphql.vscode-graphql-0.8.22/out/server/index.js:4647:3559
    at f (/Users/user/.vscode/extensions/graphql.vscode-graphql-0.8.22/out/server/index.js:4467:30007)
    at Object.p [as forEachChild] (/Users/user/.vscode/extensions/graphql.vscode-graphql-0.8.22/out/server/index.js:4467:33871)
    at Z.forEachChild (/Users/user/.vscode/extensions/graphql.vscode-graphql-0.8.22/out/server/index.js:4498:84222)
    at K4n (/Users/user/.vscode/extensions/graphql.vscode-graphql-0.8.22/out/server/index.js:4647:3543)
    at y9t (/Users/user/.vscode/extensions/graphql.vscode-graphql-0.8.22/out/server/index.js:4693:3638)
    at gFn (/Users/user/.vscode/extensions/graphql.vscode-graphql-0.8.22/out/server/index.js:4700:2873)
```

### Expected Behavior

The LSP should be able to process Svelte files correctly, or at least it should preferably not crash when a parser fails and be able to serve completions for unaffected files.

### Steps To Reproduce

1. Create a new project in VSCode with `graphql.vscode-graphql` enabled
1. Create a new Svelte file anywhere in the project
1. Add some JavaScript to the file:
   ```svelte
   <script>
     let foo = 'bar'
   </script>
   ```
1. Restart the language server by **Show All Commands > VSCode GraphQL: Manual Restart**, or alternatively, by closing VSCode and re-opening the project
1. The language server crashes 5 times and VSCode gives up restarting it

### Environment

* LSP Server Version: latest / `2.11.7` in local tests
* OS: Ubuntu 22.04 / Windows 11 / macOS Sonoma 14.1.1 
* LSP Client: `vscode-graphql` at version `v0.8.22`

### Anything else?

After a bit of digging around, the issue is that `svelte2tsx`, used by `graphql-language-service-server`, requires TypeScript as a peerDependency with the version spec `^4.9.4 || ^5.0.0`. This project's root package.json requires TypeScript in version `^4.6.4` only, but `svelte2tsx` uses TypeScript compiler API not yet available in that version (namely, the missing `getModifiers` function mentioned in the stack trace, among a few others).

Testing with a clean reproduction project let me reproduce both, the error with an "outdated" TS version as well as confirm upgrading TS to at least `4.8.4` fixed it for me, even though I suppose since `^4.9.4` is required, it should also be used.

When then looking for a minimally invasive way to fix it for the language server, upgrading TypeScript for the entire project broke the build, but explicitly requesting Version `^4.9.4` in the `vscode-graphql`'s package.json solves the problem.

If desired, I can provide a PR with this fix right away. Just wanted to check if there may be any concerns.

**Comment by acao** [comment]
hey thanks for looking into this!

it appears this bug was introduced by this PR
https://github.com/graphql/graphiql/pull/3204

it isn't detectable in our tests because of the esbuild bundle it would seem. a PR would be awesome! you may need to add `typescript` to the esbuild externals list
