### ISSUE TITLE
Update GraphiQL storage prop type

### ISSUE THREAD

**Issue by tlvenn** [graphql/graphiql#350]
The current prop type for storage is:
```
storage: PropTypes.shape({
      getItem: PropTypes.func,
      setItem: PropTypes.func
    }),
```

but now GraphiQL also leverage the `localStorage.removeItem` method as seen in:
> https://github.com/graphql/graphiql/blob/master/src/components/GraphiQL.js#L485

So the prop type for storage should read:
```
storage: PropTypes.shape({
      getItem: PropTypes.func,
      setItem: PropTypes.func,
      removeItem: PropTypes.func
    }),
```

**Comment by AGS-** [comment]
@tlvenn, is there any particular use case you have in mind for this?

cc: @asiandrummer @wincent @leebyron

**Comment by tlvenn** [comment]
Hi @AGS- yes we stumbled on that one because https://github.com/OlegIlyenko/graphiql-workspace is decorating localStorage and providing GraphiQL with an HoC.
> https://github.com/OlegIlyenko/graphiql-workspace/blob/master/src/config.js

**Comment by AGS-** [comment]
Oh cool! Awesome project.
