### ISSUE TITLE
Is `@graphiql/toolkit` ESM or not?

### ISSUE THREAD

**Issue by s100** [graphql/graphiql#3506]
After running `npm install @graphiql/toolkit` I see a directory `esm` and inside that I see numerous `*.js` files with the compiled code of the package. These source files use ES Modules syntax (`import` and `export`). Good stuff. But midway through `esm/create-fetcher/lib.js` is this line:

https://github.com/graphql/graphiql/blob/88ae24321dbf7b5810ffdb1943efde44f6b114be/packages/graphiql-toolkit/src/create-fetcher/lib.ts#L77-L79

So is this an ES module or not? Please could you explain what's going on here. This causes a ReferenceError, surely?

**Comment by dimaMachina** [comment]
Fixed in https://github.com/graphql/graphiql/releases/tag/%40graphiql%2Ftoolkit%400.11.0
