### ISSUE TITLE
[vscode-graphql-syntax] (v1.2.3) triple double-quote comment syntax broken for TypeScript 

### ISSUE THREAD

**Issue by TiE23** [graphql/graphiql#3515]
With v1.2.3 (possibly originating in #3490, though I am not certain) support for triple double-quote comments, which are used to generate doc comments for the schema (whether it's a built-in feature for Prisma or an undocumented feature for graphql-codegen I'm not sure).

### Behavior in v1.2.2
![Screenshot 2024-01-25 at 12 33 34 AM](https://github.com/graphql/graphiql/assets/2433505/4d79158a-f91d-4311-babb-ba41435e3235)

### Behavior in v1.2.3
![Screenshot 2024-01-25 at 12 32 57 AM](https://github.com/graphql/graphiql/assets/2433505/9016e35e-3ef2-43c0-89d2-6ab2b603b12d)

It appears that if the `"""` comment is placed inside a curly brace, it works fine. But in the root scope (?), it appears to break.

How this is useful to me:
<img width="359" alt="image" src="https://github.com/graphql/graphiql/assets/2433505/bea2e8be-c53d-44c4-bbb2-21b776f73221">

<img width="294" alt="image" src="https://github.com/graphql/graphiql/assets/2433505/b9a22dc0-608d-43d8-8a1e-0e81429d0518">

Current work-around is to install v1.2.2
![image](https://github.com/graphql/graphiql/assets/2433505/f5398e86-5e53-4462-8cde-64a47bb54f7b)

**Comment by acao** [comment]
ah yes, it appears to be this:

https://github.com/graphql/graphiql/pull/3490/files#diff-89a0bf9dd1dfa9498b6e3f566257d012e1bfff0cb6b663735aac011eaae74dbcR50

which was introduced to fix inline double quote queries like `graphql("#query { id }")`

can you open a PR that adds this failing case to the test suite? I can take a look after work today

**Comment by TiE23** [comment]
I hope this is what you needed!
* #3517

**Comment by acao** [comment]
@TiE23 thank you! I will finish fixing this for now, there is another huge PR someone has proposed for the textmate grammars which does not solve this problem, so I will solve this one first!

**Comment by acao** [comment]
`1.3.2` will be your fix version!
