### ISSUE TITLE
Hardcoded CSS in app.css conflicts with CodeMirror theme

### ISSUE THREAD

**Issue by ianks** [graphql/graphiql#352]
There are certain CSS declarations which conflict with theme declarations, causing the themes to render improperly. For example, in [app.css](https://github.com/graphql/graphiql/blob/317fa6cca645bf02d59b8cdb18ee2fd15d04d5c9/css/app.css#L526), `.cm-punctuation` is set which makes the punctuation illegible for dark themes. These styles should most likely be specific to the graphiql `default` theme.

**Comment by asiandrummer** [comment]
The labels ;)
@ianks that makes sense I think - I can take a look at this one unless someone wants to tackle this?

**Comment by thomasheyenbrock** [comment]
The CSS used to style the GraphiQL UI has been completely overhauled with `graphiql@2`. Closing this issue as it's probably not reproducible anymore.
