### ISSUE TITLE
[vscode-graphql-syntax] Ruby `GRAPHQL` heredoc breaks syntax higlighting in the file

### ISSUE THREAD

**Issue by danieldiekmeier** [graphql/graphiql#3524]
### Current Behavior

A few weeks ago, the `vscode-graphql-syntax` package added Ruby support (#3490), but I think something is not quite right.

This is what the example file `packages/vscode-graphql-syntax/tests/__fixtures__/test.rb` looks like in my VS Code, running the latest extension v1.3.1:

<img width="583" alt="image" src="https://github.com/graphql/graphiql/assets/2098462/e37c6450-628d-4dee-82cd-91b6910608e3">

As you can see, while the GraphQL is highlighted, it breaks the highlighting of following Ruby code.

Looking at the tests, I noticed how the snapshots for Ruby and e.g. Python are very different.

**Ruby (actual GraphQL lines don't have an annotation on the right):**

https://github.com/graphql/graphiql/blob/25c3bfd8c4e5e74625b756cbbba54fc3add42533/packages/vscode-graphql-syntax/tests/__snapshots__/ruby-grammar.spec.ts.snap#L7-L13

**Python (actual GraphQL lines are annotated):**

https://github.com/graphql/graphiql/blob/25c3bfd8c4e5e74625b756cbbba54fc3add42533/packages/vscode-graphql-syntax/tests/__snapshots__/python-grammar.spec.ts.snap#L9-L14

It looks like the Ruby grammar recognizes the start of the Heredocs also as the _end_ of the Heredoc, maybe confusing itself in the process? I don't understand a lot about the grammars, and fiddling around with the Regexes I wasn't able to produce a better result.

### Expected Behavior

I'd expect the closing `GRAPHQL` at the end of the Heredoc to end the code block and reactivate the Ruby syntax highlighting.

**Comment by krishantaylor** [comment]
I was able to fix this locally by removing the ruby syntax addition entirely (edit `package.json` and remove the grammar file). The grammar from the "Ruby LSP" extension hands things off to the graphql syntax highlighter correctly, and matches for both the `GRAPHQL` and `GQL` heredoc identifiers. Alternatively, just switching to `GQL` identifiers might do the trick, as "Ruby LSP" will still hand things off this extension without triggering its problematic grammar—which is only triggered by `GRAPHQL`.

**Comment by berniechiu** [comment]
`GQL` doesn't seem to highlight correctly either

**Comment by acao** [comment]
if someone wants to fix it, it is just a textmate grammar, so it's a set of regular expressions. should i just remove it for now? is no highlighting better than the current bugs?

**Comment by danieldiekmeier** [comment]
As @krishantaylor said, it’d still get highlighted because Ruby LSP hands it off correctly. (At least for me, you probably need to have the Ruby LSP extension.) It would definitely be better than breaking following Ruby code for the rest of the file.

**Comment by krishantaylor** [comment]
I'd rather see it removed. Ruby LSP is the current [recommended extension](https://code.visualstudio.com/docs/languages/ruby#_install-the-ruby-lsp-extension-in-vs-code) for ruby anyway.

**Comment by acao** [comment]
removal it is!

**Comment by acao** [comment]
here is the proposal to remove ruby and ruby markdown block support!

https://github.com/graphql/graphiql/pull/3592

**Comment by danieldiekmeier** [comment]
Thank you for fixing this! I didn't think to close this issue, but it has been working great for me since v1.3.6 was released. Thank you! 🧙‍♂️
