### ISSUE TITLE
Don't export react with cdn bundle

### ISSUE THREAD

**Issue by acao** [graphql/graphiql#3555]
we don't need this line, because the CDN example already shows importing `React` at `React` global umd namespace, so `React` is available without bundling it with `graphiql`/`graphiql.min` `.js`
https://github.com/graphql/graphiql/blob/4e92739d53c4e304b52c34edc8c5788bdf476788/packages/graphiql/src/cdn.ts#L47

this will require tweaking the plugin vite configs as well which are configured for this

**Comment by dimaMachina** [comment]
@acao this is not `react` but `@graphiql/react`
