### ISSUE TITLE
[lsp-server] Support go to definition for implementation first graphql setups

### ISSUE THREAD

**Issue by sbdchd** [graphql/graphiql#3558]
Basically if I have a schema first setup, I want to be able to click into a type in a graphql query string

```js
import React from 'react';
import { useQuery } from '@apollo/client';
import { gql } from '@apollo/client';

const GET_USERS = gql`
  query GetUsers {
    users {
      id
      name
      email
    }
  }
`;

const UsersList = () => {
  const { loading, error, data } = useQuery(GET_USERS);
  return null;
}
```

When configured, clicking `users` should open the implementation rather than the graphql schema file.

relay has this via a vscode config option to call a program that returns the location as text

https://github.com/facebook/relay/pull/4434

**Comment by acao** [comment]
@sbdchd you need to disable the `cacheSchemaForLookup` setting in vscode and/or graphql config, wherever you have set it

**Comment by patrick91** [comment]
@acao how does this work? I want to add support for Go To Definition from a GraphQL file to the definition for Strawberry GraphQL 😊

**Comment by acao** [comment]
the jump to definition works by looking through all the graphql strings in a peoject to find the matching type name and jumping to the file

if you want it to jump to a source file instead of a GraphQL string, I will introduce the configurable locateCommand option as per relay lsp

**Comment by patrick91** [comment]
@acao ah yes, that would be great!
