### ISSUE TITLE
vscode-graphql-syntax javascript - line between graphql( and ` character breaks syntax highlighting

### ISSUE THREAD

**Issue by osdiab** [graphql/graphiql#3559]
Hi all, I use TypeScript with the syntax highlighting plugin and I found an annoying issue - if my code looks like this:

```
graphql(`
  query asdf { ... }
`)
```

then syntax highlighting works, but when prettier formats it like this:

```
graphql(
  `
    query asdf { ... }
  `)
```

then syntax highlighting doesn't show up at all. Any idea if there's a way to configure syntax highlighting to understand that these are equivalent? Or maybe make the syntax highlighter more lenient to newline characters between the `graphql(` and the tilde?

**Comment by TallTed** [comment]
(To ease future confusion, note that ``` ` ``` is a [backtick](http://dbpedia.org/resource/Backtick), also known as a backquote, grave, or grave accent; `~` is a [tilde](https://dbpedia.org/page/Tilde).)

**Comment by acao** [comment]
@osdiab this was just a regex issue in the textmate grammars, we have re-released this fix again, enjoy!
