### ISSUE TITLE
[graphiql] bump markdown-it for SNYK-JS-MARKDOWNIT-6483324

### ISSUE THREAD

**Issue by hubofgitongithub** [graphql/graphiql#3574]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Anything else?

graphiql is a subdependency of a npm package we are using (`@backstage/plugin-api-docs` for instance). Our security scanners are triggering on graphiql, as it is using an unsafe version of `markdown-it` (version 12.x.x). Please bump this package to 13.0.2 or higher, as can be read here: https://security.snyk.io/vuln/SNYK-JS-MARKDOWNIT-6483324

**Comment by eMerzh** [comment]
it seems to have been addressed in #3569 and released already
