### ISSUE TITLE
[lsp-server] 🐞 Constant syntax errors if a file is named `exports.graphqls`

### ISSUE THREAD

**Issue by cezarmathe** [graphql/graphiql#3586]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Naming a file `exports.graphqls` makes the editor throw constant errors at you.

```
Syntax Error: Expected Name, found "}".
```

### Expected Behavior

No syntax errors.

### Steps To Reproduce

1. Create a file named `exports.graphqls`.
2. Open it and try to create any schema.

For example:

```graphql
enum DataExportType {}

extend type Query {
	exportData(ty: DataExportType!): Boolean!
}
```

### Environment

* LSP Server Version: `v1.3.5` (extension version - is this what you're looking for?)
* OS: MacOS 14.4.1 (Sonoma)
* LSP Client: `vscode-graphql`

### Anything else?

If I rename the file to `export.graphqls` the issue disappears.

**Comment by acao** [comment]
you have an empty enum so it will throw syntax errord
