### ISSUE TITLE
[lsp-server] Add configuration to disable/enable for certain files.

### ISSUE THREAD

**Issue by VrishYT** [graphql/graphiql#3591]
## Current Behavior (if applicable)
Highlighting breaks using React and Amplify GraphQL queries within a .ts or .tsx file.

![image](https://github.com/graphql/graphiql/assets/29337613/a3f33758-a6b5-415c-bab6-b381a6389506) 
With the extension (syntax highlighting goes all weird and broken)

## Desired Behavior
Allow disabling the VSCode extension for .ts and .tsx files or limit to only .graphql files.

![image](https://github.com/graphql/graphiql/assets/29337613/f841c7e6-2260-4047-90a6-48dd145ef953) 
WIthout the extension.

**Comment by acao** [comment]
we have never supported queries like this, sorry! they need to be template string delimited.

our syntax highlighting comes from textmate grammars, so to configure this, please see the vscode documentation
