### ISSUE TITLE
[lsp-server] 🐞VSCode Python autocomplete  does not work

### ISSUE THREAD

**Issue by woprandi** [graphql/graphiql#3609]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I was able to get autocomplete inside .graphql file but not inside .py files. I saw https://github.com/graphql/graphiql/blob/main/packages/vscode-graphql-syntax/tests/__fixtures__/test.py but nothing worked

### Expected Behavior

Fonctionnal autocomplete with python files

### Steps To Reproduce

1. Get fonctionnal autocomplete with .graphql files
2. Test with a python file

### Environment

* LSP Server Version: latest
* OS: Fedora 40
* LSP Client: vscode-graphql

**Comment by nrbnlulu** [comment]
have you managed to fix this?

**Comment by acao** [comment]
@nrbnlulu we do not currently offer support for autocompletion in python, only syntax highlighting
