### ISSUE TITLE
[lsp-server] vscode-graphql triggers large amounts of requests to my graphql server for bulk file change events in 0.11.0

### ISSUE THREAD

**Issue by Slessi** [graphql/graphiql#3622]
## Current Behavior (if applicable)

When I use `graphql-codegen` to generate types from my schema whilst VSCode is open, `vscode-graphql` automatically sends tens or hundreds of requests to my backend server to get the introspection schema.

In this video, I have two terminals running. Top terminal is my backend server which prints a log everytime it receives a request. Bottom terminal is me just generating types with `graphql-codegen`. You will see on `0.11.0` my backend server gets spammed, but on `0.9.3` it does not.

https://github.com/graphql/graphiql/assets/3223500/758b8773-8cc6-4df9-bfa0-d3ac5911b6c4

## Desired Behavior

A change to my generated types should not cause `vscode-graphql` to need to re-request introspection information. If it does, it should certainly not need to do it more than once.

My `graphql.config.cjs`:

```js
module.exports = {
  projects: {
    default: {
      schema: ['http://localhost:8080/graphql'],
      documents: ['src/**/!(*.d).{ts,tsx}', '!src/types/graphql.ts'],
      extensions: {
        codegen: {
          hooks: {
            afterOneFileWrite: ['prettier --write --ignore-path=.prettierignore'],
          },
          config: {
            withHooks: true,
            withHOC: false,
            withComponent: false,
            avoidOptionals: {
              field: true,
              inputValue: false,
              object: true,
              defaultValue: true,
            },
            scalars: {
              Time: {
                input: 'Date | string',
                output: 'string',
              },
            },
          },
          generates: {
            'src/types/graphql.ts': {
              plugins: ['typescript', 'typescript-operations', 'typescript-react-apollo', 'fragment-matcher'],
            },
          },
        },
      },
    },
  },
};
```

**Comment by acao** [comment]
@Slessi looking into this today, the new schema polling should not be behaving like this on watch events. Something is resetting the cache for every watched file change, that should not be

**Comment by acao** [comment]
I have an update! I've identified what might be the _true_ source of the issue, which is `MessageProcessor.cacheConfigSchemaFile()` - this method is what re-writes the cached SDL file for mixed/network schema config scenarios, and it just needs to be debounced, along with ensuring the debounce-ish effect of the short TTL schema LRU cache, hoping to have a working fix tomorrow as I juggle a few unexpected disruptions this week

**Comment by acao** [comment]
today I'm working on manually re-creating _exactly_ this bug with a decently sized project, instead of just mimicking it, so I can be sure we have a proper fix. sorry it's taking so long!

**Comment by acao** [comment]
If anyone wants to try this out, here is a vsix bundle renamed to .zip so i could upload it.  just rename from .zip to .vsix. i guess the mime types of .vsix file are application/zip anyways!


[vscode-graphql-0.11.1.zip](https://github.com/user-attachments/files/16118661/vscode-graphql-0.11.1.zip)

side note re: vscode prereleases: the last time i tried to do a vscode pre-release it really borked changesets and our release automation, because vscode extensions don't support full semver

**Comment by acao** [comment]
@Slessi thank you for asking, I had overlooked this release error!

https://github.com/graphql/graphiql/actions/runs/10197678455/job/28211011654#step:6:422

Need to fix this and run again!

**Comment by dmarkow** [comment]
@acao Definitely still happening for me with the latest version (0.11.3). Not nearly as often, but just now my dev API server got hammered with hundreds of introspection requests from the plugin and crashed.

**Comment by f-elix** [comment]
Same here! Still happening at version 12.0. My server timed out because of all the introspection requests.

**Comment by artaommahe** [comment]
@acao the issue is still here with `v0.12`, just killed our backend's pods doing several typer update in a row
