### ISSUE TITLE
[graphiql] Keep multiple responses from subscription

### ISSUE THREAD

**Issue by Sytten** [graphql/graphiql#3641]
**Description**

Currently I am using graphl-playground, its support of subscription displays all the responses received.
This is very useful since subscriptions can be very busy and you might miss some responses.
We might want to add a setting for the number of responses to keep in this history.

**Comment by Sytten** [comment]
@acao please link the original issue :)

**Comment by acao** [comment]
https://github.com/graphql/graphiql/issues/2909

**Comment by Sytten** [comment]
This is not exactly the same issue though, the issue is keeping the tab alive when switching.
What I am asking can be done separately, it is about keeping multiple responses on the right panel.

**Comment by acao** [comment]
@Sytten ok in that case, the original duplicate issue is from 2017, I will find it when I get home, but this feature is requested almost monthly since the project was released
