### ISSUE TITLE
Enhancement: title IDE for browser fuzzy autocomplete (chrome)

### ISSUE THREAD

**Issue by janat08** [graphql/graphiql#365]
Chrome will provide autocomplete options that is convenient if the page has unique title which get also parsed against address bar terms. It should probably specify itself as "graphql IDE" so that all other results from documentation don't overwhelm autocomplete.

PS graphiql is exactly specific enough, but difficult to recognize as unique with just the letter "i" setting it apart.

**Comment by asiandrummer** [comment]
@janat08 I'm not sure if I understand your request - what's the autocompletion behavior you're looking for exactly? Could you provide some examples?

**Comment by janat08** [comment]
In chrome typing "enhancement IDE graphql" will bring up this page because title of this page reads as such, and for convenience sake I thought that you could provide title tags for the localhost/graphiql page.

**Comment by AGS-** [comment]
@janat08 I don't think this would be the best approach since GraphiQL is meant to be more of an embeddable full screen React component, so I think it's more up to the implementation to take care of this.

**Comment by asiandrummer** [comment]
@janat08 - I agree with @AGS-. GraphiQL is just a React component, and how the page provides a html title tag is purely up to developers. I'm fine with having a html title tag for our example app though if that's what you were asking.
