### ISSUE TITLE
[graphiql] CommonJS syntax in ESM build

### ISSUE THREAD

**Issue by janitza-anjakr** [graphql/graphiql#3668]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

in our dev environment, we integrated GraphiQL in a React app (using Vite). While everything runs smoothly in dev mode, runtime errors occur in our final build when executing subscriptions. In the console, we get the following error messages: "require is not defined"
 
We did some digging and indeed found CommonJS syntax in the esm artifact, see for example: node_modules/@graphiql/toolkit/esm/create-fetcher/lib.js (line 58)
 
Luckily for us, vite offers an option to transform those require statements when setting build.commonjsOptions.transformMixedEsModules to true in our vite.config.ts.

### Expected Behavior

We expect that graphiql offers an esm build without CommonJS syntax.

### Environment

"@graphiql/toolkit": "^0.9.1",
"graphiql": "^3.3.2",

### Anything else?

Thanks in advance for your help.

**Comment by dimaMachina** [comment]
should be fixed in https://github.com/graphql/graphiql/releases/tag/%40graphiql%2Ftoolkit%400.11.0
