### ISSUE TITLE
[graphiql] [security vulnerability] GraphiQL leaking query in the URL

### ISSUE THREAD

**Issue by larscyl** [graphql/graphiql#3711]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When using GraphiQL, the whole query and content updates the URL to reflect the query in the URL query parameter `?query=`.

![image](https://github.com/user-attachments/assets/ae0ed1f3-b23c-42d9-94a9-c2313358f12c)

If someone develops or debugs with sensitive data like passwords, keys,... these are then effectively leaked in the:
- Browsers History
- Network logs (which VPN's may have access to)

### Expected Behavior

GraphiQL should not reflect the query in the URL, or make it an option disabled by default.

### Steps To Reproduce

1. Open GraphiQL
2. Write any query
3. Notice that the URL reflects the query and its contents

### Environment

* GraphiQL Version: 3.4.1

**Comment by acao** [comment]
@larscyl it is disabled by default, only enabled in our demos

**Comment by larscyl** [comment]
@acao thanks for your swift response! Can you point out which option this is? I can't seem to locate it in the config API.
I'm using `graphql-yoga/node`, so I'll create a ticket over there thereafter.
