### ISSUE TITLE
The normal and minified cdn files are the same size

### ISSUE THREAD

**Issue by thomas9911** [graphql/graphiql#3737]
The minified and normal files (js and css) are the same size. This doesn't sound correct.

Screenshot from jsdelivr 
![Screenshot from jsdelivr](https://github.com/user-attachments/assets/78d0c015-29af-48a6-9d7a-e64c73526696)

**Comment by dimaMachina** [comment]
Yeah, I noticed this too in discord, fixed in GraphiQL v4 alpha https://discord.com/channels/625400653321076807/966768858402816020/1270379256928800831
