### ISSUE TITLE
Shortcut to prettify the query

### ISSUE THREAD

**Issue by astorije** [graphql/graphiql#379]
After typing a query and before executing it by hitting <kbd>⌘</kbd><kbd>↩</kbd>, it is often useful to prettify the query, at least to make sure it's correctly formatted before sending it to the server.

At the moment, one has to click on the button but it would feel very natural to use a shortcut for that.
Not sure what shortcut specifically though, but if it could use the same modifier than running the query, that would make for an even nicer experience.

Thoughts?

**Comment by asiandrummer** [comment]
@astorije yeah, I can see how a shortcut would be helpful! Not sure if we want to start right away with prettifying every query runs - I'd like to think of the query prettifying as code linting, which serves a good enough purpose for optional suggestions, and is not invasive. Is there a common IDE shortcut for automatically reformatting code?

**Comment by AGS-** [comment]
@asiandrummer, basically all IDEs use different hotkeys for autoformat. ⇧⌘F (VS family), ⌥⇧⌘L for Intellij, ⌥⌘L for Nuclide (I think).

**Comment by asiandrummer** [comment]
`Shift-Ctrl-L` and `Shift-Cmd-L` sounds legit to me then. We can start with that for now.

I'd love for a contribution here if you're down for that @astorije ;)

**Comment by astorije** [comment]
@asiandrummer, I was debating between completely focusing on preparing my talk happening in less than a week, and give this a try considering I could really make use of it during my talk. Also, I pretty much know nothing about React.
So in the end, I still gave it a shot in #385 😅 

Hope you'll like it!

**Comment by astorije** [comment]
@asiandrummer, pretty ping? Did you get a chance to look at my PR? :)
Thanks!
