### ISSUE TITLE
[graphiql] Using ToolbarButton in toolbar/additionalContent throws an error

### ISSUE THREAD

**Issue by receter** [graphql/graphiql#3796]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When passing a `ToolbarButton` to the `toolbar` prop of `<GraphiQL>` (via `additionalContent`) an error is thrown:

> Uncaught Error: `Tooltip` must be used within `TooltipProvider`

```jsx
<GraphiQL
//…
        toolbar={{
          additionalContent: <ToolbarButton label="Hello" />,
        }}
//…
      />
```

At least this is the case for https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-graphiql-explorer/src/app.jsx#L173

### Expected Behavior

Using the `ToolbarButton` is possible without an error

### Steps To Reproduce

```jsx
<GraphiQL
//…
        toolbar={{
          additionalContent: <ToolbarButton label="Hello" />,
        }}
//…
      />```

### Environment

* GraphiQL Version: 3.7.1 (@graphiql/react@0.26.2)
* OS: all
* Browser: all
* Bundler: 
* `react` Version:
* `graphql` Version:


### Anything else?

_No response_

**Comment by dimaMachina** [comment]
https://github.com/graphql/graphiql/blob/2a9a77c03da60e79f7273be850aa23291a2ced0a/packages/graphiql/src/GraphiQL.tsx#L86-L89

**Comment by receter** [comment]
I tried it in my test setup with:

```
// "@graphiql/react": "^0.28.2",
// "graphiql": "^3.8.3",
import { ToolbarButton } from "@graphiql/react"
import { GraphiQL } from "graphiql"
…
    <GraphiQL
…
      toolbar={{
        additionalComponent: refreshState.enableRefresh
          ? () => <ToolbarButton>
            Test
          </ToolbarButton>
          : undefined,
      }}
…
```
An still get a "Error: `Tooltip` must be used within `TooltipProvider`"
