### ISSUE TITLE
[graphiql] Variable \"$episode\" got invalid value \"\"; Value \"\" does not exist in \"Episode\" enum."

### ISSUE THREAD

**Issue by baonguyen212002** [graphql/graphiql#3799]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```
query HeroNameAndFriends($episode: Episode) {
  hero(episode: $episode) {
    name
    friends {
      name
    }
  }
}

=====
{
  "errors": [
    {
      "message": "Variable \"$episode\" got invalid value \"\"; Value \"\" does not exist in \"Episode\" enum.",
      "locations": [
        {
          "line": 1,
          "column": 26
        }
      ]
    }
  ]
}
```

### Expected Behavior
```
{
  "data": {
    "hero": []
}
```
### Steps To Reproduce
```
{
  "episode": ""
}
```
### Environment

* GraphiQL Version:
* OS:
* Browser:
* Bundler:
* `react` Version:
* `graphql` Version:

**Comment by acao** [comment]
this would appear to be an encoding issue in your graphql server, however this is the GraphiQL repo, which is just a web/IDE client. 

if you are still stuck, try our generalized #tech-help channel on discord:
https://discord.gg/Ns5kABgg
