### ISSUE TITLE
[graphiql] Disable fetch on initial loading

### ISSUE THREAD

**Issue by palyvodaBoi** [graphql/graphiql#3801]
It would be nice to have the possibility to disable fetch on the first/initial loading of the component.
I see no need for this, and I want to disable this behavior
I didn't find this info in the documentation. Maybe I missed something?

**Comment by acao** [comment]
@palyvodaBoi so you don't want autocompletion, validation or hover? you can just supply an empty GraphQLSchema to schema prop then

**Comment by palyvodaBoi** [comment]
@acao, it seems like this is what I need. Thank you for such a quick response!
