### ISSUE TITLE
[graphiql] Query building stopped working on version 3.8.1

### ISSUE THREAD

**Issue by bernardowerneck** [graphql/graphiql#3836]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When selecting the query items from the sidebar, it does not build the corresponding query in the code editor.

### Expected Behavior

It should build the query correctly, based on the selected return items and filters

### Steps To Reproduce

This started happening recently, so I believe it is related to the latest release, version 3.8.1, that is currently in production

### Environment

* GraphiQL Version: 3.8.1
* OS: Ubuntu 24.04
* Browser: Firefox 133.0.3
* Bundler: I'm using the cdn version hosted at https://unpkg.com/graphiql/graphiql.min.js
* `react` Version: I'm using the cdn version hosted at https://unpkg.com/graphiql/graphiql.min.js
* `graphql` Version: I'm using the cdn version hosted at https://unpkg.com/graphiql/graphiql.min.js

**Comment by dimaMachina** [comment]
Thanks for reporting, I can confirm, the query editor only updates the first clicked field, this an issue due recent enabled `react-compiler`, fix is coming and will be released in few minutes

**Comment by dimaMachina** [comment]
@bernardowerneck try now 🙏

**Comment by bernardowerneck** [comment]
@dimaMachina its not working yet for me. Is it a problem in the cdn build? We are using the embedded graphiql from spring graphql, which points to the one hosted in https://unpkg.com/graphiql/graphiql.min.js. Is mantained by this repo, or should I open issue somewhere else? Do you know of a cdn that is working?

**Comment by dimaMachina** [comment]
seems I did a release only for `@graphiql/react` but not for `graphiql`, will do it right now too, sorry!

**Comment by Trsa993** [comment]
Fixed, thanks!

**Comment by dimaMachina** [comment]
thank you, lmk if you found more regression, pushing a fix for another one 😅 https://github.com/graphql/graphiql/issues/3842
