### ISSUE TITLE
[graphiql] Regression in documentation explorer search when clicking on results in dropdown

### ISSUE THREAD

**Issue by emmenko** [graphql/graphiql#3842]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When searching in the documentation explorer, attempting to click on one of the items in the dropdown doesn't yield anything. The dropdown disappears and the search results (documentation) are not changed.

### Expected Behavior

When searching in the documentation explorer, attempting to click on one of the items in the dropdown should go to the selected definition and the search documentation should change.

### Steps To Reproduce

1. Open the Documentation explorer
2. Click on the search input
3. Type something
4. Click with the cursor on one of the dropdown options
5. The dropdown disappear
6. Nothing happens, the search results (documentation) don't change 

### Environment

* GraphiQL Version: `3.8.1`
* OS: macos v14
* Browser: Arc
* Bundler:
* `react` Version: `17.0.2`
* `graphql` Version: `16.9.0`
* `@graphiql/plugin-explorer` Version: `3.2.5`
* `@graphiql/react` Version: `0.28.1`
* `@graphiql/toolkit` Version: `0.11.1`

### Anything else?

This actually works with the following versions

* `@graphiql/plugin-explorer` Version: `3.2.3`
* `@graphiql/react` Version: `0.27.1`
* `@graphiql/toolkit` Version: `0.11.1`
* `graphiql` Version: `3.8.0`

It seems it was fixed some time ago (#3364) but the related code was changed / removed in #3821.

**Comment by dimaMachina** [comment]
@emmenko thanks for reporting, fixed in https://github.com/graphql/graphiql/releases/tag/graphiql%403.8.3, lmk if you'll found more regression

**Comment by emmenko** [comment]
Thanks for the quick fix, it works as expected now 🤗
