### ISSUE TITLE
Improve autocompletion for variable types

### ISSUE THREAD

**Issue by marktani** [graphql/graphiql#389]
Consider this query:

```graphql
query posts {
  allPosts(first: 3) {
    id
    imageUrl
    description
  }
}
```

If I now want to introduce a variable, I start typing

```graphql
query posts($first: {
  allPosts(first: 3) {
    id
    imageUrl
    description
  }
}
```

after `$first:` I get autocompletion as expected. However as soon as I type something afterwards, like `$first: In` autocompletion cannot be opened anymore. You can use [this playground](https://api.graph.cool/simple/v1/ciwce5xw82kh7017179gwzn7q?query=query%20posts%20%7B%0A%20%20allPosts(first%3A%203)%20%7B%0A%20%20%20%20id%0A%20%20%20%20imageUrl%0A%20%20%20%20description%0A%20%20%7D%0A%7D) to reproduce the issue.

For longer variable types this would add a lot of value :slightly_smiling_face:

**Comment by acao** [comment]
this issue should be resolved now. if there are any bugs with type declarations for variables, please open a new ticket!
