### ISSUE TITLE
./resources/build.sh util.error: Use console.error instead

### ISSUE THREAD

**Issue by BeniCheni** [graphql/graphiql#39]
When trying the build script in `./resources/`directory, I went into the console.error and warning as the attached screen demonstrates.  Is this my local issue or build script issue?  Thank you very much in advance!

<img width="586" alt="screen shot 2015-10-03 at 9 12 12 pm" src="https://cloud.githubusercontent.com/assets/6441326/10265957/92bd965a-6a13-11e5-8c75-79ce256cc8ad.png">

**Comment by leebyron** [comment]
You're certainly seeing more of them than I am, but yes some of these currently occur with building the compiled sources.

**Comment by asiandrummer** [comment]
#99 also discusses this - I think this is actually a result from uglifying modules GraphiQL is using. I'm looking into it a bit more, but if you want to suppress this warning for the time being, there is `warning=false` option in `uglify`.
