### ISSUE TITLE
Input fails on special characters

### ISSUE THREAD

**Issue by wizzy25** [graphql/graphiql#399]
### Description
Input fails and Graphiql becomes completely (almost permanently?) unusable when certain whitespace characters are input

### Expected Behaviour
The reverse of the description

### Context
When certain whitespace characters are input (I have tested with unicode characters u2000 to u200a, u2028, u202f, could be more) errors are logged to the console (see attached photo), and typing is no longer visible to the user. As it saves the state to localStorage on `componentWillUnmount`, this makes it almost unusable even after clearing `localStorage.clear()`.  
[The spec](https://facebook.github.io/graphql/#sec-White-Space) says only `tab` and `space` white spaces are accepted, so a better job should be done to handle unaccepted characters.

### Possible solution
Perhaps better error handling? Or warning that an invalid character was inserted.

<img width="1440" alt="screen shot 2017-03-29 at 16 03 35" src="https://cloud.githubusercontent.com/assets/20454817/24500431/a55e2c28-1545-11e7-8786-282766dc9903.png">

**Comment by AGS-** [comment]
@wizzy25, thanks for opening the issue, let me look into this a bit.

**Comment by wizzy25** [comment]
Hello @AGS-, any update on this issue?
