### ISSUE TITLE
Readme improvements

### ISSUE THREAD

**Issue by tristanz** [graphql/graphiql#4]
Two possible improvements::
1. Link to http://graphql-swapi.parseapp.com/graphiql/ or something like it.
2. Add screenshot that shows autocomplete in action.

**Comment by KyleAMathews** [comment]
+1 to an animated gif

**Comment by kevinSuttle** [comment]
The example needs love (should it be moved to its own repo?), as do the docs for customizing `GraphiQL, GraphiQLLogo, GraphiQLFooter, GraphiQLToolbar`, etc

**Comment by wincent** [comment]
@kevinSuttle, as this is quite old and the original issue was resolved, I've split your comment off into [a separate issue here](https://github.com/graphql/graphiql/issues/247). I'm going to mark this as closed (something we should have done back in August 2015).
