### ISSUE TITLE
A way to pass the operationName

### ISSUE THREAD

**Issue by arunoda** [graphql/graphiql#40]
I think there is no way to pass the operationName along with request to the server. Is there any planned feature?

**Comment by leebyron** [comment]
This is currently missing but planned, yes. I'm open to suggestions on how you might like to see this built.

**Comment by arunoda** [comment]
I'd like to see a input box where I can enter this.
We could place this just below the query variables pane.

**Comment by trbngr** [comment]
Just ran into this myself. Would love to see it.
