### ISSUE TITLE
GraphiQL online with configurable endpoint

### ISSUE THREAD

**Issue by lucasconstantino** [graphql/graphiql#405]
Hello there. I'm here just to inform I've put an instance of GraphiQL online as a GitHub Pages at https://lucasconstantino.github.io/graphiql-online/.

Of course, CORS is quite an issue for most endpoints.

**Comment by AGS-** [comment]
@lucasconstantino, wow this is pretty cool. Nice job, it's always exciting to see what the community can build!

**Comment by praveenweb** [comment]
We have an online version of GraphiQL with configurable endpoint and headers. [https://graphiql-online.com](https://graphiql-online.com).
