### ISSUE TITLE
Variables field sent as `[object Object]` in GET requests

### ISSUE THREAD

**Issue by macalinao** [graphql/graphiql#416]
My "Query Variables" is being sent as an `[object Object]`. There is probably a `.toString` call where there should really be a `JSON.stringify`.

![screen shot 2017-04-07 at 19 29 37](https://cloud.githubusercontent.com/assets/401263/24823836/9492418e-1bc8-11e7-85ad-a979dd199cab.png)
![screen shot 2017-04-07 at 19 29 57](https://cloud.githubusercontent.com/assets/401263/24823841/9a69ff02-1bc8-11e7-9ecb-bb3be0cf52e6.png)

**Comment by asiandrummer** [comment]
@macalinao Are you unable to execute a query? I think we've decided to send a JSON object instead of JSON string a while ago.

**Comment by macalinao** [comment]
Yes. What do you mean by sending a JSON object instead of JSON string?

**Comment by asiandrummer** [comment]
@macalinao oh sorry - I meant we had a discussion in https://github.com/graphql/graphiql/pull/168 to change passing in variables in JSON object instead of string.

**Comment by macalinao** [comment]
ah, well it shouldn't be sending `[object Object]` should it? Or is it actually sending a JSON string and Chrome dev tools is showing some other representation?

**Comment by jborden** [comment]
I can confirm I am having this same problem with Query Variables. It seems to be isolated to the HTTP GET method calls.  HTTP POST calls will gladly pass on the proper Query Variables in the request body, but for HTTP GET method calls the query is passed on with the  parameters while the variables are just a string "[object Object]".

**Comment by wincent** [comment]
Can I get some clarification here on how to repro this exactly?

**Comment by jeroenbe** [comment]
I'm having the same issue:
I'm using the [electron app](https://github.com/skevy/graphiql-app) to query a neo4j db with graphql (if you want to go through the hassle: [neo4j-graphql](https://github.com/neo4j-graphql/neo4j-graphql)).

When inspecting the requests with charles and copying them as a cURL request I noticed `&variables\=%5Bobject%20Object%5D` (-> `[object Object]`) at the end of my request. When no variables are given the ending looks like: `&variables=null`. When replacing the values with an encoded object, everything goes fine. Effectively ruling out the server as the culprit.

I understand there's a lot of indirect stuff going on in tracing my issue, but I'm fairly confident it's the same one as described above.

**Comment by macalinao** [comment]
@wincent to reproduce, send a GraphQL request via `GET` with some variables.
