### ISSUE TITLE
cannot get queryType of undefine

### ISSUE THREAD

**Issue by fitsum** [graphql/graphiql#42]
when recreating the query from the README verbatim I get the error in the title in Chome 45.0.2454.101 and Firefox 41.0.1 OSX 10.9.5

**Comment by gajus** [comment]
Getting what I assume is the same error:

```
Uncaught TypeError: Cannot read property 'getQueryType' of undefined
```

**Comment by gajus** [comment]
```
        case Kind.OPERATION_DEFINITION:
          if (node.operation === 'query') {
            type = schema.getQueryType();
```

`schema` in TypeInfo.js is `undefined`.

**Comment by gajus** [comment]
I could not figure out to make it work.

I have since discovered https://github.com/graphql/express-graphql, express middleware that can setup draphiql instance as part of the graphql sever setup.

**Comment by leebyron** [comment]
Thanks for the report. I've got a fix in that should be on npm soon.
