### ISSUE TITLE
Saving queries/mutations?

### ISSUE THREAD

**Issue by Agrosis** [graphql/graphiql#43]
I was wondering if it could possibly be a feature to maybe save queries/mutations written to local storage or something without complicating the UI too much. I'm not familiar exactly with the scope of what graphiql is meant to solve and what its not meant to solve, but that could possibly be a neat feature.

**Comment by petrbela** [comment]
I think that's beyond the scope of GraphiQL itself. Check out https://github.com/skevy/graphiql-app -- might be what you're looking for.

**Comment by asiandrummer** [comment]
Thanks for the feedback! GraphiQL currently supports remembering the most recently manipulated query/variables using the web storage, as well as the option to let you provide the storage option of your choice as a prop. I agree with @petrbela that persisting queries is beyond GraphiQL's scope.
