### ISSUE TITLE
Subscriptions not working through GraphiQL

### ISSUE THREAD

**Issue by tkhemani** [graphql/graphiql#434]
Hi,
I'm using [this article](https://dev-blog.apollodata.com/how-to-use-subscriptions-in-graphiql-1d6ab8dbd74b) and [this video](https://youtu.be/aAwZrBgmnho) as reference to test Subscriptions via GraphiQL, but the web socket is not getting created on creating new subscription (verified via dev tools) and hence, when I post a comment from GitHunt-Angular, it doesn't show up in GraphiQL. Am I missing something here? Also tried the [hosted version](http://api.githunt.com/graphiql?query=subscription%20commentAdded%20%7B%0A%20%20commentAdded(repoFullName%3A%22apollographql%2Fapollo-client%22)%7B%0A%20%20%20%20id%2C%0A%20%20%20%20content%2C%0A%20%20%20%20createdAt%2C%0A%20%20%20%20postedBy%7B%0A%20%20%20%20%20%20login%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D&operationName=commentAdded). Same issue

**Comment by stubailo** [comment]
I think this issue should probably be filed here: https://github.com/apollographql/subscriptions-transport-ws

I don't think this is an issue with the GraphiQL core.

**Comment by wincent** [comment]
Thanks @tkhemani. If you do file an upstream issue like @stubailo suggests, maybe you can reference this issue too, or otherwise comment with a link to your upstream issue so that anybody stumbling across this can find your other post. Marking this one as closed for now.

**Comment by raeesaa** [comment]
@wincent / @stubailo Even I could not get subscriptions to work with graphiql. Subscription query is being passed as body of POST call to graphql endpoint instead of as frame in websocket call. Websocket connection is not at all being made. Do we need to do something additional in order to get subscriptions to work?

**Comment by imolorhe** [comment]
@tkhemani You could also checkout https://github.com/imolorhe/altair for GraphQL subscription support.
