### ISSUE TITLE
Possible to define an input field more than once if part of a list

### ISSUE THREAD

**Issue by andrewe123** [graphql/graphiql#441]
I have an input object that has a list of input objects
```
mutation createConversation(input: CreateConversationInput!): ConversationMutation

Input Object: CreateConversationInput
messages: [MessageWrapperInput]!

MessageWrapperInput
message: MessageInput
title: TitleInput

Input Object: MessageInput
color: String!
text: String!

Input Object: TitleInput
color: String!
text: String!
```

The following query is valid according to GraphiQL
```
mutation {
  createConversation(input: {
  messages: [
    {
      message: {
        text: “a”
      },
      message: {
        text: “b”
      }
    }
  ]}){…
  }
}

```
But I have redefined the message input object in a single list entry.

Expected:
I should get a warning like: "There can only be one input field named message for each list entry"

The correct query for reference should be something like:
```
mutation {
  createConversation(input: {
  messages: [
    {
      message: {
        text: “a”
      }
   },
   {
      message: {
        text: “b”
      }
    }
  ]}){…
  }
}

```

**Comment by asiandrummer** [comment]
@andrewe123 thanks for the report! This certainly looks like a bug, but is probably more related with https://github.com/graphql/graphql-language-service repo. I don't have a good bandwidth to tackle this one for now, but will get to it within a month or so. If anyone else is interested in taking a stab at it please feel free to do so!

**Comment by asiandrummer** [comment]
Moved to that repo instead. Thanks again!
