### ISSUE TITLE
net::ERR_INSECURE_RESPONSE - How to test with self-signed cert on localhost?

### ISSUE THREAD

**Issue by n8sabes** [graphql/graphiql#451]
How can GraphiQL, or the system (Mac OS X), be configured to query an express localhost server via https using a self-signed cert? I have https queries working correctly via several browsers, but GraphiQL produces a `net::ERR_INSECURE_RESPONSE` error, even if the cert is added to chrome or the system keychain.

The localhost server is setup as follows:

1. Generated self-signed cert
```
openssl req -newkey rsa:2048 -new -nodes -keyout key.pem -out csr.pem
openssl x509 -req -days 365 -in csr.pem -signkey key.pem -out server.crt
```

2. Implemented https in Express Server to use the self-signed cert
```
  https.createServer({
    key: fs.readFileSync('./api_emulator/key.pem', 'utf8'),
    cert: fs.readFileSync('./api_emulator/server.crt', 'utf8')
  }, app).listen(4001);
```

**Comment by asiandrummer** [comment]
@n8sabes I'm guessing the server you're creating also has the `graphql` query execution endpoint? I'm not very familiar with the self-signed cert and the workflow for that, but if your above code (2) is supposed to work, I don't see why the graphql endpoint in your server shouldn't be working.
@AGS- @wincent would you guys have an idea here?

**Comment by n8sabes** [comment]
Thanks @asiandrummer. The issue is that it appears the GraphiQL app uses an embedded Chrome browser control that I cannot get to authorize a self-signed certificate on the localhost. I also tried (a) adding the cert at the system level, (b) authorizing localhost flag in Chrome, and (c) authorizing the self-signed cert within Chrome, but nothing carried over to GraphiQL.

**Comment by wincent** [comment]
What does Chrome show in the "Security" tab of the developer tools for the certificate?

> The issue is that it appears the GraphiQL app uses an embedded Chrome browser control

It is just a normal React app; nothing Chrome-specific about it. What do you mean by "embedded" here?

**Comment by AGS-** [comment]
Closing the issue since it seems a bit stale and non actionable on our side.
