### ISSUE TITLE
0.9 cannot be installed anymore correctly

### ISSUE THREAD

**Issue by danez** [graphql/graphiql#453]
When trying to install `graphiql@^0.9` we receive this error:

```
peer invalid: codemirror@^5.25.2, required by codemirror-graphql@0.6.4
```

This happens because the latest `graphiql` version installs `codemirror@5.23.0` but the latest (patch-)version of codemirror-graphql wants ^5.25.2

We also cannot upgrade yet to `graphiql@0.10` as we do not yet use `react@15.5` which is now required.

Can you please release a new 0.9 version that works? thanks.

**Comment by wincent** [comment]
Thanks for the report, @danez.

We don't maintain separate release branches for minor releases (eg. 0.8, 0.9, 0.10); in fact, we don't even maintain separate release branches for major releases (eg. 1.0, 2.0 etc), so we should try to resolve this by forward-fixing (ie. in the next 0.10.2 or 0.11.0 release).

I think the fix here will be two-fold:

- Loosen the peer dependency in codemirror-graphql; I'll do that in a moment.
- Loosen the peer dependency on react; I'm not sure how loose we can go here without breaking things, but we can look into it.

What version of React are you using @danez?

**Comment by wincent** [comment]
I've loosened the peer deps and will cut a release. Let's see if that works.

**Comment by wincent** [comment]
@danez: v0.10.2 is out:

https://github.com/graphql/graphiql/releases/tag/v0.10.2

Let us know if that doesn't work for you and we can get back to the ol' drawing board.

**Comment by danez** [comment]
Thanks. It still doesn't work, as we use react 15.4, which is not covered by the peer dependency. But we plan to upgrade to 15.5 soonish.

**Comment by wincent** [comment]
We could probably go as far back as 15.3 without breaking things (that's the oldest 15.x release that prop-types will work with), but I didn't change that because I hadn't tested it. If you want to test this out in a local fork and confirm that everything works I'd be happy to bump it back a bit.

**Comment by danez** [comment]
Well I downgraded and pinned all graphql related packages, as the new graphiql 0.10 also cannot be used with webpack anymore due to graphql-language-service#111 and uglify afterwards chocking about ES6/Flow.

So I won't test with older react versions.

**Comment by tsunammis** [comment]
@danez I have the same issue with webpack, thus, I would like to install also the previous version, how can I do that ? (as the 0.9 is not available anymore)

**Comment by nemoDreamer** [comment]
Also having issues w/ "flow" from `graphql-language-service`...
Does my `graphiql/webpack.config.js` now need to be Flowtype-aware?

**Comment by asiandrummer** [comment]
@nemoDreamer could you elaborate on the issues you're having with flow? From https://github.com/graphql/graphql-language-service/issues/111 we've seen some flow errors - are these related perhaps?
