### ISSUE TITLE
Graphiql not working

### ISSUE THREAD

**Issue by ansarizafar** [graphql/graphiql#46]
Graphiql not working with the latest version of react.

Warning: React.findDOMNode is deprecated. Please use ReactDOM.findDOMNode from require('react-dom') instead.

Uncaught TypeError: Cannot read property 'length' of undefined.

**Comment by gre** [comment]
https://github.com/graphql/graphiql/pull/41 should fix this

**Comment by asiandrummer** [comment]
#41 was merged and GraphiQL example seems to be operational.
