### ISSUE TITLE
Upgrading from 0.10.1 to 0.10.2 shows webpack warnings

### ISSUE THREAD

**Issue by EvNaverniouk** [graphql/graphiql#460]
I am using `webpack` to bundle `graphiql` into my app. After upgrading from `graphiql` 0.10.1 to 0.10.2, `webpack` now gives me the following warnings:

```
WARNING in ./~/graphql-language-service-interface/dist/GraphQLLanguageService.js
82:26-64 Critical dependency: the request of a dependency is an expression

WARNING in ./~/graphql-language-service-interface/dist/GraphQLLanguageService.js
85:30-48 Critical dependency: the request of a dependency is an expression
```

Downgrading back to `0.10.1` makes the warnings go away.

Do you know what could be going wrong here?

**Comment by EvNaverniouk** [comment]
Not sure if an issue with `graphiq` or `graphql` itself, as this is also logged here: https://github.com/graphql/graphql-language-service/issues/111

**Comment by asiandrummer** [comment]
Will track this issue in graphql/graphql-language-service#111 - thanks for the report!
