### ISSUE TITLE
Create-react-app issue

### ISSUE THREAD

**Issue by Magneticmagnum** [graphql/graphiql#462]
I saw there was a fix for this that was already merged in, but I'm still running into the same issue;

I can render the GraphiQL UI, but it only renders half of it!  

I'm on a Windows environment, using FF, Chrome, and IE

**Comment by asiandrummer** [comment]
@Magneticmagnum could you give some more information about your issue and how to repro it?

**Comment by Magneticmagnum** [comment]
Hey @asiandrummer ,

I have an example here: https://github.com/Magneticmagnum/graphiqlTest

It is a barebones create-react-app that tries to render `GraphiQL` in `App.js`

The CSS is imported into the project in `import 'graphiql/graphiql.css';`

**Comment by fson** [comment]
@Magneticmagnum the parent element of GraphiQL needs to have an explicit height for the component to render properly. You can set the height to be the full height of the viewport like this:
```css
.App {
  height: 100vh;
}
```
(You should also remove the `text-align: center` style from `.App` to fix the text alignment.)

**Comment by asiandrummer** [comment]
@Magneticmagnum I'm closing due to an inactivity - let us know && reopen this issue if @fson's suggestion doesnt resolve your issue!
