### ISSUE TITLE
Autocomplete for required variables

### ISSUE THREAD

**Issue by intellix** [graphql/graphiql#463]
I've just created a `createUser` mutation and there are about 30 potential fields, around 20 are required.

As I type I get told that I'm missing lots of required fields like so: 

![screenshot 2017-05-09 11 48 22](https://cloud.githubusercontent.com/assets/1162531/25845602/cee92844-34ae-11e7-923d-c4436350fc39.png)

I think it'd be nice for autocomplete to add all of the required input fields so you can change booleans and fill in strings really quick. Right now it's a case of looking at the error tooltip and adding each of them manually

**Comment by asiandrummer** [comment]
@intellix eek that's painful. I can think of a couple of ways to help with this case - one is to add a button that fills all required fields with some temporary values (e.g. "" for strings, false for booleans, {} for objects, and etc).

Another is to automatically suggest variables when the query gets run, inferring from the default values for input types from your schema. Do your required fields have default values?

**Comment by intellix** [comment]
Haven't got default values, but the above sounds good to me :)

**Comment by marktani** [comment]
> @intellix eek that's painful. I can think of a couple of ways to help with this case - one is to add a button that fills all required fields with some temporary values (e.g. "" for strings, false for booleans, {} for objects, and etc).

That sounds rad!

**Comment by asiandrummer** [comment]
I'd love for a contribution here ;)

**Comment by scotmatson** [comment]
No updates in a couple of months. Has any work been done on this?

**Comment by wincent** [comment]
> Has any work been done on this?

I'm not aware of any work that's been done on it. It has the "help wanted" tag on it, so hopefully somebody that wants this enhancement will step forward with a PR.

**Comment by glinskyc** [comment]
For queries, I am observing the exact opposite behavior of what's been requested here.  That is, if I mark a field as required=True, then it does NOT appear in the auto-complete for a query of a type, while fields with required=False do appear.  

Is this expected behavior?  I expected the opposite of what's happening for me, i.e. to include _only_ the required fields in auto-complete of a query.

**Comment by acao** [comment]
this works now, i'm not sure when the feature was added, but when you type out a field name and hit enter, if it has required fields they will be automatically added.

**Comment by krishna81m** [comment]
@acao, which version is this? Can only see autocomplete field names not values. Think autocomplete configuration should be revisited to include more options for newbies (like me):
1. autocomplete.braces (complex types always need braces right?)
2. autocomplete.default.values
3. autocomplete.mandatory.fields
4. autocomplete.mutation.constructor.arguments

Or, is there something like this today in any other client?

**Comment by acao** [comment]
try graphiql 0.17.5
all graphql web IDE or electon clients use codemirror-graphql here in our repository, as far as i know
