### ISSUE TITLE
Errors not being shown in 0.10.2

### ISSUE THREAD

**Issue by lucascosta** [graphql/graphiql#477]
When upgrading from 0.10.1, a mistaken query (not in conformity with the schema), stop showing errors (red underline and errors popup).

**Comment by AGS-** [comment]
@lucascosta sorry for taking so long to respond to this, I can't seem to reproduce this. Were you able to fix it?

**Comment by lucascosta** [comment]
Not really. I can do whatever mess I want both in queries and mutations and it won't show errors. And when I change back to 0.10.1 they are there... Anyways, if you can't reproduce I'll just wait for the next version and see if someone else has the issue.
