### ISSUE TITLE
"prettify" query

### ISSUE THREAD

**Issue by gre** [graphql/graphiql#48]
my common usecase is to paste a query that was generated by Relay and see what it does.

However, the Relay queries are pretty obfuscated, it would be great to have a button that prettify the query textarea.

I was playing around with this code:
```js
function blockIndent(editor, from, to) {
  editor.operation(function() {
    for (var i = from; i < to; ++i)
      editor.indentLine(i, "smart");
  });
}
```

but it just indents, it does not do the "return to new line" work.

**Comment by leebyron** [comment]
Good suggestion
