### ISSUE TITLE
How about adding a tabular view of JSON.

### ISSUE THREAD

**Issue by nsisodiya** [graphql/graphiql#480]
Please let me know if you think adding https://www.npmjs.com/package/react-json-viewer to graphiql will help users.
graphiql show result in JSON. sometimes this JSON data is very large. react-json-viewer convert JSON into a tabular format. It will be great if we can add a switch button where user can switch between JSON view or Tabular view.
I am open for creating pull request for the same.

**Comment by AGS-** [comment]
@nsisodiya sorry for taking so long to respond to this. We're trying to keep the implementation of GraphiQL as lightweight as possible and I don't think this necessarily falls inline with that goal. I think these kinds of things would be a bit better if people using the component added them to their specific implementation.
