### ISSUE TITLE
Dragging variables editor panel doesn't work on touch devices

### ISSUE THREAD

**Issue by stubailo** [graphql/graphiql#485]
On an iPad, you can't drag the variables panel to open it or change the size.

To reproduce:

1. Go to http://api.githunt.com/graphiql
2. Open the chrome dev tools and click on the responsive preview button, select "ipad"
3. Attempt to drag open the variables panel

Happy to open a PR if this is something you'd like to fix! Would it be OK to use https://github.com/tomkp/react-split-pane which seems to "just work" everywhere I've tried it?

**Comment by AGS-** [comment]
@stubailo I don't think this is that big of an issue since in the overwhelming majority of cases people running GraphiQL are using it while actually developing something on their computer. Any input on this @wincent @asiandrummer

**Comment by stubailo** [comment]
Yeah but if it can be fixed easily why not? I'm interested in using GraphiQL on iPad specifically.

**Comment by stubailo** [comment]
(Specifically, this is an issue in Launchpad, which is a tool that can definitely be used to develop on an iPad)

**Comment by asiandrummer** [comment]
@stubailo with the emergence of iPad Pro and Surface devices, it feels like extending GraphiQL with the touch functionality would be a fun nice-to-have feature. `react-split-pane` looks usable but why couldn't we just use browser touch events (`touchstart`, `touchend`, `touchmove` and etc)? I'd like to move towards a solution that doesn't require GraphiQL depending on another library.
