### ISSUE TITLE
"graphql" being a devDependencies make it impossible to use in a dependent project

### ISSUE THREAD

**Issue by gre** [graphql/graphiql#49]
I have a project that depends on **graphiql** AND **graphql**, but I'm getting `Error: Schema must be an instance of GraphQLSchema. Also ensure that there are not multiple versions of GraphQL installed in your node_modules directory.`

and I actually have both `node_modules/graphql` and `node_modules/graphiql/node_modules/graphql` .

I don't think graphiql should devDep on graphql in the first place, because it's already a peerDep

**Comment by Sinewyk** [comment]
devDependencies of dependencies aren't supposed to be installed when you `npm i` a project.

The graphql devDep of graphiql should only have been installed if you went inside graphiql and exec-ed `npm i`, which you should not do (not have done).

It has nothing to do with this repo, this is pure npm related stuff, you probably messed up somewhere.

**Comment by gre** [comment]
Woo, I'm sorry, I was wrong. The weirdness is that graphql was being installed if I forget to put it as a dep at the top-level BUT no error was raised. (so I had to clean my node_modules and try again)
Hopefully this will be fixed by NPM 3+ (peerDep not being auto-installed)

Thanks
