### ISSUE TITLE
Codemirror integration is broken after v0.10.2 update

### ISSUE THREAD

**Issue by OlegIlyenko** [graphql/graphiql#493]
deprecation highlighting and type information are missing.

v0.10.1

![graphiql1](https://cloud.githubusercontent.com/assets/156569/26562568/a1bed4ee-44c7-11e7-8628-7fa281d29fb2.png)

after update to v0.10.2

![graphiql2](https://cloud.githubusercontent.com/assets/156569/26562565/9d686d10-44c7-11e7-8481-08944affda19.png)

**Comment by asiandrummer** [comment]
Thanks @OlegIlyenko - I'll take a look now.

**Comment by asiandrummer** [comment]
@OlegIlyenko before fixing this I'll need to update a bunch of dependencies first, in `graphql-language-service` and `codemirror-graphql`. I'm on this though - will PR out soon.

**Comment by asiandrummer** [comment]
Annnd 4cca03eb02df16215e9c28bd24d537bdfbeb4cc1 fixes it! Thanks for the report!

**Comment by OlegIlyenko** [comment]
@asiandrummer Thanks a lot for fixing it! 🏆
