### ISSUE TITLE
fetch v0.9.0 error on iPad Safari

### ISSUE THREAD

**Issue by nialexsan** [graphql/graphiql#496]
I cannot use graphiql on iPad, getting an error 
`TypeError: undefined is not an object (evaluating 't.toString')`
at fetch.min.js:9
Maybe it is due to compatibility issue with obsolete version of this library, since there is 2.0.1

**Comment by asiandrummer** [comment]
@nialexsan interesting - could you try upgrading to the latest fetch version, see if that fixed the issue? I don't own an iPad so it's a bit difficult to test - I tried on the simulator and for some reason it worked without issues.

**Comment by AGS-** [comment]
@nialexsan I tried reproducing this on my iPad, have you tried updating to the latest version of GraphiQL or would you happen to have a bit more specific repro steps? Thanks!

**Comment by asiandrummer** [comment]
I'm closing this issue for the lack of more information, but feel free to reopen and escalate if you come back to this issue. Thanks!
