### ISSUE TITLE
Events on history item selection

### ISSUE THREAD

**Issue by gdub22** [graphql/graphiql#497]
With the recent addition of the history pane (#232), when selecting a history item it would be nice to trigger the existing event hooks (`onEditQuery`,`onEditVariables`, `onEditOperationName`).

Looks like it currently just directly updates the state: https://github.com/graphql/graphiql/blob/7f930a506b5460fc6aa8b34143cf145ff93f84b9/src/components/GraphiQL.js#L456-L461

This is useful if you use those hooks to update the url's query params.

**Comment by asiandrummer** [comment]
@gdub22 great point - I'd love to ask for some contribution here as I'm currently heads down with some other things. If not I'll try to come back to this.

**Comment by gdub22** [comment]
@asiandrummer done: https://github.com/graphql/graphiql/pull/499
