### ISSUE TITLE
Latest version cannot be installed/shrinkwrapped correctly

### ISSUE THREAD

**Issue by danez** [graphql/graphiql#504]
If I install the latest version of graphiql with graphql:0.9 I get:

```
npm WARN codemirror-graphql@0.6.6 requires a peer of graphql@^0.10.0 but none was installed.
```

So I went and change to graphql:0.10 but then I get:

```
npm WARN graphiql@0.10.2 requires a peer of graphql@^0.6.0 || ^0.7.0 || ^0.8.0-b || ^0.9.0 but none was installed.
```

**Comment by asiandrummer** [comment]
https://github.com/graphql/graphiql/commit/c135bd86122933204db1e4e4dd89293d00b21b9e fixes this but we haven't cut a release yet. 0.10.3 should be coming soon, probably today.

**Comment by wincent** [comment]
@asiandrummer: is that commit right? I thought we generally want liberal/broad peer deps, and GreenKeeper has a bad habit of narrowing the range, like it did in that commit. It should have added `^0.10.0` to the range, not *replaced* the entire range with it.

**Comment by wincent** [comment]
I think we're good here now. I cut v0.11.1 earlier today and I'm going to push v0.11.2 that relaxes the peer dependencies like we used to.
