### ISSUE TITLE
When loading GraphiQL from a CDN, but bundling the servers schema, instanceof check fail

### ISSUE THREAD

**Issue by joelgriffith** [graphql/graphiql#527]
My use case is probably pretty narrow compared to most, but given the following:

- A server bundles the introspection schema in a JSON file.
- A client `require`s file bundle at build time.
- A client passes the output from `buildClientSchema(json)` to the `GraphiQL` component.
- The `GraphiQL` client is loaded from a CDN.

Internally, the `GraphiQL` module bundles its own (I assume) `GraphQL` instance on the CDN. It also performs `instanceof` checks in the supplied `schema` prop, and in my case, this call fails since the instance of GraphQL performing the schema is different from the instance of GraphQL in the client.

The obvious solution is to bundle `GraphiQL` in your build. There's some issues at the moment that are preventing this from happening in my application: https://github.com/graphql/graphql-language-service/issues/111. As an alternative, it might be nice to loosen the restriction on checking this prop from `instanceof` to something more relaxed (open to suggestions).

Any thoughts on this or more that I could elaborate on?

**Comment by asiandrummer** [comment]
@joelgriffith Thanks for opening an issue! I'm not sure if I understand your question though - is there some code I can look at? Do you mean the versions of `graphql-js` are different from the one installed and the one bundled in the GraphiQL cdn?

**Comment by joelgriffith** [comment]
Sorry for taking so long on getting back, but yes to your question! If I'm using GraphiQL from a CDN, it comes bundled with its own `graphql-js` package. Then, in the client, if I pass the `GraphiQL` component a schema (using my own instance of `graphql-js`), it'll fail `instanceof` checks since the schematic comes from a different instance of `graphql-js`.
