### ISSUE TITLE
[0.11] Empty graphiql.min.js

### ISSUE THREAD

**Issue by eugene1g** [graphql/graphiql#528]
Hi,

Looks like the most recent build is missing `graphiql.min.js` file in the distribution. That is https://unpkg.com/graphiql@0.11.0/graphiql.min.js is empty but https://unpkg.com/graphiql@0.10.2/graphiql.min.js is fine. We reference it from the CDN as `<script src="//unpkg.com/graphiql/graphiql.min.js"></script>` which now redirect to 0.11, and thus breaks some of the pages.

Is it possible to still ship the .min file?

**Comment by wincent** [comment]
Thanks for reporting! We should be able to cut a corrected release for this shortly.

**Comment by wincent** [comment]
I've fixed the build, so will cut a new release presently.

**Comment by wincent** [comment]
[v0.11.1](https://github.com/graphql/graphiql/releases/tag/v0.11.1) is now out on NPM and you can see the min build at https://unpkg.com/graphiql@0.11.1/graphiql.min.js

**Comment by srtucker22** [comment]
Seems to not have a min file in unpkq in [v0.11.2](https://unpkg.com/graphiql@0.11.2/graphiql.min.js)
