### ISSUE TITLE
live demo does not work

### ISSUE THREAD

**Issue by TLogik** [graphql/graphiql#53]
The live demo seems to be faulted.
No matter the query input the response is always:
`SyntaxError: Unexpected end of input`

Example input query:
```
{
  allStarships{
    starships{
      name
    }
  }
}
```
but i have tested several other queries with the same result.

It seems like the parser expects some more characters, but the current error response does not allow for any really constructive examination of what is wrong.

**Comment by leebyron** [comment]
Thanks for the report. Sometimes a parse deploy gets cranky. I'll look into it.

**Comment by leebyron** [comment]
Back up and running!

**Comment by TLogik** [comment]
Great. Thanks for the quick response and fix. 
And thanks for the introduction at Øredev. I am now trying GraphQL out in a non critical system to check its current usability in the .NET world.

**Comment by leebyron** [comment]
Check out https://github.com/graphql-dotnet/graphql-dotnet - I haven't personally used it, but hopefully it's approaching a near complete implementation and will be a great first foray for you.

**Comment by TLogik** [comment]
That is the one i am already implementing.
First thing i checked after leaving the Auditorium at Oeredev :-)

It is in a state where it is usable.
