### ISSUE TITLE
Errors and tooltips not being shown since 0.10.2

### ISSUE THREAD

**Issue by oliemansm** [graphql/graphiql#534]
When using the example set-up the error highlighting stops working. So the red underscore and tooltip with error message aren't shown anymore. Up to v0.10.1 it is working. It's the same issue as #477 which was closed without resolution, and looks similar to #493.

v0.10.1
![image](https://user-images.githubusercontent.com/13518144/27933503-0734011c-62a2-11e7-8313-4b5158ea960e.png)

after update to v0.10.2
![image](https://user-images.githubusercontent.com/13518144/27933547-38f02050-62a2-11e7-9d70-d97624f48ecf.png)

Am I missing a dependency here?

```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/es6-promise/4.1.1/es6-promise.auto.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/fetch/2.0.3/fetch.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/react/15.6.1/react.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/react/15.6.1/react-dom.min.js"></script>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/graphiql/0.11.2/graphiql.min.css" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/graphiql/0.11.2/graphiql.min.js"></script>
```

**Comment by asiandrummer** [comment]
Hi @oliemansm - I just ran GraphiQL example app and was able to see all of the features working correctly. You also mention of version `0.10.2`, but from your imports I see `0.11.2` - did you put an incorrect version perhaps?

**Comment by joshjcarrier** [comment]
@asiandrummer  I've also run in to the syntax underline check, and it repros on a fresh clone, `npm run build` and `npm run dev` of master.

![graphiql_syntax_check](https://user-images.githubusercontent.com/526858/27941537-d88d468c-6285-11e7-8f67-3436859e7343.gif)

**Comment by oliemansm** [comment]
@joshjcarrier Thanks for verifying!

@asiandrummer I've tried multiple versions, and seen the same behavior starting with `0.10.2` up to the latest `0.11.2`. I copied the last try, that's all. Sorry for the confusion.

**Comment by asiandrummer** [comment]
Thanks guys! I'm taking a look at this right now.

**Comment by asiandrummer** [comment]
@oliemansm @joshjcarrier https://github.com/graphql/codemirror-graphql/releases/tag/v0.6.11 takes care of this bug - I'll let greenkeeper update to this revision. Thanks again for reporting!

**Comment by joshjcarrier** [comment]
@asiandrummer did greenkeeper pick up this revision? I see `yarn.lock` still on the old version.

**Comment by wincent** [comment]
@joshjcarrier. Right you are, looks like it needs an update.
