### ISSUE TITLE
No intellisense for __typename

### ISSUE THREAD

**Issue by kbrandwijk** [graphql/graphiql#535]
If I want to use `__typename` _on any Type_ in a query, it doesn't show up in the 'intellisense-autocomplete-popup'. This is inconsistent, because top-level introspection fields like `__type` and `__schema` do show up in the popup.
![typename](https://user-images.githubusercontent.com/852069/27988025-908af7a0-6418-11e7-985c-b488bcbdd271.gif)

**Comment by wincent** [comment]
Thanks for the report, @kbrandwijk. I think this may be the result of an overly literal reading of the spec:

`__type` and `__schema` are [top-level introspection fields](http://facebook.github.io/graphql/#sec-Schema-Introspection).

`__typename` is a meta field that can be queried against [any Object, Interface or Union type](http://facebook.github.io/graphql/#sec-Type-Name-Introspection).

The `query` type, however, *is* ["an Object base type"](http://facebook.github.io/graphql/#sec-Initial-types), so does allow `__typename` (even though it is pointless to ever query for it).

**Comment by kbrandwijk** [comment]
But it doesn't show up on any Type. In my screenshot, I use it on `allFilms`, not on `query` directly. Do you agree that it should show up on 'any Object, Interface or Union type'?

**Comment by wincent** [comment]
Sorry I wasn't explicit. My comment basically boils down to, "Yes, it looks like it should appear in the typeahead, according to the spec, and I theorize that the reason it behaves like it currently does is that we just read things a little too narrowly." Probably. Haven't looked at the code yet.

**Comment by kbrandwijk** [comment]
Thanks for clearing that up :smile:
