### ISSUE TITLE
Help with best way to install

### ISSUE THREAD

**Issue by jaydreyer** [graphql/graphiql#537]
We have an angular based site (1.3) and we're trying to add graphiql to it. I haven't had any luck so using either the npm install way or trying to integrate using the example and importing graphiql.js and .css.

Before I keep spinning my wheels, is there a preferred method for integrating this into an angular app?

I'm able to build graphiql locally, independent of my site, but integration is a different story.

Thanks!

**Comment by asiandrummer** [comment]
@jaydreyer ooh, as you probably know GraphiQL is just a React component, and the only way I can think of is to `React.render` GraphiQL component on the DOM object. You may have to pull in React stuffs dynamically just to be able to do this. Other than this way I'm out of ideas - are you able to structure just one part of your application to use React to mount GraphiQL?

**Comment by jaydreyer** [comment]
Yeah. Actually, I figured it out after banging my head all morning.  Just needed to import react using bower and it's working. Now dealing with some cors issues, but we should be able to figure that out.

Thanks!
