### ISSUE TITLE
Save queries and other snippets 

### ISSUE THREAD

**Issue by mraak** [graphql/graphiql#546]
This could be a nice feature, code could be saved to localstorage and/or files on the disk. Right now the user has to copy paste into and from notepad++, MS Paint or similar.

**Comment by wincent** [comment]
Have you checked out the favorites feature in the history sidebar? That does very similar to what you're requesting (it saves to local storage).

**Comment by asiandrummer** [comment]
I'm closing this since we have a feature similar to your request. Happy to reopen it and have more discussions if we're misunderstanding something!

**Comment by alecperkey** [comment]
Can you post a screenshot of this? I see only a list of 20 in the history sidebar with no obvious favorites feature https://i.imgur.com/wtLoxZj.png
