### ISSUE TITLE
Schema docs not working

### ISSUE THREAD

**Issue by totaki** [graphql/graphiql#557]
When i open IDE, first send POST request to schema and add response to body. After i open docs ```No Schema Available```. Sorry for issue, cannot find support contacts
![2017-08-05 13-25-06](https://user-images.githubusercontent.com/6254062/28994879-ee8ba4e2-79e1-11e7-8f6f-101c2e0da84e.png)

**Comment by totaki** [comment]
Sorry, i find my error. I inspect code __fetchShema and find result set from result.data, from my server i return if result.data only data.

**Comment by wincent** [comment]
Glad to hear you got it sorted out. Thanks for reporting back.
