### ISSUE TITLE
Can i use graphiql in a vue application?

### ISSUE THREAD

**Issue by Nemesisesq** [graphql/graphiql#562]
I am building some api documentation for my graphql api and I would like to include graphiql as an interactive browser for users to play around with. Is there anyway I can use graphiql without the needing to implement the react component?

**Comment by wincent** [comment]
GraphiQL *is* a React component. If you can find a way to mount a React component inside a Vue app, then you can use GraphiQL. I'm afraid I don't have enough experience with Vue to tell you how to do that, but I assume it is possible and you can find the answer with a Google search, or by asking in a Vue-specific forum. Good luck!

**Comment by wincent** [comment]
Also, if you do find the answer, it would be great if you added a comment back here so that others searching in here and running across this issue can follow the breadcrumbs.

**Comment by Nemesisesq** [comment]
Will do! Thanks for your reply

**Comment by sw-yx** [comment]
hello from the future. yes i would very much like a graphiql implementation in vue. @Nemesisesq maybe we can collaborate on one. im not 100% sure im up to it but it will be an interesting challenge
