### ISSUE TITLE
Code hint didn't destroy when GraphiQL/CodeMirror instance destroyed

### ISSUE THREAD

**Issue by cpunion** [graphql/graphiql#563]
My project built with react-router and GraphiQL. When GraphiQL shows a hint, and then I switch to other UI, the code hint still stay on screen.

I tried to modify QueryEditor code:
```js
componentWillUnmount() {
  this.editor.setValue('')
  // ...other code
}
```

It can destroy the code hint. But I don't know if it's the right way.

**Comment by acao** [comment]
ah yikes, this is an interesting bug

**Comment by benjie** [comment]
Hopefully when we migrate to hooks things like this will be eradicated by virtue of `useEffect` cleaning up after itself; but I think fixing this in the interrim would be welcome too.

**Comment by AndrewBastin** [comment]
Is this issue still relevant ?

If so, can I get assigned to do this ? I would love to work on this :smile:

**Comment by acao** [comment]
we’re in the midst of replacing codemirror with monaco, so the logic for all of this is about to change
