### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by Noor0** [graphql/graphiql#565]
wouldn't it be great to be able to

- add request headers.
- view response headers.
- create and set environment variables.

**Comment by wincent** [comment]
Thanks for your feature request!

Please see #500 for most recent discussion around setting request headers. For visualizing response headers, are the Chrome dev tools sufficient for your needs? For "environment variables", I am not even sure what that means in the context of GraphiQL (it's just a React component), but the answer is likely the same: you can configure it with an arbitrary `fetcher` function, but GraphiQL itself has no business knowing or caring how you transport data to and from the schema; if you care about that you should be able to get pretty far by composing GraphiQL within your React UI, and doing whatever you want/need in your custom `fetcher`.

Closing this for now, but feel free to comment again if you have further questions/thoughts etc.

**Comment by AlexanderChen1989** [comment]
@wincent We just want a easy way to test api!

**Comment by asiandrummer** [comment]
@AlexanderChen1989 I'm sorry if our responses felt like that, but I just want to make sure we're ignoring your requests. In #500, I listed a couple of options that you can look into if you really wanted setting custom headers:
- Examples from individual contributors in [this issue](https://github.com/graphql/graphiql/issues/59)
- http://toolbox.sangria-graphql.org/ (powered by Sangria)

Hopefully those options fulfill your needs. @wincent has again made a great explanation as to why we wouldn't want the custom header feature in GraphiQL, so I'll avoid being repetitive here.

About environmental variables, in which cases would you need to use env vars? What would you like to configure/customize, and how would the env variables help? If you're using our example code to fire up a GraphiQL instance to test your queries, then you should be able to alter the server code however you need to solve your use case. If you're embedding GraphiQL as a standalone React component, then there should be a far more freedom for you to do whatever/however you wanna do. Please let us know if we're misunderstanding something.

**Comment by imolorhe** [comment]
@AlexanderChen1989 You can also checkout https://github.com/imolorhe/altair
