### ISSUE TITLE
Results render before all promises resolved, do not update

### ISSUE THREAD

**Issue by Jonathan-Millar** [graphql/graphiql#57]
with large (long running) queries, the results render before all of the promises have resolved and do not update once they have completed. 

In my implementation, due to the concurrency of resolve methods, I hit many API # of connections limitations. so I delay 1second and reattempt for a set number of tries. According to my logs that part works great but the results returned in graphical do not show a good portion of the data returned.

**Comment by leebyron** [comment]
I'm having trouble understanding what the issue is here. There should be only one single promise involved with requesting a query using GraphiQL, and that's the network request. GraphiQL displays what the network returns on the right pane.

@Jonathan-Millar could you clarify as to the rendering issue you're seeing and how it may be related to the network connection to a graphql server?

**Comment by Jonathan-Millar** [comment]
Right now I'm using https://github.com/graphql/express-graphql for the server and as I'm typing this realize that is probably a better location for the issue. 

The other promises are in the resolve functions for data access. I have a feeling the promise for the data request is being triggered to resolve prematurely. I have the resolve functions logging all the api  calls they are performing and at the moment I'm watching the logs and see the graphql server is still performing api calls after the (partial) result has been displayed in graphiql 

Feel free to close this if you agree.

**Comment by leebyron** [comment]
Yeah, it sounds like this is not an issue with the GraphiQL browser, but is an issue with your GraphQL server's resolve functions.

If you're still having issues, you should problem open them on github.com/graphql/graphql-js where we discuss the GraphQL server itself.
