### ISSUE TITLE
react libs 404

### ISSUE THREAD

**Issue by Billy-** [graphql/graphiql#572]
At the time of writing, unpkg is returning 404s for the react libs:

```
unpkg.com/react@15.6.1/dist/react.min.js
Failed to load resource: the server responded with a status of 404 ()
unpkg.com/react-dom@15.6.1/dist/react-dom.min.js
Failed to load resource: the server responded with a status of 404 ()
```

**Comment by jimaek** [comment]
You can use jsDelivr instead http://cdn.jsdelivr.net/npm/react@15.6.1/dist/react.min.js
It was built for production use and its more stable.

**Comment by astorije** [comment]
It seems to me this can be closed now, probably a temporary issue:

```sh
$ curl -I https://unpkg.com/react@15.6.1/dist/react.min.js
HTTP/1.1 200 OK
Date: Sat, 19 Aug 2017 18:39:48 GMT
Content-Type: application/javascript
Content-Length: 23040
...

$ curl -I https://unpkg.com/react-dom@15.6.1/dist/react-dom.min.js
HTTP/1.1 200 OK
Date: Sat, 19 Aug 2017 18:41:09 GMT
Content-Type: application/javascript
Content-Length: 130293
...
```

Maybe related to [this](https://twitter.com/unpkg/status/895882834656632833)?

**Comment by Billy-** [comment]
If jsDelivr is a better option as @jimaek suggests, I personally would be tempted to switch.

More importantly I would look at providing some sort of fallback - a local copy perhaps?

**Comment by asiandrummer** [comment]
Forgive me if I'm missing something @Billy-, but where are we using unpkg for loading static resource? The only reference I see is from `prop-types` dependency lib, and it's not loading `react`.

Nonetheless of that, I'm for having a local copy as a fallback for examples. Would be lovely to have some contributions here please.

**Comment by Billy-** [comment]
Sorry, I didn't look into the source code. I just loaded up graphiql (in it's own tab) and was being greeted with a blank page and only those two errors in the console. I assumed it must be how graphiql loaded those libs as to not include them as dependencies of graphql

**Comment by asiandrummer** [comment]
@Billy- got it - no worries! I'll close this issue then; if there is any other things please feel free to open another issue.

**Comment by Billy-** [comment]
Can I ask, out of interest, if you aren't using unpkg, then how can these errors have appeared and caused the whole interface to break?
