### ISSUE TITLE
Markdown in type documentation is not rendered

### ISSUE THREAD

**Issue by astorije** [graphql/graphiql#575]
Assuming I have the following GraphQL type and field:

```graphql
type Foo {
 # **Hello**, is it _me_ you're `looking for`?
 bar: String!
}
```

The docs panel properly converts the Markdown tags in the comment when looking at documentation of the `bar` field:

<img width="250" alt="screen shot 2017-08-19 at 16 38 39" src="https://user-images.githubusercontent.com/113730/29490051-5ba8fb70-84fe-11e7-8ef4-531b31d6638d.png">

but not when displaying the documentation of the `Foo` type:

<img width="250" alt="screen shot 2017-08-19 at 16 38 30" src="https://user-images.githubusercontent.com/113730/29490052-6954e3ba-84fe-11e7-80c2-82930f656659.png">

I would be very happy to help fixing this and open a PR if you are interested.

---

This is not directly relevant for GraphiQL, but for the record, and for myself when I want to reproduce / test the fix, I'm using [Sangria for Scala](sangria-graphql.org) and this is the code for this type (that way I can just copy-paste it, /me lazy):

```scala
import sangria.macros.derive._

case class Foo(
  @GraphQLDescription("**Hello**, is it _me_ you're `looking for`?")
  bar: String
)

object Foo {
  implicit val FooType = deriveObjectType[Unit, Foo]()
}
```

**Comment by asiandrummer** [comment]
@astorije there should be some decent test cases for this not to go haywire, but yeah, I think this is a bug, and your contribution would be most appreciated. For the test cases, I'm basically wondering if a support for markdown would break the overflow/UI ordering/etc. If that's okay then I'm all for reviewing/accepting the PR!

Also, keep in mind that https://github.com/graphql/graphiql/pull/581 exists and we may be merging it pretty soon ;)
