### ISSUE TITLE
Version 1.0 fails to run introspection query

### ISSUE THREAD

**Issue by voroshkov** [graphql/graphiql#583]
When trying to run ChromiQL against local GQL server, getting the following error in UI:
```
{
  "errors": [
    {
      "message": "Cannot query field \"locations\" on type \"__Directive\"."
    }
  ],
  "data": null
}
```
Although it was working fine with 0.1 version.

**Comment by wincent** [comment]
@voroshkov: Looks like this one was intended for https://github.com/ermanc/ChromeiQL

**Comment by voroshkov** [comment]
Indeed. Sorry, missed the repo
