### ISSUE TITLE
How to use Graphiql when /graphql protected by JWT token (authorization header)

### ISSUE THREAD

**Issue by sulliwane** [graphql/graphiql#59]
My **/graphql** route is protected by **JWT token**, so every HTTP request needs to set:

```
 headers: {
      Authorization: 'Bearer ' + token
    }
```

To get through the authentication middleware and hit **/graphql**.

How to manage this authentication step when using **graphiql** ? graphiql is so convenient, it's a pity to not use it :(
thanks for any suggestion!

**Comment by KyleAMathews** [comment]
Download @skevy's https://github.com/skevy/graphiql-app and your header. I have the same setup as you and use this daily.

**Comment by sulliwane** [comment]
@KyleAMathews awesome, I will give it a shot (my main computer is linux distro though...). thanks

**Comment by skevy** [comment]
@sulliwane - I'm sure it would compile on Linux - just haven't tried.

**Comment by sulliwane** [comment]
I just tried ```npm install && npm start``` under linux (ubuntu 14.04) and graphiql-app-V0.3.1, but got blank screen, see here: https://github.com/skevy/graphiql-app/issues/10

I close this issue as I have the answer now.

**Comment by cancan101** [comment]
Any reason to close this issue and opposed to adding the header editor to the (main) graphiql?

**Comment by sulliwane** [comment]
No reason, indeed it would be nice if we could set the header directly into graphiql app. (I'm using graphiql-app right now.)

**Comment by leebyron** [comment]
GraphiQL is generic and doesn't know anything about the network! This is great because you can configure it to use whatever your GraphQL server uses. This is how @skevy was able to build a standalone app version of GraphiQL.

I suggest taking a look at the [example](https://github.com/graphql/graphiql/blob/master/example/index.html) - where you see `graphQLFetcher` is where you can configure your network fetching however you like, in your case by including any authentication details that may be necessary.

Often, when your GraphQL endpoint is behind a authorization feature like this, it is common to expose the GraphiQL tool via a different endpoint on your server.

**Comment by MarkAndrewJohnson** [comment]
@leebyron I would agree being generic is a reason not to automate everything.  I would think, though, that being generic is exactly why it DOES makes sense to have a field allowing custom headers to be set manually by the user!

I'm also unclear as to your last statement.  It doesn't avoid the need for auth tokens to be pushed around.

**Comment by eugenehp** [comment]
@MarkAndrewJohnson @sulliwane @cancan101 @KyleAMathews  Guys, it would be interesting to get your opinion on this https://github.com/graphql/express-graphql/issues/101

**Comment by mzohaibqc** [comment]
I found a way to fix this problem. On Chrome, you can install an extention `ModHeader` https://chrome.google.com/webstore/detail/modheader/idgpnmonknjnojddfkpgkljpfnnfcklj which will allow you to modify request or response headers. In this way, you can send Authorization header with each request and graphiql will work fine.

**Comment by vitalcode** [comment]
Look at auth-graphiql (https://github.com/vitalcode/auth-graphiql) that wraps GraphiQL providing support for bearer token and arbitrary URL. Great for testing GraphQL services secured with OAuth 2.0.

**Comment by jasonmorita** [comment]
For those still having this issue, my coworker came up with a cheap solution (in Express in my case) Have your GraphiQL answer at another endpoint as Lee said above and apply `basic-auth` to that, where you can supply your JWT, add it to the headers and then let `express-jwt` pick it up in the next middleware.

**Comment by hunt** [comment]
Actually, I use a simple solution between our GraphQL development process. If you GraphQL server parse a `access_token` from `querystring` more than just a http header.

We can pass `access_token` in query string to the browser's address bar at our GraphiQL page `?access_token=xxx&query=...` then GraphiQL will send `access_token` to `req.query`

I parse a token with something like `express-bearer-token`

**Comment by dimpiax** [comment]
if you are using `Content-Type: application/graphql`, I propose to request token in query:
```
$ curl ... http://localhost:3000/graphql\?\token=TOKEN
```

**Comment by estaub** [comment]
FWIW... _In dev mode only_, I've set up my server to save the most recent valid token used for the graphql endpoint, and slap it on any subsequent graphiql-driven queries (where the referer header is graphiql).  I just sign into the app and then can use graphiql at will.

**Comment by sasso** [comment]
Easy implementation to get JWT Token support in GraphiQL

https://gist.github.com/sasso/3c3d728e0049d5b66a2c19b349b7f164

**Comment by PetrSnobelt** [comment]
@sasso Thanks, but your old version does not support websockets :-(

**Comment by Durisvk** [comment]
@sulliwane @KyleAMathews @skevy @cancan101 @leebyron @MarkAndrewJohnson @eugenehp @mzohaibqc @vitalcode @jasonmorita @hunt @dimpiax @estaub @sasso @PetrSnobelt 

Hello I've implemented the feature you've requested

Here are the links to the library files:
https://cdn.jsdelivr.net/npm/graphiql-custom-headers@1.0.0/graphiql-custom-headers.css
https://cdn.jsdelivr.net/npm/graphiql-custom-headers@1.0.0/graphiql-custom-headers.js
https://cdn.jsdelivr.net/npm/graphiql-custom-headers@1.0.0/graphiql-custom-headers.min.js

Here is a simple example of how to use it:
https://github.com/Durisvk/graphiql

It's really simple, you don't have to do almost any changes to your current running app.

And it's also available on NPM: https://www.npmjs.com/package/graphiql-custom-headers

This is how it looks like: http://imgur.com/a/3VQDT

I've also implemented it already to my project: https://github.com/Durisvk/senegraph
so it's already available on HapiJS servers. Somewhere in the future I would like to implement it also on Express. Maybe you could help me out with this.

Hopefully you'll like my solution ...

**Comment by emjaksa** [comment]
Hope this helps. How I implimented custom headers for my GraphiQL interface with a express-graphql server.

Modify your server to handle post one endpoint and get requests to the graphiql on another.

```
app.post(
  '/graphql',
  expressGraphQL({
    schema: GraphQLSchema,
    graphiql: false, // Disable graphiql for posts requests
  }),
)

app.get(
  '/graphql',
  expressGraphQL({
    schema: GraphQLSchema,
    graphiql: true, // Enable graphiql for get requests
  }),
)
```

Basically you need to create a new index.html for your GraphiQL interface and you can add it to your servers public directory i.e. `<public-path>/graphql/index.html`. In that file you can **modify the fetch function** to send any additional headers in your requests. I got my index.html from the graphiql [example](https://github.com/graphql/graphiql/blob/master/example/index.html). 

I use webpack and the [html-webpack-plugin](https://github.com/jantimon/html-webpack-plugin) to bundle the index.html. This allows it to get the correct version of graphql used in my project from the CDN. Below is an example of my webpack config and my ejs template of the index.html.

**webpack.config.js**
```
new HtmlWebpackPlugin({
  filename: 'graphql/index.html', // Write the file to <public-path>/graphql/index.html
  inject: false, // Do not inject any of your project assets into the template
  GRAPHQL_VERSION: packageJSON.dependencies.graphql.replace(/[^0-9.]/g, ''), // Get the graphql version from my package.json
  template: 'graphiql.ejs', // path to template
}),
```

**graphiql.ejs**
```
<!--
 *  Copyright (c) Facebook, Inc.
 *  All rights reserved.
 *
 *  This source code is licensed under the license found in the
 *  LICENSE file in the root directory of this source tree.
-->
<!DOCTYPE html>
<html>
  <head>
    <style>
      body {
        height: 100%;
        margin: 0;
        width: 100%;
        overflow: hidden;
      }
      #graphiql {
        height: 100vh;
      }
    </style>

    <!--
      This GraphiQL example depends on Promise and fetch, which are available in
      modern browsers, but can be "polyfilled" for older browsers.
      GraphiQL itself depends on React DOM.
      If you do not want to rely on a CDN, you can host these files locally or
      include them directly in your favored resource bunder.
    -->
    <script src="//cdn.jsdelivr.net/es6-promise/4.0.5/es6-promise.auto.min.js"></script>
    <script src="//cdn.jsdelivr.net/fetch/0.9.0/fetch.min.js"></script>
    <script src="//cdn.jsdelivr.net/react/15.4.2/react.min.js"></script>
    <script src="//cdn.jsdelivr.net/react/15.4.2/react-dom.min.js"></script>

    <link href="//cdn.jsdelivr.net/npm/graphiql@<%= htmlWebpackPlugin.options.GRAPHQL_VERSION %>/graphiql.css" rel="stylesheet" />
    <script src="//cdn.jsdelivr.net/npm/graphiql@<%= htmlWebpackPlugin.options.GRAPHQL_VERSION %>/graphiql.min.js"></script>
  </head>
  <body>
    <div id="graphiql">Loading...</div>
    <script>

      /**
       * This GraphiQL example illustrates how to use some of GraphiQL's props
       * in order to enable reading and updating the URL parameters, making
       * link sharing of queries a little bit easier.
       *
       * This is only one example of this kind of feature, GraphiQL exposes
       * various React params to enable interesting integrations.
       */

        // Parse the search string to get url parameters.
      var search = window.location.search;
      var parameters = {};
      search.substr(1).split('&').forEach(function (entry) {
        var eq = entry.indexOf('=');
        if (eq >= 0) {
          parameters[decodeURIComponent(entry.slice(0, eq))] =
            decodeURIComponent(entry.slice(eq + 1));
        }
      });

      // if variables was provided, try to format it.
      if (parameters.variables) {
        try {
          parameters.variables =
            JSON.stringify(JSON.parse(parameters.variables), null, 2);
        } catch (e) {
          // Do nothing, we want to display the invalid JSON as a string, rather
          // than present an error.
        }
      }

      // When the query and variables string is edited, update the URL bar so
      // that it can be easily shared
      function onEditQuery(newQuery) {
        parameters.query = newQuery;
        updateURL();
      }

      function onEditVariables(newVariables) {
        parameters.variables = newVariables;
        updateURL();
      }

      function onEditOperationName(newOperationName) {
        parameters.operationName = newOperationName;
        updateURL();
      }

      function updateURL() {
        var newSearch = '?' + Object.keys(parameters).filter(function (key) {
          return Boolean(parameters[key]);
        }).map(function (key) {
          return encodeURIComponent(key) + '=' +
            encodeURIComponent(parameters[key]);
        }).join('&');
        history.replaceState(null, null, newSearch);
      }

      // Defines a GraphQL fetcher using the fetch API. You're not required to
      // use fetch, and could instead implement graphQLFetcher however you like,
      // as long as it returns a Promise or Observable.
      function graphQLFetcher(graphQLParams) {
		// Get token from local storage
      	var token = localStorage.getItem('token')

        // This example expects a GraphQL server at the path /graphql.
        // Change this to point wherever you host your GraphQL server.
        return fetch('/graphql', {
          method: 'post',
          headers: {
            'Accept': 'application/json',
            'Content-Type': 'application/json',
            'Authorization': token ? 'Bearer '+ token : null,
          },
          body: JSON.stringify(graphQLParams),
          credentials: 'include',
        }).then(function (response) {
          return response.text();
        }).then(function (responseBody) {
          try {
            return JSON.parse(responseBody);
          } catch (error) {
            return responseBody;
          }
        });
      }

      // Render <GraphiQL /> into the body.
      // See the README in the top level of this module to learn more about
      // how you can customize GraphiQL by providing different values or
      // additional child elements.
      ReactDOM.render(
        React.createElement(GraphiQL, {
          fetcher: graphQLFetcher,
          query: parameters.query,
          variables: parameters.variables,
          operationName: parameters.operationName,
          onEditQuery: onEditQuery,
          onEditVariables: onEditVariables,
          onEditOperationName: onEditOperationName
        }),
        document.getElementById('graphiql')
      );
    </script>
  </body>
</html>
```

**Comment by wincent** [comment]
Thanks for sharing @emjaksa.

**Comment by gauravmakkar** [comment]
@emjaksa Your code is working fine with query operations, what about subscriptions?...

**Comment by AndreyMalykhin** [comment]
I've ended up passing access token through Graphiql's Query Variables pane:

`{
  "accessToken": "azaza"
}`

**Comment by imolorhe** [comment]
@AndreyMalykhin You can use https://altair.sirmuel.design/ also.

**Comment by greghaygood** [comment]
@AndreyMalykhin +1 to Altair over the GraphiQL client if only for the ability to edit the headers when my tokens change (rather than deleting and re-entering them).

**Comment by nitrnitr** [comment]
What about
```
GraphiQL::Rails.config.headers['Authorization'] = -> (context) do
  "your jwt"
end
```
on the `graphiql.rb` initializer

**Comment by khaledosman** [comment]
its really sad that this is still open after 3 years... All the solutions provided in the comments are just workarounds or reference to other tools. It shouldn't be too complicated to implement some form in the UI to add the headers.. Are there any intentions to implement this?

**Comment by praveenweb** [comment]
@khaledosman - We have a forked version of GraphiQL which adds a header UI. It comes with a configurable endpoint and headers and is hosted online at [https://graphiql-online.com](https://graphiql-online.com).

The source of the fork is [here](https://github.com/hasura/graphql-engine/tree/master/community/tools/graphiql-online).

Hope its helpful for some people :)

**Comment by christophermlne** [comment]
> GraphiQL is generic and doesn't know anything about the network! This is great because you can configure it to use whatever your GraphQL server uses. This is how @skevy was able to build a standalone app version of GraphiQL.
> 
> I suggest taking a look at the [example](https://github.com/graphql/graphiql/blob/master/example/index.html) - where you see `graphQLFetcher` is where you can configure your network fetching however you like, in your case by including any authentication details that may be necessary.
> 
> Often, when your GraphQL endpoint is behind a authorization feature like this, it is common to expose the GraphiQL tool via a different endpoint on your server.

How is adding the ability for the end user to enter request headers 'non-generic'?
These workarounds are a PITA.

**Comment by mkanand33** [comment]
I have a question about graphene authentication...how can I create different tokens for two different logins using graphene -jwt? I want to return a token for user login and also a token for manual admin login? how can I do both?

**Comment by johndpope** [comment]
I got here from google search found answer in issue below - in the graphql - http headers at bottom just add

{
    "Authorization": "Bearer your-token-goes-here"
}
https://github.com/howtographql/howtographql/issues/448

**Comment by acao** [comment]
You can customize headers as they do here, with a custom fetcher:
https://github.com/graphql/graphiql#getting-started

**Comment by westpole** [comment]
> I got here from google search found answer in issue below - in the graphql - http headers at bottom just add
> 
> {
> "Authorization": "Bearer your-token-goes-here"
> }
> [howtographql/howtographql#448](https://github.com/howtographql/howtographql/issues/448)

GraphiQL has only "Query variables" section. It does not have "http headers". How did you get that section? What type of UI do you use to test GraphQL queries?

**Comment by christophermlne** [comment]
@westpole https://github.com/absinthe-graphql/absinthe_plug/blob/master/lib/absinthe/plug/graphiql.ex

Make sure you have configured the correct interface.
If you have the correct interface, there is a button you can push to access the headers functionality

**Comment by sorenhoyer** [comment]
I don't get why they don't just add a "headers" section just like the "query variables" section. I'm sure there is no good reason for not doing so...

**Comment by benjie** [comment]
@sorenhoyer The reason is that GraphQL is not a HTTP API, it's a function call. It can be consumed locally in your programming language of choice, or over a custom TCP/UDP protocol, or via HTTP, or via Websockets, or through IPC, or through any number of other transports. Headers are only used for the HTTP transport (and, possibly, for websockets, although typically they're not used there by clients). So headers are a concern outside of GraphiQL, only the `fetcher` function needs to know about them, and that function also lives outside of GraphiQL. You can already add your own interface for managing headers outside of the main GraphiQL component, and you can even add a button inside of GraphiQL to open said interface - this is [what I do in PostGraphile's `--enhance-graphiql` mode](https://github.com/graphile/postgraphile/blob/7979cfb10f3246c7c198be8db2c929e82e0e4323/postgraphiql/src/components/PostGraphiQL.js#L640-L644) in case you want to see an example.

In GraphiQL v1 we're planning to add a plugin system where you can easily insert these "external concerns" into the GraphiQL interface, and a preset system with sharable plugin configurations for a particular use case. We're hoping this will enable people to use a HTTP preset that will pull in common HTTP concerns such as headers, URL bar, cookie configuration, etc. so you can get the interface you want with minimal effort. We've only recently started on this project so it's still a while away (most of us are independent open source developers doing this in our spare time, and only became maintainers very recently) but progress is good.

**Comment by sorenhoyer** [comment]
Thanks for your elaborate answer @benjie and good luck on your future work on graphiql.

For now, for those of us in need of a graphiql-ish interface, with headers support, I can recommend: https://chrome.google.com/webstore/detail/graphiql-feen/mcbfdonlkfpbfdpimkjilhdneikhfklp

**Comment by benjie** [comment]
That’s not hacking it, that’s exactly how it is intended to be used.

GraphiQL is the building blocks with which you can make a custom GraphQL IDE, and has a very well defined boundary: you worry about the transport and all the transport concerns (via the fetcher function) and GraphiQL worries about the text editing and GraphQL features/documentation.

**Comment by vinny42** [comment]
"That’s not hacking it, that’s exactly how it is intended to be used."

That sounds like a very very poor excuse not to have to do work :-)
In the end; the majority of applications for graphiql require that it sends headers. The fact that it cannot do so without the user changing code is ridiculous. 

This issue has been open for four years, you could save us all a ton of misery by just implementing a basic version of this feature and let whoever needs to override it do so.

I'm sorry, it's just ridiculous.

**Comment by imolorhe** [comment]
@SephReed @vinny42 The core of the GraphiQL tool isn't specific to HTTP as a transport mechanism (that's what @benjie is saying). While it is true that the majority of the cases so far have used HTTP as a transport mechanism, that is solely as a result of the use cases that exist.

On the other hand, the GraphiQL team was recently restructured and already have this implementation in mind, to make GraphiQL pluggable (https://github.com/graphql/graphiql/issues/829) such that there would be plugins providing some of these features, and also presets that bundle plugins together as they make sense for certain scenarios.

The suggestions here are for working with headers in the current GraphiQL version, and how that can be achieved. Most likely there wouldn't be any modifications to this current (soon to be old) version, and if you don't like the approaches suggested, you could consider other tools for now (there's a number of them available) until the GraphiQL v1.0.0 is released.

**Final note: the members of the team maintaining GraphiQL are opensource contributors!**

**Comment by SephReed** [comment]
> the members of the team maintaining GraphiQL are opensource contributors

Who runs the internal politics though?  I highly doubt that everyone collectively agreed "making http easy is bad."  God speed to open-source contributors, but using them as a human shield for what is almost certainly a top down decision is kind of cheap, eh?

**Comment by Neitsch** [comment]
@SephReed - would you mind laying out how we can improve and make concrete suggestions? 
Above you made a suggestion about using a different props structure, but I am getting a feeling that there is something overarching missing for you to ramp up on GraphiQL quickly.
Open source is great, because people with different ideas come together. Therefore I value your input. I'd be more than happy to review/approve any pull requests that make it even easier to use or improve the documentation :)

**Comment by SephReed** [comment]
Gladly.

I think it's important to have configuration and I also it's also important to have good defaults.  In terms of pretty much any **javascript** implementation of graphiql, it seem safe to assume that good default for fetcher is just fetch pointed at "/graphql."  This definitely wouldn't cover every use case, but it's a good starting place.

Following is about all the code I think it should take to setup graphql, with fetch, pointed to an arbitrary endpoint, with a header component added to the mix:
```
GraphiQL.renderIn("graphiql", {
  fetcher: "/gql-endpoint",
  showHeaderInputComponent: true,
});
```

Having 20-50 lines of boilerplate to achieve a simple api with jwt authentication is just a oppressive nuisance when it could pretty easily be supplied by a tiny function like the one above.   This would cover most api use cases... all the ones I can think of at least, but definitely not all.  Still, by default, this seems like all it should really take to get a project with graphiql up and running.

**Comment by SephReed** [comment]
I guess what I'm really trying to say is, you've made a wonderful project.  It's very nice and I don't mean to be a bother.

**Comment by Haseeb717** [comment]
Is there any way to send header from Graphiql now? which something official from graphiql

**Comment by khaledosman** [comment]
> @SephReed - would you mind laying out how we can improve and make concrete suggestions?
> Above you made a suggestion about using a different props structure, but I am getting a feeling that there is something overarching missing for you to ramp up on GraphiQL quickly.
> Open source is great, because people with different ideas come together. Therefore I value your input. I'd be more than happy to review/approve any pull requests that make it even easier to use or improve the documentation :)

With no way to set authentication headers the library is unusable for most people, most people don't build demo todo apps, but real world apps for customers and corporates, so authentication is kinda important.

With no workarounds or recommended way to do it at a README or a documentation file, you're pushing people away from using your open-source tools because you don't even acknowledge it as a normal usecase, which is way everyone else in this thread is suggesting an alternative library.

My question is, As a contributor to this library, have you every used this tool before? have you ever needed to build authentication? if yes, how did you do it?

**Comment by vinny42** [comment]
One last FYI:

We've taken the previous advice and ditched graphiql as "unusable for our purpose".

"While it is true that the majority of the cases so far have used HTTP as a transport mechanism, that is solely as a result of the use cases that exist."

Yes, the majority of use cases are HTTP, that's the point; there is no benefit to being network-protocol-agnostic and refusing to add features for HTTP in a tool that is pretty much only used over HTTP is... I'll let you fill in the bits where I might say bad things.

Thanks for the response, I hope GraphiQL will some day be a good alternative again.

**Comment by Neitsch** [comment]
@khaledosman - thank you for your input. Would you mind help me understand it in some more detail? Are you looking for an explicit method for setting the HTTP headers? At this point I believe you can do something like this:

```
// This is where you can choose what auth headers to add
function headerGenerator() {
  return {
    'Authorization': 'Bearer <your token goes here>',
  }
}

// Semi generic GraphQL query execution method
function graphQLFetcher(additionalHeadersFunction) {
  return function(graphQLParams) {
    return fetch('/graphql', {
      method: 'post',
      headers: {
        'Accept': 'application/json',
        'Content-Type': 'application/json',
        ...additionalHeadersFunction()
      },
      body: JSON.stringify(graphQLParams),
      credentials: 'include',
    }).then(function(response) {
      return JSON.parse(response.text());
    });
  }
}

ReactDOM.render(
  React.createElement(GraphiQL, {
    fetcher: graphQLFetcher(headerGenerator),
  }),
  document.getElementById('graphiql')
);
```

This level of effort appears relatively low to me. Would you mind elaborating what you would like to see? Am I missing anything that this solution fundamentally does not deliver? Would you like to see this as a setup in the example package of the repo?

**Comment by khaledosman** [comment]
@Neitsch a setup example/readme would be a good start.

 I think most people use the graphiql middleware and don't setup/use the react component manually, so I'd expect to bypass the component configuration all together and have some form for the headers rendered as part of the component or hidden behind a button that takes care of this by default.

**Comment by Neitsch** [comment]
@khaledosman - ah, apologies if I missed that before. That sounds pretty reasonable, especially small setups don't want to go through the trouble of setting all that up. I briefly looked into this. The key challenge is that `express-graphql` basically only gives you server side configuration options. There are a few things we could attempt:
* Modify https://github.com/graphql/express-graphql/blob/master/src/renderGraphiQL.js to somehow include the jwt token. Maybe a configuration key could be a stringified function that does whatever you want to do to set the token (gross solution, but works for everyone)
* Fork `express-graphql` and make it work for your case. I would anticipate that it's pretty low effort, but it's a headache to maintain.

Neither solution is particularly good, but that's the only two I can come up with right now. I'll keep thinking about it some more. Thanks again for the input!

**Comment by khaledosman** [comment]
For some inspiration this is how prisma's [playground](https://github.com/prisma-labs/graphql-playground) does it which is included by default in the new apollo-server v2
![image](https://user-images.githubusercontent.com/2937633/65605060-bd9a0c00-dfa8-11e9-8985-4fa545a65da4.png)

**Comment by aamod1990** [comment]
> My **/graphql** route is protected by **JWT token**, so every HTTP request needs to set:
> 
> ```
>  headers: {
>       Authorization: 'Bearer ' + token
>     }
> ```
> 
> To get through the authentication middleware and hit **/graphql**.
> 
> How to manage this authentication step when using **graphiql** ? graphiql is so convenient, it's a pity to not use it :(
> thanks for any suggestion!

Currently we are using Modify Headers add ons to pass the token in our graphql

**Comment by acao** [comment]
Just specify that header when creating your required fetcher!

**Comment by rs-ds** [comment]
For firefox users, here is the `Modify Header Value` addon: https://addons.mozilla.org/en-US/firefox/addon/modify-header-value/?src=search

**Comment by gsugambit** [comment]
I definitely think it's easier to use something like mod header to solve this problem. It's avaiable in chrome or firefox

**Comment by acao** [comment]
we will be providing an example soon, but all of this is possible with the current GraphiQL

**Comment by penx** [comment]
@acao is this via the plugin system (in v1.0.0-alpha?) previously mentioned by @benjie ?

> In GraphiQL v1 we're planning to add a plugin system

**Comment by acao** [comment]
the plugin system will make it easier to provide a nice UI for this. there are going to be quite a few more alpha versions before we have a plugin system

this is all possible currently though, in 0.7.5 or the alpha, so i had hoped to provide a full auth example before I got too deep into working on monaco or the react refactor for plugins

**Comment by hassaaneforte** [comment]
> I found a way to fix this problem. On Chrome, you can install an extention `ModHeader` https://chrome.google.com/webstore/detail/modheader/idgpnmonknjnojddfkpgkljpfnnfcklj which will allow you to modify request or response headers. In this way, you can send Authorization header with each request and graphiql will work fine.

how to use it? please guide me

**Comment by luisdav86** [comment]
I used https://chrome.google.com/webstore/detail/altair-graphql-client/flnheeellpciglgpaodhkhmapeljopja

**Comment by mrceperka** [comment]
This one works for me :)
![image](https://user-images.githubusercontent.com/22822651/82575378-b0a9d880-9b88-11ea-8493-d0b90607c8b4.png)

**Comment by acao** [comment]
I've decided - given that we are doing one final 1.0.0 (pre rewrite/plugins) stable release for GraphiQL, we get to have *one* feature.

And that's a headers tab. Whoever wants to, feel free to add a single tab for headers in a PR, and if we can get it merged next week, we can at least have that until we have a stable beta plugin API!

**Comment by connorshea** [comment]
I've opened a draft PR for this :) #1543

**Comment by harshithpabbati** [comment]
As header tab is added to GraphiQL now we can close this issue right @acao?

**Comment by connorshea** [comment]
Yep, if you upgrade to 1.0.0 you can enable the headers editor :D I have it enabled on my app [here](https://vglist.co/graphiql).

The code I use to create the GraphiQL instance with the headers editor enabled and pre-filled is this:

```js
let graphQLFetcher = (graphQLParams, opts = { headers: {} }) => {
  return fetch(window.location.origin + '/graphql', {
    method: 'post',
    headers: Object.assign({ 'Content-Type': 'application/json', 'User-Agent': 'vglist.co GraphiQL' }, opts.headers),
    body: JSON.stringify(graphQLParams),
  }).then(response => response.json());
}

ReactDOM.render(
  React.createElement(GraphiQL, {
    fetcher: graphQLFetcher,
    headerEditorEnabled: true,
    headers: '{\n  "X-User-Email": "foo@example.com",\n  "X-User-Token": "API_TOKEN_HERE"\n}'
  }),
  document.getElementById("graphiql-injection-point")
);
```

We should probably update the README to mention give a code example for using the headers editor and sending headers with the GraphiQL requests.

**Comment by acao** [comment]
@connorshea excellent point, yes.

possibly we can add custom headers to the graphiql cdn exmaple?

**Comment by jonaskello** [comment]
The `headerEditorEnabled` is great :-). Is there also some way to include those headers when graphiql asks for the schema? It seems like `graphQLFetcher` is also used for fetching the schema but in that case `opts` have empty headers (at least from my limited testing).

**Comment by acao** [comment]
I'm deep into 2.0.0 plugin API now, but possibly @connorshea can add that for another 1.0.0 release? I should have caught that in the review, my bad.

**Comment by acao** [comment]
to confirm, @jonaskello it was not added. i will pivot to fix this issue!

**Comment by acao** [comment]
released #1593 as `graphiql@1.03`, enjoy!

**Comment by connorshea** [comment]
👍 @acao I think we can close this now :)

**Comment by jonaskello** [comment]
@acao I can confirm it works! Thanks :-)

**Comment by acao** [comment]
thanks everyone!

for the record, and you can see this in the GraphiQL readme now, you can enable the headers editor with `headerEditorEnabled` prop, and even use a static `headers` string prop to set the default headers in the headers editor, and users can override this per-request in the headers tab.

thanks @connorshea for your work and @harshithpabbati and @ncthbrt for helping to review!

any new features for this will be part of `graphiql@2.0.01 plugins, as, following the Spec WG, HTTP-driven functionality is now part of a seperate GraphQL HTTP Spec. We must honor the HTTP agnostic default spec by default, and then will have http plugins to follow the HTTP spec.

consider this a bonus for the very long feature freeze as we had to spend so long preparing GraphiQL for the rewrite, performing the rewrite, and are now working on the plugin spec. the new SDK-oriented approach will be very rewarding!

**Comment by acao** [comment]
to add, if there are any more bugs with this new feature, we will gladly introduce them to 1.0.x patches :)

**Comment by jcarroll2007** [comment]
> for the record, and you can see this in the GraphiQL readme now,

@acao I'm not seeing this in the readme. Would you possibly mind a link to docs on how to use this feature?

**Comment by penx** [comment]
> for the record, and you can see this in the GraphiQL readme now, you can enable the headers editor with `headersEditorEnabled` prop

@acao you may want to edit this to save people time trying to figure out why it doesn't work - it's `headerEditorEnabled` not `headersEditorEnabled`

**Comment by acao** [comment]
@penx thanks for the catch, will update!

your middleware looks great but it exposes a huge template injection attack surface - exposing xss and other potential attack vectors! i had to issue a CVE for graphql playground and issue a security fix for the same exact reasons. playground repo now has an example with a readme that explains all of this

we will be rolling our own middeware packages soon when i have time to get to it. there is still an open PR that needs cleanup if you want to create a new PR based off that to help advance that! We actually use ReactDOM/server in that PR there, but an xss filtered template tag implementation ala the new playground fix would be welcome as well. you can introduce several new typescript packages if you want, or just a basic underling renderer method like playground-html

**Comment by craigmit** [comment]
> Easy implementation to get JWT Token support in GraphiQL
> 
> https://gist.github.com/sasso/3c3d728e0049d5b66a2c19b349b7f164
> 
> ![screenshot 2017-07-07 09 46 20](https://user-images.githubusercontent.com/8398242/27968261-27bed1b0-62fb-11e7-9d1a-88f0a82c2f00.png)

This worked great, except the graphiql screen falls off the bottom of the page.

Here's a version using flexbox that aligns it properly:  https://gist.github.com/craigmit/44499818664fc34083f2aa96069f0636

**Comment by benjie** [comment]
You could also use the headers editor:

![Screenshot_20210218_145143](https://user-images.githubusercontent.com/129910/108374484-eacc0780-71f8-11eb-8ada-cf195761a0a6.png)

**Comment by craigmit** [comment]
Thanks @benjie 

I wasn't seeing the `Request Headers` tab.  I've now figured out how to get it to show:
1.  You need the latest version (currently 11.0.0).
2.  You have to add the property:
```
graphiql:
  props:
    variables:
      headerEditorEnabled: "true"
```
And, yes, the value for `headerEditorEnabled` is expected to be a string, not a boolean.

But now it shows, and works perfectly!  😃

**Comment by craigmit** [comment]
I've now modified the new GraphiQL, to automatically set the auth header from a # param:

https://gist.github.com/craigmit/0cce78ffe33ca3551fbcc35016e8b3e2

Usage is:
```
graphiqlSetAuth.html#[JWT_TOKEN]
```
and it will set the Authorization header for you.

The only change to the original graphiql html was the addition of:
```javascript
const tokenParam = window.location.hash.substr(1);

if (tokenParam) {
  headers = {"Authorization": "Bearer " + tokenParam}
  window.history.replaceState({}, document.title, window.location.href.split('#')[0]);
}
```

**Comment by njlr** [comment]
The request headers box works a treat! However, you must pass the headers through in your fetcher. For example:

```javascript
const graphQLFetcher = async (graphQLParams, opts) => {
  const { headers = {} } = opts;

  const response = await fetch('/graphql', {
    method: 'post',
    headers: {
      'Accept': 'application/json',
      'Content-Type': 'application/json',
      ...headers,
    },
    body: JSON.stringify(graphQLParams),
  });

  return response.json();
};
```

**Comment by m-thirumal** [comment]
![Screen Shot 2022-09-23 at 6 57 08 PM](https://user-images.githubusercontent.com/6417222/191970705-5b0b7a6d-0882-464a-bf90-80f2cb815ab0.png)
Add Authentication in the UI itself

**Comment by cedricDevWP** [comment]
@m-thirumal hello, i try to configure api platform with jwt and graphql but I can’t do it… all the time I have 403 when I use security granted… 

can you explain how have you configure security.yaml (and other file maybe) to make work pls 😕 ?

**Comment by Akifcan** [comment]
```
graphqlHTTP({
    schema,
    rootValue,
    graphiql: {
      headerEditorEnabled: true
    }
  })
```

**Comment by KenEucker** [comment]
I have been digging through this thread trying to find a way to pass a header, the authorization header, to Graphiql in the request. I am running Graphiql in an iFrame from `localhost:8000/graphql` and I want to be able to do something like `localhost:8000/graphql?headers=serializedheadersstring` and have the header values be populated into the editor for all tabs. 

Is this possible?

**Comment by njlr** [comment]
> I have been digging through this thread trying to find a way to pass a header, the authorization header, to Graphiql in the request. I am running Graphiql in an iFrame from `localhost:8000/graphql` and I want to be able to do something like `localhost:8000/graphql?headers=serializedheadersstring` and have the header values be populated into the editor for all tabs.
> 
> Is this possible?

No a solution but a work-around. You can run a local proxy that puts the GraphiQL UI and the GraphQL endpoint on the same port then the headers are shared automatically.
