### ISSUE TITLE
Question: Does support for file upload exists?

### ISSUE THREAD

**Issue by petrovic-ivan** [graphql/graphiql#591]
Does exist any support for file upload in the editor? I would like to have a mutation which uploads the file to server and possibility to test from GraphiQL editor. Is it this functionality expected in future?

**Comment by AGS-** [comment]
No, you could probably build something to upload a file based on a base64 encoded string but it's probably not an optimal solution.

**Comment by loganvolkers** [comment]
Here's an interesting proposal: https://github.com/jaydenseric/graphql-multipart-request-spec
