### ISSUE TITLE
Error while running example

### ISSUE THREAD

**Issue by knowbody** [graphql/graphiql#6]
### Issue
- project assumes `babel` and `browserify` are installed globally

I cannot run: `npm install` simply because I don't have `babel` and `browserify` installed globally, and I think this would be most of the cases.

### Possible solution
Quick hack would be to include `graphiql.css` and `graphiql.min.js` in the project, but that would increase the size of it.

Or just change the way the resources are being built.

**Comment by leebyron** [comment]
I'm a bit confused. Could you share the exact steps you followed to get this error? Babel and Browserify are included in the package dependencies, so installing the main project should work.

**Comment by gaearon** [comment]
I think this is the issue:

https://github.com/graphql/graphiql/blob/master/example/build.sh#L4

Shouldn't it be something like

```
./node_modules/.bin/babel server.js --optional runtime -o dist/server.js
```

?

**Comment by knowbody** [comment]
yeah, exactly that, thanks @gaearon 

@leebyron yeah they are being installed but the when the examples try to install the dependencies, they install the local graphiql which has:

```
"prepublish": "npm run build"
```

which is run before the `npm install` is done and it runs the `./resource/build.sh` which uses global `babel`

**Comment by leebyron** [comment]
Have you run "npm install" in the main project directory first?

The build script is not meant to be run directly, but only via npm scripts, which puts node_modules/.bin into $PATH

**Comment by gaearon** [comment]
I just tried running `npm install` in root and then in `example` folder and I don't have any problems.

**Comment by leebyron** [comment]
I'll add that step to the readme in examples

**Comment by knowbody** [comment]
cool, now works :+1:
