### ISSUE TITLE
Support React16

### ISSUE THREAD

**Issue by brucewpaul** [graphql/graphiql#603]
With react currently at -rc.3 and should be actually releasing 16 this week, is it possible to bump these dependencies?

**Comment by AGS-** [comment]
I definitely think it could be possible as soon as the release comes out.

**Comment by brucewpaul** [comment]
just released :)

**Comment by asiandrummer** [comment]
We'd be interested in a contribution for this please!

**Comment by brucewpaul** [comment]
the pr should be all good to go and is ready to be merged/released
