### ISSUE TITLE
Subscription operationName not sent

### ISSUE THREAD

**Issue by codepunkt** [graphql/graphiql#605]
When having multiple named subscriptions and sending one of them, the operationName is not sent with the query string.

![subscription_operationname](https://user-images.githubusercontent.com/603683/30849912-2db7b5bc-a2a4-11e7-92d1-82792220464c.PNG)

The error message is not shown correctly (see #604). Looking at the console, the operationName is not sent via websocket connection:

![namedsubscriptionstart](https://user-images.githubusercontent.com/603683/30850019-72951b0c-a2a4-11e7-84f4-f466f7bebcd5.PNG)

Therefore, the subscription errors with "Must provide operation name if query contains multiple operations."

**Comment by andrew-w-ross** [comment]
Is there any update on this?

**Comment by acao** [comment]
@andrew-w-ross new maintainer team here! thanks for the solid bug report. I will get set up to work on this.

**Comment by benjie** [comment]
@acao Did you have any luck looking at this?

**Comment by acao** [comment]
@benjie i was able to reproduce this i thought? i feel like maybe we fixed it and this was a dupe. let me check

**Comment by acao** [comment]
resolved by #664

**Comment by acao** [comment]
resolved by #664
