### ISSUE TITLE
Typescript declarations

### ISSUE THREAD

**Issue by samrae7** [graphql/graphiql#610]
Would a typescript declarations file be welcome as part of the project? I have looked for one online and so far can't find one. Would it be useful to submit one as a PR?

**Comment by asiandrummer** [comment]
@samrae7 I don't see why not, but what's the purpose? Just wanted to understand more since I'm a complete TypeScript noob :D

**Comment by samrae7** [comment]
@asiandrummer thanks for the reply

On reflection the use case is limited, and even then I think someone could easily add the types themselves. It would be for people who want to add the graphiQL component to existing typescript projects, and then not have to declare eg. the prop type ( eg. fetcher: () => Promise<any>) themselves. However, like I say people could add that quite easily themselves if they really needed to make it part of a ts project.

In any case I realised that for what I wanted it for, I could just have it as a separate js repo that I can fire up when I need it ( rather than adding it to the main app, which is written in ts). I think I will close this issue, as it makes sense why no one else has needed it up until now.

**Comment by AlexCppns** [comment]
+1 for full typescript support.

**Comment by diegoaguilar** [comment]
@samrae7 did you find any solution or tool that worked out for you? I'm actually in the same situation

**Comment by imolorhe** [comment]
@diegoaguilar as of the latest release, all the packages in this repo are now all in typescript and have typescript declarations as well.
