### ISSUE TITLE
GraphiQL.Menu not working

### ISSUE THREAD

**Issue by danez** [graphql/graphiql#614]
When using `GraphiQL.Menu` everything of the menu that is outside the toolbar, like the dropdown will be cut off. 

![bildschirmfoto 2017-10-12 um 14 32 29](https://user-images.githubusercontent.com/231804/31496325-3b707ca2-af5b-11e7-87c7-5c00c604b657.png)

This regressed with #579. If i remove the `overflow-x` it works again.
/cc @asiandrummer

**Comment by pleunv** [comment]
The menu should be fixed now.

**Comment by wincent** [comment]
@pleunv: yep, as of v0.11.8.

Thanks for the report, @danez.
