### ISSUE TITLE
Usage Example invalid: Identifier Expected

### ISSUE THREAD

**Issue by sw-yx** [graphql/graphiql#615]
Hi, in your Readme you have a usage example that doesnt seem valid. in particular this line:

```
 <GraphiQL ref={c => { this.graphiql = c; }} ...this.state>
```
weirdly tries to spread `this.state` into props. i've never seen this pattern before and VSCode is giving me grief:
![image](https://user-images.githubusercontent.com/6764957/31514650-54aeb1ac-af60-11e7-9241-dab8d54e8dac.png)

am i overlooking something dumb here or is there some typo in the readme?

**Comment by sw-yx** [comment]
think the fix is
```
<GraphiQL ref={c => { this.graphiql = c; }} {...this.state}>
```

**Comment by dlredden** [comment]
That fixed the spread operator issue for me too, but I'm getting the following error in regard to the `ref` keyword.

> Unexpected token, expected ,

**Comment by sw-yx** [comment]
do you guys want a PR to fix the readme?

**Comment by dlredden** [comment]
I had already submitted a PR to fix this https://github.com/graphql/graphiql/pull/616

**Comment by wincent** [comment]
#616 is merged, so closing this one.

**Comment by wincent** [comment]
And by #616, I actually mean #618, because I somehow saw that one first.
