### ISSUE TITLE
Dynamically change schema

### ISSUE THREAD

**Issue by syrusakbary** [graphql/graphiql#62]
Right now `<GraphiQL />` doesn't support to change the schema dynamically through props (`schema` or `fetcher`). However QueryEditor seems to support it (https://github.com/graphql/graphiql/blob/master/src/components/QueryEditor.js#L115)

I could work on a PR if that is something you would like to improve :)

**Comment by leebyron** [comment]
Yeah, this seems useful, and probably is a bug. If GraphiQL is provided a new schema, that schema should take effect.

**Comment by syrusakbary** [comment]
Schema could be constructed by the fetcher if is not provided. Even with the fix if we change the fetcher and provide a null schema, it will not reconstruct a new one (as the construction is triggered in `componentDidMount`).
Moving the logic from [componentDidMount](https://github.com/graphql/graphiql/blob/master/src/components/GraphiQL.js#L207) to another method `buildSchema`? (which could be called also in [componentWillReceiveProps](https://github.com/graphql/graphiql/blob/master/src/components/GraphiQL.js#L181)) should solve this too :)

**Comment by leebyron** [comment]
Great point, the fetcher prop could also update. I just added another commit.

**Comment by BransonGitomeh** [comment]
**Dynamically change schema** - i'm thinking that this means that graphiQl is supposed to detect new changes in the server's schema once it changes . i always find myself needing to refresh graphiQl to detect new things or changes. I do it via the normal `f5` browser refresh. how can i have graphiQl detect new changes . is there anything inbuilt, a refresh button maybe?  or how should this be setup?

**Comment by leebyron** [comment]
You'll first need your server to be able to indicate when this has occurred via some subscribe hook. Check out packages like "watchify" to see how this is done in development environments. Then when your client is made aware that the server schema has changed, you'll need to write the code which refetches and produces a new schema instance to provide to <GraphiQL>. Thanks to this task, the graphiql view will automatically update.

**Comment by BransonGitomeh** [comment]
none of this is built in , ill have to write it all myself right?  thanks

**Comment by leebyron** [comment]
Correct.

**Comment by BransonGitomeh** [comment]
OK thanks, ill attempt this and see how it goes
