### ISSUE TITLE
Add the ability to group the mutations

### ISSUE THREAD

**Issue by yordis** [graphql/graphiql#621]
I don't if this should be here or in the actual spec but. Right now practices like put the resource name and then action for example `postCreate` because we want to have some order in the mutations can be resolve with some soft of tag or grouping.

I think it will be good to add that functionality so it's easier to manage the mutations and we do not have to create some weird names because the tooling force us to do for a better experience on it.

**Comment by asiandrummer** [comment]
Hi @yordis - I'm not sure if I understand your proposal, but regardless I don't think `GraphiQL` should be the place to open this issue because I'm guessing you're suggesting for a feature addition in graphql reference implementation. I think opening an issue in [graphql-js](https://github.com/graphql/graphql-js/issues) for feature addition like this would be better.

As such, I'm going to close this issue for now. Feel free to reopen it if you think GraphiQL should handle this - if that's the case I'd love to see some example code + a more detailed use case scenario please.

**Comment by yordis** [comment]
@asiandrummer many people flip the order of the naming for example `createOrder` vs `orderCreate`. If you have multiple actions around the `order` you will normally put `updateOrder`, `createOrder` ... so on. But this will spread the mutation list all over the place in the `Dos` section, instead of put them together for be better organized.

I am not sure how to do some code example because it is more about what GraphiQL does, or rather does not do. I am not quite sure if the introspection is forced by Graphql on what you could put inside. For example add `group:` key to the schema in the introspection.

So I need to do is some way of tagging the mutation so I can group them for example
```elixir
@group :order
mutation :create_order do
....
end

@group :order
mutation :update_order do
...
end
```

so it will be something like

```
{
  __schema {
    group <--- I guess
    queryType {
      name
    }
  }
}
```

Something like that, where you could read from the introspection and be able to group them (probably use the same navigation in the `Docs` section) 

The reason I didn't open it there is because I am not sure if the introspection shape is forced by GraphQL or you could relay on some added feature from it.

**Comment by yordis** [comment]
@asiandrummer could you reopen this please so we have track of the feature request.

Related to https://github.com/facebook/graphql/issues/376
Related to https://github.com/facebook/graphql/issues/300

**Comment by sebastienbarre** [comment]
Was there ever a resolution to this? I can't be the only one with an absolutely unruly list of queries and mutations, almost 1800 lines long. My "Execute Query" button requires scrolling several screens down to reach the last one. Are you guys using a different set of tooling to solve this? From a UI perspective, allowing the "Execute Query" to have sub-menus for "groups" would be logical step. Thank you.
