### ISSUE TITLE
Bundle size?

### ISSUE THREAD

**Issue by sw-yx** [graphql/graphiql#622]
Hey this is just a quick question for somebody knowledgeable about the ecosystem... when I put graphiql in my app it balloons bundle size by about 2mb. Culprits are: codemirror + graphql-language-service-interface+graphql-language-service-utils + graphiql +graphql and I'm not sure I need -ALL- that in my frontend? Just looking for tips on how to cut the bundle. thank you! 
![image](https://user-images.githubusercontent.com/6764957/31592173-5694f44a-b1f4-11e7-921d-c3355e9c70be.png)

**Comment by asiandrummer** [comment]
@sw-yx Hi there!

A short answer is yup, you'd need all those things. Just to give a short rundown:
- `graphql-js`: The ref implementation of GraphQL - this powers every GraphQL-related needs.
- `graphql-language-service-*`: The core of the GraphQL online syntax parser/validator
- `codemirror` and `codemirror-graphql`: A series of wrappers around `graphql-language-service` in CodeMirror editor. This provides the CodeMirror mode/hint/lint functions for query/variables editor, and other cool stuffs such as onHover tooltip implementations

I did a simple `du -hs` for the libraries listed above, and `codemirror` wins with being 3.2mb of the size. Now I understand this may not be the exact size of how much CodeMirror's size is as `graphiql.min.js` may have a different proportions between libraries bundled in - my point is I think GraphiQL is as compact as it could be for now.

**Comment by wincent** [comment]
@sw-yx: It's definitely big, and something that you probably want to use webpack bundle splitting to ensure that it doesn't get baked into the bundle for the rest of your app.

**Comment by sw-yx** [comment]
very cool guys, thank you so much! loving it (of course) and will look to see where I can contribute.

**Comment by acao** [comment]
bundle size has dropped precipitously, with plans afoot to optimize even further, hold my kombucha:
https://github.com/graphql/graphiql/pull/1001
![image](https://user-images.githubusercontent.com/1368727/69927889-bea75800-1487-11ea-9af6-312464ca7479.png)
![image](https://user-images.githubusercontent.com/1368727/69927895-c7982980-1487-11ea-99b4-90e751615f04.png)
