### ISSUE TITLE
updated marked to new 8fold-marked 0.3.8 to prevent nsp failure

### ISSUE THREAD

**Issue by gabriel-hernandez-ck** [graphql/graphiql#628]
https://github.com/chjj/marked/issues/937

**Comment by wincent** [comment]
See previous discussion about switching away from Marked in #581.

FWIW, at this point we probably have enough to warrant switching to the better-maintained library. (In that PR the main concern is we didn't have any concrete examples of bugs that would be ameliorated by switching, but right here we have one.)

**Comment by asiandrummer** [comment]
Closing this since we've switched to markdown-it.

**Comment by asiandrummer** [comment]
Oops, actually, we haven't switched yet - I'll reopen #581 in favor of closing this one.
