### ISSUE TITLE
example fails to run

### ISSUE THREAD

**Issue by gre** [graphql/graphiql#63]
I'm using node v5.1.0 and npm 3.3.12 which is probably the cause of this.

after having properly `npm install` (in example/),
when running `npm start`, the build.sh will fail:

```
 @ prestart /Users/gre/perso/graphiql/example
> npm run build


> @ build /Users/gre/perso/graphiql/example
> . build.sh

cp: node_modules/graphiql/graphiql.js: No such file or directory
```

**Comment by gre** [comment]
```
$ ls node_modules/graphiql
LICENSE      README.md    package.json
```

and actually I think the prepublish don't work in graphiql.

If I run `npm run prepublish` myself (in root project), I'm falling into https://github.com/graphql/graphiql/blob/master/resources/prepublish.sh#L5, is this normal?

**Comment by leebyron** [comment]
Thanks for the report, sorry for the confusion. I had forgotten to update the example's readme after changing our build process.
