### ISSUE TITLE
Using with multiple servers

### ISSUE THREAD

**Issue by axos88** [graphql/graphiql#641]
Please add an option to be able to make requests against multiple GraphQL servers, and the possibility to choose using a dropdown list from a predefined list of servers (or even just an edit box with the url would help a lot)

**Comment by pingvinen** [comment]
I actually have this exact need right now.

We have a bunch of internal services that are all GraphQL based, but do not provide Graphiql themselves, so having a single page you could access to dig around in the various services would be very nice.

**Comment by axos88** [comment]
@pingvinen 
I recently found this: https://github.com/graphcool/graphql-playground
Look interesting, might be worth checking out, although I did not have a chance to do so yet.

**Comment by pingvinen** [comment]
@axos88 Just tried the linux desktop version - it is actually pretty nice for local development :)

**Comment by imolorhe** [comment]
@pingvinen @axos88 You can also try https://github.com/imolorhe/altair

**Comment by acao** [comment]
this is possible in your react app that wraps graphiql already, i’ve seen this done a few ways. we may introduce built in multi-schema support in the future
