### ISSUE TITLE
Multiple requests

### ISSUE THREAD

**Issue by VinayakBagaria** [graphql/graphiql#646]
Its tedious to write queries/ mutations from scratch everytime the developer opens GraphiQL interface. Can there be some way how we can keep previous requests in history in the editor and only execute what part we want?

**Comment by kevinsimper** [comment]
I have the exact same problem and it would be great if you could do like other mysql clients where you can select something and then only that is executed 😄

**Comment by imolorhe** [comment]
GraphiQL supports history feature now, where you can see your previously written queries. I assume that solves your issue. Or if you're referring to the ability to have multiple requests at the same time (like tabs for different requests), then maybe you should consider other tools like [Altair](https://altair.sirmuel.design/) or GraphQL Playground.
