### ISSUE TITLE
CodeMirror-hint-information missing flex-direction: column;

### ISSUE THREAD

**Issue by brubbel** [graphql/graphiql#647]
It seems that for multi-paragraph descriptions, the CodeMirror autocomplete hints are rendered in the row direction by default, at least on Chrome + graphiql 0.11.11:
![image](https://user-images.githubusercontent.com/5667690/34793484-c4822284-f64b-11e7-860d-4db8d1737652.png)
After adding `flex-direction: column;` to [.CodeMirror-hint-information .content](https://github.com/graphql/graphiql/blob/5ceca93f59f76a2947fd477ec9d19ef5cd18ace5/css/app.css#L428), things are fine again:
![image](https://user-images.githubusercontent.com/5667690/34793559-1a75d15e-f64c-11e7-9ce9-2c54cfd2cedf.png)

**Comment by thomasheyenbrock** [comment]
The hint tooltips have been reworked in `graphiql@2` and `codemirror-graphql@2` and the field description is now shown to the right of the field, so this should no longer be an issue.
