### ISSUE TITLE
Remove duplicate entries automatically

### ISSUE THREAD

**Issue by deadcoder0904** [graphql/graphiql#653]
# Before Pressing ▶️

```graphql
{
	id
	type
	name
	type
}
```

# After Pressing ▶️

```graphql
{
	id
	type
	name
}
```

Sometimes by accident I enter duplicate fields so it would be good if it gets removed automatically from the input bcz anyways I get the output without Duplicate fields. I do think this might be useful. But if you think its not, you can close it 😉

**Comment by kevinsimper** [comment]
It could be part of `prettify` perhaps?

**Comment by deadcoder0904** [comment]
Yep anything will do

**Comment by thomasheyenbrock** [comment]
Having duplicate in GraphQL queries is valid according to the spec, and GraphiQL as reference implementation is not opinionated if this is desirable or not. So the built-in behavior will always be to leave the query as-is and not remove duplicate fields, also when prettifying.

However, if you want to have this behavior, then you can extend the toolbar using the `toolbar` prop of the `GraphiQL` component. You can pass a React component there, which will be rendered inside the toolbar. This component can implement the custom behavior of removing duplicate fields from the query by altering the state part of the `EditorContext` (you can use the `useEditorContext` hook from `@graphiql/react` to consume that contexts value).
