### ISSUE TITLE
Plugin: set Prettier `print-width` to editor width

### ISSUE THREAD

**Issue by vjpr** [graphql/graphiql#658]
Because graphiql has 3 panes, the editor can be rather narrow.

Prettier should use [`print-width`](https://prettier.io/docs/en/options.html#print-width) of the visible editor.

**Comment by acao** [comment]
unfortunately we aren't using prettier under the hood yet, but we hope to for v1.
however we choose to solve this isue, i agree

**Comment by benjie** [comment]
I don't think this should be the default behaviour; I think it should wrap to the default of either 80 or 120 columns. A plugin could be used to customise this.

In the mean time, here's how we replaced the default graphql.js `print` function with `prettier` in PostGraphile: https://github.com/graphile/postgraphile/blob/bfad92fc3a71c3c390ee8705931ccec5b4ec0c1b/postgraphiql/src/components/PostGraphiQL.js#L498-L511

**Comment by acao** [comment]
i’m tempted to introduce prettier. it was only about 4kb in the bundle for the monaco prototype this weekend. you just have to import prettier/core and prettier/graphql-parser directly like in the docs for browser usage

**Comment by benjie** [comment]
Sounds good to me; `prettier` formats the AST much nicer than `print` does. (This particular issue should still be a plugin though; prettier should default to 80 columns as standard since that's what people will want to copy/paste into their code independent of the pane width within GraphiQL.)

**Comment by acao** [comment]
consolidating to this disucssion: #1517, and there's an RFC branch too!
