### ISSUE TITLE
ReferenceError: b is not defined

### ISSUE THREAD

**Issue by marcgreenstock** [graphql/graphiql#665]
Apologies if this is out of scope, but I have a bug in webpack 4 with `--mode production`.

It appears it is a result of the `optimization.minimize` config, turning minimize off fails to reproduce the issue. I couldn't identify which uglify option specifically causes it though.

```JSON
"dependencies": {
  "graphiql": "^0.11.11",
  "graphql": "^0.11.7",
  "codemirror": "^5.36.0",
  "codemirror-graphql": "^0.6.12",
  "react": "^16.2.0",
  "react-dom": "^16.2.0"
}
```

<img width="491" alt="screen shot 2018-03-27 at 14 49 06" src="https://user-images.githubusercontent.com/287739/37968311-119bf546-31ce-11e8-82c4-eee0cf4d0442.png">

**Comment by jimmybrawn** [comment]
any updates on this?

**Comment by marcgreenstock** [comment]
@jimmybrawn are you seeing this too?

**Comment by jimmybrawn** [comment]
Yes and it drives me crazy.. Its only in production.

**Comment by marcgreenstock** [comment]
@jimmybrawn I haven't resolved it, the best I could do was disabling `optimization.minimize` entirely. I've moved on from this for now. I will revisit this again once  #663 is resolved since my codebase depends on graphqljs v0.13 now.

**Comment by whtsky** [comment]
running into the same problem with graphqljs 0.13 & graphiql 0.11.11

**Comment by whtsky** [comment]
https://github.com/mishoo/UglifyJS2/issues/3010#issuecomment-373957512
https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/265

**Comment by jimmybrawn** [comment]
@whtsky so is it now fixed with uglify-es then?

**Comment by whtsky** [comment]
@jimmybrawn nope. uglify-es will not be maintained so I forked uglifyjs-webpack-plugin to make it use uglify-js ( which does not support ES6 by the way): https://github.com/whtsky/uglifyjs-3-webpack-plugin

**Comment by jimmybrawn** [comment]
So we've fixed it by doing the following in webpack 4:
```
 minimizer: [
      new UglifyJsPlugin({
        cache: true,
        parallel: true,
        uglifyOptions: {
          compress: false,
          ecma: 6,
          mangle: true
        }
      })
    ]
```
this seems to work on production

**Comment by sekharp** [comment]
Instead of doing cache: false in your webpack minimizer options, we took the approach of just excluding graphiql from minimization with this option in the minimizer UglifyJsPlugin object argument options, like so: `exclude: [/graphiql/]`. This fixed this for production for us.

**Comment by acao** [comment]
@sekharp the current webpack 4 example we have, which uses webpack's new alternative to uglify (the name escapes me) is out and working with 0.17.0, please give that a try with webpack 4 if you can? or maybe it will work with uglifyjs plugin again too?
