### ISSUE TITLE
Unknown cause: Broken GraphiQL UI

### ISSUE THREAD

**Issue by westbranch** [graphql/graphiql#666]
At some point, I faced the issue when the UI becomes kind of flat and all the buttons stop responding (see the screenshots). Therefore I can't work with that anymore, because It's now imposible to add any headers, or browse through my saved queries or recent URLs. 
What could be the possible cause?
![image](https://user-images.githubusercontent.com/7197444/37974926-26d62154-31ef-11e8-9412-3468af03f8a1.png)
Clicking the buttons and dropdowns does nothing

**Comment by IvanGoncharov** [comment]
@westbranch From your screenshot, I saw that you are using graphlql-toolbox.
This particular repo doesn't have any UI components so I think you should report this issue to either graphlql-toolbox or GraphiQL repo.

**Comment by IvanGoncharov** [comment]
@westbranch I checked graphql-toolbox and it's using GraphiQL `0.11.5` but latest version is `0.11.11`.
https://github.com/OlegIlyenko/graphql-toolbox/blob/master/package.json#L11
So updating it to the last version could help.

**Comment by acao** [comment]
@westbranch can we close this issue?

**Comment by westbranch** [comment]
@acao Sure! I'm sorry, forgot it's still open. It's not relevant anymore since I started using side client that supports graphql
