### ISSUE TITLE
Incremental Introspection Queries

### ISSUE THREAD

**Issue by tvvignesh** [graphql/graphiql#668]
I noticed that you guys are getting the entire schema through an introspection query as a JSON. 

Is there anyway to make graphiql to incrementally get schema through introspection queries as and when user clicks on the right side docs explorer if the schema (JSON) itself is too large to load at once?

**Comment by imolorhe** [comment]
The schema from the introspection query is not just for loading the data in the docs. It's also used for other things in the editor like autocompleting fields and arguments, and also for identifying errors in the query. These are quite important for the editor to give a good developer experience.

**Comment by tvvignesh** [comment]
@imolorhe Hmm.. I see. Any way you think we can make this incremental rather than getting the schema all at once? I understand that this may affect suggestions. Maybe, suggestions can also come from a server side component rather than the client having to preload a JSON and give suggestions based on it. Rather, we can hit an endpoint and get the suggestions as and when user types, something like typeahead.

I understand this will cause a major rewrite if needed, but this is a question which people are asking me since the business schema is too large and graphiql will load them all at once.

**Comment by imolorhe** [comment]
Schema generation via introspection should ideally only be used in development and not in production, so in a way it's expected for the entire schema to be downloaded when it's requested (similar to how a source map would be fully downloaded when a developer opens the dev tools in the browser). The editor should still be active without even before the schema is downloaded, just without the intelligence.

This, however, would be a higher level discussion and I'm not sure how best your specific scenario would be solved. Maybe others could help.

**Comment by acao** [comment]
excellent discussion here!
@imolorhe is right, we do kind of need the entire introspection schema to operate currently, though there might be other inroads to this.
the solution you propose @tvvignesh is an interesting idea, however this would break the entirely clientside pattern of GraphiQL and codemirror-graphiql, unfortunately.
a potential alternative architecture to ours that would work - an electron (or other node desktop runtime) using monaco editor that interacts directly with the LSP server (`graphql-language-service-server`) over `json-rpc`, similarly to how vscode editor plugins work.

**Comment by acao** [comment]
here's an issue that has some solutions:
https://github.com/graphql/graphiql/issues/595
