### ISSUE TITLE
Unable to getting started

### ISSUE THREAD

**Issue by ghost** [graphql/graphiql#672]
I get some errors when I follow the instructions to get GraphiQL running.

```
$ npm install --save graphiql
npm WARN saveError ENOENT: no such file or directory, open '/private/tmp/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/private/tmp/package.json'
npm WARN graphiql@0.11.11 requires a peer of prop-types@>=15.5.0 but none was installed.
npm WARN graphiql@0.11.11 requires a peer of react@^15.6.0 || ^16.0.0 but none was installed.
npm WARN graphiql@0.11.11 requires a peer of react-dom@^15.6.0 || ^16.0.0 but none was installed.
npm WARN codemirror-graphql@0.6.12 requires a peer of graphql@^0.10.0 || ^0.11.0 but none was installed.
npm WARN graphql-language-service-types@0.1.14 requires a peer of graphql@^0.10.0 || ^0.11.0 but none was installed.
npm WARN tmp No description
npm WARN tmp No repository field.
npm WARN tmp No README data
npm WARN tmp No license field.

+ graphiql@0.11.11
added 41 packages in 3.812s
```

The command `npm install --save graphiql` results in a lot of errors of uninstalled requirements. What command needs to be executed to run GraphiQL to test a local(!) GraphQL service. And how does GraphiQL know where that service is? Where can I put the address of the GraphQL service?

The `README` doesn't cover that kind of first steps with GraphiQL.

Hints:
- GraphiQL is described as a GraphQL IDE. So my expectation is that I can download or just use it somehow, put a URL into it and send GraphQL requests to some/my GraphQL service. The longer I look at GraphiQL, it starts to look like a framework to build my own IDE. If that is the case, it would be a big difference.
- I am not a Node expert. That means, I don't know what I have to do with the code fragment that is shown in the `README` just after a few lines of text. If using GraphiQL implies that I have to deal with Node.js first, please point that out (as some kine of requirement) in your documentation.

So, this issue is more about to be able to understand what GraphiQL is, what it isn't and how to use it out of the box (if that is intended). And if this results in enhancing the `README`, it would be a profit for us all.

**Comment by acao** [comment]
@ghost your best bet is to check out the [GraphiQL Swapi Example](https://github.com/graphql/swapi-graphql/blob/master/public/index.html) index.html. You can update the CDN sources to 0.13.0, and you should be good to go!
