### ISSUE TITLE
[Feature] generate fragments in a name pattern!

### ISSUE THREAD

**Issue by xialvjun** [graphql/graphiql#673]
Let's say we have such a schema:

```graphql
scalar Date
scalar JSON

type Person {
  id: ID!
  name: String!
  age: Int
  books: [Book!]!
}

type Book {
  id: ID!
  title: String!
  content: String!
  owner: Person!
}
```

Then we can have fragments:

```graphql
fragment person_f on Person {
  id name age
}
fragment person_f1 on Person {
  id name age
  book { id title content }
}
# OR
fragment person_f__books_f on Person {
  id name age
  book { id title content }
}

fragment person_f__books_f1 on Person {
  id name age
  book {
    id title content
    owner { id name age }
  }
}
# OR JUST
fragment person_f2 on Person {
  id name age
  book {
    id title content
    owner { id name age }
  }
}
```

## So, what's my pattern?

1. `person_f` get all scalar fields on `Person`;
2. `person_f1` get all scalar fields and other types with just one depth level scalar fields;
3. `person_f2`, you must have known it;
4. `person_f__books_f` get all scalar fields on `Person` and all scalar fields on field `books` of type `Book`;
5. `person_f__books_f1`, yes, you guess it right;

## Is my fragments name pattern the best?
I don't know, maybe there are many other patterns better than this.

But my purpose is just hoping `graphiql` offer a way to generate `fragments` based on some name pattern.

## Why generate fragments?
In fact, `generating fragments` is not good in programing. But sometimes, like in `rapid developing, make a prototype/mvp`, a tool which can generate fragments is helpful.

**Comment by thomasheyenbrock** [comment]
Hey @xialvjun 👋 GraphiQL is the reference implementation that follows only the GraphQL spec. As there is no "officially" recommended pattern for fragment names in the spec, GraphiQL will also be non-opinionated about this, and any fragment naming pattern won't be built-in to GraphiQL.

There's a couple things you could do however:
- You can pass additional validation rules (using the `validationRules` prop of the `GraphiQL` component) where you could assert that your fragment names follow a certain pattern. Such validation errors would then show up in the query editor.
- You write your own plugin and pass it to the `GraphiQL` component using the `plugins` prop. A plugin is in essence just a React component in which you can render arbitrary content and modify the GraphiQL state as you like. You could build a plugin that generates fragment with names following your pattern.
