### ISSUE TITLE
[Feature] Map name to description for more informative queries

### ISSUE THREAD

**Issue by OmriKaduri** [graphql/graphiql#674]
Hello

I'm using `graphiql` for some time and I have a use case at my application where I want to let my user build his own query. Fortunately, my user is familiar with query languages, so I'm planning on giving him the `graphiql` editor (I don't have the time for creating him a good enough DSL). 

Yet, I thought of how nicer and friendlier for him could it be if `graphiql` would just map between the field `name` and `description`.

For example, for schema which contains those fields:
```graphql
type User {
   # identity number
   id: ID!
   # email address
   email: String!
  }
```
 Instead of asking him writing a query like (which is very readable to programmers) :
```graphql
user(id:1){
   email
}
``` 
If `graphiql` would map between name and description fields, he would write a query like:
```graphql
user(identity number:1){
   email address
}
```

And when `graphiql` will go on to build the query, it will map backwards the `description` to `name`.
That way, I can create a so-called DSL (even not in English at all) very fast.

Would like to hear your opinions before I start work on it. If sounds good I'll try make a PR.

Thanks!

**Comment by acao** [comment]
hey there @OmriKaduri ! good question. theres another way to do this actually!

https://graphql.org/learn/queries/#variables
this you should find very helpful: https://graphql.org/learn/queries/#variables
