### ISSUE TITLE
Make it work offline

### ISSUE THREAD

**Issue by jedwards1211** [graphql/graphiql#676]
Title says it all.  Maybe it's easier to drop Graph*i*QL into an app when it fetches all of its code and styles from the internet, but remember, some devs occasionally would like to get work done without an internet connection.

**Comment by imolorhe** [comment]
@jedwards1211 There are several solutions for working with GraphQL offline. There's the GraphiQL mac app, there's chromeiQL, there's also [altair](https://altair.sirmuel.design/).

**Comment by caugner** [comment]
Looks like these lines are the reason it doesn't work offline out of the box:
https://github.com/graphql/graphiql/blob/297edd99b66af9b9e78c2fbf10bb5afd5ea8b386/example/index.html#L30-L33

**Comment by caugner** [comment]
@imolorhe Getting rid of these online dependencies, would not only enable GraphiQL to work offline, but also increase privacy and security.

**Comment by styk-tv** [comment]
![screen shot 2018-08-30 at 12 33 20](https://user-images.githubusercontent.com/838921/44849096-e8544c80-ac50-11e8-86af-7bdcf7d04054.png)

https://insomnia.rest/

**Comment by AGS-** [comment]
@caugner yeah, I agree. @asiandrummer, do you remember if there's some historical reason as to why we don't just bundle these?

**Comment by IvanGoncharov** [comment]
@AGS- It would be great to provide bundled build 👍 
But many libraries/apps wrap graphiql in their own React components or provide their own polyfills so I would argue that it should be a separate file inside NPM package something like `*.bundle.min.js`.

**Comment by acao** [comment]
I was thinking for 0.14 of distributing a `graphiql.bundled.min.js` alongside the standard `graphiql.min.js`. also we may be moving to rollup FWIW

**Comment by deadcoder0904** [comment]
Would love to see this bundled. Yesterday, it stopped working when my net went off.

**Comment by acao** [comment]
see the webpack or CRA example of how to build your own custom offline bundle!

**Comment by deadcoder0904** [comment]
@acao It's bundled in Prisma's Nexus so not sure how I can do that?

**Comment by acao** [comment]
@deadcoder0904 then prisma needs to make it available offline! maybe open an issue in their repository?

**Comment by acao** [comment]
our https://github.com/graphql/express-graphql/ bundles projects offline
