### ISSUE TITLE
0.11.11 - not working after upgrade from 0.11.2

### ISSUE THREAD

**Issue by hlship** [graphql/graphiql#682]
When I click the QueryRoot link, I see an exception in the JS console.  I've reloaded, flushed logs, etc.

I've run the introspection query inside GraphiQL and it works, returning 200 respond with correct data, no errors.

![image](https://user-images.githubusercontent.com/52660/40868338-c4869960-65c0-11e8-8821-bfffdac704b8.png)

**Comment by hlship** [comment]
The screenshot shows an abbreviated query, but I've used the full introspection query without problems.

WebSocket support is NOT enabled in my server; not shure why it is trying to connect WS when there's no subscriptions in my schema.

**Comment by hlship** [comment]
Just did a quick test, reverting my client build to be 0.11.2 and it works perfectly, so something about the upgrade to 0.11.11 broke things.

**Comment by hlship** [comment]
I still seen JS console errors r.e. WebSockets even with 0.11.2.

**Comment by AGS-** [comment]
Closing this issue since we have upgraded the version.
