### ISSUE TITLE
GraphiQL Edit HTTP Headers Bug

### ISSUE THREAD

**Issue by Powers-RC** [graphql/graphiql#684]
I am really new to graphql and graphiql but I ran into a large bug that really hindered any use of the UI. I entering the headers into the form prompted by Edit HTTP Headers button and did so with quotes around my text. After doing this I can no longer prompt the form to generate or open or close a new queries. I have tried reloading graphiql, closing the application and restarting the computer and nothing resets the state. Is it stored in a file or the browser? Any tips for resetting the state? When I click the play button the error below is returned. 

<img width="872" alt="screen shot 2018-06-07 at 8 41 12 pm" src="https://user-images.githubusercontent.com/18079341/41136390-4c50530a-6a93-11e8-8962-8e303020190a.png">

**Comment by jakesorce** [comment]
@Powers-RC: If you get into developer tools with option + cmd + i and then type localStorage.clear() and restart the app that will fix the problem for you!

**Comment by Powers-RC** [comment]
I just went to the application -> Clear Storage. Thanks

**Comment by liesislukas** [comment]
While clearing local storage helps, the bug is still there. I just saved incorrect header and was not able to edit the headers. Button didn't work.

Had to dig localstorage, find the json there, edit, save. I wanted to keep my history & other headers :/

**Comment by GUNT001-SME** [comment]
I am able to see "EDIT  http headers, but unable to open it by clicking , its not responding. any help on this.
![image](https://user-images.githubusercontent.com/83650614/126190649-d2655674-5dd8-4749-9704-87c5e392afed.png)

**Comment by harshithpabbati** [comment]
> I am able to see "EDIT http headers, but unable to open it by clicking , its not responding. any help on this.
> ![image](https://user-images.githubusercontent.com/83650614/126190649-d2655674-5dd8-4749-9704-87c5e392afed.png)

@GUNT001-SME I don't think you are using the official version of GraphiQL? which GraphiQL editor is it?

**Comment by PritiGangrade** [comment]
> > I am able to see "EDIT http headers, but unable to open it by clicking , its not responding. any help on this.
> > ![image](https://user-images.githubusercontent.com/83650614/126190649-d2655674-5dd8-4749-9704-87c5e392afed.png)
> 
> @GUNT001-SME I don't think you are using the official version of GraphiQL? which GraphiQL editor is it?

I am running into the same problem. I installed GraphiQL from homebrew, even tried removing and re-installing and I keep running into the same issue.
