### ISSUE TITLE
Custom Keybindings

### ISSUE THREAD

**Issue by mrsimonfletcher** [graphql/graphiql#687]
## What

I would love to be able to create my own custom keybindings. Ideally it would work in a similar way to the was that [VSCode handles it](https://code.visualstudio.com/docs/getstarted/keybindings) albeit the implementation details may need to be different.

## Why

I use vim keybindings `hjkl` a lot to move around certain areas of applications I am viewing. It would be nice if I could set up a way to move from say the query view to the query variables view and back again without having to leave the keyboard.

Maybe these don't need to be custom and we just add to the existing keyboard shortcuts. Maybe this already exists? And pertains to the discussion on https://github.com/graphql/graphiql/issues/670

**Comment by thomasheyenbrock** [comment]
Support for custom keymaps have been added in #2501 and is available starting from `graphiql@1.9.9`
