### ISSUE TITLE
Not working on ie11

### ISSUE THREAD

**Issue by psyCodelist** [graphql/graphiql#688]
Hi,

Thank you in advance. Just wanted to let you know the the web interface not working on ie11. 

looks like we need add Array.from polyfill: err:  Object doesn't support property or method 'from'

Thanks again,

**Comment by kumarharsh** [comment]
The best way to fix this is to use babel-polyfill in your code or bundle the Array.frmo polyfill with your codebase.

**Comment by psyCodelist** [comment]
Thanks for the note, but graphiql UI code has nothing to do with our UI code base. We use poly-fill but again 2 different codebase.

**Comment by kumarharsh** [comment]
You would be bundling the graphiql lib somehow. Just load the array polyfill too.

**Comment by mzins** [comment]
The same is true for MS Edge

**Comment by kumarharsh** [comment]
Edge has support for Array.from: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from

**Comment by shablenko-sednor** [comment]
I have this error in Edge

SCRIPT1028: Expected identifier, string or number

which is caused by line 226

![image](https://user-images.githubusercontent.com/37369710/66667490-cbfc4f00-ec5b-11e9-8dfc-fa96ef4b9b28.png)

**Comment by acao** [comment]
@shablenko-sednor are you bundling the node module yourself or using one of the pre made CDN bundles? is this with GraphiQL?

**Comment by acao** [comment]
our npm main modules have changed targets, with typescript libraries targeting es2018 for native async await, etc. so if you are using those this is expected without bundling. but if you’re using the CDN bundles, graphiql.js or graphiql.min.js then this would be a bug.

**Comment by VassilIordanov** [comment]
While using `graphql-language-service-interface` `2.3.0` from npm, I see the following code using a default function parameter. 

```
Original Position: 
    webpack:///node_modules/graphql-language-service-interface/dist/getDiagnostics.js, Line 35:37

Code Section: 
30 |         ];
31 |     }
32 |     return validateQuery(ast, schema, customRules, isRelayCompatMode);
33 | }
34 | exports.getDiagnostics = getDiagnostics;
35>| function validateQuery(ast, schema = null, customRules, isRelayCompatMode) {
                                          ^
36 |     if (!schema) {
37 |         return [];
38 |     }
39 |     const validationErrorAnnotations = mapCat(graphql_language_service_utils_1.validateWithCustomRules(schema, ast, customRules, isRelayCompatMode), error => annotations(error, exports.SEVERITY.ERROR, 'Validation'));
40 |     const deprecationWarningAnnotations = !graphql_1.findDeprecatedUsages
```
I was expecting the target to be `es5` at most, but default function parameters are an `es2015` feature. Is that the intended behavior?

**Comment by acao** [comment]
yes, please read my comment above

**Comment by acao** [comment]
these libraries are isomorphic, so we are exporting them in the most performant and progressive ways possible. adding a module key next go around. downstream bundler config will need to account for this. use @babel/preset-env with your webpack config to set browserslist targets, i can show you how. Targeting es5 would lead to too many sup-optimizations for modern browsers or the node runtime, for the language server

**Comment by acao** [comment]
@VassilIordanov if you need more support with this issue, come to our [GraphiQL support channel on Discord](https://discord.gg/APVs69)

**Comment by linkan111** [comment]
@acao I use Angular 8 and upgraded from graphiql 0.12.0 to 0.17.15 and i get the error SCRIPT1028: Expected identifier, string or number in Edge. The problem is with state.prevState = { ...state }; here :
 `function pushRule(rules, state, ruleKind) {
    if (!rules[ruleKind]) {
        throw new TypeError('Unknown rule: ' + ruleKind);
    }
    state.prevState = { ...state };
    state.kind = ruleKind;
    state.name = null;
    state.type = null;
    state.rule = rules[ruleKind];
    state.step = 0;
    state.needsSeperator = false;
}`

How can i fix this in Angular 8?

**Comment by acao** [comment]
you'll need to transpile those modules to the desired browser target. we ship progressively and then you can customize using your bundler

**Comment by acao** [comment]
oh hmm, this is usually available in webpack/rollup etc but not in angular CLI i guess:
https://github.com/angular/angular-cli/issues/11892

**Comment by linkan111** [comment]
Is this something you could fix, so that Angular CLI users also can use this library?

**Comment by acao** [comment]
I think I will backport a fix for one of our last 0.17.x releases, and just target es5. Is angular CLI consuming the es6 (module) or commonjs (main) modules?  Do the errors show with .esm.js files or just .js files?

**Comment by linkan111** [comment]
Ok, thank you that would be great. Angular cli supports es6 modules. The error I got was only showing in the bundled main.js fils or the vendor.js file. I managed to do a workaround and make it work. If someone else is having this issue maybe this can help.

I added these three lines in angular.json under scripts:
`            "scripts": [
              "node_modules/react/umd/react.production.min.js",
              "node_modules/react-dom/umd/react-dom.production.min.js",
              "node_modules/graphiql/graphiql.min.js"
            ]`

and then in my component instead of importing graphiql I did this:
`declare var GraphiQL: any;
export class GraphQLComponent implements AfterViewInit{
.....

      ReactDOM.render(
        React.createElement(GraphiQL, {
          fetcher: this.graphQLFetcher
        }),
        this.getRootDomNode()
      );
`

**Comment by acao** [comment]
https://github.com/graphql/graphiql#browserslistrc our UMD bundle no longer supports IE. let us know if this is an issue, and we can consider a legacy build.

if you need IE11 support, there are ways to configure webpack or other bundlers to achieve this
