### ISSUE TITLE
Styles not loaded correctly when using lazy load(loadable) with react-router

### ISSUE THREAD

**Issue by fa93hws** [graphql/graphiql#693]
Hi
I tried a minimal example 
```
import axios from 'axios';
import GraphiQL from 'graphiql';
import * as React from 'react';

import { axiosConfig } from '../../app-setting';
import { bindthis } from '../../decorator';

import 'graphiql/graphiql.css'
import './style.css'

export default class GraphQLDebugger extends React.Component {
  public render() {
    return (
      <main className='graphql__wrapper'>
        <GraphiQL
          fetcher={ this.graphQLFetcher }
        />
      </main>
    )
  }

  @bindthis
  private graphQLFetcher(graphQLParams: any) {
    return axios({
      data: graphQLParams,
      method: 'POST',
      url: axiosConfig.baseURL + 'graphql',
    }).then(resp => resp.data);
  }
}

```
and I would like to enable lazy load so I did
```
const GraphiQl = Loadable({
  loader: () => import('./pages/graphql-playground'),
  loading: () => null,
})

export default class App extends React.Component {
  public render() {
    return (
      <GraphiQl />
    )
}
```
However, I can only see a grey screen after built (It works fine in development environments)
![Grey screen](https://s3-ap-southeast-2.amazonaws.com/large-timber-blog/1/QQ%E5%9B%BE%E7%89%8720180707185005.png "Logo Title Text 1")

However, everything works fine if I commented the lazy load and import it usually.

Could anyone help me to find the reason why it happens?
Thanks

**Comment by JohannesMerz** [comment]
any update on this? am running into the same problem

**Comment by fa93hws** [comment]
> any update on this? am running into the same problem

I managed to solve this problem with out of box solution.
Instead of building graphiql into the bundle, you can actually download the pre-built version of the HTML, JS and CSS and deploy them separately.

**Comment by JohannesMerz** [comment]
mh, that does not work in my case. What i came up with as a workaround is to include the css in the main bundle and only lazy load the rest. Ups the bundle size a bit, but the css file is not too big

**Comment by thomasheyenbrock** [comment]
With the latest versions of GraphiQL and React Router, this problem seems to no longer exist. I created a sandbox that demonstrates this: https://codesandbox.io/s/gallant-star-dfnfup?file=/src/App.tsx

I also deployed the sandbox here to check that it also works in a prod environment: https://csb-dfnfup-68u4ssh5e-thomasheyenbrock.vercel.app

**Comment by simPod** [comment]
@thomasheyenbrock 

v2.0.6:

> [postcss-is-pseudo-class: Complex selectors in ':is(.CodeMirror-info .info-deprecation)>*' can not be transformed to an equivalent selector without ':is()'.

> [postcss-is-pseudo-class: Complex selectors in ':is(.graphiql-markdown-deprecation,.CodeMirror-hint-information-deprecation-reason,.CodeMirror-info .info-deprecation) code,:is(.graphiql-markdown-deprecation,.CodeMirror-hint-information-deprecation-reason,.CodeMirror-info .info-deprecation) pre' can not be transformed to an equivalent selector without ':is()'.

> postcss-is-pseudo-class: Complex selectors in ':is(.CodeMirror-info .info-deprecation) pre' can not be transformed to an equivalent selector without ':is()'.

> postcss-is-pseudo-class: Complex selectors in ':is(.CodeMirror-info .info-deprecation) code' can not be transformed to an equivalent selector without ':is()'.](postcss-is-pseudo-class: Complex selectors in ':is(.CodeMirror-info .info-deprecation)>*' can not be transformed to an equivalent selector without ':is()'.)](postcss-is-pseudo-class: Complex selectors in ':is(.graphiql-markdown-deprecation,.CodeMirror-hint-information-deprecation-reason,.CodeMirror-info .info-deprecation) code,:is(.graphiql-markdown-deprecation,.CodeMirror-hint-information-deprecation-reason,.CodeMirror-info .info-deprecation) pre' can not be transformed to an equivalent selector without ':is()'.)

and many others, can you revalidate?
