### ISSUE TITLE
Direct link to query

### ISSUE THREAD

**Issue by jtomson-mdsol** [graphql/graphiql#7]
First off this is very cool! It'd be great to be able to share a link to a particular query, is this in the works?

**Comment by leebyron** [comment]
Yes, this is definitely something we want to have! Thanks for the reminder - I'll keep the task open to track progress.

**Comment by leebyron** [comment]
This is now enabled thanks to:

38a5fbc3d8cae4c8ee672238a3402e2327edac91
6cb4ab1dfe3d7a6863ea60d3f6a6c3568e2f8cd5
8905e649baa97de3a99ecaf20d4c07ab7800b687
7edd606658981e55ee5722e65c0005e233c00e06

**Comment by jtomson-mdsol** [comment]
awesome that's some quick work! :100:
