### ISSUE TITLE
Cursor invisible in default theme

### ISSUE THREAD

**Issue by joeflack4** [graphql/graphiql#701]
## Description
Cursor is not visible with default theme / settings in GraphiQL.

In the image below, my cursor was located at the of the line reading "id". However, either I am partially color blind and did not know it, or it is essentially invisible to the naked eye.

<img width="326" alt="screen shot 2018-07-22 at 1 39 50 pm" src="https://user-images.githubusercontent.com/13045020/43048378-c6700bfa-8db4-11e8-88e4-49f2b6139b5c.png">

**Comment by KennyWho** [comment]
I fix it by myself.I use chrome extends **stylish**, and  create a rule.The point is `.CodeMirror-cursor` have a **transport** background.
`
.CodeMirror-cursor {
	background: #fff!important;
}
`

**Comment by joeflack4** [comment]
@KennyWho Sounds great! I will use that for now.

**Comment by eljenso** [comment]
Any other way to fix this issue? Don't want to install a browser extension just for this.

**Comment by vinniejames** [comment]
+1

**Comment by jhalborg** [comment]
Two other workarounds that both worked for me:

https://github.com/prisma/graphql-playground/issues/790#issuecomment-409221277
https://github.com/prisma/graphql-playground/issues/790#issuecomment-407153297

**Comment by thomasheyenbrock** [comment]
`graphiql@2` comes with completely reworked styles, in particular for the CodeMirror editors. This issue should now be fixed.
