### ISSUE TITLE
Make MAX_HISTORY_LENGTH a react prop

### ISSUE THREAD

**Issue by hmeerlo** [graphql/graphiql#706]
It would be nice of the MAX_HISTORY_LENGTH was configurable. Right now the query/mutation always just falls of the list of max 20 elements :-)

**Comment by pinaegineering4403** [comment]
[protecting_older_consumers_-_ftc_report_10-18-18.pdf](https://github.com/graphql/graphiql/files/2501097/protecting_older_consumers_-_ftc_report_10-18-18.pdf)
[Uploading protecting_older_consumers_-_ftc_report_10-18-18.pdf…]()
I'm am Fredrick Ralph piña

**Comment by thomasheyenbrock** [comment]
There already is a `maxHistoryLength` prop for quite some time! (Since `1.4.0` I think)

**Comment by acao** [comment]
@thomasheyenbrock this was the issue that led to it, we just didn't link it haha
