### ISSUE TITLE
How to use this with .Net Core GraphQL server?

### ISSUE THREAD

**Issue by khteh** [graphql/graphiql#709]
How to use it? Is this an application which could be installed and run like Postman and execute query against GraphQL service implemented with .Net Core?

**Comment by KarandikarMihir** [comment]
@khteh Yes. This works exactly like postman, except for the fact that you get intellisense and graphql documentation viewer for free. You only have to provide the URL to your graphql server and that's it! Graphiql will load the docs automatically in the right pane.

**Comment by khteh** [comment]
How to install and use it?

**Comment by KarandikarMihir** [comment]
@khteh Get the electron version from [here](https://github.com/skevy/graphiql-app/releases)

**Comment by jimitndiaye** [comment]
Check out https://github.com/graphql-dotnet/examples
The example hosts a graphql endpoint using web api and consumed using GraphiQL
