### ISSUE TITLE
Cannot find module 'graphql/validation/rules/ExecutableDefinitions' from 'xxx/node_modules/graphql-language-service-utils/dist'

### ISSUE THREAD

**Issue by huaweihan123** [graphql/graphiql#711]
Hi,
After get the source, I tried install and build the package, an error pop-up. 
Thanks in advance. 

The error shows "Cannot find module 'graphql/validation/rules/ExecutableDefinitions' from '/home/major/git/graphiql/node_modules/graphql-language-service-utils/dist'".

Full log:
-----------------------------------------------------------------------------------------
major@VM-0-16-ubuntu:~/git/graphiql$ npm install && npm run build
npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.

> graphiql@0.11.11 prepublish /home/major/git/graphiql
> . ./resources/prepublish.sh

npm WARN graphiql@0.11.11 requires a peer of react@^15.6.0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN graphiql@0.11.11 requires a peer of react-dom@^15.6.0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN graphql-config@2.0.1 requires a peer of graphql@^0.11.0 || ^0.12.0 || ^0.13.0 but none is installed. You must install peer dependencies yourself.
npm WARN graphql-import@0.4.5 requires a peer of graphql@^0.11.0 || ^0.12.0 || ^0.13.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-test-renderer@15.6.1 requires a peer of react@^15.6.1 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

up to date in 5.732s

> graphiql@0.11.11 build /home/major/git/graphiql
> bash ./resources/build.sh

src/components/DocExplorer/Argument.js -> dist/components/DocExplorer/Argument.js
src/components/DocExplorer/DefaultValue.js -> dist/components/DocExplorer/DefaultValue.js
src/components/DocExplorer/FieldDoc.js -> dist/components/DocExplorer/FieldDoc.js
src/components/DocExplorer/MarkdownContent.js -> dist/components/DocExplorer/MarkdownContent.js
src/components/DocExplorer/SchemaDoc.js -> dist/components/DocExplorer/SchemaDoc.js
src/components/DocExplorer/SearchBox.js -> dist/components/DocExplorer/SearchBox.js
src/components/DocExplorer/SearchResults.js -> dist/components/DocExplorer/SearchResults.js
src/components/DocExplorer/TypeDoc.js -> dist/components/DocExplorer/TypeDoc.js
src/components/DocExplorer/TypeLink.js -> dist/components/DocExplorer/TypeLink.js
src/components/DocExplorer.js -> dist/components/DocExplorer.js
src/components/ExecuteButton.js -> dist/components/ExecuteButton.js
src/components/GraphiQL.js -> dist/components/GraphiQL.js
src/components/HistoryQuery.js -> dist/components/HistoryQuery.js
src/components/QueryEditor.js -> dist/components/QueryEditor.js
src/components/QueryHistory.js -> dist/components/QueryHistory.js
src/components/ResultViewer.js -> dist/components/ResultViewer.js
src/components/ToolbarButton.js -> dist/components/ToolbarButton.js
src/components/ToolbarGroup.js -> dist/components/ToolbarGroup.js
src/components/ToolbarMenu.js -> dist/components/ToolbarMenu.js
src/components/ToolbarSelect.js -> dist/components/ToolbarSelect.js
src/components/VariableEditor.js -> dist/components/VariableEditor.js
src/index.js -> dist/index.js
src/utility/CodeMirrorSizer.js -> dist/utility/CodeMirrorSizer.js
src/utility/QueryStore.js -> dist/utility/QueryStore.js
src/utility/StorageAPI.js -> dist/utility/StorageAPI.js
src/utility/debounce.js -> dist/utility/debounce.js
src/utility/elementPosition.js -> dist/utility/elementPosition.js
src/utility/fillLeafs.js -> dist/utility/fillLeafs.js
src/utility/find.js -> dist/utility/find.js
src/utility/getQueryFacts.js -> dist/utility/getQueryFacts.js
src/utility/getSelectedOperationName.js -> dist/utility/getSelectedOperationName.js
src/utility/introspectionQueries.js -> dist/utility/introspectionQueries.js
src/utility/normalizeWhitespace.js -> dist/utility/normalizeWhitespace.js
src/utility/onHasCompletion.js -> dist/utility/onHasCompletion.js
Bundling graphiql.js...
Error: Cannot find module 'graphql/validation/rules/ExecutableDefinitions' from '/home/major/git/graphiql/node_modules/graphql-language-service-utils/dist'
    at /home/major/git/graphiql/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:17
    at process (/home/major/git/graphiql/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (/home/major/git/graphiql/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (/home/major/git/graphiql/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/major/git/graphiql/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /home/major/git/graphiql/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:149:21)
-----------------------------------------------------------------------------------------

**Comment by Lucashuang0802** [comment]
I had the same issue by following the README.md under `example` folder.

**Comment by acao** [comment]
make sure you are using the right version of graphql. `ExcutableDefinitions` requires graphql-js 0.12 or later
