### ISSUE TITLE
graphiql does not properly validate default values for required fields

### ISSUE THREAD

**Issue by slisaasquatch** [graphql/graphiql#719]
Here's the ticket for the new spec: https://github.com/facebook/graphql/pull/418
It allows the schema to be defined like this:
```graphql
type Query {
  field(arg: Int! = 0): Int
}
```
For the example above, if you don't provide `arg` in the query, graphiql will consider the query invalid.

**Comment by thomasheyenbrock** [comment]
I tried to reproduce this exact example in the latest version, but couldn't. Both queries `{ field }` and `{ field(arg: 42) }` don't get any linter errors and execute fine. Closing this as the issue seems to have been fixed at some point in the past.
