### ISSUE TITLE
How to run a mutation? Add example to Readme

### ISSUE THREAD

**Issue by extrajordanary** [graphql/graphiql#72]
I can query just fine, but I'm having a hard time figuring out the correct format for mutations. Here's a screenshot of what I'm playing with:

https://www.dropbox.com/s/4g0r4ii3z3u7zir/Screenshot%202015-12-16%2010.58.25.png?dl=0

Basically I'm just not sure of the correct format for setting up the `ChangeCohortInput` but I remember seeing someone else do it by making that as a variable in the Query Variables section.

**Comment by tinnou** [comment]
Let say your `ChangeCohortInput` has the fields `clientMutationId` and `title`.

Your mutation would look like:
```
mutation example($cohort: ChangeCohortInput!){
  change_cohort(input: $cohort) {
    user {
      cohort {
        title
      }
    }
  }
}
```
and variables 
```
{
  "cohort": {
  	"clientMutationId": "random",
  	"title": "New cohort title"
  }
}
```

**Comment by asiandrummer** [comment]
Thanks for the answer @tinnou. I do feel like the example for mutation operation better belongs to [GraphQL Specifications Document] (http://facebook.github.io/graphql/), as it already explains the correct specifications, requirements, and examples for running a mutation operation.

**Comment by holmesal** [comment]
@asiandrummer I think a lot of people (like me, 5 minutes in the past :grin:) are going to land on the graphiql README looking for precisely the example above, and while the graphql specification document technically has the info you need, it's a lot to parse/search.

Might be worth adding an example for first-timers?

**Comment by extrajordanary** [comment]
@asiandrummer I agree with @holmesal, the GraphQL Specifications Document is extremely dense. I would never be able to find the info needed within it if I didn't already know what the answer is so that I can `ctrl-f` the page for `$`. 

the screenshot on the readme alone is already a 100% improvement, but even a simple list of links to the most relevant parts of the GraphQL Specifications Document would be another good and not-too-painful improvement for users

**Comment by asiandrummer** [comment]
Per lots of requests for the examples in README (simple query examples && GraphiQL component customizations), I'm working on adding/improving the README. Please stay tuned for upcoming updates :D

**Comment by extrajordanary** [comment]
@asiandrummer greatly appreciate it, really do love using GraphiQL :)

**Comment by asiandrummer** [comment]
Alright, I've tried adding some examples to README - go check it out!
I'll close this issue for now, but if you have any other suggestions, feel free to open another issue or reopen this one.

**Comment by sarink** [comment]
If you're like me, you simply missed the sneaky "variables" input box (bottom left corner):

<img width="1357" alt="screen shot 2018-10-09 at 5 08 59 pm" src="https://user-images.githubusercontent.com/1881761/46701650-10d34d00-cbe6-11e8-9a43-d349555a1d7f.png">

<img width="1357" alt="screen shot 2018-10-09 at 5 09 10 pm" src="https://user-images.githubusercontent.com/1881761/46701649-10d34d00-cbe6-11e8-9964-202566c79654.png">
