### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by khteh** [graphql/graphiql#725]
npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.

> graphiql@0.12.0 prepublish C:\Projects\graphiql
> . ./resources/prepublish.sh

'.' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! graphiql@0.12.0 prepublish: `. ./resources/prepublish.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the graphiql@0.12.0 prepublish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

Log:
707 verbose stack Error: graphiql@0.12.0 prepublish: `. ./resources/prepublish.sh`
707 verbose stack Exit status 1
707 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:304:16)
707 verbose stack     at EventEmitter.emit (events.js:182:13)
707 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
707 verbose stack     at ChildProcess.emit (events.js:182:13)
707 verbose stack     at maybeClose (internal/child_process.js:961:16)
707 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:250:5)
708 verbose pkgid graphiql@0.12.0
709 verbose cwd C:\Projects\graphiql
710 verbose Windows_NT 10.0.17134
711 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
712 verbose node v10.9.0
713 verbose npm  v6.2.0
714 error code ELIFECYCLE
715 error errno 1
716 error graphiql@0.12.0 prepublish: `. ./resources/prepublish.sh`
716 error Exit status 1
717 error Failed at the graphiql@0.12.0 prepublish script.
717 error This is probably not a problem with npm. There is likely additional logging output above.
718 verbose exit [ 1, true ]

**Comment by acao** [comment]
apologies, our prepublish scripts currently do not support windows, we will be fixing this eventually, but currently this is a wont fix
