### ISSUE TITLE
Pre-packaged download?

### ISSUE THREAD

**Issue by solderjs** [graphql/graphiql#730]
I was kinda hoping to find something where I can just copy some files over into a directory and maybe set a variable in a json config file as to where to find my `/graphql` endpoint and `graphql.schema` and roll.

Is there any sort of pre-packaged static site for this?

**Comment by imolorhe** [comment]
It sounds like you are looking for this: https://github.com/graphql/graphiql/blob/master/packages/examples/graphiql-cdn/index.html

**Comment by acao** [comment]
@solderjs here in a few months we will have a better solution, but for now the quickest route is what @imolorhe has linked to above. Check out our discord (link in the readme) for support if you need more info!
