### ISSUE TITLE
Errors installing graphiql example on Windows 10.

### ISSUE THREAD

**Issue by abuhman** [graphql/graphiql#737]
I am trying to install graphiql on Windows 10.  I tried following the instructions found here: https://github.com/graphql/graphiql/tree/master/example.

First I cloned the git repository.  Then I ran "npm install && npm run build", which ended with errors:

> npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
> npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
> npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.
> 
> > graphiql@0.12.0 prepublish C:\Users\Username\Desktop\graphiql\graphiql
> > . ./resources/prepublish.sh
> 
> '.' is not recognized as an internal or external command,
> operable program or batch file.
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! graphiql@0.12.0 prepublish: `. ./resources/prepublish.sh`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the graphiql@0.12.0 prepublish script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\Username\AppData\Roaming\npm-cache\_logs\2018-10-31T13_34_23_652Z-debug.log

Should I do something different to install this?  Thanks very much, and have a good day.

**Comment by abuhman** [comment]
You can install Graphiql by going to this website: https://electronjs.org/apps/graphiql and clicking the download button.  That will give an executable file to install, and you will be able to use Graphiql.

I wasn't able to get it to install using the instructions above on either Windows or Linux.

**Comment by acao** [comment]
Let us know if there are any more issues!

**Comment by charles-lewis-disc** [comment]
> You can install Graphiql by going to this website: https://electronjs.org/apps/graphiql and clicking the download button. That will give an executable file to install, and you will be able to use Graphiql.
> 
> I wasn't able to get it to install using the instructions above on either Windows or Linux.

Link no longer works.
