### ISSUE TITLE
[request] Way to clear all the localStorage data

### ISSUE THREAD

**Issue by gfx** [graphql/graphiql#740]
I have struggled with bugs in codemirror-graphql for years: https://github.com/graphql/codemirror-graphql/issues/236

In this bug, the data in localStorage are broken and there's no way to fix it; even when I clear localStorage in devtool, they are immediately restored.  If there is a way to clear localStorage data, I can avoid this issue.

Of course, the bug should be fixed, but I believe "clear the data" feature is useful because there might remain unknown critical issues.

**Comment by acao** [comment]
does `codemirror-graphql` use localStorage? I think it's `graphiql` that does. this is a good idea for a feature though!

**Comment by acao** [comment]
@gfx long overdue, but this was released somewhere in a patch release of graphiql@2, enjoy!
