### ISSUE TITLE
Treat * as address bar URL

### ISSUE THREAD

**Issue by lukepighetti** [graphql/graphiql#745]
I am serving GraphQL over express using `apollo-server-express` like so

```
const app = express();
const path = "*";
server.applyMiddleware({ app, path });
```

But when I load up GraphiQL the URL is shown as `*`. Since `*` is not a URL, would it be reasonable for GraphiQL to default to its current path?

And if not, is there a correct way for me to set the default URL?

Default value
<img width="863" alt="screen shot 2018-11-19 at 10 42 57 am" src="https://user-images.githubusercontent.com/666539/48717747-06926e80-ebe8-11e8-877d-26344258f6fb.png">

Replaced with address bar value
<img width="913" alt="screen shot 2018-11-19 at 10 43 32 am" src="https://user-images.githubusercontent.com/666539/48717752-08f4c880-ebe8-11e8-9cd6-01129eeff230.png">

**Comment by alsong** [comment]
Its like you are using graphql-yoga and that's the playground that it provides. The one for Graphiql is different

**Comment by imolorhe** [comment]
I agree with @alsong. What you have in your screenshot is GraphQL playground, not GraphiQL. Given the new direction GraphiQL is taking, I guess this can be easily implemented as a custom plugin for GraphiQL, or added into GraphiQL itself (based on how much demand there is for this). Cc @acao .

**Comment by lukepighetti** [comment]
Woops, good point. I'll let someone else close this since there is some discussion.

**Comment by benjie** [comment]
Closing this as I think it's a concern outside of GraphiQL. (GraphiQL itself doesn't care about URLs.)
