### ISSUE TITLE
Cannot read property 'GraphQLSchema' of undefined

### ISSUE THREAD

**Issue by loveyoubaby5120** [graphql/graphiql#749]
import { ajaxPost } from 'common/ajax';
import * as GraphiQL from 'graphiql';
import 'graphiql/graphiql.css';
import * as React from 'react';
import { render } from 'react-dom';

function graphQLFetcher(graphQLParams) {
    return new Promise((resolve, reject) => {
        const url = `127.0.0.1:8000/graphql`;
        ajaxPost(
            url,
            graphQLParams,
            (result) => resolve(result),
            (error) => reject(error));
    });
}

render(<GraphiQL fetcher={graphQLFetcher} />,
    document.getElementById('app'));

**Comment by acao** [comment]
I'm not sure what `ajaxPost` is, try `@graphiql/toolkit` `createFetcher()` if you want something that works out of the box
