### ISSUE TITLE
v0.12.0 on cdnjs gives 404

### ISSUE THREAD

**Issue by marceloverdijk** [graphql/graphiql#758]
The following give a 404:
- `https://cdnjs.cloudflare.com/ajax/libs/graphiql/0.12.0/graphiql.min.css`
- `https://cdnjs.cloudflare.com/ajax/libs/graphiql/0.12.0/graphiql.js`
- `https://cdnjs.cloudflare.com/ajax/libs/graphiql/0.12.0/graphiql.min.js`

However `https://cdnjs.cloudflare.com/ajax/libs/graphiql/0.12.0/graphiql.css` does give correct response.

Maybe related to https://github.com/graphql/graphiql/issues/528?

**Comment by acao** [comment]
all of these appear to be working now, this might have been an issue with cdnjs at the time. thanks for reporting this!
