### ISSUE TITLE
GraphiQL editor appears unstyled

### ISSUE THREAD

**Issue by jeromecovington** [graphql/graphiql#76]
The graphiql component appears to be rendering, but is not styled like the examples.

![image](https://cloud.githubusercontent.com/assets/486493/12098986/945cc6ce-b2f3-11e5-944d-ea14b087d76d.png)

**Comment by primathon** [comment]
Added this, seems to have fixed things for the time being:
`<link rel="stylesheet" type="text/css" href="http://cdn.jsdelivr.net/graphiql/0.4.4/graphiql.css" />`

**Comment by jeromecovington** [comment]
My page was pulling in styles and scripts from the rest of my app and they were interfering with the rendering. Once that was sorted, graphiql behaved as expected.

**Comment by aleksandrenko** [comment]
Is there a way to do that without using the cdn?

**Comment by asiandrummer** [comment]
Hi @aleksandrenko - I think the problem was a overridden/interfering styles from the rest of the app.
