### ISSUE TITLE
The description for arguments not showing

### ISSUE THREAD

**Issue by wszgxa** [graphql/graphiql#760]
Hi, I have added a description for argument. But, It will not show in graphiql.I can find the description in http response: 
![image](https://user-images.githubusercontent.com/6060475/50579731-c67b0880-0e82-11e9-9ce4-2169f2cefdb5.png)

But it will not show in doc.

**Comment by acao** [comment]
i started experimenting with this, very easy to add programatically, but I'm not sure how or where it should render. Do you have any suggestions as to how it should look?

**Comment by acao** [comment]
![Screen Shot 2019-06-10 at 7 24 56 AM](https://user-images.githubusercontent.com/1368727/59192576-ebba2400-8b50-11e9-8481-aef1ad769a4c.png)
this is what it looks like without any styling :/

**Comment by aniketbiswas21** [comment]
@acao I'd like to work on this. Can you help me get started?

**Comment by acao** [comment]
sure! offhand I believe the file is `packages/graphiql/src/components/DocExplorer/Arguments.tsx`
probably best to re-use or create a new css class to style this description item as well

**Comment by acao** [comment]
We resolved this bug last year - enjoy!

While you're here, we also now have field argument deprecation 😍 

Thanks for reporting this!
