### ISSUE TITLE
Fetcher Must Return GraphQL parsed JSON object

### ISSUE THREAD

**Issue by SamBroner** [graphql/graphiql#766]
What exactly does this mean?

Fetcher must return JSON of the data that matches the schema?
Fetcher must return the result of some operation performed by a GraphQL engine?

Is there a document that points to the format of this data if you don't intend to use a plugin?

Personally I'm building my own fetcher and hand describing my own schema.

**Comment by acao** [comment]
just JSON of the response, so that `ResultViewer` can render it.  see [GraphQL Response Spec](https://github.com/graphql/graphql-spec/blob/master/spec/Section%207%20--%20Response.md)
