### ISSUE TITLE
Proposal: Reduce assumptions about authentication

### ISSUE THREAD

**Issue by solderjs** [graphql/graphiql#768]
This seems to be way too opinionated (in my opinion) about how authentication and authorization are handled.

I see tons of issues have been opened (and closed without resolution) about that.

For the sake of the greater good of all the people who use this (which seems to be bundled with every graphql server framework as the de facto "hello world" client) could we have an less opinionated option? Like a simple way to add a request hook and some sort of way to make it so that I can inject that regardless of the opinions of the framework I happen to be using? (which happens to be postgraphile in my case, btw)

In the simplest case that could just be something like documentation of how to add a request hook and comment string in the code that's easy to do an on-the-fly, stupid, inefficient, find-and-replace as express or whatever is serving the file, something like `/* PASTE REQUEST HOOK HERE */`.

Or, much more convenient, a button that opens up a section to add headers?

Just something that's not so forcefully opinionated and requiring hard-forking or direct modification of the original source.

**Comment by coolaj86** [comment]
P.S. And thanks for creating this.

**Comment by coolaj86** [comment]
In other words: If someone created such a patch, how would you want it to look for it to be accepted.

**Comment by acao** [comment]
nothing forceful at all about it, I hate to say.
you can resolve any promise as the fetcher for graphql. fetch with a post being the default example, however you can define any client side async logic to resolve your GraphQL queries/mutations/subscriptions
see the example in [Getting Started](https://github.com/graphql/graphiql/tree/master/packages/graphiql#getting-started)
