### ISSUE TITLE
"s" Plural Attachment About

### ISSUE THREAD

**Issue by gdemir** [graphql/graphiql#769]
Hi,

It makes more sense to use a prefix (ex.: plural : `all_of_hero`, table: `hero`) like `all_of_` instead of the English **`s`** plural attachment. Because both the system works fast and the tables should not be required to be in English name.

Even Ruby on Rails doing this mistake!(ex.: rails relationship and dependencies)

Best regeards

**Comment by acao** [comment]
@gdemir thaks for the feedback! where is there such a pluralisation in the UI? Do you mean `Docs`?

**Comment by gdemir** [comment]
Yes I mean the documents : https://guides.rubyonrails.org/active_record_basics.html#naming-conventions

**Comment by imolorhe** [comment]
@gdemir I don't think this issue is related to this repo. You are probably looking for https://github.com/rails/rails ?

**Comment by gdemir** [comment]
@imolorhe please learn english

**Comment by imolorhe** [comment]
😄 I'm not sure how to respond to that. Maybe you can explain yourself again?

**Comment by gdemir** [comment]
@imolorhe I said "Use plural suffixes as `all_of`". Look at this page https://graphql.org/learn/queries/#default-variables

Samples;

i think **wrong** struct : 
```diff
query HeroNameAndFriends($episode: Episode = JEDI) {
    hero(episode: $episode) {
        name
++   friends {
            name
        }
    }
}
```

i think **correct** struct : 
```diff
query HeroNameAndFriends($episode: Episode = JEDI) {
    hero(episode: $episode) {
        name
++   all_of_friend {
            name
        }
    }
}
```

**Comment by imolorhe** [comment]
Then what you are looking for is still not this repo. That documentation is located here: https://github.com/graphql/graphql.github.io

**Comment by gdemir** [comment]
I understood, but I presented my idea when you could do it that way

**Comment by acao** [comment]
@gdemir this documentation is not in this repo, youll need to report this issue in the docs repositority @imolorhe linked to above

**Comment by gdemir** [comment]
I suggested the approach method. I didn't say the article was wrong. I said it would be nice to have it like this. approach method is `all_of`
