### ISSUE TITLE
URL param to ensure docs panel displays?

### ISSUE THREAD

**Issue by kevinSuttle** [graphql/graphiql#77]
Is there a way to specify a link to a certain view with the docs panel open?

**Comment by alexanderchan** [comment]
Currently, there doesn't appear to be, it is just a part of state and doesn't read from props to determine if it should start open:

https://github.com/graphql/graphiql/blob/master/src/components/GraphiQL.js#L178

The other interesting part of the code would be where it determines if the DocExplorer should be open.

https://github.com/graphql/graphiql/blob/master/src/components/GraphiQL.js#L337

**Comment by asiandrummer** [comment]
Sorry it took long to respond! I'd like to revisit this.
I think this would be a good-to-have feature, enabling GraphiQL to be a source of documentations as well. To start it'd be great if the doc explorer (via GraphiQL props) would accept props to specify the initial status (e.g. `isOpen` and an entry to display). This way at the GraphiQL installation this 'status' could be determined and passed into GraphiQL components.

**Comment by sw-yx** [comment]
checking in from the future. i also want this and am implementing it in my fork

**Comment by acao** [comment]
this is a good feature to note for the doc viewer plugin for version 1.x
