### ISSUE TITLE
Please upgrade codemirror-graphql to 0.8.3 (in order to support graphql 14.0.0)

### ISSUE THREAD

**Issue by jonaskello** [graphql/graphiql#773]
The graphiql package now supports graphql 14.0.0 as peer dependecy which is great! 👍 (See  #739).

However, when I install graphiql with yarn, it installs codemirror-graphql  0.7.1 which does not support graphql 14.0.0 as peer dependency. So in order to fully support graphql 14.0.0 transitively I guess graphiql must upgrade codemirror-graphql to 0.8.3 [here](https://github.com/graphql/graphiql/blob/master/package.json#L54). (Because codemirror-graphql 0.8.3 supports graphql 14.0.0 as peer dependency.)

**Comment by mikefowler** [comment]
@AGS- @RamonSaboya would you be able to help out with this?

**Comment by AGS-** [comment]
Merged! Thanks!
