### ISSUE TITLE
'Query variables' is not expandable by clicking on it in Chrome Canary.

### ISSUE THREAD

**Issue by toomastahves** [graphql/graphiql#78]
Browser: Google Chrome
Version 49.0.2617.0 canary (64-bit)
OS: Win 10

Problem: 'QUERY VARIABLES' tab is not expandable by clicking on it.
It might be browser problem..

Also tested in Firefox Nightly 46.0a1, everything good there.

**Comment by asiandrummer** [comment]
Thanks for the report - I took a look and it seems like `EditorBar` component's `clientHeight` is being incorrectly calculated during `mousemove` event. I'm investigating as to why this happens.

**Comment by leebyron** [comment]
@asiandrummer Keep in mind this may be a bug with Canary - if so we could report an issue to Chrome (https://code.google.com/p/chromium/issues/list). 

GraphiQL only strive to support the latest release version of major browsers, not nightly or pre-release builds which can often have their own bugs.

**Comment by asiandrummer** [comment]
@leebyron good point - I was browsing through the issue list the other day and couldn't find anything. I'll open an issue with them, see if we can progress with that.

**Comment by asiandrummer** [comment]
I tried to reproduce this and the issue seems to have gone away - I'll close this for now. Let us know if this happens again!
