### ISSUE TITLE
Fallback introspection query never actually happens

### ISSUE THREAD

**Issue by dallonf** [graphql/graphiql#79]
Just starting messing with GraphiQL and the [graphql-java](https://github.com/andimarek/graphql-java) implementation, which doesn't support subscriptionType yet. According to #55, this was fixed with a fallback query, but it seems to be implemented by `catch`ing the `fetcher`'s result.

The thing is... it appears that the `fetcher` is not actually supposed to (and, at least in the example directory, does not) throw, at least in the case of a standard GraphQL error!

For reference, the result that is returned when introspection fails is this:
```
{
  "errors": [
    {
      "validationErrorType": "FieldUndefined",
      "message": "Validation error of type FieldUndefined: Field subscriptionType is undefined",
      "locations": [
        {
          "line": 6,
          "column": 7
        }
      ],
      "errorType": "ValidationError"
    }
  ],
  "data": null
}
```

I also tried manually throwing in the fetcher if the result contains errors; this works, but degrades the user experience as normal validation errors will not show up in the right-hand panel.

**Comment by sazzer** [comment]
I've just come across this myself, and I can't actually find subscriptionType mentioned in the [GraphQL Specification](https://facebook.github.io/graphql/) anywhere. It looks like this turned up in the graphql-js codebase back in September, as commit [8a589f6](https://github.com/graphql/graphql-js/commit/8a589f6e88ecf675ce34d39d813a7b271dae46aa), and GraphiQL has just inherited it automatically as a dependency.

**Comment by leebyron** [comment]
Thanks for reporting this and sorry for the delay in fixing. Subscriptions is an experimental feature, and GraphiQL has growing experimental support.
