### ISSUE TITLE
Publish New Release

### ISSUE THREAD

**Issue by stephahart** [graphql/graphiql#793]
Please publish a new release so we can pull in the changes from https://github.com/graphql/graphiql/pull/784. Thanks!

**Comment by stephahart** [comment]
@AGS- sorry to spam, but there doesn't seem to be much activity on recent open issues

**Comment by stephahart** [comment]
bump 😅

**Comment by stephahart** [comment]
@leebyron do you happen to know who took over this project who can publish a new release for us? Thanks.

**Comment by daern91** [comment]
Please also include #779 for the next release. Super small 1 line change that solves issue #794

**Comment by acao** [comment]
@stephahart @daern91 we should have a new release here shortly!

**Comment by acao** [comment]
https://github.com/graphql/graphiql/releases/tag/v0.13.1
new release, but its not on NPM yet: https://github.com/graphql/graphiql/issues/818

**Comment by acao** [comment]
Hoping we can figure out the npm credential issue at the WG meeting tomorrow (see wg-agenda) but currently we don't know who has the keys to the npm namespace 🤣

**Comment by acao** [comment]
Update: We are supposed to get NPM access from Facebook's open source department at some point soon. It's officially out of @asiandrummer  and @AGS- 's hands at this point.

**Comment by acao** [comment]
just got npm access two days ago, 0.13.2 is on npm! these are now combined into a monorepo, so it'll be much easier for us to update codemirror/etc
