### ISSUE TITLE
Execute named operation under a cursor

### ISSUE THREAD

**Issue by OlegIlyenko** [graphql/graphiql#81]
When I'm working with GraphiQL, more often than not, I have several queries in the editor pane. A typical use-case is to have a mutation and query around in order to make changes and see their effects on different queries.

At the moment I need to comment out all of the queries except one I would like to execute. It can become tiresome after some time. That's because I would like to suggest an alternative approach: an ability to execute query under the cursor. As far as i saw, this is pretty common feature available in similar applications. For instance, I use this feature a lot in elasticsearch [sense](https://chrome.google.com/webstore/detail/sense-beta/lhjgkmllcaadmopgmanpapmpjgmfcfig?hl=en) (which is now part of marvel plugin) and find it pretty useful.

So the idea would be to either have a separate context sensitive shortcut/button or make existing shortcut and "run" button context sensitive. If an editor cursor is positioned somewhere inside of some named query, then in addition to a query, GraphiQL will also send the operation name to a server.

**Comment by leebyron** [comment]
This is a great suggestion.

**Comment by KyleAMathews** [comment]
I've used Sense a lot as well and agree it works very well and would fit
easily into GraphiQL.

**Comment by asiandrummer** [comment]
I love this idea! I'm leaning towards making existing shortcut and "run" button context sensitive - GraphQL operations could be huge and it might be difficult to position/find the separate `run` button, but maybe there is a way to mitigate that.

We could also do the similar background-color change for each operation context to clarify UI a bit more.

**Comment by opatut** [comment]
To reduce the magic, the UI could have one execute ("play" icon) button next to each query/mutation definition (e.g. in the gutter to the left), instead of the global button. 

The current query/mutation would be indicated by highlighting one of the buttons, the Shortcut would "press" that highlighted button.
