### ISSUE TITLE
Support for Unary and Binary types

### ISSUE THREAD

**Issue by abdul-takt** [graphql/graphiql#811]
Will there be support for Binary and Unary types?  Example would be Maybe, Either, or Pair type, commonly found in Haskell.

http://hackage.haskell.org/package/base-4.12.0.0/docs/Data-Either.html
http://hackage.haskell.org/package/base-4.12.0.0/docs/Data-Maybe.html
https://en.cppreference.com/w/cpp/utility/pair

**Comment by benjie** [comment]
@abdul-takt In GraphQL the Either type would most likely map to a `union` (or maybe an `interface`), the `Maybe` type would be a nullable type (all types are nullable by default), and a pair could be a type with two fields. GraphiQL supports displaying all these things.

Is there a GraphQL API you have that uses these types that you feel is not working in GraphiQL; or did you mean to file this against a different repository?

**Comment by benjie** [comment]
Closing as you re-opened here: https://github.com/graphql/graphql-spec/issues/582
