### ISSUE TITLE
custom serializing & parsing for nullable and non-nullable data types

### ISSUE THREAD

**Issue by abdul-takt** [graphql/graphiql#812]
I'd like to handle serializers & parsers for nullable and non-nullable data types differently.  An example is using Maybe types to handle `Nullable` values.

example
```graphql
type data {
  nullable: Int,
  nonNullable: Int!
}
```
parseValue for nullable Int  (using sanctuary.js or ramda.js)
```javascript
import S from 'sanctuary';

serialize (val) {
  if (val == null) return 'Nothing';
  else return `Just (${val})`;
}
parseValue (val) {
  if (val == 'null' || !val) return S.Nothing
  else return S.Just (parseInt (val, 10));
}
```

parseValue for non-Nullable Int
```javascript
serialize (val) {
  return String (val);
}
parseValue (val) {
  return Number (val)
}
```

Is there a way to override the default methods or a way to check to see if the value has been define as nullable or not in the serializer, parser or resolver functions?

**Comment by benjie** [comment]
Hi @abdul-takt, thanks for your interest in GraphQL. This repository is for GraphiQL which is a graphical interactive in-browser GraphQL IDE. I think your question relates to the [GraphQL-js project](https://github.com/graphql/graphql-js) and would be better suited for StackOverflow.

**Comment by abdul-takt** [comment]
I did not notice the `i`.  Closing...  Thanks!
