### ISSUE TITLE
Create a GraphiQL PR deploy for testing?

### ISSUE THREAD

**Issue by orta** [graphql/graphiql#813]
Using something like Netlify there could be a working build of every PR to this repo with a static deploy of graphiql which could hook up to the Star Wars API?

**Comment by acao** [comment]
great idea! as in https://swapi.graph.cool/?

**Comment by orta** [comment]
Every PR should get a build, for example Artsy deploys an instance of storybook js for every PR so you can preview the changes live. e.g. https://github.com/artsy/reaction/pull/2392#issuecomment-491077963

**Comment by orta** [comment]
E.g. this PR https://github.com/graphql/graphiql/pull/781#issuecomment-491115471 would have been trivial to test because it would have a working copy of GraphiQL linked in the PR

**Comment by acao** [comment]
agreed! I wonder... there's already the `/example` there, so if we just instructed that to build each time in travis, or just dropped an `index.html` in the root, even, we could use `github-pages`. Netlify would give us more options without potentially cluttering the repository

**Comment by acao** [comment]
@orta the example project would be a good starting point for this possibly?

**Comment by acao** [comment]
@orta you wanna take this on? Netlify would be a perfect candidate for this

**Comment by orta** [comment]
Alright, yeah, I've done this on my own fork in https://github.com/orta/graphiql/pull/1 (sorry, #815 )

I'll request netlify to be added to this org (/cc admins @leebyron ) then once that's approved I can move it over.

**Comment by acao** [comment]
looking good!

i would normally just use gh-pages, but netlify allows us to seamlessly host the build artifacts without committing them to source or a gh-pages branch

**Comment by orta** [comment]
You can only have one gh-pages deploy, many (e.g. per PR) - so, it wouldn't be feasible to do it on a per-PR basis 👍

**Comment by acao** [comment]
ohh! i see what you mean. i thought you meant a build of every PR merge. so you mean one for each PR! even better.

**Comment by orta** [comment]
OK, this now has a PR to the monorepo branch - https://github.com/acao/graphiql/pull/6

**Comment by acao** [comment]
thanks @orta ! this is a great feature. has made the refactoring effort a lot easier
