### ISSUE TITLE
Outdated npm api_key

### ISSUE THREAD

**Issue by acao** [graphql/graphiql#818]
@AGS- @leebyron @asiandrummer, anyone with npm deploy permissions for this project:

The api_key in travis.yml still prompts for an OTP:
https://travis-ci.org/graphql/graphiql/builds/531154858#L681

> NPM API key format changed recently. If your deployment fails, check your API key in ~/.npmrc.
http://docs.travis-ci.com/user/deployment/npm/

thanks @orta for tracking this down

**Comment by asiandrummer** [comment]
I'm working with Facebook to transfer the ownership to the GraphQL foundation - hang tight please.

**Comment by acao** [comment]
thanks @asiandrummer ! let me know what else I can do. we need to be able to release `graphql-language-server` and `codemirror-graphql` on npm as well if that's possible

**Comment by acao** [comment]
we got it!
