### ISSUE TITLE
Live demo link is broken in README

### ISSUE THREAD

**Issue by RussianCow** [graphql/graphiql#834]
[The link](https://graphql.org/swapi-graphql) gives a Page Not Found error:

![image](https://user-images.githubusercontent.com/1589155/58652327-25289f00-82c8-11e9-9caf-ece177579fb5.png)

**Comment by acao** [comment]
Oh dear, that's a new one. Possibly part of the facebook -> graphql foundation transition. I'll ask around.

**Comment by acao** [comment]
Can you report that here @RussianCow ? https://github.com/graphql/swapi-graphql
Might have to do with updated deps
