### ISSUE TITLE
Discussion: Modernization

### ISSUE THREAD

**Issue by Zaba505** [graphql/graphiql#838]
_This is merely a rough draft for a foundation of discussion_

## Design Criteria
Before getting into design details I think it's worth while to provide a definition of graphiql in order to provide context for this design; **graphiql**: An in-browser IDE for exploring GraphQL.

This definition means that graphiql can be split into two components: **ui** and **business logic** (i.e. http req/resp). 
The primary use case for graphiql (in my opinion) is for development/testing of a graphql service, which means assuming an **offline** environment is not too far of a reach.

Now, equipped with the criteria of providing a **ui**, **business logic** (http req/resp), and an **offline experience**, what follows is my proposal for redesign. (**Note**: the current design does satisfy all of these criteria)

### Web Component
In line with the current design, a [web component](https://www.webcomponents.org/introduction) (built with [StencilJS](https://stenciljs.com)?) will be provided to allow for embedding of graphiql into another project. The exported component need not be a web component, per se, it could still just be a React component, but a web component would be more framework neutral.

One major difference will be that the component must be provided an http client object instead of the fetcher function. A default client will also be exported.

### Default Environment
A default graphiql app would be hosted on github pages at https://graphiql.github.io.
The main ui of the site will be the graphiql component but combined with a form input field to change the graphql http endpoint. The schema would then be loaded from this endpoint through introspection.

```html
<form>
  Endpoint: <input typ="text" name="endpoint"/>
</form>

<graphiql endpoint=endpoint></graphiql> <!-- Web component -->
<!-- Have a script tag update endpoint value and the web component should rerender itself -->
```

To support offline development, instead of requiring developers to spin up there own server just to display graphiql, a [Service Worker](https://developers.google.com/web/fundamentals/primers/service-workers/) will be registered to cache all assets associated with graphiql.github.io.

**Comment by benjie** [comment]
Hi @Zaba505; could you expand on what part of GraphiQL is not already enabling you to use GraphiQL offline first? You mention:

>  instead of requiring developers to spin up there own server just to display graphiql

however, GraphiQL is just a React component, it does not require a webserver to function.

I've not tried, but I think you should already be able to bundle GraphiQL and its assets up inside your offline-first codebase, installing relevant parts to a service worker if you so desire?

The fetcher function does not need to be implemented via HTTP, it can use any communication method that JS can use wherever it is running, which enables it to check your offline cache before attempting to connect to the network, so I think this is inline with what you need already.

**Comment by Zaba505** [comment]
Hi @benjie, you're right and as I noted in the criteria section, the current implementation does satisfy the offline environment criteria. My design (which I am now realizing is two: 1. React => Web component 2. Provide service worker impl.), is more of a modernization of graphiql. The current implementation requires you, _the developer_, to set up your "graphiql" environment (through the React component) or to be connected to the internet and go to https://graphiql.github.io.

I'm not sure where the index.html is located for graphiql.github.io, so my proposal is to then just add a service worker to it. Thus, providing a better offline experience for developers.

If you know where the graphiql github page is being served I'll open a PR to add a SW to it.

If they're are no other questions relating to the SW, then I'm going to close this issue and open a separate one for reimplementing the React component as a Web component.

**Comment by benjie** [comment]
GraphiQL.github.io is not ours: https://github.com/graphiql/graphiql.github.io

We’re not planning to move this specific project away from React, but with the v1 rearchitecture overhaul we’re aiming to make GraphiQL even more modular so you can reuse parts of it to build your own web component editor.

**Comment by acao** [comment]
@Zaba505 if you want to build your own web component based editor, check out our project codemirror-graphql! For example, Altair used it to build a GraphQL client using angular.

GraphiQL is meant to be a minimal reference implementation of our codemirror mode, and a foundation on which to build react-based GraphQL IDEs.

Your idea for using webworkers for offline support would make a great plugin for v1, but probably we will not include it in the default base GraphiQL client. It's a feature that I could imagine many implementations would want, however.

**Comment by imolorhe** [comment]
> GraphiQL.github.io is not ours: https://github.com/graphiql/graphiql.github.io

I think this is a case that should be potentially reported to Github? Anyone could easily fall for thinking that URL belongs to the graphiql team. Looks like a clear case of impersonation to me.

**Comment by acao** [comment]
@imolorhe we also have a guy who has parked the graphql dockerhub orgspace and refuses to give it up 🤷‍♂

**Comment by acao** [comment]
@Zaba505 have you tried using codemirror-graphql to build your own web component based query tool? you totally could! I'm going to close this as won't fix because we don't plan on supporting anything other then React for GraphiQL
