### ISSUE TITLE
Can the Documentation Explorer show directives?

### ISSUE THREAD

**Issue by mgeraci** [graphql/graphiql#841]
I wrote a custom directive to authenticate parts of my graph, a little something like this:
```.graphql
type Query {
  publicField: String!

  user(id: String!): User @isLoggedIn
}
```

But when I browse the graph in the GraphiQL Documentation Explorer, I don't see any reference to this directive (at this level or nested within either the `user` field or `User` entity's documentation):

<img width="350" alt="Screenshot 2019-06-07 10 52 58" src="https://user-images.githubusercontent.com/89606/59113143-7fea7800-8912-11e9-9a63-ea18d49d9c75.png">

This seems like it could be a useful feature, but I'd love to know if I'm missing something and it either already exists, or would cause issues that I don't understand!

And I'm using `graphiql: "0.13.0"`. Let me know if there's other info I can provide!

**Comment by benjie** [comment]
Interestingly the directive you've added there does not physically exist as part of the schema once it is constructed (once it becomes a `GraphQLSchema` object); instead it gets factored into how the resolvers (or similar) are built.

There's an open issue in the graphql-spec about exposing "user-defined meta-data" (i.e. these kinds of 'directives') via schema introspection:

https://github.com/graphql/graphql-spec/issues/300

(Aside: I actually know this issue number off-by-heart it seems!)

Until GraphQL has this feature, we cannot know that `@isLoggedIn` even exists, and thus cannot implement this feature. For now, you may be better adding a `Query._meta` field (or similar) that exposes this additional information in whatever format makes sense for your application; you might want to look at the [Apollo federation spec](https://www.apollographql.com/docs/apollo-server/federation/federation-spec/) for how they solve this kind of problem.

Alternatively you could change how `@isLoggedIn` is implemented, such that it also edits the field description and adds the information there.

Either way, there's nothing GraphiQL can do for you currently, so I'm going to close this issue for now. Once the underlying feature is added to GraphQL/GraphQL-js, please feel free to re-open 👍

**Comment by mgeraci** [comment]
Thanks for the explanation; it's much appreciated!

**Comment by mgeraci** [comment]
In case anyone comes across this thread in the future, @benjie's suggestion of overwriting the field description worked out really well. My directive looks like this now:

```.js
class IsLoggedInDirective extends SchemaDirectiveVisitor {
  visitFieldDefinition(field, { objectType }) {
    const { resolve = defaultFieldResolver } = field;
    const description = "Uses the @isLoggedIn directive to ensure that requests are authenticated.";
    field.description = `${(field.description || "")} ${description}`; // eslint-disable-line no-param-reassign

    field.resolve = (...args) => { // eslint-disable-line no-param-reassign
      const [, , context] = args;

      if (!context || !context.isLoggedIn) {
        throw new AuthenticationError(`You must be logged in to access the field ${this.visitedType.name}.`);
      }

      return resolve.apply(this, args);
    };
  }
}
```
