### ISSUE TITLE
live demo does not work

### ISSUE THREAD

**Issue by jasp402** [graphql/graphiql#843]
![image](https://user-images.githubusercontent.com/8978470/59138719-420e4380-8954-11e9-837e-e06f225fdb85.png)

**Forwards to an old url**
![image](https://user-images.githubusercontent.com/8978470/59138760-69651080-8954-11e9-9677-33edc51f66dc.png)

**and the page shows this message**

![image](https://user-images.githubusercontent.com/8978470/59138780-839eee80-8954-11e9-825e-e5602b2c19f8.png)

**Comment by benjie** [comment]
Thanks for your bug report; this is a known issue you can track here:

https://github.com/graphql/swapi-graphql/issues/143

In the mean time, try:

https://graphql.github.io/swapi-graphql/

**Comment by orta** [comment]
Closing as duplicate graphql/swapi-graphql#143
