### ISSUE TITLE
Cannot run example 

### ISSUE THREAD

**Issue by mihaiandreiolteanu** [graphql/graphiql#848]
Hi,

I am following the steps from [example](https://github.com/graphql/graphiql/tree/master/example)
After running the the app with `npm start`, I am getting several errors in console such as:
`Refused to apply style from 'http://localhost:54286/node_modules/graphiql/graphiql.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.` and `Uncaught ReferenceError: GraphiQL is not defined at (index):136`
Checking the node_modules/graphiql/ path, indeed I am not able to find graphiql.css and graphiql.js files.

Can you please help me ? 

Best regards

**Comment by acao** [comment]
@mihaiandreiolteanu did you try running `yarn build` in the root directory first before running `yarn start` in the example?

**Comment by mihaiandreiolteanu** [comment]
@achao I ran `npm run build` in the root directory but I was getting a bash error because I was using the windows cmd. I ran again using a bash terminal and now it works. Thanks for your support !

**Comment by mihaiandreiolteanu** [comment]
Sounds good . Cheers !
