### ISSUE TITLE
Graphql 14 dependency issues

### ISSUE THREAD

**Issue by austinnichols101** [graphql/graphiql#863]
codemirror@0.8.3 specifies 

`"graphql": "^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0"`

However, the dependencies of codemirror@0.8.3 do NOT support graphql 14:

`    
"graphql-language-service-interface": "^1.3.2",
"graphql-language-service-parser": "^1.2.2"
`

**Comment by acao** [comment]
This should be resolved now in codemirror 0.9/graphiql 0.14!

**Comment by austinnichols101** [comment]
@acao 
FYI https://github.com/graphql/graphiql/releases shows `v0.13.2` as the latest release.
NPM disagrees: https://www.npmjs.com/package/graphiql/v/0.14.2

**Comment by benjie** [comment]
Hi @austinnichols101; since this is now a monorepo (and the packages within it are independently versioned) we can't have one over-arching version any more.

Please refer to the CHANGELOG instead:

https://github.com/graphql/graphiql/blob/master/CHANGELOG.md
