### ISSUE TITLE
Ace Editor support

### ISSUE THREAD

**Issue by Nishchit14** [graphql/graphiql#864]
Codemirror support looks very awesome!!
Is there any plan to support for Ace cloud9 Editor? We're highly dependant on it :smile:

**Comment by Neitsch** [comment]
@Nishchit14  - what would it take to support this editor? I would think that this requires more work on the Ace Cloud9 side, since an editor would build on this here.

**Comment by benjie** [comment]
Does Ace cloud9 editor support Language Server Protocol (LSP)?

**Comment by acao** [comment]
@Nishchit14 so, `codemirror-graphql` should serve as a nice prior art for an implementation of an editor mode for ace. You will likely need to use `graphql-language-service-interface` and `graphql-language-service-parser`, just like the codemirror mode. There are no current plans to officially support Ace Editor, and for 1.0 we are considering moving to monaco-editor, actually.

**Comment by acao** [comment]
in fact, stick as closely to `graphql-language-service-interface` as possible if you can when it comes to spec implementation. our goal with the monaco mode is to instantiate the `GraphQLLanguageService` class itself, which will give you access to our config/cache/plugin system eventually. I'll have more to show you before the end of the year. For now, just using the interface functions that class consumes will have you 90% of the way there.  The goal is for everything to be driven by the LSP spec. So, codemirror-graphql is not always the best example, as it ends up working around the LSP spec sometimes laboriously. Granted, the LSP spec wasnt as dominant when all this first began.

I'm going to close this ticket for now, but if you have any questions @Nishchit14 please hit us up with any questions on our Discord, linked from the readme. Would love to see an Ace editor mode and I'd be happy to help you get it off the ground. Also, note that we just recently kicked out some new releases for these packages, so please enjoy!

**Comment by benjie** [comment]
(Closing as stated by @acao)
