### ISSUE TITLE
Unable to pass schema to codemirror

### ISSUE THREAD

**Issue by KarthikNedunchezhiyan** [graphql/graphiql#865]
Hello everyone,
        When i passed graphql schema to codemirror like below i am getting error. I followed the steps recommended in [https://github.com/graphql/codemirror-graphql/issues/255](url)

`Error: Expected { astNode: undefined, extensionASTNodes: undefined, _queryType: Query, _mutationType: null, _subscriptionType: null, _directives: [@include, @skip, @defer], _typeMap: { Query: Query, String: String, workflowTable: workflowTable, ID: ID, Boolean: Boolean, conditionsTable: conditionsTable, moduleDetails: moduleDetails, fieldUpdate: fieldUpdate, moduleData: moduleData, emailDetails: emailDetails, __Schema: __Schema, __Type: __Type, __TypeKind: __TypeKind, __Field: __Field, __InputValue: __InputValue, __EnumValue: __EnumValue, __Directive: __Directive, __DirectiveLocation: __DirectiveLocation }, _implementations: {}, _possibleTypeMap: undefined, __validationErrors: undefined, __allowedLegacyNames: [] } to be a GraphQL schema.`

This is how i am using editor

`
let schema = buildClientSchema(interpolationQuery);
let editor = CodeMirror.fromTextArea(__('gql_edit'), {
                    mode: "graphql",
                    lint: {
                        schema: schema
                    },
                    hintOptions: {
                        schema: schema
                    },
                    autoCloseBrackets: true,
                    theme: "default",
                    lineNumbers: true,
                    textIndent: true,
                    foldGutter: true,
                    gutters: ["CodeMirror-linenumbers", "CodeMirror-foldgutter"]
                });`

**Comment by imolorhe** [comment]
@KarthikNedunchezhiyan Are you passing the `interpolationQuery` itself to `buildClientSchema()`? If not, you should be passing the result of sending the introspection request. Also can you show the versions for `graphql` and `codemirror-graphiql` you have in your package.json file?

**Comment by yoshiakis** [comment]
The error message is probably thrown from here:
https://github.com/graphql/graphql-js/blob/v14.4.1/src/type/schema.js#L48

**Comment by yoshiakis** [comment]
I guess that `instanceOf` function [here](https://github.com/graphql/graphql-js/blob/v14.4.1/src/type/schema.js#L42) returned false because `schema` is not an instance of this `GraphQLSchema` class defined in this file but one of `GraphQLSchema` class defined using another `graphql-js` module because of having multiple `graphql-js` as dependencies.

**Comment by acao** [comment]
@KarthikNedunchezhiyan can you confirm that what @yoshiakis suggests is true? This one of the main reasons why there can't be clashing versions of graphql-js :(. Maybe try setting `resolutions: { "graphql": "14.3.1"}` in your package.json, or whatever version you are using?

**Comment by KarthikNedunchezhiyan** [comment]
@acao sorry i have forgot this issue as it happened long before also we have dropped the plan of using codemirror-graphql instead we are using monaco editor now.
