### ISSUE TITLE
webpack 1.15.0 cant parse 'codemirror-graphql/hint' && 'codemirror-graphql/lint'

### ISSUE THREAD

**Issue by Ahkari** [graphql/graphiql#867]
I use codemirror-graphql according to the method in Getting Started.
But there is two file cant parse by webpack 1.15.0.

there is warning:

WARNING in ./~/_graphql-language-service-interface@1.2.2@graphql-language-service-interface/dist/getOutline.js.flow
Module parse failed: /Users/ahkari/Documents/tb-project/new-steins/node_modules/_graphql-language-service-interface@1.2.2@graphql-language-service-interface/dist/getOutline.js.flow Unexpected token (11:12)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (11:12)

**Comment by Neitsch** [comment]
Can this be closed?

**Comment by acao** [comment]
this could also be achieved with the @babel/preset-flow
