### ISSUE TITLE
type lookup in hint fails

### ISSUE THREAD

**Issue by timsuchanek** [graphql/graphiql#868]
Hi,

we're using the `codemirror-graphql` in the GraphQL Playground and experience problems, that the `type` property of a suggestion is undefined.
It happens in  this line of code:
https://github.com/graphql/codemirror-graphql/blob/master/src/hint.js#L66

The problem is, that `item.detail` can contain `!` in the case of a non-nullable type.
`item.detail` comes from here https://github.com/graphql/graphql-language-service/blob/master/packages/interface/src/getAutocompleteSuggestions.js#L97

`schema.getType()` however is just returning `getTypeMap()[name]` - as there is no type with the name `User!`, `undefined` is returned.
https://github.com/graphql/graphql-js/blob/master/src/type/schema.js#L182

Now is the question what the solution for this could be.
The quick-fix, that would work for us, is just not calling `.getType()` in `hint` anymore.
But I guess that the type lookup has been added for a reason.

@asiandrummer would be awesome to hear your take on that.

Thanks!

**Comment by acao** [comment]
@timsuchanek thanks for your fix for this, I'm going to consider this resolved

**Comment by acao** [comment]
@yoshiakis is this not resolved yet? i think i mistook the PR above as having solved this

**Comment by yoshiakis** [comment]
@acao This issue is not solved yet. Sorry for stopping fixing this issue. Can I continue to be responsible to solve this issue? I think I can throw fixed PR in 1 or 2 weeks.

**Comment by acao** [comment]
would love your help, you are right on track already, that timeline sounds perfect!

**Comment by acao** [comment]
@yoshiakis this is in codemirror-graphql@0.12.0-alpha.5 which now has graphql 15 support! enjoy

**Comment by yoshiakis** [comment]
@acao would you please reopen this issue? Unfortunately, this issue hasn't been fixed yet. I'm currently modifying the test code in [a branch](https://github.com/graphql/graphiql/pull/902) which needs to be merged to fix this issue.

**Comment by acao** [comment]
@yoshiakis i merged as is, and I can add more tests in another PR, is that ok?

**Comment by yoshiakis** [comment]
@acao yeah, it's ok. and thank you for merging! I want to do other PRs for refactoring and adding test cases and changing code of hint.js a little bit because the way how the value of documentation in completion list is determined has been slightly changed in graphql-language-servide-interface by #1541.

**Comment by acao** [comment]
@yoshiakis @timsuchanek do we feel this bug is resolved now?

**Comment by yoshiakis** [comment]
@acao yeah, i think so :) (refactoring the test cases still remains, but the bug has been fixed so I think this issue can be closed.)

**Comment by acao** [comment]
speaking of which, do you have any reccomendations for getting flow + typescript working side by side in vscode? i can't seem to get it working without temporarily disabling Check JS for the entire workspace. it's been an issue since the typescript conversion

**Comment by acao** [comment]
also, thank you @yoshiakis so very much for your stewardship of `codemirror-graphql`!

**Comment by yoshiakis** [comment]
unfortunately, i don't know either. it's a pain, though :(

**Comment by acao** [comment]
closing now, if any new issues with this arise with `codemirror-graphql`, please let me know!
