### ISSUE TITLE
Would it be possible to render newline characters in string values for GraphQL results

### ISSUE THREAD

**Issue by kbrandwijk** [graphql/graphiql#869]
I get results like this very often:
![image](https://user-images.githubusercontent.com/852069/32465494-f0ee7308-c343-11e7-86c1-488375cbc0fd.png)

Especially in case of errors. It would be very helpful if these values were rendered parsing the newline characters.

It think that should be in this line, but I have no idea how to add the newline functionality there:
https://github.com/graphql/codemirror-graphql/blob/master/src/results/mode.js#L101

**Comment by acao** [comment]
these messages come from `graphql-js` itself.
this sounds like something that could be a user preference
