### ISSUE TITLE
Graphiql height is not 100%

### ISSUE THREAD

**Issue by blaiprat** [graphql/graphiql#87]
When I open Graphiql it looks like this
![screen shot 2016-02-03 at 11 35 53](https://cloud.githubusercontent.com/assets/723386/12781113/50a5eee0-ca6a-11e5-8a02-58fbfb7b41bb.png)

It looks like that `html` and `body` tags need to have their height set to 100% so the layer `#graphiql-container` can expand too.

I've tried also opening in safari and in chrome on incognito window (without any extension running) and the same happens.

**Comment by KATT** [comment]
+1

**Comment by leebyron** [comment]
Are you running graphiql via `express-graphql`?

I realized that I had just released a breaking change in a point release, so I republished to account for the breaking change. I'll make the change to express-graphql now as well.

**Comment by leebyron** [comment]
Ok, I could easily reproduce this issue when trying to update http://graphql-swapi.parseapp.com/. I've got  new versions of both `graphiql` and `express-graphql` on npm which should fix this, and have unpublished the offending ones so people don't accidentally run into this when they npm install!

Thanks again for the fast report

**Comment by blaiprat** [comment]
Reinstalled `node_modules` and it shows fine now. Thanks for the quick fix and the awesome work!

**Comment by leebyron** [comment]
Most excellent, thanks for confirming the fix!

**Comment by xuorig** [comment]
Hello! I've got the same behaviour using `build.sh` on master, what was the fix to this?

**Comment by mkuts12** [comment]
Hey @leebyron, I have the same issue but I don't use `express-graphql`.
I work in a company with closed network and `express-graphql` uses cdns.

I use webpack with css and style loaders for the css.
I've made a project with the problem. It's very simple and I will be happy if you help me. I'm simply lost

**Comment by mkuts12** [comment]
Hey again,
after investing almost two days into figuring out what the hell is going on, it appears that the problem is the id of the div i try to render into.
In your example it is set to 'graphiql' and in my project it is 'app'.
when chaning my app to 'graphiql' it worked. and when changing in your example 'graphql' to 'unique' it didn't work anymore.

I am shocked

**Comment by mkuts12** [comment]
I am infinitely sorry. Of course it won't work since the way css works.
maybe you can write about it in the readme or bind the css to the component, please?

**Comment by leebyron** [comment]
I'm glad you figured out what was going on! I'll find a way to make the css bindings more appropriate so that this kind of issue is harder to get yourself into in the future.
