### ISSUE TITLE
GraphQL 14 Support

### ISSUE THREAD

**Issue by divyenduz** [graphql/graphiql#889]
Since GraphQL 0.14 is [around the corner](https://github.com/graphql/graphql-js/releases). Creating an issue to track its support. 

I can take up the implementation part as I am maintaining the [vscode-graphql](https://github.com/prismagraphql/vscode-graphql) extension and we have [some issues](https://github.com/prismagraphql/vscode-graphql/issues/18) regarding this change already. 

Do any of the maintainers have any comments on this before I start to work on it? Thanks.

**Comment by acao** [comment]
should be able to get this all released shortly! then we have some follow up work to deprecate support for <graphql 0.12

**Comment by acao** [comment]
this should be resolved in the latest 2.1.0 releases! sorry it took so long.
