### ISSUE TITLE
Ship LS as a Docker image

### ISSUE THREAD

**Issue by mickaelistria** [graphql/graphiql#890]
I'd like to evaluate integration of graphql-language-server in Eclipse IDE.
However, I'm currently kind of stuck by the complex process to get the LS installed and working, especially with the dependency to watchman and so on.
Would it be possible for the project to publish a ready to use Docker image that I could try directly without having to install things manually on my dev environment?

**Comment by Neitsch** [comment]
Hi @mickaelistria , watchman should not be a hard dependency of the LSP. GraphiQL itself is not using watchman, but is using the LSP. Could you go into more detail what kind of issues you are facing?

**Comment by mickaelistria** [comment]
I'm not going to work on GraphQL LS integration soon as far as I know, so let's close this issue.
