### ISSUE TITLE
Unknown Directives

### ISSUE THREAD

**Issue by mattblackdev** [graphql/graphiql#892]
Is there a way to point to my custom directives?

For example: 

```
"Thing.gql"

type Thing {
  secretField: String @auth(role: "admin")
  otherThings: [OtherThings] @link(to: "otherThings")
}
```

No squiggly under ```@auth```. But there is a squiggly under ```@link```. And a tooltip that says: 
```
[graphql] Unknown directive "link". (KnownDirectives)
```

**Comment by Neitsch** [comment]
Could you just append your directives to the existing schema? If not, you could set up a custom command to append the directive definition to your existing schema and write it to a new file.

**Comment by justinfagnani** [comment]
@Neitsch

> Could you just append your directives to the existing schema?

Is there some standard way to declare a directive? I don't see anything in the GraphQL docs.

**Comment by acao** [comment]
the official docs site needs to be updated to describe schema directives, however this article should describe what you’re looking for:
https://www.graphql-tools.com/docs/schema-directives/

this is all present when you `printSchema()` with your final schema. all custom scalars and directivws should be there at that point.
