### ISSUE TITLE
Support Reason apps

### ISSUE THREAD

**Issue by Gregoirevda** [graphql/graphiql#894]
We be good to have support for Reason apps: 
https://reasonml.github.io/
Autocompletion currently doesn't work, but we do have type validation: 
https://github.com/mhallin/graphql_ppx

**Comment by Neitsch** [comment]
Shouldn't be too hard to do. Basically we just have to look for the tag `[%graphql {|`. @Gregoirevda would you mind taking charge here?

**Comment by acao** [comment]
#1679 will encompass this work! Considering this a dupe despite it’s age. let’s concentrate the effort over there.

@zth has made some awesome inroads into reason support for graphql.
