### ISSUE TITLE
`kitchen-sink.graphql` should be substituted with swapi-graphql

### ISSUE THREAD

**Issue by asiandrummer** [graphql/graphiql#898]

**Comment by thomasheyenbrock** [comment]
@acao can you provide more context what this issue is about? What should be solved or changed?

**Comment by acao** [comment]
There is a test fixture file called `kitchen-sink.graphql` used by `codemirror-graphql`, the `language-service` and LSP server, which contains a reference graphql schema

This is probably more actively maintained than `swapi-graphql` at the moment, plus I don't like using an external repo for test fixtures if we can avoid it, even if it's our own repo.
