### ISSUE TITLE
Ensure we have a regression test for state.rule bug

### ISSUE THREAD

**Issue by wincent** [graphql/graphiql#899]
As mentioned here, we'll want a regression test for this one: https://github.com/graphql/codemirror-graphql/pull/112#issuecomment-278198802

**Comment by acao** [comment]
@imolorhe would you be interested in checking in on this? myself or @yoshiakis can help you get familiar with the parser

**Comment by imolorhe** [comment]
@acao okay I'll take a look. Yeah I'll likely need a primer on the parser.

**Comment by acao** [comment]
@imolorhe let me know if you'd like to hop on a discord session any time this weekend!
