### ISSUE TITLE
Error with rendering when using alongside another version of React

### ISSUE THREAD

**Issue by keithpitt** [graphql/graphiql#9]
When I include GraphiQL inside my application alongside Relay, I get the following error when trying to render the component:

```
Uncaught TypeError: Cannot read property 'firstChild' of undefined
```

I did some Googling, and it seems to suggest there may be 2 versions of React present. My `package.json` file looks like this:

```
  "dependencies": {
    "assets-webpack-plugin": "^2.2.0",
    "babel-loader": "^5.3.2",
    "babel-relay-plugin": "0.1.2",
    "babel-runtime": "^5.8.20",
    "basscss": "^7.0.3",
    "basscss-border-colors": "^1.1.1",
    "classnames": "^2.1.3",
    "css-loader": "^0.16.0",
    "cssnext-loader": "^1.0.1",
    "file-loader": "^0.8.4",
    "graphiql": "^0.1.0",
    "graphql": "^0.4.2",
    "graphql-relay": "^0.3.1",
    "react": "^0.14.0-beta3",
    "react-dom": "^0.14.0-beta3",
    "react-relay": "^0.1.1",
    "react-router": "^1.0.0-beta3",
    "relay-nested-routes": "^0.3.1",
    "style-loader": "^0.12.3",
    "url-loader": "^0.5.6",
    "webpack": "^1.11.0"
  }
```

If I go ahead and delete `rm -rf node_modules/graphiql/node_modules/react`, then rendering works a treat!

**Comment by leebyron** [comment]
Thanks for the report. I'm not entirely sure what the best fix for this is, any ideas?

**Comment by JaRail** [comment]
Sounds like an NPM semver issue. When you have

> "react": "^0.13.3"

react-0.14.0-beta3 does not satisfy that requirement. When the major version is 0, the a minor version bump is breaking. You could change your package.json to allow react 0.14.

> "react": "^0.13.3 || ^0.14.0-beta4"

**Comment by leebyron** [comment]
Great suggestion.

I made React a peer-dependency, and made that more pervasive.

**Comment by keithpitt** [comment]
Awesome, thanks!! :dancers:
