### ISSUE TITLE
"Prettify" button removes query/ mutation

### ISSUE THREAD

**Issue by BobertForever** [graphql/graphiql#90]
When you click the prettify button in the navbar, it removes "query" or "mutation" from the query. That's fine for queries, but for mutations it causes the execution to fail (since it tries the request as a query which generally doesn't work).

**Comment by asiandrummer** [comment]
That actually sounds like it's a problem with a GraphQL Parser/Printer - I'll see if I can reproduce

**Comment by BobertForever** [comment]
The smallest example I can come up with (for our schema) is:
```
query {
  viewer {
    id,
  },
}
```
When you run prettify, it removes `query`. For this, it's fine, but if it was actually a mutation, that gets removed.

**Comment by asiandrummer** [comment]
[This line from `graphql-js`] (https://github.com/graphql/graphql-js/blob/master/src/language/printer.js#L34) probably caused the printer to ignore `operation` name, thinking that it's an anonymous query. `name` should be optional.

**Comment by asiandrummer** [comment]
Following up what I found, the temporary workaround is that if you supply operation name:
```
mutation test { id, name }
```
prettifying mutation works as expected.

**Comment by BobertForever** [comment]
`name` is optional, yes. For `query`, so is the operation (as defined [in the spec](https://facebook.github.io/graphql/#sec-Language.Query-Document.Operations)). It appears as if the code from `graphql-js` assumes if it's an anonymous, it's also a query.

I can open a bug on their repo regarding the issue.

**Comment by BobertForever** [comment]
Just opened an issue there. Since you were correct in it not being an issue with graphiql, I'm going to close this issue out. Thanks @asiandrummer!

**Comment by asiandrummer** [comment]
@BobertForever no worries, thanks for the quick response in this!

**Comment by BobertForever** [comment]
Thanks for finding what was actually broken! I probably should have dug into it a little more before opening an issue :wink:. Thanks again!
