### ISSUE TITLE
GraphQL language server - VSCode integration

### ISSUE THREAD

**Issue by asiandrummer** [graphql/graphiql#900]
@kumarharsh - I'm going to work on #6, and with that I'd love to talk about integrating this language server with [your existing `graphql-for-vscode` library](https://github.com/kumarharsh/graphql-for-vscode)!

I think you've already put in a lot of effort into supporting GraphQL in VSCode, and I'd love to contribute to your repo and/or collaborate together by hooking up this language server if you're okay with it. I've already started [some work by exporting the Atom syntax highlighter into .plist file](https://gist.github.com/asiandrummer/381aa4d45045e4cd975973b9afbd6cda).

Let me know what you think please!

**Comment by ganemone** [comment]
I recently made changes to https://github.com/prisma/vscode-graphql which add total support for lsp in both js and graphql files.

**Comment by kumarharsh** [comment]
We've also spun off the language server part from `@playlyfe/gql` to https://github.com/Mayank1791989/gql-language-server

**Comment by acao** [comment]
we are about to come out with our own official vscode graphql extension that provides a spec compliant implementation for other extensions to implement.

**Comment by acao** [comment]
revision to earlier announcement: we will have an example vscode plugin, that implements the LSP and shows off the features, no more than a few hundred lines for both server/client at most.

also i've updated our entry on langserver.org. we are doing pretty great. going to open a new ticket for bumping the vscode-languageserver version, and some more GH projects to finish off some other LSP features.
