### ISSUE TITLE
Example setup documentation regression

### ISSUE THREAD

**Issue by shunter55** [graphql/graphiql#901]
When I try to run the example I get stuck on a `Loading..` screen with error: 
```
Refused to apply style from 'http://localhost:49909/graphiql.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
Failed to load resource: the server responded with a status of 404 (Not Found)
```

Here are the commands I ran:
```
graphiql:
	npm install
	yarn install
	npm build
graphiql/packages/graphiql:
	npm install
	npm run build
graphiql/packages/graphiql/example:
	npm install
	npm start
```

**Comment by shunter55** [comment]
Setup script didn't run in `example`. `"setup": "cp ../graphiql.js ../graphiql.css ."`

**Comment by acao** [comment]
this one is my bad, i didn't update the docs for this. changed it for the netlify deployment.

im going to reopen to ensure i update the docs. thanks for reporting this
