### ISSUE TITLE
Prettify Query shortcut (Shift-Ctrl-P) non-functional for Firefox users

### ISSUE THREAD

**Issue by justinclift** [graphql/graphiql#905]
Trying GraphiQL for the first time, the default message has a helpful line:

```
Prettify Query:  Shift-Ctrl-P (or press the prettify button above)
```

Unfortunately, at least with Firefox that won't work, as Firefox has a hard coded key binding for "Shift-Ctrl-P".  Instead it just brings up a Private Browsing window, and the key combination doesn't make it through to the GraphiQL window:

![FF1](https://user-images.githubusercontent.com/406299/60685700-e483fd00-9ee7-11e9-9117-570285b92baf.png)

Firefox doesn't natively have any ability to change key bindings either (ugh).  There is a "Saka Key" extension which can apparently allow for key binding changes, but that seems pretty non-optimal.

Is there a way to change the GraphiQL key binding instead?

**Comment by benjie** [comment]
Currently this isn't easily customisable:

https://github.com/graphql/graphiql/blob/3537316fac65e9710ae00d38cae50ff6d75bd7f6/packages/graphiql/src/components/QueryEditor.js#L139-L143

Do you have a recommendation for an alternate keybinding that'd work well in firefox and relates to "prettify"?

**Comment by justinclift** [comment]
Hmmm.  All of the letters in Prettify already have existing key bindings in Firefox.  It may need to be something non-obvious instead. :man_shrugging:

**Comment by benjie** [comment]
What do you suggest?

**Comment by justinclift** [comment]
Both <kbd>Shift</kbd>-<kbd>Ctrl</kbd>-<kbd>V</kbd>, and <kbd>Shift</kbd>-<kbd>Ctrl</kbd>-<kbd>B</kbd> seem available.  Either of those should be ok.  Probably the B one then, just coz? :smile:

**Comment by benjie** [comment]
`B` for `beautify` seems like a good solution :+1:

**Comment by justinclift** [comment]
Sounds good to me. :smile:

**Comment by benjie** [comment]
Once https://github.com/graphql/graphiql/pull/759 is merged, adding this should be as easy as adding a line to this file:

https://github.com/graphql/graphiql/blob/aa82f547b61c8aa40aa4467613456580dd556e95/packages/graphiql/src/utility/commonKeys.js#L8

**Comment by benjie** [comment]
#759 is merged

**Comment by nasehim7** [comment]
@benjie Hi can we directly change the binding like from this:
'Shift-Ctrl-P': () => { 
   if (this.props.onPrettifyQuery) { 
     this.props.onPrettifyQuery(); 
   } 
 }
to
'Shift-Ctrl-B': () => { 
   if (this.props.onPrettifyQuery) { 
     this.props.onPrettifyQuery(); 
   } 
 }

**Comment by benjie** [comment]
Yes; rather than changing we should add the new binding in addition to the old. 👍 Thanks!

**Comment by nasehim7** [comment]
I understand, thanks for the heads up on this benjie :)

**Comment by acao** [comment]
in vscode/monaco(for the new graphiql) it will be by default:
`shift + alt/option + F` (for Format)

**Comment by benjie** [comment]
Let’s go with that then, if it works in Firefox. Can you confirm, @nasehim7?

**Comment by homersimpsons** [comment]
I think this have been wrongly closed....

[Current GraphiQL](https://graphql.org/swapi-graphql) seems to have the exact same shortcut. Furthermore the [commit fdf98ba](https://github.com/graphql/graphiql/commit/fdf98ba2cabc140f2c52b7da6b36e53c4c1b154f) did set <kbd>Shift</kbd>-<kbd>Ctrl</kbd>-<kbd>F</kbd> which seems to be overriden ([search: <kbd>Shift</kbd>-<kbd>Ctrl</kbd>-<kbd>P</kbd>](https://github.com/graphql/graphiql/search?q=Shift-Ctrl-P&unscoped_q=Shift-Ctrl-P) vs [search: <kbd>Shift</kbd>-<kbd>Ctrl</kbd>-<kbd>F</kbd>](https://github.com/graphql/graphiql/search?q=Shift-Ctrl-F&unscoped_q=Shift-Ctrl-F)).

To me <kbd>Shift</kbd>-<kbd>Ctrl</kbd>-<kbd>F</kbd> seems to close to <kbd>Ctrl</kbd>-<kbd>F</kbd> (search), I was ok with the <kbd>Shift</kbd>-<kbd>Ctrl</kbd>-<kbd>B</kbd> shortcut an rename to `Beautify` (<kbd>Ctrl</kbd>-<kbd>B</kbd> is a shortcut for bookmarks).

As a side note this bug might also affect older version of Edge (as this one had the same shortcut <kbd>Shift</kbd>-<kbd>Ctrl</kbd>-<kbd>P</kbd>). Newer versions, based on chromium, have the <kbd>Shift</kbd>-<kbd>Ctrl</kbd>-<kbd>N</kbd> shortcut.
