### ISSUE TITLE
Add vim mode

### ISSUE THREAD

**Issue by nikitavoloboev** [graphql/graphiql#910]
It would be nice if you can run some simplified version of vim inside the editor. Specifically I wish I could do `di{` to delete inside `{}` brackets. But some other vim features would be very nice to have too.

Perhaps [neovim](https://neovim.io) could be embedded to serve this purpose.

**Comment by Neitsch** [comment]
Going to close this in favor of #909

**Comment by nikitavoloboev** [comment]
Oops, I thought I searched the thread before adding. My bad.

**Comment by Neitsch** [comment]
@nikitavoloboev - I think you just double posted for some reason :)
