### ISSUE TITLE
GraphiQL browser underlines nested lists in a query, but the query still works

### ISSUE THREAD

**Issue by KontosTwo** [graphql/graphiql#914]
The schema is:
Organization has many Projects
Projects each has many Users
Here is the GraphQL schema:
```graphql
schema {
  query: QueryType
}

directive @fetch(from : String!) on FIELD_DEFINITION

type QueryType {
  hello: String
  organization(id: ID!): Organization
}

type Organization {
  id: ID! @fetch(from: "idString")
  name: String
  projects: [Project!]!
}

type Project {
  id: ID! @fetch(from: "idString")
  name: String!
  users: [User!]!
}

type User {
  id: ID! @fetch(from: "idString")
  name: String!
}
```
Here is the query:
```graphql
{
  organization(id:"5ceec32b25414b03dd85aacb"){
    name
    id
    projects{
      name
      id
      users{
        name
        id
      }
    }
  }
  hello
}
```
This shows up in the GraphiQL browser when the query is attempted on the schema
[link](https://imgur.com/Eut6C3o) 

The query still executes fine, it's just that the red underline is confusing. Autocomplete does not work either.

**Comment by acao** [comment]
can you see if this is an issue in other editors, like playground or insomnia? i think this is a bug with the editor mode

**Comment by benjie** [comment]
Further, @KontosTwo, can you show what the error is when you hover over the red underline? (Another screenshot is preferred.)

Normally I find this is an issue where the GraphiQL component has been fed an out of date schema, or has not been reloaded after changing the GraphQL schema.
