### ISSUE TITLE
[RFC][LSP] Pluggable schema loading

### ISSUE THREAD

**Issue by Neitsch** [graphql/graphiql#915]
Hi all,

Here at FB we have some schema extensions that live in a separate file and are applied during the build. While this is not particularly relevant for GraphiQL, we really want to have this as part of the LSP. Therefore I propose the following:
* In the configuration of the LSP (`.graphqlrc`), the user can specify the following:
  * (required) a package that provides two functions: `async init()` and `async getSchema()`. The latter returns the latest GraphQLSchema. Hopefully this can work in a similar way to babel plugins or webpack loaders.
  * (optional) arguments that are provided to the `init` function, before the `getSchema` function is called for the first time.
  * (optional) a glob relative to the `.graphqlrc` that triggers the schema to be reloaded on file change.

With this, I believe we can provide a very flexible schema loading experience. The first schema loaders we implement should probably be: a file schema loader to provide the current LSP experience and an introspection query schema loader to make it work with GraphiQL.

**Comment by acao** [comment]
I love the sound of all of this. Moving the introspection query schema loader down to the LSP sounds excellent, and is similar to how `vscode-json-languageservice` loads JSONSchema definitions in a pluggable fashion.

**Comment by acao** [comment]
Also, I wouldn't rule out alternative schema loading patterns, even alternative protocols being more readily supported for graphiql-1.0.0-alpha. for example, using wss to locally (or over the wire?) transmit json-rpc from a language server.
https://github.com/TypeFox/monaco-languageclient/blob/master/example/src/client.ts

**Comment by acao** [comment]
The interface that the typescript language service uses for adding LSP plugins is interesting, and is designed to work in browsers, vscode, monaco, etc
https://github.com/microsoft/TypeScript/wiki/Writing-a-Language-Service-Plugin

We could do something similar with `-interface`, or possibly a layer on top of it designed for greater parity with existing vscode-<language>-languageservice implementations

**Comment by acao** [comment]
@Neitsch there are two ways we can go about this for graphiql - we can do something provisional, where GraphiQL has a prop for this and we can do that very soon, but then we would have to migrate to the new monaco implementation, ideally keeping parity from the GraphiQL side of things. the other would be of course just waiting for the new monaco implementation, which means defining the loader in the LS itself, as with monaco-vscode.

**Comment by acao** [comment]
we have a way to do this with `graphql-config@3` now, using commonjs for sync operations at least. that said, its very flexible, and by specifying a URL with a `.graphql` extension it will just do a get instead of an introspection request. with a remote `.json` extension it will detect whether its document node or introspection.
if you still find that schema loader restrictive, we are thinking of rolling our own schema loader. the language server also allows specifying custom extensions for, amongst other things, overriding the schema loaders
