### ISSUE TITLE
Can't set endpoint in graphiql

### ISSUE THREAD

**Issue by krux02** [graphql/graphiql#925]
Hello. I am completely new to GraphQL. I just saw this [video here](https://www.youtube.com/watch?v=broQmxQAMjM&t=695s) where GraphiQL is shown. I found the link to get GraphiQL running, but anything above the horizontal gray bar (with the play button and the Docs button) was completely missing. I could not specify the endpoint at all. I would like to do what is shown in the video, but I can't set the endpoint and therefore all queries that I type are pointless.

And yea, docs also seem to not work.

**Comment by acao** [comment]
Hey there!

So if you look at the Readme, there is an example where you can learn how to pass a custom fetch instance to React for adopting your particular http patterns, including endpoint. The new major version of GraphiQL will allow you to customize it in the UI. By default, it makes POST requests against the same origin, or can be custom implemented using various express middlewares. Or you can use webpack and the component and customize it.

**Comment by krux02** [comment]
I don't really get what you are talking about. I am not a javascript developer. I don't do anything with React. I try to develop a terminal application that happens to use a web API. And I thought I could use GraphiQL as an online Editor to play with some queries before I embed them in my program.

**Comment by orta** [comment]
It sounds like you want something like the GraphiQL app which wraps GraphiQL and adds a location: https://github.com/skevy/graphiql-app#graphiqlapp

**Comment by krux02** [comment]
Well, I figured out for me that GraphiQL isn't something I want to deal with. Thanks for the help.
