### ISSUE TITLE
Publish a new release of graphiql

### ISSUE THREAD

**Issue by jdehaan** [graphql/graphiql#933]
There are a few interesting commits that fix annoying problems in our case. Notably https://github.com/graphql/graphiql/commit/ca226ee6e299f253364b9e66c723c1edff620246, that makes graphiql behave well if integrated within other react components that appear/disappear.

Personally I consider it worth a release. Looking forward to getting the next package :-)

Best regards.

**Comment by acao** [comment]
@jdehaan there's one more fix we are about to merge for this release. the most belabouring part about releasing is summarizing everything. we need to release the GLS ecosystem first as ita been a year, and the new graphiql already depends on them in master. So it might be a week or two but hopefully soon

**Comment by ganemone** [comment]
@acao I think there is the option to publish an alpha release without the full changelog and release notes to unblock a bunch of people.

**Comment by acao** [comment]
@ganemone for sure! just wanted to get this right since its the first release from the monorepo

**Comment by acao** [comment]
see: GraphQL 0.14.0. You'll now need regenerator runtime now because graphql-language-service-interface 2.0.0 added async/await. Same for codemirror-graphql in general.
