### ISSUE TITLE
schema not showing - aspnet core

### ISSUE THREAD

**Issue by nmarun** [graphql/graphiql#939]
I have my repo at https://github.com/nmarun/customergraph. When I run the application, I don't see any schemas in the document explorer. Instead I get an error message:

{"errors":[{"message":"GraphQL.ExecutionError: A query is required. ---> GraphQL.ExecutionError: A query is required.\r\n   at GraphQL.DocumentExecuter.ValidateOptions(ExecutionOptions options)\r\n   at GraphQL.DocumentExecuter.ExecuteAsync(ExecutionOptions options)\r\n   --- End of inner exception stack trace ---","extensions":{"code":"EXECUTION_ERROR"}}]}

![image](https://user-images.githubusercontent.com/5554175/63134179-f6c48100-bfe5-11e9-914a-d1498603845c.png)

Interestingly, the calls through Postman are working when I hit the http://localhost:54068/graphql/ endpoint.

My Startup.cs looks as below:

```
using CustomerGraph.Models.Schema;
using CustomerGraph.Models.Services;
using GraphiQl;
using GraphQL;
using GraphQL.Server;
using GraphQL.Types;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;

namespace CustomerGraph
{
    public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_2);
            services.AddScoped<IDocumentExecuter, DocumentExecuter>();
            services.AddSingleton<ICustomerService, CustomerService>();
            services.AddSingleton<CustomerType>();
            services.AddSingleton<CustomersQuery>();
            services.AddSingleton<CustomerSchema>();
            services.AddSingleton<IDependencyResolver>(
                c => new FuncDependencyResolver(type => c.GetRequiredService(type)));

            services.AddGraphQL(_ =>
            {
                _.EnableMetrics = true;
                _.ExposeExceptions = true;
            });

            var sp = services.BuildServiceProvider();
            services.AddSingleton<ISchema>(new CustomerSchema(new FuncDependencyResolver(type => sp.GetService(type))));

        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
                app.UseHsts();
            }
            app.UseGraphQL<ISchema>("/graphql");
            app.UseGraphQLWebSockets<CustomerSchema>("/graphql");
            app.UseWebSockets();
            app.UseGraphiQl("/graphql");
            app.UseHttpsRedirection();
            app.UseMvc();
        }
    }
}
```
Please assist.
Thanks,
Arun

**Comment by benjie** [comment]
Hi; please change this line:

```
            app.UseGraphiQl("/graphql");
```

to this:

```
            app.UseGraphiQl("/graphiql");
```

And then open the interface at `/graphiql` instead of `/graphql`

If this works then you'll need to figure out how to share the `/graphql` endpoint between GraphQL and GraphiQL - it seems at the moment that `UseGraphQL` is consuming all of the incoming requests for that endpoint, and thus `UseGraphiQl` is never being called. If you put `UseGraphiQl` before `UseGraphQL` then it might work, but I'm not an ASPNet developer so I can't tell you.

I'm going to close this issue because it's not directly related to this project - if you need more help you should open it with the ASPNet GraphQL/GraphiQL modules instead.
