### ISSUE TITLE
Examples links are broken

### ISSUE THREAD

**Issue by cmcarey** [graphql/graphiql#952]
On this page - https://github.com/graphql/graphiql/tree/master/packages/graphiql#getting-started

Just before the beginning of the features section, there are example links to here: https://github.com/graphql/graphiql/blob/master/packages/graphiql/example

That link is broken.

**Comment by popadi** [comment]
@cmcarey 
According to [this](https://github.com/graphql/graphiql/commit/07fc6fee2780cb65668c1ca6b03688cdb82fcf44) commit, apparently the files from `graphiql/example` were moved to `packages/graphiql-examples/cdn/` but the README.md still points to the old files. You can check there if you still need some examples to work with. I'll make an pull-request with this change soon :)
