### ISSUE TITLE
Support of the Headers

### ISSUE THREAD

**Issue by vangavroche** [graphql/graphiql#96]
Is any plan to support header setting in the GraphiQL?

**Comment by asiandrummer** [comment]
Hey @vangavroche, I'm not sure I follow - could you elaborate a bit more?
Do you mean the app header (Toolbar), or http headers?

**Comment by vangavroche** [comment]
What I mean is the http headers :）

It will be good if we can specify the headers as easy as we now specify the query variables in the GraphiQL .

**Comment by asiandrummer** [comment]
Thanks for the clarification @vangavroche! So #59 talked about this a while back - I also think it'll be good to leave GraphiQL independent to the network configuration, and let the GraphQL server deal with the network configuration part. @leebyron provides an example:
> I suggest taking a look at the [example] (https://github.com/graphql/graphiql/blob/master/example/index.html) - where you see graphQLFetcher is where you can configure your network fetching however you like, in your case by including any authentication details that may be necessary.

Hope this helps.

**Comment by vangavroche** [comment]
Got it. Thanks.

**Comment by eugenehp** [comment]
@vangavroche Weihong, it would be interesting to get your opinion on this https://github.com/graphql/express-graphql/issues/101

**Comment by Durisvk** [comment]
@vangavroche @eugenehp 

Hello I've implemented the feature you've requested

Here are the links to the library files:
https://cdn.jsdelivr.net/npm/graphiql-custom-headers@1.0.0/graphiql-custom-headers.css
https://cdn.jsdelivr.net/npm/graphiql-custom-headers@1.0.0/graphiql-custom-headers.js
https://cdn.jsdelivr.net/npm/graphiql-custom-headers@1.0.0/graphiql-custom-headers.min.js

Here is a simple example of how to use it:
https://github.com/Durisvk/graphiql

It's really simple, you don't have to do almost any changes to your current running app.

And it's also available on NPM: https://www.npmjs.com/package/graphiql-custom-headers

This is how it looks like: http://imgur.com/a/3VQDT

I've also implemented it already to my project: https://github.com/Durisvk/senegraph
so it's already available on HapiJS servers. Somewhere in the future I would like to implement it also on Express. Maybe you could help me out with this.

Hopefully you'll like my solution @MarkAndrewJohnson  ...

**Comment by imolorhe** [comment]
https://github.com/imolorhe/altair

**Comment by karanaug88** [comment]
thanks @imolorhe 

This was one of the solutions i was looking for me and also works across all platforms....

https://github.com/imolorhe/altair
