### ISSUE TITLE
Permalinks (share URL link)?

### ISSUE THREAD

**Issue by borekb** [graphql/graphiql#961]
According to #7, queries in URL are a feature of GraphiQL and I've seen them in the wild, for example, in the [Pokemon API](https://graphql-pokemon.now.sh/?query=%7B%0A%20%20pokemon(name%3A%20%22Pikachu%22)%20%7B%0A%20%20%20%20id%0A%20%20%7D%0A%7D). But I've also encountered several GraphiQL installations that don't have queries in URLs, e.g., [Shopify's](https://help.shopify.com/en/api/storefront-graphiql), [MongoDB todo list](https://todo-mongo-graphql-server.herokuapp.com/), etc.

In https://github.com/graphql/graphiql/issues/703, it is mentioned that it's supported via graphiql-rails but is that the only way?

I'm just asking for clarification. On the APIs that support the `?query=` URL links, I find it a bit suspicious that it's `?` and not `#` (I'd imagine queries working purely client-side).

**Comment by benjie** [comment]
Hi @borekb, yes you can do this with GraphiQL. This example shows you how:

https://github.com/graphql/graphiql/blob/master/packages/graphiql-examples/cdn/index.html#L48-L55

(The location of this example file moved when we turned this repo into a monorepo.)

Hope this helps!

(I'm assuming that the `?query=` enables server-side rendering of GraphiQL, but I may be wrong on that.)

**Comment by borekb** [comment]
Thanks, @benjie!

**Comment by gilesbradshaw** [comment]
@benjie that link 404's dunno if you could possibly edit?

**Comment by acao** [comment]
@gilesbradshaw we moved the examples around.

You’ll find an example of how to do this in `packages/graphiql/resources/renderGraphiQL.js`

**Comment by benjie** [comment]
I've updated my comment above to a link equivalent to what was there before (but permanent). Rikki's example is better; but it has also moved; it's now (permalink) here:

https://github.com/graphql/graphiql/blob/bcb27538d9074afdac3ff56074046965b456e57a/packages/graphiql/resources/renderExample.js

**Comment by benjie** [comment]
Whoops sorry!
