### ISSUE TITLE
License for @apollographql/graphql-language-service-interface

### ISSUE THREAD

**Issue by OliverCole** [graphql/graphiql#963]
It seems like some packages and repos got moved around. Is [@apollographql/graphql-language-service-interface](https://www.npmjs.com/package/@apollographql/graphql-language-service-interface) published from this repo?

If so, can we please publish the latest version for `interface`, `parser`, `types` and `utils`, as these all contain valid licenses, but [2.0.2](https://www.npmjs.com/package/@apollographql/graphql-language-service-interface/v/2.0.2) does not.

If not, can you direct me to the right repo?

**Comment by benjie** [comment]
Hi @OliverCole; you seem to be asking about a fork of `graphql-language-server-interface`. I'm afraid we do not control that package - you'll have to ask the folks over at @apollographql about that. It seems the repository no longer exists: https://github.com/apollographql/graphql-language-service

You can use the official packages directly if you prefer, for example: [graphql-language-server-interface](https://www.npmjs.com/package/graphql-language-service-interface)
