### ISSUE TITLE
Results panel can be made inaccessible through resizing

### ISSUE THREAD

**Issue by FidelVe** [graphql/graphiql#969]
Playing around in graphiql today I hid the result frame to make some more room for the text editor window and then couldn't find a way to bring it back, this video can show what am talking about:

https://gfycat.com/playfulalarmedbird

As you can see, if you resize the result "frame" minimizing it all the way to the right, if you try to drag it back you will resize the entire browser window, there's also no button or other intuitive way of bringing the frame back, clicking on "run" should automatically bring the results frame back, or maybe adding a button to the top bar.

the only way to bring it back is by double-clicking inside the text editor frame, which is not very intuitive.

**Comment by benjie** [comment]
I've renamed this issue because I don't agree with using a button to solve the issue, but I agree it's an issue.

I think the solution is to ensure that the resize bar for the result frame is always visible, perhaps by using `flex-basis` or `min-width` if appropriate, or perhaps by tweaking the JS layout logic.

I think achieving it should be _fairly_ straight forward so I've added the "good first issue" label; if someone wanted to take a look at doing this, let us know and we can give some pointers :+1:

**Comment by FidelVe** [comment]
@benjie If it's no problem with you, I can do it. I haven't looked at the source code for graphiql yet, so any pointers would be appreciated.

**Comment by benjie** [comment]
Of course!

The size of the editor panel is controlled by the `editorFlex` value on state:

https://github.com/graphql/graphiql/blob/2da818b1f4e7adb1f1e519e314a428e846dc257e/packages/graphiql/src/components/GraphiQL.js#L913

Which is then used as the `flex-grow` value via shorthand `flex` syntax for the CSS of the editor:

https://github.com/graphql/graphiql/blob/2da818b1f4e7adb1f1e519e314a428e846dc257e/packages/graphiql/src/components/GraphiQL.js#L307

Since this is all flexbox; I think we can fix it by making the `resultWrap` have a non-zero `flex-basis` here:

https://github.com/graphql/graphiql/blob/73a3f9016124dfae6b327ca3a0c9946eaf12638e/packages/graphiql/css/app.css#L117-L123

e.g.

![Screenshot_20191007_182806](https://user-images.githubusercontent.com/129910/66334195-73157980-e930-11e9-9813-7b2b751345ca.png)

**Comment by FidelVe** [comment]
Well you basically did all the work there 😅. Either way I could make a PR, implement the changes and check if nothing else break. I'll have it done by the end of the day.

**Comment by benjie** [comment]
I didn't test it to see if I could break it; I've also not figured out why the number is 13px (not having a "magic number" would be a good idea!), so I think there's still a few things for you to figure out :wink: 

Looking forward to your PR :smile:

**Comment by FidelVe** [comment]
Hi! @benjie 

sorry to bother you, am having some errors trying to build graphiql for testing and fixing the bug, maybe am doing something wrong, this is what I did.
* forked the `graphql/graphiql` repo.
* `git clone` of my fork to my machine. and `cd` to my local `graphiql` folder.
*  run `yarn`
* run `yarn build` and got this result
```javasacript
yarn run v1.17.3
$ tsc --build && lerna run build --scope codemirror-graphql --scope graphiql --scope graphql-language-service --scope graphql-language-service-server
lerna notice cli v3.16.4
lerna info versioning independent
lerna info filter [ 'codemirror-graphql',
lerna info filter   'graphiql',
lerna info filter   'graphql-language-service',
lerna info filter   'graphql-language-service-server' ]
lerna info Executing command in 4 packages: "yarn run build"
00h00m00s 0/0: : lerna ERR! yarn run build exited 1 in 'codemirror-graphql'
lerna ERR! yarn run build stderr:
ERROR: [Errno 2] No such file or directory: 'run'

lerna ERR! yarn run build exited 1 in 'codemirror-graphql'
lerna WARN complete Waiting for 1 child process to exit. CTRL-C to exit immediately.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Even though I got that error I then `cd` to `packages/graphiql` and run `yarn dev` to see if the dev server could still run and got this error.

```javascript
yarn run v1.17.3
$ babel-node test/server.js
Initial build...
Error building graphiql.js
{ Error: Cannot find module 'codemirror-graphql/lint' from '/media/fidel/data/Projects/graphiql/packages/graphiql/src/components'
    at /media/fidel/data/Projects/graphiql/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:17
    at process (/media/fidel/data/Projects/graphiql/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (/media/fidel/data/Projects/graphiql/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (/media/fidel/data/Projects/graphiql/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/media/fidel/data/Projects/graphiql/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /media/fidel/data/Projects/graphiql/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:154:21)
```

I know I might be doing something wrong, do you guys have a doc explaining how to setup the dev server for new developers like myself?

**Comment by benjie** [comment]
> do you guys have a doc explaining how to setup the dev server for new developers like myself?

That's one of my tasks. I'm slowly working towards it.

> run yarn build and got this result

I just tested and yarn build works on a clean checkout for me. Couple questions:

What OS are you on?

What shell (bash, zsh, fish, git-bash, etc) are you using?

**Comment by FidelVe** [comment]
Hi @benjie thanks for replying.

```shell
System:
    OS: Linux 5.0 Ubuntu 19.04 (Disco Dingo)
    CPU: (4) x64 Intel(R) Core(TM) i3-8145U CPU @ 2.10GHz
    Shell: 5.0.3 - /bin/bash
  Binaries:
    Node: 10.15.2 - /usr/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.11.3 - /usr/local/bin/npm
```

**Comment by benjie** [comment]
@FidelVe I'm on Ubuntu and bash too and it works for me. The error you're getting is bizarre - something about `ERROR: [Errno 2] No such file or directory: 'run'` from the `yarn run build` command... It shouldn't be trying to access a file called `run`; `run` is a yarn subcommand! I've no idea what's going on. Are you able to narrow it down by stepping through the `package.json` commands and running them each individually at all? (You may need to reconfigure your `$PATH` to add the relevant `node_modules/.bin` folder.)

**Comment by FidelVe** [comment]
Clearly there's something wrong with `yarn` on my machine, I have reproduced the bug a couple of times on my machine by doing this:

- forked [https://github.com/graphql/graphiql](https://github.com/graphql/graphiql) project.

- `git clone` my fork of the project.

- on root folder, run `yarn` (no errors). Then running `yarn build` throws the following error:

```bash
yarn run v1.19.1
$ tsc --build && lerna run build --scope codemirror-graphql --scope graphiql --scope graphql-language-service --scope graphql-language-service-server
lerna notice cli v3.16.4
lerna info versioning independent
lerna info filter [ 'codemirror-graphql',
lerna info filter   'graphiql',
lerna info filter   'graphql-language-service',
lerna info filter   'graphql-language-service-server' ]
lerna info Executing command in 4 packages: "yarn run build"
00h00m00s 0/0: : lerna ERR! yarn run build exited 1 in 'codemirror-graphql'
lerna ERR! yarn run build stderr:
ERROR: [Errno 2] No such file or directory: 'run'

lerna ERR! yarn run build exited 1 in 'codemirror-graphql'
lerna WARN complete Waiting for 1 child process to exit. CTRL-C to exit immediately.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

As you can see am already running the latest `yarn` version.

I wasn't able to solve it but I manage to find a way to work around it and run the `dev` server. Heres a step by step of what I did.

- edited `lerna.json` and changed the `npmClient: "yarn"` entry for `npmClient: "npm"`.

- changed the entry `build: "yarn run build-js && yarn run build-flow"` for `build: "npm run build-js && npm run build-flow"` on the files `packages/graphql-language-service-server/package.json` `packages/graphiql/package.json` `packages/graphql-language-service/package.json`.

- ran `npm run build` on the root folder with the following results

```bash
> @ build /media/fidel/data/Projects/graphiql2/graphiql
> tsc --build && lerna run build --scope codemirror-graphql --scope graphiql --scope graphql-language-service --scope graphql-language-service-server

lerna notice cli v3.16.4
lerna info versioning independent
lerna info filter [ 'codemirror-graphql',
lerna info filter   'graphiql',
lerna info filter   'graphql-language-service',
lerna info filter   'graphql-language-service-server' ]
lerna info Executing command in 4 packages: "npm run build"
lerna info run Ran npm script 'build' in 'codemirror-graphql' in 3.6s:

> codemirror-graphql@0.11.1 build /media/fidel/data/Projects/graphiql2/graphiql/packages/codemirror-graphql
> babel src --root-mode upward --ignore __tests__ --out-dir .

Successfully compiled 27 files with Babel.
lerna info run Ran npm script 'build' in 'graphql-language-service-server' in 6.9s:

> graphql-language-service-server@2.3.0 build /media/fidel/data/Projects/graphiql2/graphiql/packages/graphql-language-service-server
> npm run build-js && npm run build-flow


> graphql-language-service-server@2.3.0 build-js /media/fidel/data/Projects/graphiql2/graphiql/packages/graphql-language-service-server
> node ../../resources/buildJs.js

Successfully compiled 9 files with Babel.

> graphql-language-service-server@2.3.0 build-flow /media/fidel/data/Projects/graphiql2/graphiql/packages/graphql-language-service-server
> node ../../resources/buildFlow.js

lerna info run Ran npm script 'build' in 'graphql-language-service' in 6.0s:

> graphql-language-service@2.3.0 build /media/fidel/data/Projects/graphiql2/graphiql/packages/graphql-language-service
> npm run build-js && npm run build-flow


> graphql-language-service@2.3.0 build-js /media/fidel/data/Projects/graphiql2/graphiql/packages/graphql-language-service
> node ../../resources/buildJs.js

Successfully compiled 2 files with Babel.

> graphql-language-service@2.3.0 build-flow /media/fidel/data/Projects/graphiql2/graphiql/packages/graphql-language-service
> node ../../resources/buildFlow.js

lerna info run Ran npm script 'build' in 'graphiql' in 13.4s:

> graphiql@0.15.1 build /media/fidel/data/Projects/graphiql2/graphiql/packages/graphiql
> npm run build-js && npm run build-flow


> graphiql@0.15.1 build-js /media/fidel/data/Projects/graphiql2/graphiql/packages/graphiql
> bash ./resources/build.sh

Successfully compiled 47 files with Babel.
Bundling graphiql.js...
Bundling graphiql.min.js...
Bundling graphiql.css...
Done

> graphiql@0.15.1 build-flow /media/fidel/data/Projects/graphiql2/graphiql/packages/graphiql
> node ../../resources/buildFlow.js

lerna success run Ran npm script 'build' in 4 packages in 17.0s:
lerna success - codemirror-graphql
lerna success - graphiql
lerna success - graphql-language-service-server
lerna success - graphql-language-service
```

At this moment I was able to at least successfully build the project, the next thing I did was `cd` into `packages/graphiql/` and run `npm run dev`, but the console throw the following error:

```bash
> graphiql@0.15.1 dev /media/fidel/data/Projects/graphiql2/graphiql/packages/graphiql
> babel-node test/server.js

sh: 1: babel-node: not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! graphiql@0.15.1 dev: `babel-node test/server.js`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the graphiql@0.15.1 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

ran `npm install` successfully and tried `npm run dev` again but it showed me the same error, at this moment I realized that the _yarn workspaces_ declared in the **package.json** in the root folder are not compatible with `npm` and because of this `babel` doesn't exists in the `node_modules` folder inside `packages/graphiql/`.

From inside `packages/graphiql/` I installed the following packages:

```bash
npm install @babel/cli @babel/core @babel/node @babel/plugin-proposal-class-properties @babel/plugin-transform-runtime @babel/polyfill @babel/preset-env @babel/preset-flow @babel/preset-react @babel/register --save-dev
```

Now finally I was able to run the `dev server` from inside **graphiql**

```bash
graphiql$ npm run dev

> graphiql@0.15.1 dev /media/fidel/data/Projects/graphiql2/graphiql/packages/graphiql
> babel-node test/server.js

Initial build...
graphiql.js: 1874247 bytes written (6.77 seconds)
Started on http://localhost:41985/
```

This is a weird bug, clearly, there's something wrong with `yarn` on my machine, I hope this info is helpful for anyone going through the same or anyone that is able to identify the main reason of the bug and find a better more easy solution.

Now that I can run the dev server, I'm going to take the day off and tomorrow work on the main bug for this open issue :laughing:

**Comment by benjie** [comment]
Thanks for the detailed reply @FidelVe. I'm none the wiser, but it may help others more familiar with the subject. (Though we rely on yarn workspaces for the monorepo you *might* be able to get `lerna` to do the equivalent using npm - something like `lerna bootstrap` IIRC.)

**Comment by StanLindsey** [comment]
I've had success with running `lerna bootstrap && lerna link convert` on a lerna project when we had some iffy packages.

**Comment by FidelVe** [comment]
Well the important thing is that I was able to run the server and fix the issue :smile:
