### ISSUE TITLE
Automatically navigate to current type in DocExplorer

### ISSUE THREAD

**Issue by opatut** [graphql/graphiql#97]
I'd love to enable automatic documentation, so when I navigate within the query code, i.e. move the cursor in various places, the corresponding type is openend in DocExplorer. 

Could be enabled/disabled by some toggle/checkbox at the bottom of the DocExplorer panel...

**Comment by asiandrummer** [comment]
@opatut There's already a similar feature in typeahead - when you open up a typeahead, the bottom description box should contain a link to the page that has the corresponding type information. Would that suffice for you?

P.S. I do see a couple of typeahead states without the doc page link (e.g. VariableDeclaration and TypeCondition), and this shall be fixed soon.

**Comment by opatut** [comment]
While that feature is definitely useful, it's just not quite right for me. First, I have to move to the mouse to click that link to find out more about that type, and then it does not work quite well with the mouse (i.e. when moving the mouse down towards the Link, I hover over other typeahead elements, activating them, and my Link disappears -- also when clicking the link weird stuff happens to my focus and I cannot continue typing).

But that link gave me a different idea: instead of automatically updating the DocExplorer view when navigating, we could add Ctrl+Click (Cmd+Click ?) on Symbol names in the query input as action to open the corresponding type's docs. This would be similar to Eclipse's "Open declaration". We could then also add a shortcut to trigger this action for the item under the cursor (I think it's F3 in Eclipse, but I'm not sure).

That'd be less magic and less navigation between docs while simply typing your query. Also, probably better performance.

**Comment by asiandrummer** [comment]
I can see how losing focus from the editor can cause pain. I think I'm growing on the idea.

Another shortcut makes sense - I'm not sure how a custom click action should play out, but it'd be a good workflow to treat doc explorer as a reference, which is exactly one of the purposes it should serve.

**Comment by leebyron** [comment]
I really like this idea, @opatut! I think an "open declaration" feature would be great and agree that cmd-click is probably the right place to start with implementing this. 

A keyboard shortcut to do the same for whatever is under your cursor is also a great idea.
