### ISSUE TITLE
Feature request: Execute specific query or mutation

### ISSUE THREAD

**Issue by tanhenggek** [graphql/graphiql#975]
graphiql currently execute all queries or mutations in the editor. We have to comment it if we want to exclude it from execution. The would be a great feature if it allows us to run specific query (like DBMS client).

**Comment by benjie** [comment]
When you supply multiple query or mutation operations, GraphiQL allows you to choose which one is to be executed:

![Screenshot_20191007_183158](https://user-images.githubusercontent.com/129910/66334378-dbfcf180-e930-11e9-8bb8-9dd880f83b01.png)

**Comment by tanhenggek** [comment]
thanks. I always use Command + Enter shortcut to execute query and mutation. Is there any way to achieve it through keyboard shortcut?

**Comment by tanhenggek** [comment]
the keyboard shortcut works well. Thanks! @benjie

**Comment by benjie** [comment]
(For future visitors to this issue, the keyboard shortcut runs the operation that contains your cursor at the time, so if your cursor was next to the `b: __typename` it would run query B.)
