### ISSUE TITLE
Broken minified build for graphiql 0.16.0

### ISSUE THREAD

**Issue by dinvlad** [graphql/graphiql#976]
Hi All,

The jsDelivr CDN distribution of GraphiQL seems broken at the moment.

I followed the official example at https://github.com/graphql/graphiql/blob/master/packages/examples/graphiql-cdn/index.html, and then changed the CDN URL from `./graphiql.js` to https://cdn.jsdelivr.net/npm/graphiql/graphiql.min.js, which results in `Minified React error #130`.

Changing it to the full version ( https://cdn.jsdelivr.net/npm/graphiql/graphiql.js) seems to fix it.

Not sure if this issue belongs here, just something to note.
Thanks!

**Comment by acao** [comment]
@dinvlad thanks for reporting this, i’ll take a look, the latest release builds with typescript so its a big factor here

**Comment by imolorhe** [comment]
@acao Maybe [this line](https://github.com/graphql/graphiql/blob/master/packages/graphiql/resources/build.sh#L16) needs to be changed to:

```diff
+ browserify -g browserify-shim -t uglifyify -s GraphiQL graphiql.min.js | uglifyjs -c > graphiql.min.js
- browserify -g browserify-shim -t uglifyify -s GraphiQL graphiql.js | uglifyjs -c > graphiql.min.js
```

 if the intention is to use the file that was just built in the previous line to create the minified version?

**Comment by imolorhe** [comment]
Created a PR to address this issue. @acao

**Comment by acao** [comment]
I can’t figure out how to stay logged in to github on my iphone for some
reason, hope to check this out soon

**Comment by acao** [comment]
@imolorhe apologies, did not mean to close this issue!

we will track this known bug here.

fix is a few PRs away.

**Comment by acao** [comment]
unfortunately we won't have anyone to review PRs this weekend or for a while, so despite having a working minified bundle [demo](https://deploy-preview-1001--graphiql-lighthouse.netlify.com/) [minified bundle](https://deploy-preview-1001--graphiql-lighthouse.netlify.com/) it may still be a few weeks until a maintainer has the time to review this. But hey once it's released it'll be less than 1/4 of the original bundle size!

i spent a few nights just trying to get the legacy browserify build to work, but for whatever reason I couldn't, so the only option was the full path forward with webpack (I had spiked with Rollup previously some months ago, and I just couldnt get the legacy umd global interface working right). Webpack is the most versatile tool for the job IMO.

I originally introduced it as a mega-PR but then tried to slice it into smaller chunks, so i broke the PR up into several. It wasn't possible to break them down much further and still having building PRs. This is just unfortunately a chokepoint, given the complexity, so any peer review folks want to help with would be excellent and much appreciated, and would help my co-maintainers be able to review much more quickly.

**Comment by dinvlad** [comment]
Sounds good, thanks for working on this!!

**Comment by acao** [comment]
https://unpkg.com/browse/graphiql@0.17.0/graphiql.min.js

0.17.0 minified build is now available. re-creating it requires two pending and already well reviewed PRs to be merged, but it's been thoroughly tested. 

an alpha probably would have been a better choice but some would argue 0.x.y versions are _always_ prerelease. either way, there you have it! please let me know if there are any regressions. i have not tested this new minified build in IE yet, which is another issue
