### ISSUE TITLE
Deprecate React 15 peer support

### ISSUE THREAD

**Issue by acao** [graphql/graphiql#984]
React 15.6.2 was the last release of the `15.x.y` major version [2 years ago](https://www.npmjs.com/package/react/v/15.6.2). There is really no need to support it any longer, and thus we should be able to begin to use React 16 features in GraphiQL itself.

We should update `peerResolutions` to no longer support `15.x.y`, update all the tests and examples to use react 16, and kick out a new minor release and document that break clearly.

I was thinking we could even go so far as to create an intelligent error boundary component, which could detect the react version and give some helpful instruction, but that's probably overkill.

**Comment by acao** [comment]
@sgrove @hwillson @pieh how do y'all feel about this? anyone still using React 15 still and in need of some more support before we make this switch?

**Comment by hwillson** [comment]
@acao I'm definitely okay with this 👍 - thanks!
