### ISSUE TITLE
React duplicate key warning in QueryHistory component since 0.16.0

### ISSUE THREAD

**Issue by MichaelBurgess** [graphql/graphiql#988]
Since upgrading to `0.16.0` I'm getting duplicate key warnings from the `QueryHistory` component. I have a few of the same items in the history - this looks to be the issue here: https://github.com/graphql/graphiql/blob/87e9d465b51487d41f03e7c09eda5d2e7116e1cb/packages/graphiql/src/components/QueryHistory.js#L96

```
0.chunk.js:319590 Warning: Encountered two children with the same key, `mutation SomeMutation($input: SomeMutationInput!) {
  someMutation(input: $input) {
    result
  }
}`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
    in ul (created by QueryHistory)
    in section (created by QueryHistory)
    in QueryHistory (created by GraphiQL)
    in div (created by GraphiQL)
    in div (created by GraphiQL)
```

**Comment by MickaelNeves** [comment]
Getting the same problem

![console](https://user-images.githubusercontent.com/20476271/67678886-aa030c00-f97f-11e9-9b8e-d55cdb5cd020.PNG)

**Comment by acao** [comment]
About to take care of this in the upgrade to react 16 this week. Thanks for
reporting it!

**Comment by moroshko** [comment]
@acao Any luck?

**Comment by acao** [comment]
@moroshko ah dangit my bad, forgot to bring this into the 0.17.0 release. this is a no-go, and we need to fix it immediately! I will get on a 0.17.1 bugfix release today, much smaller effort.

**Comment by acao** [comment]
@moroshko able to give this a try to confirm? looks good to me:
![Screen Shot 2019-12-01 at 1 02 36 PM](https://user-images.githubusercontent.com/1368727/69918022-02c03b80-143b-11ea-8647-d8221e321710.png)

**Comment by moroshko** [comment]
@acao Thanks for fixing this, let's release the fix!

**Comment by acao** [comment]
@moroshko we have a few more PRs waiting for the next release, one in particular that fixes our minified build. our currently published one is provisional from that PR. our minified builds are the most widely used. so hopefully later this week!
