### ISSUE TITLE
WARN: Side effects in initialization of unused variable _error when trying to build on Ubuntu

### ISSUE THREAD

**Issue by leoalves** [graphql/graphiql#99]
When running npm run build on Ubuntu the build freezes with a warning saying WARN: Side effects in initialization of unused variable _error [-:621,1418]

> leoalves@ubuntu:~/graphiql$ npm run build
> 
> graphiql@0.5.0 build /home/leoalves/graphiql
>  . ./resources/build.sh
> 
> src/codemirror/lint/json-lint.js -> dist/codemirror/lint/json-lint.js
> src/codemirror/lint/jsonLint.js -> dist/codemirror/lint/jsonLint.js
> src/components/DocExplorer.js -> dist/components/DocExplorer.js
> src/components/ExecuteButton.js -> dist/components/ExecuteButton.js
> src/components/GraphiQL.js -> dist/components/GraphiQL.js
> src/components/QueryEditor.js -> dist/components/QueryEditor.js
> src/components/ResultViewer.js -> dist/components/ResultViewer.js
> src/components/ToolbarButton.js -> dist/components/ToolbarButton.js
> src/components/VariableEditor.js -> dist/components/VariableEditor.js
> src/index.js -> dist/index.js
> src/utility/elementPosition.js -> dist/utility/elementPosition.js
> src/utility/fillLeafs.js -> dist/utility/fillLeafs.js
> src/utility/find.js -> dist/utility/find.js
> src/utility/introspectionQueries.js -> dist/utility/introspectionQueries.js
> WARN: Side effects in initialization of unused variable _error [-:621,1418]

tried in two different machines and both happened the same issue.
Node v 5.7.0
npm v 3.6.0

ran npm install before running the build command

**Comment by asiandrummer** [comment]
Does it completely freeze? For me it just takes a little more time (maybe ~45 seconds, which I just let it run and do other stuff meanwhile) until it finishes building.

That warning message seemed to come from `uglify` catching unused variables/functions in other modules in `node_modules` dir. The message could be suppressed by having an option to disable warning while running `uglify` (`-c warnings=false`).
