### ISSUE TITLE
Unable to prettify query variables input

### ISSUE THREAD

**Issue by Ambro17** [graphql/graphiql#990]
As a user it is really useful to prettify the input query/mutation/suscription. But AFAIK there's currently no way to prettify the query variables section.
If one follows the convention for mutations to receive a unique input field, it becomes cumbersome when a mutation has many arguments as one has to indent them manually.

![image](https://user-images.githubusercontent.com/11272260/67804231-540c9200-fa6d-11e9-8b46-07d17181c080.png)

**Comment by acao** [comment]
Thanks for reporting this bug. We will be moving to a plugin that uses the
prettier module itself, thus we can rely on their algorithm to handle this
case. The current solution is flawed.

**Comment by acao** [comment]
oh right that would be easy!

**Comment by Ambro17** [comment]
Thanks both for the fast reply. If I can be of any help testing/coding just ask

**Comment by benjie** [comment]
@Ambro17 a PR doing this would be welcome. Try and make it as minimal as possible to encourage pain-free merging :)

**Comment by acao** [comment]
we have this discussion going now: #1517, and there's an RFC branch too!
