### ISSUE TITLE
 Invalid aria prop `aria-description` in ToolbarButton

### ISSUE THREAD

**Issue by gjvoosten** [graphql/graphiql#995]
#967 introduced a new warning:
```
Warning: Invalid aria prop `aria-description` on <button> tag. For details, see https://fb.me/invalid-aria-prop
    in button (created by ToolbarButton)
    in ToolbarButton (created by GraphiQL)
```
`aria-description` is not an official prop (but https://github.com/w3c/aria/issues/891 [re]started an attempt to include it).
Since there's already a `title`, I believe `aria-description` can be dropped without consequence.

**Comment by benjie** [comment]
@kasperisager could you chime in on this?

**Comment by kasperisager** [comment]
If memory serves me right, this was just my attempt at future proofing the error message. It can for sure be dropped without impact on current AT.

**Comment by benjie** [comment]
Thanks @kasperisager! :pray: 

@gjvoosten a PR dropping this prop until it's official would be welcome :+1:

**Comment by gjvoosten** [comment]
@benjie PR is there; not sure what's up with the failing Travis CI build though, seems unrelated to the one removed line…

**Comment by acao** [comment]
Apologies, flaky end to end suite, I have a PR that makes it less flaky by
using a static site. Originally implemented the test server w weback dev
server which is slow.

I re-ran the build for now, lmk if that doesn't work for you (I’m at work
but I can check in here or there)

**Comment by gjvoosten** [comment]
@acao I'm fully aware of flaky CI builds (esp. timing related issues in end-to-end tests). :slightly_smiling_face:
The **Node.js:12** job in the build matrix failed (had I permissions, I would have clicked _Restart job_; lather, rinse, repeat…); the **Node.js :10** job succeeded.

**Comment by acao** [comment]
i already did re-run both builds, so that means the node 12 build failed
again

**Comment by gjvoosten** [comment]
@acao Sorry I wasn't clear enough; I was referring to the results of the *restarted* build run (initially _both_ jobs failed, so there _is_ progress :wink: ).
